KISSY.add("gallery/chart",function(h){function o(a,b){if(!(this instanceof o))return new o(a,b);if(a=this.elCanvas=j.get(a)){var e=a.width,f=a.height;this.elCanvas=a;this.width=e;this.height=f;this.ctx=-1;this.tooltip=o.getTooltip();this._chartAnim=new d.Anim(0.3,"easeIn");if(b){this.data=b;this._initContext()}}}var g=h.Event,j=h.DOM,d=h.namespace("Gallery.Chart"),c={left:40,top:40};o.getTooltip=function(){if(!o.tooltip)o.tooltip=new d.SimpleTooltip;return o.tooltip};o.MOUSE_LEAVE="mouse_leave";o.MOUSE_MOVE=
"mouse_move";h.augment(o,h.EventTarget,{render:function(a){var b=this;if(b.ctx==-1){b.data=a;b._initContext()}else if(b.ctx===0)b.data=a;else{b._data=new d.Data(a);if(b._data){a=b._data;b.initChart();b._drawcfg=h.merge(c,a.config,{width:b.width,height:b.height});if(a.type==="bar"||a.type==="line"){b._drawcfg.max=a.axis().y.max||d.Axis.getMax(a.max(),b._drawcfg);b.axis=new d.Axis(a,b,b._drawcfg);b._frame=new d.Frame(b._data,b._drawcfg);b.layers.push(b.axis);b.layers.push(b._frame)}b.element=d.Element.getElement(b._data,
b,b._drawcfg);b.layers.push(b.element);a=a.config;var e=b.ctx.createLinearGradient(0,0,0,b.height);b.backgroundFillStyle=null;if(a.backgroundStyle&&typeof a.backgroundStyle==="object"){e.addColorStop(0,a.backgroundStyle.start);e.addColorStop(1,a.backgroundStyle.end);b.backgroundFillStyle=e}else if(h.isString(a.backgroundStyle))b.backgroundFillStyle=a.backgroundStyle;setTimeout(function(){b._redraw();b.initEvent()},100)}}},_initContext:function(){var a=this;if(typeof a.ctx!="object")if(a.elCanvas.getContext)setTimeout(function(){a.ctx=
a.elCanvas.getContext("2d");a._contextReady()},150);else{a.ctx=0;a._count=typeof a._count=="number"?a._count-1:30;if(a._count>=0)setTimeout(function(){a._initContext()},150);else{var b=j.create("<p class='ks-chart-error' > \u7cdf\u4e86\uff0c\u4f60\u7684\u6d4f\u89c8\u5668\u8fd8\u4e0d\u652f\u6301\u6211\u4eec\u7684\u56fe\u8868</p>");j.insertAfter(b,a.elCanvas)}}},_contextReady:function(){this.data&&this.render(this.data)},loading:function(){this.showMessage("\u8f7d\u5165\u4e2d...")},showMessage:function(a){var b=this.ctx,e=this.width/2,f=this.height/2;b.clearRect(0,0,this.width,this.height);b.save();
b.font="12px Arial";b.textAlign="center";b.fillStyle="#808080";b.fillText(a,e,f);b.restore()},initChart:function(){this._chartAnim.init();this.layers=[];this.offset=j.offset(this.elCanvas);this.loading();h.each([this.element,this.axis],function(a){if(a){a.destory();g.remove(a)}});this.axis=this.element=null;if(this._event_inited){g.remove(this.elCanvas,"mousemove",this._mousemoveHandle);g.remove(this.elCanvas,"mouseleave",this._mouseLeaveHandle);g.remove(this,o.MOUSE_LEAVE,this._drawAreaLeave)}this.tooltip.hide()},
initEvent:function(){var a=this;a._event_inited=true;g.on(a.elCanvas,"mousemove",a._mousemoveHandle,a);g.on(a.elCanvas,"mouseleave",a._mouseLeaveHandle,a);g.on(a,o.MOUSE_LEAVE,a._drawAreaLeave,a);a.type==="bar"&&g.on(a.element,"barhover",a._barHover,a);if(a.axis){g.on(a.axis,"xaxishover",a._xAxisHover,a);g.on(a.axis,"leave",a._xAxisLeave,a);g.on(a.axis,"redraw",a._redraw,a)}g.on(a.element,"redraw",a._redraw,a);g.on(a.element,"showtooltip",function(b){b=h.isString(b.message)?b.message:b.message.innerHTML;
a.tooltip.show(b)});g.on(a.element,"hidetooltip",function(){a.tooltip.hide()})},draw:function(){var a=this.ctx,b=this._chartAnim.get(),e=this._drawcfg;a.save();a.globalAlpha=b;if(this.backgroundFillStyle){a.fillStyle=this.backgroundFillStyle;a.fillRect(0,0,e.width,e.height)}else a.clearRect(0,0,e.width,e.height);h.each(this.layers,function(f){f.draw(a,e)});a.restore();b<1&&this._redraw()},ctx:function(){if(this.ctx)return this.ctx;if(this.elCanvas.getContext)return this.ctx=this.elCanvas.getContext("2d");
else return null},_redraw:function(){this._redrawmark=true;this._running||this._run()},_run:function(){var a=this;clearTimeout(a._timeoutid);a._running=true;a._redrawmark=false;a._timeoutid=setTimeout(function(){a.draw();if(a._redrawmark)a._run();else a._running=false},1E3/24)},_barHover:function(){},_xAxisLeave:function(){this.fire("axisleave")},_xAxisHover:function(a){this.fire("axishover",{index:a.index,x:a.x});this._redraw()},_drawAreaLeave:function(){this.tooltip.hide()},_mousemoveHandle:function(a){var b=
a.offsetX||a.pageX-this.offset.left;a=a.offsetY||a.pageY-this.offset.top;this._frame&&this._frame.path&&this._frame.path.inpath(b,a)||!this._frame?this.fire(o.MOUSE_MOVE,{x:b,y:a}):this.fire(o.MOUSE_LEAVE)},_mouseLeaveHandle:function(a){var b=this.tooltip;(a=a.relatedTarget)&&(a===b.n_c[0]||b.n_c.contains(a))||this.fire(o.MOUSE_LEAVE)}});return d.Chart=o},{requires:["./chart/anim","./chart/axis","./chart/simpletooltip","./chart/frame","./chart/element","./chart/data"]});
KISSY.add("gallery/chart/format",function(h){var o=function(g,j){if(typeof j==="string"){var d=-1<j.indexOf(","),c=j.split(".");if(1<c.length)g=g.toFixed(c[1].length);else if(2<c.length)throw"NumberFormatException: invalid format, formats should have no more than 1 period:"+j;else g=g.toFixed(0);g=g.toString();if(d){c=g.split(".");d=c[0];g=[];for(var a=d.length,b=Math.floor(a/3),e=d.length%3||3,f=0;f<a;f+=e){if(f!=0)e=3;g[g.length]=d.substr(f,e);b-=1}g=g.join(",");if(c[1])g+="."+c[1]}return j.replace(/[\d,?\.?]+/,
g)}};return h.namespace("Gallery.Chart").format=o});
KISSY.add("gallery/chart/color",function(h){var o=function(){var g=function a(b,e,f,l){var m=arguments.length,n=function(k){return parseInt(k,16)};if(m<3){if(typeof b==="string"){b=b.substr(b.indexOf("#")+1);var p=b.length===3;b=n(b);p&&(b=(b&3840)*4352|(b&240)*272|(b&15)*17)}m===2&&(l=e);e=(b&65280)/256;f=b&255;b>>>=16}if(!(this instanceof a))return new a(b,e,f,l);this.channels=[typeof b==="string"&&n(b)||b,typeof e==="string"&&n(e)||e,typeof f==="string"&&n(f)||f,typeof l!=="string"&&typeof l!==
"number"&&1||typeof l==="string"&&parseFloat(l)||l]},j=g.prototype,d=Math,c;g.RGBtoHSL=function(a){var b=a[0],e=a[1];a=a[2];b/=255;e/=255;a/=255;var f=d.max(b,e,a),l=d.min(b,e,a),m,n=(f+l)/2;if(f===l)m=l=0;else{var p=f-l;l=n>0.5?p/(2-f-l):p/(f+l);switch(f){case b:m=(e-a)/p+(e<a?6:0);break;case e:m=(a-b)/p+2;break;case a:m=(b-e)/p+4;break}m/=6}return[m,l,n]};g.HSLtoRGB=function(a){var b=a[0],e=a[1],f=a[2];a=function(n,p,k){if(k<0)k+=1;if(k>1)k-=1;if(k<1/6)return n+(p-n)*6*k;if(k<0.5)return p;if(k<
2/3)return n+(p-n)*(2/3-k)*6;return n};if(e===0)e=f=b=f;else{var l=f<0.5?f*(1+e):f+e-f*e,m=2*f-l;e=a(m,l,b+1/3);f=a(m,l,b);b=a(m,l,b-1/3)}return[e*255,f*255,b*255]};g.rgb=function(a,b,e,f){return new g(a,b,e,typeof f!=="undefined"?f:1)};g.hsl=function(a,b,e,f){a=g.HSLtoRGB([a,b,e]);b=d.ceil;return new g(b(a[0]),b(a[1]),b(a[2]),typeof f!=="undefined"?f:1)};g.TO_STRING_METHOD="hexTriplet";g.parse=function(a){a=a.replace(/^\s+/g,"").toLowerCase();if(a[0]==="#")return new g(a);var b=a.substr(0,3),e;a=
a.replace(/[^\d,.]/g,"").split(",");for(e=a.length;e--;)a[e]=a[e]&&parseFloat(a[e])||0;switch(b){case "rgb":return g.rgb.apply(g,a);case "hsl":a[0]/=360;a[1]/=100;a[2]/=100;return g.hsl.apply(g,a)}return null};(g.clearColors=function(){c={transparent:[0,0,0,0]}})();g.define=function(a,b){c[a.toLowerCase()]=b};g.get=function(a){a=a.toLowerCase();if(Object.prototype.hasOwnProperty.call(c,a))return g.apply(null,[].concat(c[a]));return null};g.del=function(a){return delete c[a.toLowerCase()]};g.random=
function(a,b){typeof a==="string"&&(a=g.get(a))&&(a=a.getValue());typeof b==="string"&&(b=g.get(b))&&(b=b.getValue());var e=d.floor,f=d.random;b=(b||16777215)+1;if(!isNaN(a))return new g(e(f()*(b-a)+a));return new g(e(f()*b))};j.toString=function(){return this[g.TO_STRING_METHOD]()};j.valueOf=j.getValue=function(){var a=this.channels;return a[0]*65536|a[1]*256|a[2]};j.setValue=function(a){this.channels.splice(0,3,a>>>16,(a&65280)/256,a&255)};j.hexTriplet="01".substr(-1)==="1"?function(){return"#"+
("00000"+this.getValue().toString(16)).substr(-6)}:function(){var a=this.getValue().toString(16);return"#"+(new Array(a.length<6?6-a.length+1:0)).join("0")+a};j.css=function(){return this.channels[3]===1?this.hexTriplet():this.rgba()};j.rgbData=function(){return this.channels.slice(0,3)};j.hslData=function(){return g.RGBtoHSL(this.rgbData())};j.rgb=function(){return"rgb("+this.rgbData().join(",")+")"};j.rgba=function(){return"rgba("+this.channels.join(",")+")"};j.hsl=function(){var a=this.hslData();
return"hsl("+a[0]*360+","+a[1]*100+"%,"+a[2]*100+"%)"};j.hsla=function(){var a=this.hslData();return"hsla("+a[0]*360+","+a[1]*100+"%,"+a[2]*100+"%,"+this.channels[3]+")"};return g}();return h.namespace("Gallery.Chart").Color=o});
KISSY.add("gallery/chart/data",function(h){function o(a){if(a&&a.type){if(!this instanceof o)return new o(a);var b=a.config;this.origin=a;a=h.clone(a);this.type=a.type.toLowerCase();this.config=b=h.merge(j,d[this.type],b);h.each({left:"paddingLeft",top:"paddingTop",bottom:"paddingBottom",right:"paddingRight"},function(e,f){if(f in b&&h.isNumber(b[f]))b[e]=b[f]});this._elements=this._initElement(a);this._elements=this._expandElement(this._elements);this._initElementItem();this._axis=a.axis}}var g=
h.namespace("Gallery.Chart"),j={paddingTop:30,paddingLeft:20,paddingRight:20,paddingBottom:20,showLabels:true,colors:[],animationDuration:0.5,animationEasing:"easeInStrong",backgroundStyle:false,axisTextColor:"#999",axisBackgroundColor:"#EEE",axisGridColor:"#e4e4e4",numberFormat:false,frameColor:"#d7d7d7"},d={line:{drawbg:-1},bar:{},pie:{animationDuration:1.8,animationEasing:"bounceOut",paddingTop:10,paddingBottom:10,paddingLeft:10,paddingRight:10,shadow:true,labelTemplete:"{name} {pecent}%",firstPieOut:false}},
c={"default":{label:"{name} -  {data}"},line:{},pie:{},bar:{}};h.augment(o,{axis:function(){return this._axis},elements:function(){return this._elements},maxElementLength:function(){var a=0;h.each(this._elements,function(b){a=h.isArray(b.items)?Math.max(a,b.items.length):Math.max(a,1)});return a},getColor:function(a,b){var e=this._elements.length,f=this.config.colors;if(h.isArray(f)&&f[a])return f[a];if(h.isFunction(f))return f(a);return this.getDefaultColor(a,e,b)},sum:function(){var a=0;this.eachElement(function(b){a+=
b.data});return a},max:function(){return this._max},getDefaultColor:function(a,b){var e=1/3,f=e*a;if(a<3)f=e*a+0.05;else{if(b%3==0)if(a===b-1)a=b-2;else if(a===b-2)a=b-1;f=a%3;b=Math.ceil(b/3);a=Math.ceil((a+1)/3);f=f*e+e/b*(a-1)}return g.Color.hsl(f,0.7,0.65).hexTriplet()},eachElement:function(a){h.each(this._elements,function(b,e){b.items?h.each(b.items,function(f,l){a(f,e,l)}):a(b,e,-1)})},_initElementItem:function(){var a=this;a._max=null;a.eachElement(function(b,e,f){if(e===0&&!f)a._max=b.data||
0;f=h.merge(c["default"],c[a.type]||{});b.data=h.isNumber(b.data)?b.data:0;if(h.isArray(a.config.numberFormats))b.format=a.config.numberFormats[e];if(typeof b.format=="undefined")b.format=a.config.numberFormat;b.label=b.label||f.label;b.label=h.substitute(b.label,{name:b.name,data:b.format?g.format(b.data,b.format):b.data});a._max=Math.max(a._max,b.data)})},_expandElement:function(a){var b;h.each(a,function(e){if(h.isArray(e.datas)){e.items=e.items||[];h.each(e.datas,function(f,l){b={name:e.name,
data:f};if(e.label)b.label=e.label;if(e.labels&&h.isString(e.labels[l]))b.label=e.labels[l];delete e.datas;e.items.push(b)})}});return a},_initElement:function(a){var b=null,e,f=this;if(a.elements&&h.isArray(a.elements))b=h.clone(a.elements);if(!a.elements&&a.element&&h.isArray(a.element.names)){b=[];e=a.element;h.each(e.names,function(l,m){b.push({name:l,data:f._getLabel(e.datas,m),label:f._getLabel(e.labels,m)||e.label})})}return b},_getLabel:function(a,b){return h.isArray(a)?b<a.length?a[b]:null:
false}});return g.Data=o},{requires:["./color"]});
KISSY.add("gallery/chart/path",function(h){function o(){}function g(c,a,b,e){this.rect={x:c,y:a,w:b,h:e}}function j(c,a,b,e,f,l){this._arc={x:c,y:a,r:b,b:e,e:f,a:l}}var d=h.namespace("Gallery.Chart");h.augment(o,{draw:function(){},inpath:function(){}});h.extend(g,o,{draw:function(c){var a=this.rect;c.beginPath();c.rect(a.x,a.y,a.w,a.h)},inpath:function(c,a){var b=this.rect,e=b.x,f=b.y,l=e+b.w;b=f+b.h;return c>e&&c<l&&a>f&&a<b}});h.extend(j,o,{draw:function(c){var a=this._arc;c.beginPath();c.moveTo(a,
x,a.y);c.arc(a.x,a.y,a.r,a.b,a.e,a.a);c.closePath()},inpath:function(c,a,b){if(b){this.draw(b);return b.isPointInPath(c,a)}a=this._arc;b=c-a.x;c=c-a.y;if(!(Math.pow(b,2)+Math.pow(c,2)<=Math.pow(a.r,2)))return false;if(b===0)if(c===0)return false;else da=c>0?Math.PI/2:Math.PI*1.5}});d.Path=o;d.RectPath=g;d.ArcPath=j;return{Path:o,RectPath:g,ArcPath:j}});
KISSY.add("gallery/chart/frame",function(h){function o(j,d){this.data=j;this.path=new g.RectPath(d.paddingLeft,d.paddingTop,d.width-d.paddingRight-d.paddingLeft,d.height-d.paddingBottom-d.paddingTop)}var g=h.namespace("Gallery.Chart");h.augment(o,{draw:function(j){j.save();j.strokeStyle=this.data.config.frameColor;j.lineWidth=2;this.path.draw(j);j.stroke();j.restore()}});return g.Frame=o});
KISSY.add("gallery/chart/anim",function(h){function o(d,c){this.duration=d*1E3;this.fnEasing=h.isString(c)?j[c]:c}var g=h.namespace("Gallery.Chart"),j=h.Easing;h.augment(o,{init:function(){this.start=(new Date).getTime();this.finish=this.start+this.duration},get:function(){var d=(new Date).getTime();if(d>this.finish)return 1;return this.fnEasing((d-this.start)/this.duration)}});return g.Anim=o});
KISSY.add("gallery/chart/simpletooltip",function(h){function o(){var c=this;this.el_c=j.create("<div class='ks-chart-tooltip'>");this.n_c=h.one(this.el_c);this._offset={left:0,top:0};this.hide();h.ready(function(){document.body.appendChild(c.el_c)});d.on(document.body,"mousedown",this._mousemove,this);d.on(document.body,"mousemove",this._mousemove,this)}var g=h.namespace("Gallery.Chart"),j=h.DOM,d=h.Event;h.augment(o,{_mousemove:function(c){var a=c.pageX;c=c.pageY;if(this._show)this._updateOffset(a,
c);else{this._offset.left=a;this._offset.top=c}},_updateOffset:function(c,a){if(c>j.scrollLeft()+j.viewportWidth()-100)c-=this.n_c.width()+6;if(a>j.scrollTop()+j.viewportHeight()-100)a-=this.n_c.height()+20;this.n_c.offset({left:c,top:a+12})},show:function(c){this._show=true;this.n_c.html(c).css("display","block").offset(this._offset)},hide:function(){this._show=false;this.n_c.css("display","none")},_init:function(){}});return g.SimpleTooltip=o});
KISSY.add("gallery/chart/axis",function(h){function o(d,c,a){this.chart=c;this.type=d.type;this.data=d;this.axisData=d.axis();this.cfg=a;this.current_x=-1;this.initEvent();h.each(this.axisData,function(b){b.name="name"in b&&h.isString(b)&&b.name.length>0?"("+b.name+")":false});this.initdata(this.axisData,a)}var g=KISSY.namespace("Gallery.Chart"),j=h.Event;h.mix(o,{getMax:function(d,c){c=Math.ceil((c.height-c.paddingBottom-c.paddingTop)/40);d=d/c;var a;if(d<=1)d=1;else if(d>1&&d<=5)d=Math.ceil(d);
else if(d>5&&d<=10)d=10;else{a=1;do{a*=10;d/=10}while(d>10);d=Math.ceil(d)*a}return d*c}});h.augment(o,h.EventTarget,{initYLabel:function(d,c){if(d.y.labels)return null;var a=c.max;c=Math.ceil((c.height-c.paddingBottom-c.paddingTop)/40);a=a/c;var b=[];for(i=0;i<=c;i++)b.push(a*i);d.y.labels=b},initdata:function(d,c){this.initYLabel(d,c);var a=d.x;d=d.y;var b=a.labels.length,e=d.labels.length,f=c.height,l=c.width-c.paddingRight,m=c.paddingLeft,n=f-c.paddingBottom;c=c.paddingTop;var p=(n-c)/(e-1),k=
l-m,q,r,s=Math.ceil(120*b/k);a._lpath={x:l*2-m,y:f-n+20};a._path=[];a._area=[];a._showlabel=[];for(i=0;i<b;i++){if(this.type==="line"){q=k/(b-1);f=m+i*q;r=i===0?f:f-q/2;q=i===b-1?f:f+q/2}else{q=k/b;f=m+(i+0.5)*q;r=f-q/2;q=f+q/2}a._showlabel.push(i===0||i%s===0);a._path.push({left:r,right:q,top:c,bottom:n,x:f});a._area.push(new g.RectPath(r,c,q-r,n-c))}d._lpath={x:(n-c)/2+c,y:-10};d._path=[];for(i=0;i<e;i++)d._path.push({y:n-p*i,left:m,right:l})},initEvent:function(){if(this.type==="line"){j.on(this.chart,
g.Chart.MOUSE_MOVE,this.chartMouseMove,this);j.on(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave,this)}},destory:function(){if(this.type===ATYPE.LINE){j.remove(this.chart,g.Chart.MOUSE_MOVE,this.chartMouseMove);j.remove(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave)}},chartMouseMove:function(d){var c=this;h.each(c.axisData.x._area,function(a,b){if(b!==c.current_x&&a.inpath(d.x,d.y)){c.current_x=b;c.fire("xaxishover",{index:b,x:c.axisData.x._path[b].x});c.fire("redraw");return false}})},
chartMouseLeave:function(){this.current_x=-1;this.fire("redraw");this.fire("leave")},draw:function(d,c){var a=this.data.config,b=this.data.axis(),e=b.x,f=b.y,l=e.labels.length,m=f.labels.length,n=this.type==="line",p=this.type==="bar",k,q;d.save();for(k=0;k<m;k++){q=f._path[k];b=f.labels[k];if(k%2===1&&k>0){d.save();d.globalAlpha=0.3;d.fillStyle=a.axisBackgroundColor;d.fillRect(q.left,q.y,q.right-q.left,f._path[k-1].y-q.y);d.restore()}if(k!==0&&k!==m-1){d.strokeStyle=a.axisGridColor;d.lineWidth="1.0";
d.beginPath();d.moveTo(q.left,q.y);d.lineTo(q.right,q.y);d.stroke()}if(b){d.font="12px Tohoma";d.textAlign="right";d.textBaseline="middle";d.fillStyle=a.axisTextColor;d.fillText(b,q.left-5,q.y)}}for(k=0;k<l;k++){m=k===this.current_x;f=e._path[k];b=e.labels[k];q=e._showlabel[k];d.strokeStyle=n&&m?"#404040":a.axisGridColor;d.lineWidth=n&&m?"1.6":"1.0";if(p)if(k!==0){d.beginPath();d.moveTo(f.left,f.bottom);d.lineTo(f.left,f.top);d.stroke()}if(n)if(k!==0&&k!==l-1){d.beginPath();d.moveTo(f.x,f.bottom);
d.lineTo(f.x,f.top);d.stroke()}if(b&&q){d.font="13px Tahoma";d.textAlign=n&&k===0?"left":n&&k===l-1?"right":"center";d.textBaseline="top";d.fillStyle=a.axisTextColor;d.fillText(b,f.x,f.bottom+5)}}if(this.current_x!==-1){f=e._path[this.current_x];b=e.labels[this.current_x];d.font="12px Tahoma";e=d.measureText(b).width+6;d.fillStyle="#333";l=Math.max(f.x-e/2,a.paddingLeft);l=Math.min(l,c.width-a.paddingRight-e);d.fillRect(l,f.bottom,e,20);d.textAlign="left";d.fillStyle="#ffffff";d.fillText(b,l+2,f.bottom+
5)}d.restore();this.drawLabels(d)},drawLabels:function(d){var c=this.data.axis(),a=c.y.name,b=c.x.name,e=c.x._lpath;c=c.y._lpath;d.save();d.font="10px Arial";d.fillStyle="#808080";d.textAlign="center";d.textBaseline="middle";b&&d.fillText(b,e.x,e.y);if(a){d.rotate(Math.PI/2);d.translate(c.x,c.y);d.fillText(a,0,0)}d.restore()}});return g.Axis=o});
KISSY.add("gallery/chart/element",function(h){function o(){}var g=h.namespace("Gallery.Chart");h.mix(o,{getElement:function(j,d,c){var a;switch(j.type){case "line":a=g.LineElement;break;case "pie":a=g.PieElement;break;case "bar":a=g.BarElement;break}return new a(j,d,c)},getMax:function(j){var d=j[0].data[0],c,a=j.length,b,e;for(c=0;c<a;c++){element=j[c];b=0;for(e=element.data.length;b<e;b++)d=Math.max(d,element.data[b]||0)}return d}});h.augment(o,h.EventTarget,{drawNames:function(j){var d=this.drawcfg,
c=this.data.elements(),a=c.length-1,b=d.width-d.paddingRight;d=d.paddingTop-12;for(var e,f;a>=0;a--){e=c[a];if(!e.notdraw){f=this.data.getColor(a);j.save();j.textAlign="end";j.textBaseline="middle";j.fillStyle="#808080";j.font="12px Arial";j.fillText(e.name,b,d);b-=j.measureText(e.name).width+10;j.restore();j.save();j.beginPath();j.fillStyle=f;j.arc(b,d,5,0,Math.PI*2,true);j.closePath();j.fill();j.restore();b-=10}}},init:function(){},initdata:function(){},destory:function(){},draw:function(){},drawBar:function(){},
getTooltip:function(){}});return g.Element=o});
KISSY.add("gallery/chart/element-line",function(h){function o(d,c,a){this.chart=c;this.data=d;this.elements=d.elements();this._current=-1;this.config=d.config;this.drawcfg=a;this.initdata(a);this._ready_idx=-1;this.init();this.anim=new g.Anim(this.config.animationDuration,this.config.animationEasing);this.anim.init()}var g=h.namespace("Gallery.Chart"),j=h.Event;h.extend(o,g.Element,{initdata:function(d){var c=this.data,a=c.maxElementLength(),b=d.paddingLeft,e=d.height-d.paddingBottom,f=e-d.paddingTop,
l=(d.width-d.paddingRight-b)/(a-1),m=[];this.items=m;c.eachElement(function(n,p,k){m[p]||(m[p]={_points:[],_labels:[],_color:c.getColor(p),_maxtop:e,_drawbg:p===c.config.drawbg});p=m[p];ptop=Math.max(e-n.data/d.max*f,d.paddingTop-5);p._maxtop=Math.min(p._maxtop,ptop);p._labels[k]=n.label;p._points[k]={x:b+l*k,y:ptop,bottom:e}})},draw:function(d,c){var a=this,b=a.data,e=c.paddingLeft,f=c.width-c.paddingRight,l=c.height-c.paddingBottom,m,n,p,k,q,r,s=a.anim.get(),v;b.config.showLabels&&a.drawNames(d,
c);if(s>=1&&this._ready_idx<a.items.length-1){a._ready_idx++;a.anim.init();s=a.anim.get()}if(this._ready_idx!==b.elements().length-1||s!==1)this.fire("redraw");h.each(a.items,function(t,y){r=y!==a._ready_idx?y>a._ready_idx?0:1:s;m=t._color;p=t._points;if(t._drawbg){d.save();d.globalAlpha=0.4;maxtop=l-(l-t._maxtop)*r;v=d.createLinearGradient(e,maxtop,e,l);v.addColorStop(0,m);v.addColorStop(1,"rgb(255,255,255)");d.fillStyle=v;d.beginPath();d.moveTo(e,l);for(k=0;k<p.length;k++){t=p[k];n=l-(l-t.y)*r;
d.lineTo(t.x,n)}d.lineTo(f,l);d.stroke();d.fill();d.restore()}d.save();q=p.length;d.strokeStyle=m;d.lineWidth=2;d.beginPath();for(k=0;k<q;k++){t=p[k];n=l-(l-t.y)*r;k===0?d.moveTo(t.x,n):d.lineTo(t.x,n)}d.stroke();d.restore();d.save();for(k=0;k<q;k++){t=p[k];n=l-(l-t.y)*r;d.fillStyle=m;d.beginPath();d.arc(t.x,n,5,0,Math.PI*2,true);d.closePath();d.fill();if(k!==a._current){d.fillStyle="#fff";d.beginPath();d.arc(t.x,n,3,0,Math.PI*2,true);d.closePath();d.fill()}}d.restore()})},init:function(){this._ready_idx=
0;j.on(this.chart,"axishover",this._axis_hover,this);j.on(this.chart,"axisleave",this._axis_leave,this)},destory:function(){j.remove(this.chart,"axishover",this._axis_hover);j.remove(this.chart,"axisleave",this._axis_leave)},_axis_hover:function(d){d=d.index;if(this._current!==d){this._current=d;this.fire("redraw");this.fire("showtooltip",{message:this.getTooltip(d)})}},_axis_leave:function(){this._current=-1;this.fire("redraw")},getTooltip:function(d){var c,a;c="<ul>";h.each(this.items,function(b){a=
"<li><p style='color:"+b._color+"'>"+b._labels[d]+"</p></li>";c+=a});c+="</ul>";return c}});return g.LineElement=o},{requires:["./element"]});
KISSY.add("gallery/chart/element-bar",function(h){function o(c,a,b){this.data=c;this.chart=a;this.drawcfg=b;this.config=c.config;this.initData(b);this.initEvent();this.current=[-1,-1];this.anim=new g.Anim(this.config.animationDuration,this.config.animationEasing);this.anim.init()}var g=h.namespace("Gallery.Chart"),j=h.Event,d=function(c){c=c.hslData();var a=c[2],b=c[1];a=(a+b/2)*0.6-b/2;return new g.Color.hsl(c[0],b,a)};h.extend(o,g.Element,{initData:function(c){var a=this,b=a.data,e=b.elements().length;
b=b.maxElementLength();var f=c.paddingLeft,l=c.height-c.paddingBottom,m=(c.width-c.paddingRight-f)/b,n=m/5/e,p=m/3/e,k=(m-(e-1)*n-2*p)/e,q,r,s,v,t=[];a.maxLength=b;a.items=t;a.data.eachElement(function(y,z,u){if(u===-1)u=0;t[z]||(t[z]={_x:[],_top:[],_left:[],_path:[],_width:[],_height:[],_colors:[],_dcolors:[],_labels:[]});var w=t[z];q=(l-c.top)*y.data/c.max;r=f+u*m+p+z*(k+n);s=l-q;v=g.Color(a.data.getColor(z,"bar"));colord=d(v);w._left[u]=r;w._top[u]=s;w._width[u]=k;w._height[u]=q;w._path[u]=new g.RectPath(r,
s,k,q);w._x[u]=r+k/2;w._colors[u]=v;w._dcolors[u]=colord;w._labels[u]=y.label})},draw:function(c){var a=this,b=a.items,e=a.maxLength,f,l,m,n,p,k,q=a.anim.get(),r;a.data.config.showLabels&&a.drawNames(c);h.each(b,function(s,v){for(r=0;r<e;r++){p=s._left[r];m=s._height[r];n=m*q;k=s._top[r]+m-n;barwidth=s._width[r];f=s._colors[r];dcolor=s._dcolors[r];l=c.createLinearGradient(p,k,p,k+n);l.addColorStop(0,f.css());l.addColorStop(1,dcolor.css());c.fillStyle=l;c.fillRect(p,k,barwidth,n);if(e===1&&m>25){c.save();
c.fillStyle="#fff";c.font="20px bold Arial";c.textBaseline="top";c.textAlign="center";b=a.data.elements()[v];c.fillText(g.format(b.data,b.format),s._x[r],k+2);c.restore()}}});q<1&&a.fire("redraw")},initEvent:function(){j.on(this.chart,g.Chart.MOUSE_MOVE,this.chartMouseMove,this);j.on(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave,this)},destory:function(){j.remove(this.chart,g.Chart.MOUSE_MOVE,this.chartMouseMove);j.remove(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave)},chartMouseMove:function(c){var a=
[-1,-1],b=this.items;h.each(this.items,function(e,f){h.each(e._path,function(l,m){if(l.inpath(c.x,c.y))a=[f,m]})});if(!(a[0]===this.current[0]&&a[1]===this.current[1])){this.current=a;if(a[0]+a[1]>=0){this.fire("barhover",{index:a});this.fire("showtooltip",{top:b[a[0]]._top[a[1]],left:b[a[0]]._x[a[1]],message:this.getTooltip(a)})}else this.fire("hidetooltip")}},chartMouseLeave:function(){this.current=[-1,-1]},getTooltip:function(c){var a=c[1];c=this.items[c[0]];return"<div class='bartip'><span style='color:"+
c._colors[a].css()+";'>"+c._labels[a]+"</span></div>"}});return g.BarElement=o},{requires:["./element"]});
KISSY.add("gallery/chart/element-pie",function(h){function o(c,a,b){this.data=c;this.chart=a;this.type=0;this.config=c.config;this.drawcfg=b;this.initdata(b);this.init();this.anim=new g.Anim(this.config.animationDuration,this.config.animationEasing);this.anim.init()}var g=h.namespace("Gallery.Chart"),j=h.Event,d=function(c){if(h.isString(c))c=g.Color(c);c=c.hslData();var a=c[1],b=c[2];b=(b+a*0.5)*1.05-a*0.5;return new g.Color.hsl(c[0],a,b)};h.extend(o,g.Element,{initdata:function(c){var a=this,b=
a.data,e=0,f,l,m,n;a._x=b.config.showLabels?c.width*0.618/2:c.width/2;a._y=c.height/2;a._r=Math.min(c.height-c.paddingTop-c.paddingBottom,c.width-c.paddingLeft-c.paddingRight)/2;a._r=Math.min(a._r,a._x-c.paddingLeft);a._lx=c.width*0.618;a.angleStart=-Math.PI/4;a.antiClock=true;a.items=[];a._currentIndex=-1;e=b.sum();n=0;h.each(b.elements(),function(p,k){m=p.data/e;f=n+m;l=b.getColor(k);a.items.push({start:n,end:f,color:l,color2:d(l).css(),textColor:"#999",labelRight:c.width-50,labelY:50+20*k});n=
f;if(k===0)a.angleStart+=m*Math.PI})},drawLabels:function(c){var a=this,b=a.data,e=a.items,f,l=b.sum(),m,n,p;c.save();c.textBaseline="middle";c.textAlign="right";b.eachElement(function(k,q){f=e[q];p=f.labelY;n=f.labelRight;c.fillStyle=e[q].color;c.beginPath();c.moveTo(n,p);c.font="15px sans-serif";c.fillRect(n-10,p-5,10,10);c.closePath();c.fillStyle=e[q].textColor;m=h.substitute(a.data.config.labelTemplete,{data:g.format(k.data,k.format),name:k.name,pecent:g.format(k.data/l*100,"0.00")});c.fillText(m,
n-15,p)});c.restore()},draw:function(c){var a=this,b=a._x,e=a._y,f=a._r,l,m,n,p,k=a.anim.get(),q=a.data.config;k<1&&a.fire("redraw");q.showLabels&&a.drawLabels(c);if(q.shadow){c.save();c.fillStyle="#fff";c.shadowBlur=10;c.shadowColor="black";c.beginPath();c.moveTo(b,e);n=a.angleStart;p=a.antiClock?n-Math.PI*2*k:n+Math.PI*2*k;c.arc(b,e,f-1,n,p,a.antiClock);c.fill();c.restore()}c.save();c.lineWidth=0.5;c.strokeStyle="#fff";h.each(a.items,function(r,s){l=r.start*k*2*Math.PI;m=r.end*k*2*Math.PI;c.save();
c.fillStyle=s===a._currentIndex?r.color2:r.color;c.beginPath();r._currentStart=a.antiClock?a.angleStart-l:a.angleStart+l;r._currentEnd=a.antiClock?a.angleStart-m-0.0050:a.angleStart+m+0.0050;if(s===0&&k>=1&&q.firstPieOut){c.moveTo(b+2,e-2);c.arc(b+2,e-2,f,r._currentStart,r._currentEnd,a.antiClock)}else{c.moveTo(b,e);c.arc(b,e,f,r._currentStart,r._currentEnd,a.antiClock)}c.closePath();c.fill();c.stroke();c.restore()});c.restore()},init:function(){j.on(this.chart,g.Chart.MOUSE_MOVE,this.chartMouseMove,
this);j.on(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave,this)},destory:function(){j.remove(this.chart,g.Chart.MOUSE_MOVE,this.chartMouseMove);j.remove(this.chart,g.Chart.MOUSE_LEAVE,this.chartMouseLeave)},chartMouseMove:function(c){var a=this._r,b=c.x-this._x,e=c.y-this._y,f;c=this.items;if(b*b+e*e>a*a){this.fire("hidetooltip");this._currentIndex=-1;this.fire("redraw")}else{if(b!=0){a=Math.atan(e/b);if(e<0&&b>0)a+=2*Math.PI;if(b<0)a+=Math.PI}else a=e>=0?Math.PI/2:3*Math.PI/2;for(i=c.length-
1;i>=0;i--){e=c[i];b=e._currentStart;e=e._currentEnd;if(b>e){f=b;b=e;e=f}f=e-b;b%=Math.PI*2;if(b<0)if(b+f<0||a>Math.PI)b+=Math.PI*2;if(a>b&&a<b+f&&i!==this._currentIndex){this._currentIndex=i;this.fire("redraw");this.fire("showtooltip",{message:this.data.elements()[i].label})}}}},chartMouseLeave:function(){this._currentIndex=-1;this.fire("hidetooltip");this.fire("redraw")}});return g.PieElement=o},{requires:["./element"]});
