KISSY.add("gallery/kcharts/1.1/linechart/index",function(i,o,r,t,n,y,w,z,A,j,B,C,p){var g=i.all,m=i.Event,k="ks-chart-default",x=["circle","triangle","rhomb","square"],s,o=function(a){this._cfg=a;this.init()};i.extend(o,n,{init:function(){n.prototype.init.call(this,this._cfg);this.chartType="linechart";if(this._$ctnNode[0]){var a={themeCls:k,autoRender:!0,comparable:!1,lineType:"straight",colors:[],title:{content:"",css:{"text-align":"center","font-size":"16px"},isShow:!0},subTitle:{content:"",css:{"text-align":"center",
"font-size":"12px"},isShow:!0},points:{attr:{type:"circle",stroke:"#fff",r:4,"stroke-width":1.5,fill:"{COLOR}"},hoverAttr:{type:"circle",stroke:"#fff",r:5,fill:"{COLOR}","stroke-width":0}},xLabels:{isShow:!0,css:{color:"#666","font-size":"12px","white-space":"nowrap",position:"absolute"}},yLabels:{isShow:!0,css:{color:"#666","font-size":"12px","white-space":"nowrap",position:"absolute"}},xAxis:{isShow:!0,css:{zIndex:10}},yAxis:{isShow:!0,css:{zIndex:10},num:5},xGrids:{isShow:!0,css:{}},yGrids:{isShow:!0,
css:{}},areas:{isShow:!0,css:{}},line:{isShow:!0,attr:{"stroke-width":"3px"},hoverAttr:{"stroke-width":"4px"}},pointLines:{isShow:!1,css:{}},legend:{isShow:!1},tip:{isShow:!0,clsName:"",template:"",css:{},offset:{x:0,y:0},boundryDetect:!0}};this._lines={};this._finished=[];k=this._cfg.themeCls||a.themeCls;this._cfg=i.mix(i.mix(a,A[k],j,j,!0),this._cfg,j,j,!0);this.color=s=new y({themeCls:k});0<this._cfg.colors.length&&s.removeAllColors();for(var b in this._cfg.colors)s.setColor(this._cfg.colors[b]);
this._cfg.autoRender&&this.render(!0)}},drawTitle:function(){var a=this.htmlPaper,b=k+"-title",c=this._cfg,d=0.6*this._innerContainer.y;c.title.isShow&&""!=c.title.content&&(this._title=a.rect(0,0,this._$ctnNode.width(),d).addClass(b).css(i.mix({"line-height":d+"px"},c.title.css)).html(c.title.content))},drawSubTitle:function(){var a=this.htmlPaper,b=k+"-subtitle",c=this._cfg,d=this._innerContainer,e=0.4*d.y;c.subTitle.isShow&&""!=c.subTitle.content&&(this._subTitle=a.rect(0,0.6*d.y,this._$ctnNode.width(),
e).addClass(b).css(i.mix({"line-height":e+"px"},c.subTitle.css)).html(c.subTitle.content))},getRealPointsNum:function(a){var b=0,c;for(c in a)a[c].x&&a[c].y&&b++;return b},getVisableLineNum:function(){for(var a=this._cfg,b=a.series.length,c=b,d=0;d<b;d++)!1==a.series[d].isShow&&c--;return c},drawLine:function(a,b){var c=this._points[a];if(c&&c.length){var d=this.getLinePath(c),e=this.paper,c=this.color.getColor(a).DEFAULT,d=e.path(d).attr(i.mix(this._cfg.line.attr,{stroke:c})),e=this.getVisableLineNum();
this._stocks[a].stocks=this.drawStocks(a,this.processAttr(this._cfg.points.attr,c));this._finished.push(!0);this._finished.length==e&&b&&b();return d}},animateLine:function(a,b){var c=this,d=c._cfg,e=c.paper,f=c._points[a],l=c._stocks[a].type,h=c.getLinePath(f),D=t.getTotalLength(h),E=f.length||0,g=c.getRealPointsNum(f),j=d.anim?d.anim.duration||500:500,m=c.get("area-width"),k=[],n,q=0,o,p,r,u=i.mix({stroke:s.getColor(a).DEFAULT},d.line.attr),v=e.path(n).attr(u);k[0]=c.drawStock(f[0].x,f[0].y,c.processAttr(d.points.attr,
u.stroke),l);p=c.getVisableLineNum();e=new C({duration:j,easing:"easeNone",onstep:function(a,b){o=b*D;n=t.getSubpath(h,0,o);r=t.pathBBox(n);q=Math.floor(r.width/m);!k[q]&&f[q]&&(k[q]=c.drawStock(f[q].x,f[q].y,c.processAttr(d.points.attr,u.stroke),l));v&&v.attr({path:n})},onend:function(){1<g&&!k[g-1]&&f[g-1]&&(k[g-1]=c.drawStock(f[g-1].x,f[g-1].y,c.processAttr(d.points.attr,u.stroke),l));c._stocks[a].stocks=k;c._finished.push(!0);c._finished.length==p&&b&&b()}});e.INTERVAL=j/E/8||25;e.run();return v},
getLinePath:function(a){for(var b="",c=this.getRealPointsNum(a),d=0;!a||!a[d]||!a[d].x||!a[d].y;)if(d<c)d++;else break;if(d>=c)throw Error("\u6570\u636e\u683c\u5f0f\u6709\u8bef\uff0c\u8bf7\u68c0\u67e5defineKey\u7684\u503c");b+="M"+a[d].x+","+a[d].y;if("arc"==this._cfg.lineType&&2<c){b+=" R";d+=1;for(c=a.length;d<c;d++)a[d].x&&a[d].y&&(b+=a[d].x+","+a[d].y+" ")}else{d+=1;for(c=a.length;d<c;d++)a[d].x&&a[d].y&&(b+=" L"+a[d].x+","+a[d].y)}return b},drawLines:function(a){var b=this._cfg,c=x.length;this._lines={};this._stocks={};for(var d in this._points){var e=
this.getLinePath(this._points[d]),f=s.getColor(d),l=this.processAttr(this._cfg.points.attr,f.DEFAULT),h=this.processAttr(this._cfg.points.hoverAttr,f.HOVER);this._stocks[d]={points:this._points[d],color:f,attr:l,hoverAttr:h,type:"auto"==l.type?x[d%c]:l.type};l=b.anim?!1==b.series[d].isShow?j:this.animateLine(d,a):!1==b.series[d].isShow?j:this.drawLine(d,a);this._lines[d]={line:l,path:e,points:this._points[d],color:f,attr:i.mix({stroke:f.DEFAULT},this._cfg.line.attr)}}return this._lines},processAttr:function(a,
b){var c=i.clone(a),d;for(d in c)c[d]&&"string"==typeof c[d]&&(c[d]=c[d].replace("{COLOR}",b));return c},drawStocks:function(a,b){var c=[],d=this._points[a],e=this._stocks[a].type,f;for(f in d)d[f].x&&d[f].y?c.push(this.drawStock(d[f].x,d[f].y,b,e)):c.push("");return c},drawStock:function(a,b,c,d){var e=this.paper,f=this._cfg.points.attr;if(a&&b){switch(d){case "triangle":a=p.triangle(e,a,b,6);break;case "rhomb":a=p.rhomb(e,a,b,10,10);break;case "square":a=p.rhomb(e,a,b,10,10,45);break;default:a=
e.circle(a,b,f.r,c)}return a.attr(f).attr(c)}},drawGridsX:function(){var a=this._points[0],b=[];if(1<a.length){var c=(a[1].x-a[0].x)/2;b.push({x:a[0].x-c});for(var d in a)b.push({x:a[d].x- -c})}a=0;for(c=b.length;a<c;a++)this._gridsX.push(this.drawGridX(b[a]));return this._gridsX},drawGridX:function(a){var b=this._cfg.themeCls+"-gridsx";return this.htmlPaper.lineY(a.x,this._innerContainer.tl.y,this._innerContainer.height).addClass(b).css(this._cfg.xGrids.css)},drawGridY:function(a,b){var c=this._innerContainer.width,
b=b||this._cfg.yGrids.css,d=this._cfg.themeCls+"-gridsy";return this.htmlPaper.lineX(a.x,a.y,c).addClass(d).css(b)},drawGridsY:function(){for(var a=this._innerContainer.tl.x,b=this._pointsY,c=0,d=b.length;c<d;c++)this._gridsY[c]={"0":this.drawGridY({x:a,y:b[c].y}),num:this.coordNum[c]}},drawAreas:function(){var a=this._innerContainer,b=a.tl.y,c=this._points[0],a=Math.round(c&&c[0]&&c[1]&&c[1].x-c[0].x||a.width),d=Math.round(this._innerContainer.height),e=this.htmlPaper,f=this._cfg.themeCls+"-areas",
l=this._cfg.areas.css;this.set("area-width",a);for(var h=0,g=c.length;h<g;h++)this._areas.push(e.rect(c[h].x-a/2,b,a,d).addClass(f).css(l))},drawAxisX:function(){var a=this._innerContainer,b=a.bl,c=this._cfg.themeCls+"-axisx";return this._axisX=this.htmlPaper.lineX(b.x,b.y,a.width).addClass(c).css(this._cfg.xAxis.css||{})},drawAxisY:function(){var a=this._innerContainer,b=a.tl,c=this._cfg.themeCls+"-axisy";return this._axisY=this.htmlPaper.lineY(b.x,b.y,a.height).addClass(c).css(this._cfg.yAxis.css||
{})},drawLabelsX:function(){var a=this._cfg.xAxis.text,b;for(b in a)this._labelX[b]=this.drawLabelX(b,a[b])},drawLabelsY:function(){for(var a in this._pointsY)this._labelY[a]={"0":this.drawLabelY(a,this._pointsY[a].number),num:this._pointsY[a].number};return this._labelY},drawLabelX:function(a,b){var c=this.htmlPaper,d=this._pointsX,e=this._cfg.themeCls+"-xlabels",f;f="";if(a<(d.length||0))return f=this._cfg.xLabels.template||"{{data}}",f=i.isFunction(f)?f(a,b):r(f).render({data:b}),d=d[a],d[0]=c.text(d.x,
d.y,"<span class="+e+">"+f+"</span>","center").children().css(this._cfg.xLabels.css),d[0]},drawLabelY:function(a,b){var c=this.htmlPaper,d=this._cfg.themeCls+"-ylabels",e;e="";e=this._cfg.yLabels.template||"{{data}}";return(e=i.isFunction(e)?e(a,b):r(e).render({data:b}))&&c.text(this._pointsY[a].x,this._pointsY[a].y,"<span class="+d+">"+e+"</span>","right","middle").children().css(this._cfg.yLabels.css)},drawPointLines:function(){var a=this.htmlPaper,b=this._cfg.themeCls+"-pointlines",c=this._innerContainer;
this._pointlines=[];for(var d in this._pointsX)this._pointlines.push(a.lineY(this._pointsX[d].x,c.tl.y,c.height).addClass(b).css(this._cfg.pointLines.css).css({display:"none"}));return this._pointlines},renderTip:function(){var a=this._cfg,b=this._innerContainer,a=i.mix(a.tip,{rootNode:this._$ctnNode,clsName:a.themeCls,boundry:a.tip.boundryDetect?{x:b.tl.x,y:b.tl.y,width:b.width,height:b.height}:{}},j,j,!0);return this.tip=new B(a)},renderEvtLayout:function(){var a=this._innerContainer,b=this._points[0],
c=b&&b[0]&&b[1]&&b[1].x-b[0].x||a.width,d=a.height,e=this._multiple,f=this._evtEls._areas=[],l=this._evtEls._rects=[],h;h=this._evtEls.paper?this._evtEls.paper:this._evtEls.paper=new w(this._$ctnNode,{clsName:"ks-chart-evtlayout",prependTo:!1,width:a.width,height:d,left:a.tl.x,top:a.tl.y,css:{"z-index":20,background:"#fff",filter:"alpha(opacity =1)","-moz-opacity":0.01,"-khtml-opacity":0.01,opacity:0.01}});for(var g=0,l=b.length;g<l;g++)f[g]=h.rect(b[g].x-c/2,a.tl.y,c,d).addClass("ks-chart-evtlayout-areas");
if(e)for(g in this._stocks)if(a=this._stocks[g],l=[],b=a.points,a.stocks){for(var i in b)l[i]=h.rect(b[i].x-c/2,b[i].y-5,c,10).attr({line_index:g,index:i}).addClass("ks-chart-evtlayout-rects");this._evtEls._rects[g]=l}},clearEvtLayout:function(){if(this._evtEls._areas)for(var a in this._evtEls._areas)this._evtEls._areas[a].remove();if(this._evtEls._rects)for(a in this._evtEls._rects)for(var b in this._evtEls._rects[a])this._evtEls._rects[a][b].remove()},renderLegend:function(){var a=this._cfg.legend,
b=a.container&&g(a.container)[0]?g(a.container):this._$ctnNode;return this.legend=new z({container:b,evtBind:!0,chart:this,iconType:"circle",css:a.css||{}})},render:function(a){var b=this,c=b._cfg,d=c.themeCls;a&&b._$ctnNode.html("");b.paper=t(b._$ctnNode[0],c.width,c.height);b.htmlPaper=new w(b._$ctnNode,{clsName:d});b.drawTitle();b.drawSubTitle();c.tip.isShow&&b.renderTip();c.areas.isShow&&b.drawAreas();c.xGrids.isShow&&b.drawGridsX();c.yGrids.isShow&&b.drawGridsY();b._cfg.comparable&&b.drawPointLines();
c.xAxis.isShow&&b.drawAxisX();c.yAxis.isShow&&b.drawAxisY();c.xLabels.isShow&&b.drawLabelsX();c.yLabels.isShow&&b.drawLabelsY();b.drawLines(function(){b.renderEvtLayout();b.bindEvt();c.legend.isShow&&b.renderLegend();i.log("finish");b.afterRender()});i.log(b)},bindEvt:function(){var a=this,b=a._evtEls,c=a._cfg.themeCls+"-areas-hover",d=function(){for(var b in a._stocks)if(a._stocks[b].stocks)return b}(),e=a._points[d],f=a._stocks[d];m.detach(g(".ks-chart-evtlayout-rects",g(".ks-chart-evtlayout",a._$ctnNode)),
"mouseenter");d&&m.on(g(".ks-chart-evtlayout-rects",g(".ks-chart-evtlayout",a._$ctnNode)),"mouseenter",function(b){var c=g(b.currentTarget),b=c.attr("index"),c=c.attr("line_index");d!=c&&(d=c,a.lineChangeTo(d));m.fire(g(".ks-chart-evtlayout-areas",g(".ks-chart-evtlayout",a._$ctnNode))[b],"mouseenter")});m.detach(g(".ks-chart-evtlayout-areas",g(".ks-chart-evtlayout",a._$ctnNode)),"mouseenter");d&&m.on(g(".ks-chart-evtlayout-areas",g(".ks-chart-evtlayout",a._$ctnNode)),"mouseenter",function(){var b=
i.indexOf(this,g(".ks-chart-evtlayout-areas",g(".ks-chart-evtlayout",a._$ctnNode)));f=a._stocks[d];for(var h in a._stocks)for(var k in a._stocks[h].stocks)a._stocks[h].stocks[k]&&a._stocks[h].stocks[k].attr&&a._stocks[h].stocks[k].attr(a._stocks[h].attr);if(e&&e[b]&&e[b].y){if(a._pointlines){for(h in a._pointlines)a._pointlines[h].hide();a._pointlines[b].show()}if(a._cfg.comparable)for(h in a._stocks)a._stocks[h].stocks&&a._stocks[h].stocks[b]&&a._stocks[h].stocks[b].attr&&a._stocks[h].stocks[b].attr(a._stocks[h].hoverAttr);
else f.stocks[b]&&f.stocks[b].attr&&f.stocks[b].attr(f.hoverAttr);a._areas[b].addClass(c).siblings().removeClass(c);a._points[d][b].dataInfo&&(a.stockChange(d,b),a._cfg.tip.isShow&&a.tipHandler(d,b))}a.areaChange(b)});m.detach(b.paper.$paper,"mouseleave");d&&m.on(b.paper.$paper,"mouseleave",function(){a._lines[d].line.attr(a._lines[d].attr);a.tip&&a.tip.hide();for(var b in a._pointlines)a._pointlines[b].hide();for(b in a._areas)a._areas[b].removeClass(a._cfg.themeCls+"-areas-hover");for(b in a._stocks)for(var c in a._stocks[b].stocks)a._stocks[b].stocks[c]&&
a._stocks[b].stocks[c].attr&&a._stocks[b].stocks[c].attr(a._stocks[b].attr);a.paperLeave()})},lineChangeTo:function(a){var b=this._cfg;if(!this._isAnimating){for(var c in this._stocks)this._stocks[c].points=this._points[c];for(c in this._lines)c!=a&&this._lines[c].line&&this._lines[c].line.attr(this._lines[c].attr);this._lines[a].line.remove();for(c in this._stocks[a].stocks)this._stocks[a].stocks[c].remove&&this._stocks[a].stocks[c].remove();this._lines[a].line=this.drawLine(a).attr(b.line.hoverAttr);
for(c in this._stocks)for(var d in this._stocks[c].stocks)this._stocks[c].stocks[d]&&(a=this._stocks[c].stocks[d],a.attr&&a.attr(this._stocks[c].attr))}},hideLine:function(a){var b=this,c;n.prototype.removeData.call(b,a);b.animateGridsAndLabels();b._lines[a].line.remove();for(var d in b._stocks){if(a==d){for(var e in b._stocks[a].stocks)b._stocks[a].stocks[e]&&b._stocks[a].stocks[e].remove();delete b._stocks[a].stocks}b._stocks[d].points=b._points[d]}for(d in b._lines)if(d!=a&&(c=b.getLinePath(b._points[d]),
b._lines[d].path!=c&&""!=c))for(e in b._isAnimating=!0,b._lines[d].line&&b._lines[d].line.stop()&&b._lines[d].line.animate({path:c},500,function(){b._isAnimating=!1}),b._lines[d].path=c,b._stocks[d].stocks)b._stocks[d].stocks[e]&&(c=b._stocks[d].stocks[e],c.stop().animate({transform:"T"+(b._stocks[d].points[e].x-b._stocks[d].stocks[e].attr("cx"))+","+(b._stocks[d].points[e].y-b._stocks[d].stocks[e].attr("cy"))},500));b.clearEvtLayout();b.renderEvtLayout();b.bindEvt();i.log(b)},showLine:function(a){var b=
this;b._cfg.series[a].isShow=!0;n.prototype.recoveryData.call(b,a);b.animateGridsAndLabels();b._lines[a].line=b.drawLine(a);for(var c in b._stocks)b._stocks[c].points=b._points[c];for(c in b._lines)if(a=b.getLinePath(b._points[c]),b._lines[c].path!=a&&b._lines[c].line){b._isAnimating=!0;b._lines[c].line&&b._lines[c].line.stop().animate({path:a},500,function(){b._isAnimating=!1});b._lines[c].path=a;for(var d in b._stocks[c].stocks)b._stocks[c].stocks[d]&&(a=b._stocks[c].stocks[d],a.stop(),a.animate({transform:"T"+
(b._stocks[c].points[d].x-b._stocks[c].stocks[d].attr("cx"))+","+(b._stocks[c].points[d].y-b._stocks[c].stocks[d].attr("cy"))},500))}b.clearEvtLayout();b.renderEvtLayout();b.bindEvt()},animateGridsAndLabels:function(){Math.max(this._pointsY.length,this._gridsY.length);for(var a in this._labelY)this._labelY[a]&&this._labelY[a][0]&&this._labelY[a][0].remove(),this._gridsY[a]&&this._gridsY[a][0]&&this._gridsY[a][0].remove();this.drawGridsY();this.drawLabelsY()},tipHandler:function(a,b){var c=this._lines[a].color.DEFAULT,
d=this.tip,e=this._cfg,f=e.series,g=e.tip.template;d.getInstance();var h=this._points[a][b];if(g){if(this._cfg.comparable){var g={datas:{}},k=[],j;for(j in this._points)if(this._stocks[j].stocks){this._points[j][b].dataInfo.color=this._stocks[j].color.DEFAULT;var m=i.merge(this._points[j][b].dataInfo,f[j]);delete m.data;g.datas[j]=m}for(j in g.datas)k.push(g.datas[j]);g.datas=n.prototype.arraySort(k,!0,"y");f=g}else f=i.merge(this._points[a][b].dataInfo,f[a]),delete f.data;d.fire("setcontent",{data:f});
d.fire("move",{x:h.x,y:h.y,style:this.processAttr(e.tip.css,c)})}},areaChange:function(){this.fire("areaChange",this)},paperLeave:function(){this.fire("paperLeave",this)},stockChange:function(a,b){var c=this._stocks[a];this.fire("stockChange",i.mix({target:c.stocks[b],currentTarget:c.stocks[b],lineIndex:Math.round(a),stockIndex:Math.round(b)},c.points[b]))},afterRender:function(){this.fire("afterRender",this)},getPaper:function(){return this.htmlPaper},clear:function(){this._$ctnNode.html("")}});
return o},{requires:"base,gallery/template/1.0/index,gallery/kcharts/1.1/raphael/index,gallery/kcharts/1.1/basechart/index,gallery/kcharts/1.1/tools/color/index,gallery/kcharts/1.1/tools/htmlpaper/index,gallery/kcharts/1.1/legend/index,gallery/kcharts/1.1/linechart/theme,gallery/kcharts/1.1/tools/touch/index,gallery/kcharts/1.1/tip/index,gallery/kcharts/1.1/ft/index,gallery/kcharts/1.1/tools/graphtool/index".split(",")});
KISSY.add("gallery/kcharts/1.1/linechart/theme",function(){return{"ks-chart-default":{title:{content:"",css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px",color:"#666"},isShow:!0},points:{attr:{stroke:"#fff",r:4,"stroke-width":1.5,fill:"{COLOR}"},hoverAttr:{stroke:"#fff",r:5,fill:"{COLOR}","stroke-width":0}},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},
xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},pointLines:{css:{color:"#ccc"}},tip:{css:{border:"2px solid {COLOR}"}}},"ks-chart-analytiks":{title:{content:"",css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px",color:"#666"},isShow:!0},points:{attr:{type:"circle",stroke:"{COLOR}",fill:"#fff",r:4,"stroke-width":2},hoverAttr:{type:"circle",
stroke:"{COLOR}",fill:"#fff",r:5,"stroke-width":2}},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},pointLines:{css:{color:"#ccc"}},tip:{css:{background:"{COLOR}"}}},"ks-chart-rainbow":{title:{content:"",css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center",
"font-size":"12px",color:"#666"},isShow:!0},points:{attr:{type:"circle",stroke:"#fff",r:4,"stroke-width":1.5,fill:"{COLOR}"},hoverAttr:{type:"circle",stroke:"#fff",r:5,fill:"{COLOR}","stroke-width":0}},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},pointLines:{css:{color:"#ccc"}},tip:{css:{background:"{COLOR}"}}}}});
