KISSY.add("gallery/switchable/1.0/aria",function(h,c,m,i){function g(){this.stop&&this.stop()}function k(){this.start&&this.start()}i.addPlugin({name:"aria",init:function(c){if(c.config.aria){var j=c.container;m.on(j,"focusin",g,c);m.on(j,"focusout",k,c)}}});var l=["a","input","button","object"];return{setTabIndex:function(f,j){f.tabIndex=j;h.each(c.query("*",f),function(f){var e=f.nodeName.toLowerCase();h.inArray(e,l)&&(c.hasAttr(f,"oriTabIndex")||c.attr(f,"oriTabIndex",f.tabIndex),f.tabIndex=-1!=
j?c.attr(f,"oriTabIndex"):j)})}}},{requires:["dom","event","./base"]});
KISSY.add("gallery/switchable/1.0/autoplay",function(h,c,m,i,g){var k=window,l=function(f){var j=c.scrollTop(),n=c.viewportHeight(),e=c.offset(f),f=c.height(f);return e.top>j&&e.top+f<j+n};h.mix(i.Config,{pauseOnScroll:!1,autoplay:!1,interval:5,pauseOnHover:!0});i.addPlugin({name:"autoplay",init:function(c){function j(){d=h.later(function(){c.paused||c.next()},e,!0)}var n=c.config,e=1E3*n.interval,d;if(n.autoplay&&(n.pauseOnScroll&&(c.__scrollDetect=h.buffer(function(){c[l(c.container)?"start":"stop"]()},
200),m.on(k,"scroll",c.__scrollDetect)),j(),c.stop=function(){if(d){d.cancel();d=g}c.paused=true},c.start=function(){if(d){d.cancel();d=g}c.paused=false;j()},n.pauseOnHover))m.on(c.container,"mouseenter",c.stop,c),m.on(c.container,"mouseleave",c.start,c)},destroy:function(c){c.__scrollDetect&&(m.remove(k,"scroll",c.__scrollDetect),c.__scrollDetect.stop())}});return i},{requires:["dom","event","./base"]});
KISSY.add("gallery/switchable/1.0/base",function(h,c,m,i){function g(b,a){this._triggerInternalCls=h.guid(e);this._panelInternalCls=h.guid(d);a=a||{};"markupType"in a||(a.panelCls?a.markupType=1:a.panels&&(a.markupType=2));for(var p=this.constructor;p;)a=h.merge(p.Config,a),p=p.superclass?p.superclass.constructor:null;this.container=c.get(b);this.config=a;this.activeIndex=a.activeIndex;var r;-1<this.activeIndex||("number"==typeof a.switchTo?r=a.switchTo:this.activeIndex=0);this._init();this._initPlugins();
this.fire(j);r!==i&&this.switchTo(r)}function k(b){var a={};a.type=b.type;a.target=b.target;return{originalEvent:a}}var l=h.makeArray,f=m.Target,j="init",n="remove",e="ks-switchable-trigger-internal",d="ks-switchable-panel-internal";g.getDomEvent=k;g.addPlugin=function(b,a){for(var a=a||g,c=b.priority=b.priority||0,r=0,e=a.Plugins=a.Plugins||[];r<e.length&&!(e[r].priority<c);r++);e.splice(r,0,b)};g.Config={markupType:0,navCls:"ks-switchable-nav",contentCls:"ks-switchable-content",triggerCls:"ks-switchable-trigger",
panelCls:"ks-switchable-panel",triggers:[],panels:[],hasTriggers:!0,triggerType:"mouse",delay:0.1,activeIndex:-1,activeTriggerCls:"ks-active",switchTo:i,steps:1,viewSize:[]};h.augment(g,f,{_initPlugins:function(){for(var b=this,a=[],c=b.constructor;c;)c.Plugins&&a.push.apply(a,[].concat(c.Plugins).reverse()),c=c.superclass?c.superclass.constructor:null;a.reverse();h.each(a,function(a){a.init&&a.init(b)})},_init:function(){var b=this.config;this._parseMarkup();b.hasTriggers&&this._bindTriggers();this._bindPanels()},
_parseMarkup:function(){var b=this.container,a=this.config,p,e,d=[],f=[];switch(a.markupType){case 0:(p=c.get("."+a.navCls,b))&&(d=c.children(p));e=c.get("."+a.contentCls,b);f=c.children(e);break;case 1:d=c.query("."+a.triggerCls,b);f=c.query("."+a.panelCls,b);break;case 2:d=a.triggers,f=a.panels}this.length=Math.ceil(f.length/a.steps);this.nav=p||a.hasTriggers&&d[0]&&d[0].parentNode;if(a.hasTriggers&&(!this.nav||0==d.length))d=this._generateTriggersMarkup(this.length);this.triggers=l(d);this.panels=
l(f);this.content=e||f[0].parentNode},_generateTriggersMarkup:function(b){var a=this.config,e=this.nav||c.create("<ul>"),d,f;e.className=a.navCls;for(f=0;f<b;f++)d=c.create("<li>"),f===this.activeIndex&&(d.className=a.activeTriggerCls),d.innerHTML=f+1,e.appendChild(d);this.container.appendChild(e);this.nav=e;return c.children(e)},_bindTriggers:function(){var b=this,a=b.config,c=b._triggerInternalCls,e=h.one(b.nav);h.each(b.triggers,function(a){b._initTrigger(a)});e.delegate("click","."+c,function(a){var c=
b._getTriggerIndex(a.currentTarget);b._onFocusTrigger(c,a)});"mouse"===a.triggerType&&e.delegate("mouseenter","."+c,function(a){var c=b._getTriggerIndex(a.currentTarget);b._onMouseEnterTrigger(c,a)}).delegate("mouseleave","."+c,function(){b._onMouseLeaveTrigger()})},_initTrigger:function(b){c.addClass(b,this._triggerInternalCls)},_bindPanels:function(){var b=this;h.each(b.panels,function(a){b._initPanel(a)})},_initPanel:function(b){c.addClass(b,this._panelInternalCls)},_onFocusTrigger:function(b,
a){this._triggerIsValid(b)&&(this._cancelSwitchTimer(),this.switchTo(b,i,k(a)))},_onMouseEnterTrigger:function(b,a){var c=this;if(c._triggerIsValid(b)){var e=k(a);c.switchTimer=h.later(function(){c.switchTo(b,i,e)},1E3*c.config.delay)}},_onMouseLeaveTrigger:function(){this._cancelSwitchTimer()},_triggerIsValid:function(b){return this.activeIndex!==b},_cancelSwitchTimer:function(){this.switchTimer&&(this.switchTimer.cancel(),this.switchTimer=i)},_getTriggerIndex:function(b){return h.indexOf(b,this.triggers)},
_resetLength:function(){this.length=this._getLength()},_getLength:function(b){var a=this.config;b===i&&(b=this.panels.length);return Math.ceil(b/a.steps)},_afterAdd:function(b,a,c){this._resetLength();b=this._getLength(b+1)-1;1==this.config.steps&&this.activeIndex>=b&&(this.activeIndex+=1);var e=this.activeIndex;this.activeIndex=-1;this.switchTo(e);a?this.switchTo(b,i,i,c):c()},add:function(b){var a=b.callback||h.noop,e=this.nav,d=this.content,f=b.trigger,n=b.panel,j=b.active,i=this.panels.length,
b=null!=b.index?b.index:i,g=this.triggers,m=this.panels,k=this.length,o=null,o=null,b=Math.max(0,Math.min(b,i)),i=m[b]||null;m.splice(b,0,n);d.insertBefore(n,i);1==this.config.steps?(o=g[b],e.insertBefore(f,o),g.splice(b,0,f)):(o=this._getLength(),o!=k&&(c.append(f,e),g.push(f)));this._initPanel(n);this._initTrigger(f);this._afterAdd(b,j,a);this.fire("add",{index:b,trigger:f,panel:n})},remove:function(b){function a(){q&&(c.remove(q),m.splice(g,1));if(l){c.remove(l);for(var a=0;a<k.length;a++)if(k[a]==
l){d.triggers.splice(a,1);break}}d._resetLength();d.fire(n,{index:g,trigger:l,panel:q})}var e=b.callback||h.noop,d=this,f=d.config.steps,j=d.length,g,m=d.panels;g="index"in b?b.index:b.panel;var b=d._getLength(m.length-1),k=d.triggers,l=null,q=null;if(m.length&&(g=h.isNumber(g)?Math.max(0,Math.min(g,m.length-1)):h.indexOf(g,m),l=1==f?k[g]:b!==j?k[j-1]:null,q=m[g],!1!==d.fire("beforeRemove",{index:g,panel:q,trigger:l})))if(0==b)a(),e();else{var o=d.activeIndex;1<f?o==b?d.switchTo(o-1,i,i,function(){a();
e()}):(a(),d.activeIndex=-1,d.switchTo(o,i,i,function(){e()})):o==g?d.switchTo(0<o?o-1:o+1,i,i,function(){a();0==o&&(d.activeIndex=0);e()}):(o>g&&(o--,d.activeIndex=o),a(),e())}},switchTo:function(b,a,c,e){var d=this,f=d.config,n=d.activeIndex,j=d.triggers;if(!d._triggerIsValid(b)||!1===d.fire("beforeSwitch",{fromIndex:n,toIndex:b}))return d;d.fromIndex=n;f.hasTriggers&&d._switchTrigger(j[n]||null,j[b]);a===i&&(a=b>n?"forward":"backward");d.activeIndex=b;d._switchView(a,c,function(){e&&e.call(d)});
return d},_switchTrigger:function(b,a){var d=this.config.activeTriggerCls;b&&c.removeClass(b,d);c.addClass(a,d)},_getFromToPanels:function(){var b=this.fromIndex,a;a=this.config.steps;var c=this.panels,d=this.activeIndex,b=-1<b?c.slice(b*a,(b+1)*a):null;a=c.slice(d*a,(d+1)*a);return{fromPanels:b,toPanels:a}},_switchView:function(b,a,d){var e=this,f=e._getFromToPanels(),b=f.fromPanels,f=f.toPanels;b&&c.css(b,"display","none");c.css(f,"display","block");setTimeout(function(){e._fireOnSwitch(a)},0);
d&&d.call(this)},_fireOnSwitch:function(b){this.fire("switch",h.merge(b,{fromIndex:this.fromIndex,currentIndex:this.activeIndex}))},prev:function(b){this.switchTo((this.activeIndex-1+this.length)%this.length,"backward",b)},next:function(b){this.switchTo((this.activeIndex+1)%this.length,"forward",b)},destroy:function(b){for(var a=this,d=a.constructor;d;)h.each(d.Plugins,function(b){b.destroy&&b.destroy(a)}),d=d.superclass?d.superclass.constructor:null;b?m.remove(a.container):c.remove(a.container);
a.nav=null;a.content=null;a.container=null;a.triggers=[];a.panels=[];a.detach()}});return g},{requires:["dom","event"]});
KISSY.add("gallery/switchable/1.0/circular",function(h,c,m,i){function g(f){var e=this,d=e.fromIndex,b=e.config,a=e.length,g="scrollx"===b.scrollType,i=g?"left":"top",h=e.activeIndex,g=e.viewSize[g?0:1],k=e.panels,l={},s={},u,t=e._realStep;u=g*a;l[i]=-g*h;-1==d?(c.css(e.content,l),f&&f()):(h+t>a?(s={position:"relative"},s[i]=u,u=h+t-a,c.css(k.slice(0,u),s),c.css(k.slice(u,t),j)):c.css(k.slice(0,t),j),k=c.css(k[d],"position"),(d+a-h)%a<(h-d+a)%a&&"relative"==k?c.css(e.content,i,-(g*(a+d))):d==a-1&&
0==h?c.css(e.content,i,g):c.css(e.content,i,-(g*d)),e.anim&&e.anim.stop(),e.anim=(new m(e.content,l,b.duration,b.easing,function(){e.anim=0;f&&f()})).run())}function k(n,e){var d=this,b=d.fromIndex,a=d.config,j=d.length,g="scrollx"===a.scrollType,h=g?"left":"top",i=d.activeIndex,k=d.viewSize[g?0:1],g=-k*i,s=d.panels,u=d.config.steps,t={},q,o="backward"===e;q=o&&0===b&&i===j-1||!o&&b===j-1&&0===i;d.anim&&(d.anim.stop(),"relative"==s[b*u].style.position&&f.call(d,s,b,h,k,1));q&&(g=l.call(d,s,i,h,k));
t[h]=g+"px";-1<b?d.anim=(new m(d.content,t,a.duration,a.easing,function(){q&&f.call(d,s,i,h,k,1);d.anim=void 0;n&&n()})).run():(c.css(d.content,t),n&&n())}function l(f,e,d,b){var a=this.config.steps,j=this.length,f=f.slice(e*a,(e+1)*a);c.css(f,"position","relative");c.css(f,d,(e?-1:1)*b*j);return e?b:-b*j}function f(f,e,d,b,a){var j=this.config.steps,g=this.length,f=f.slice(e*j,(e+1)*j);c.css(f,"position","");c.css(f,d,"");a&&c.css(this.content,d,e?-b*(g-1):"")}var j={position:"",left:"",top:""};
h.mix(i.Config,{circular:!1});i.adjustPosition=l;i.resetPosition=f;i.addPlugin({name:"circular",priority:5,init:function(c){var e=c.config,d=e.effect;if(e.circular&&("scrollx"===d||"scrolly"===d))e.scrollType=d,e.effect=c._realStep?g:k}})},{requires:["dom","anim","./base","./effect"]});
KISSY.add("gallery/switchable/1.0/effect",function(h,c,m,i,g,k){var l;h.mix(g.Config,{effect:"none",duration:0.5,easing:"easeNone"});g.Effects={none:function(f){var j=this._getFromToPanels(),g=j.fromPanels,j=j.toPanels;g&&c.css(g,"display","none");c.css(j,"display","block");f&&f()},fade:function(f){var j=this,g=j._getFromToPanels(),e=g.fromPanels,g=g.toPanels;e&&1!==e.length&&h.error("fade effect only supports steps == 1.");var d=j.config,b=e?e[0]:null,a=g[0];j.anim&&(j.anim.stop(),c.css(j.anim.fromEl,
{zIndex:1,opacity:0}),c.css(j.anim.toEl,"zIndex",9));c.css(a,"opacity",1);b?(j.anim=(new i(b,{opacity:0},d.duration,d.easing,function(){j.anim=k;c.css(a,"z-index",9);c.css(b,"z-index",1);f&&f()})).run(),j.anim.toEl=a,j.anim.fromEl=b):(c.css(a,"z-index",9),f&&f())},scroll:function(f,g,h){var e=this,g=e.fromIndex,d=e.config,b="scrollx"===d.effect,a={};a[b?"left":"top"]=-(e.viewSize[b?0:1]*e.activeIndex)+"px";e.anim&&e.anim.stop();h||-1<g?e.anim=(new i(e.content,a,d.duration,d.easing,function(){e.anim=
k;f&&f()})).run():(c.css(e.content,a),f&&f())}};l=g.Effects;l.scrollx=l.scrolly=l.scroll;g.addPlugin({priority:10,name:"effect",init:function(f){var g=f.config,i=g.effect,e=f.panels,d=f.content,b=g.steps,a=e[0],k=f.container,m=f.activeIndex;if("none"!==i)switch(c.css(e,"display","block"),i){case "scrollx":case "scrolly":c.css(d,"position","absolute");"static"==c.css(d.parentNode,"position")&&c.css(d.parentNode,"position","relative");"scrollx"===i&&(c.css(e,"float","left"),c.width(d,"999999px"));f.viewSize=
[g.viewSize[0]||a&&c.outerWidth(a,!0)*b,g.viewSize[1]||a&&c.outerHeight(a,!0)*b];f.viewSize[0]||h.error("switchable must specify viewSize if there is no panels");1==b&&a&&(e=1,d=f.viewSize,a=a.parentNode.parentNode,k=[Math.min(c.width(k),c.width(a)),Math.min(c.height(k),c.height(a))],"scrollx"==i?e=Math.floor(k[0]/d[0]):"scrolly"==i&&(e=Math.floor(k[1]/d[1])),e>g.steps&&(f._realStep=e));break;case "fade":var l=m*b,v=l+b-1,x;h.each(e,function(a,b){x=b>=l&&b<=v;c.css(a,{opacity:x?1:0,position:"absolute",
zIndex:x?9:1})})}}});h.augment(g,{_switchView:function(c,g,i){var e=this,d=e.config.effect;(h.isFunction(d)?d:l[d]).call(e,function(){e._fireOnSwitch(g);i&&i.call(e)},c)}});return g},{requires:["dom","event","anim","./base"]});KISSY.add("gallery/switchable/1.0/index",function(h,c,m,i,g,k){h.mix(c,{Accordion:m,Carousel:i,Slide:g,Tabs:k});return c},{requires:"gallery/switchable/1.0/base,gallery/switchable/1.0/accordion/base,gallery/switchable/1.0/carousel/base,gallery/switchable/1.0/slide/base,gallery/switchable/1.0/tabs/base,gallery/switchable/1.0/lazyload,gallery/switchable/1.0/effect,gallery/switchable/1.0/circular,gallery/switchable/1.0/carousel/aria,gallery/switchable/1.0/autoplay,gallery/switchable/1.0/aria,gallery/switchable/1.0/tabs/aria,gallery/switchable/1.0/accordion/aria".split(",")});
KISSY.add("gallery/switchable/1.0/lazyload",function(h,c,m){var i="beforeSwitch",g="img",k="textarea",l={};l[g]="lazyImgAttribute";l[k]="lazyTextareaClass";h.mix(m.Config,{lazyImgAttribute:"data-ks-lazyload-custom",lazyTextareaClass:"ks-datalazyload-custom",lazyDataType:k});m.addPlugin({name:"lazyload",init:function(f){function j(a){var h=f._realStep||e.steps,a=a.toIndex*h;m.loadCustomLazyData(f.panels.slice(a,a+h),d,b);a:{var l,w,v;if(a=(h=d===g)?"img":d===k?"textarea":""){a=c.query(a,f.container);
l=0;for(v=a.length;l<v;l++)if(w=a[l],h?c.attr(w,b):c.hasClass(w,b)){h=!1;break a}}h=!0}h&&f.detach(i,j)}var m=h.require("datalazyload"),e=f.config,d=e.lazyDataType,b;"img-src"===d?d=g:"area-data"===d&&(d=k);e.lazyDataType=d;b=e[l[d]];m&&d&&b&&(f.on(i,j),j({toIndex:f.activeIndex}))}});return m},{requires:["dom","./base"]});
