KISSY.add("gallery/kscroll/1.0/index",function(i,m){function j(a,b){j.superclass.constructor.call(this,b);this._init(a)}var k=m.all,l=function(a){return isNaN(parseInt(a))?0:parseInt(a)};j.ATTRS={prefix:{value:"ks-"},duration:{value:0.1},easing:{value:"easeNone"},container:{},body:{},track:{},drag:{},arrowUp:{},allowArrow:{value:!0},arrowDown:{},step:{}};i.extend(j,i.Base,{_init:function(a){var b="."+this.get("prefix"),a=this._wrap(k(a));this.set("container",a);this.set("body",a.one(b+"body"));this.set("track",
a.one(b+"track"));this.set("drag",this.get("track").one(b+"drag"));this.get("allowArrow")?(this.set("arrowUp",a.one(b+"arrowup")),this.arrowUpHeight=this.get("arrowUp").outerHeight(),this.set("arrowDown",a.one(b+"arrowdown")),this.arrowDownHeight=this.get("arrowDown").outerHeight()):this.arrowUpHeight=this.arrowDownHeight=0;this._bindEvt();this._setSize()},destroy:function(){var a=this.get("container");this.get("track");var b=this.get("arrowUp"),c=this.get("arrowDown"),d=a.children().item(0);b&&b.remove();
c&&c.remove();d.insertBefore(a);a.remove();d.css(this.__backup);d.removeClass(this.get("prefix")+"body")},_wrap:function(a){var b=this.get("prefix"),c=k("<div></div>");6==i.UA.ie&&a.css({overflow:"auto"});c.insertAfter(a).append(a);c.addClass(b+"container").css({position:"relative",overflow:"hidden",width:a.outerWidth(),height:a.outerHeight()});c.append(i.substitute('<div class="{prefix}track" style="position: absolute;right:0;"><div class="{prefix}drag" style="position: absolute;left:0;overflow:hidden;"><div class="{prefix}dragtop"></div><div class="{prefix}dragbottom"></div><div class="{prefix}dragcenter"></div></div></div>',
{prefix:b}));this.get("allowArrow")&&(c.append(i.substitute('<a href="javascript:void(\'scroll {type}\')" style="position: absolute;right:0;text-indent:-9999px;{style};" class="{prefix}arrow{type}">scroll {type}</a>',{type:"up",style:"top:0px;",prefix:b})),c.append(i.substitute('<a href="javascript:void(\'scroll {type}\')" style="position: absolute;right:0;text-indent:-9999px;{style};" class="{prefix}arrow{type}">scroll {type}</a>',{type:"down",style:"bottom:0px;",prefix:b})));var d=a[0].style;this.__backup=
{position:d.position,top:d.top,left:d.left,width:d.width,height:d.height,overflow:d.overflow};a.css({position:"absolute",top:0,left:0,width:"100%",height:"auto",overflow:"visible"}).addClass(b+"body");return c},_bindArrow:function(a){var b=this,c=a.charAt(0).toUpperCase()+a.substring(1),d=0,f=null,e=b.get("prefix"),g=b.get("arrow"+c),h=function(){d+=1;var c=b.get("step"),e=300-25*d;b.scrollByDistance("up"==a?c:-c);30>=e&&(e=30);f=setTimeout(function(){h()},e)};g.on("click",function(){var c=b.get("step");
b.scrollByDistance("up"==a?c:-c)}).on("mousedown",function(){g.addClass(e+"arrow"+a+"-active");h()}).on("mouseup",function(){g.removeClass(e+"arrow"+a+"-active");d=0;clearTimeout(f)}).on("mouseleave",function(){g.removeClass(e+"arrow"+a+"-active");d=0;g.removeClass(e+"arrow"+a+"-hover");clearTimeout(f)}).on("mouseover",function(){g.addClass(e+"arrow"+a+"-hover")})},_bindDrag:function(){var a=k(document),b=this,c,d=b.get("prefix"),f=0,e=b.get("drag"),g=b.get("track"),h=function(a){var d=g.outerHeight(),
h=e.outerHeight(),d=d-h,a=f+(a.pageY-c);0>a&&(a=0);a>d&&(a=d);e.css("top",a);b.scrollByPercent(a/d,1)};e.on("mouseenter",function(){e.addClass(d+"drag-hover")}).on("mouseleave",function(){e.removeClass(d+"drag-hover")}).on("click",function(a){a.stopPropagation()}).on("mousedown",function(b){e.addClass(d+"drag-active");f=parseInt(e.css("top"))||0;c=b.pageY;a.on("mousemove",h).on("mouseup",function(){e.removeClass(d+"drag-active");a.detach("mousemove",h);a.detach("mouseup",arguments.callee);c=0})})},
_bindHotkey:function(){var a=this,b=a.get("body"),c=a.get("container");c.css("outline","none").attr("tabindex",i.guid()).on("keydown",function(d){var f=d.keyCode,e=a.get("step");if(~"38,39,36,40,37,35".indexOf(f)){var g=~"38,39,36".indexOf(f)?e:-e,h=l(b.css("top"));!(0<g&&0<=h||0>g&&h+b.outerHeight()<=c.outerHeight())&&d.halt();switch(f){case 38:case 39:a.scrollByDistance(e);break;case 40:case 37:a.scrollByDistance(-e);break;case 36:a.scrollByPercent(0);break;case 35:a.scrollByPercent(1)}}})},_bindTrack:function(){var a=
this,b=a.get("prefix"),c=a.get("track");c.unselectable().on("click",function(b){a.scrollByPercent((b.pageY-c.offset().top)/c.outerHeight())}).on("mousedown",function(a){a.preventDefault()}).on("mouseenter",function(){c.addClass(b+"track-hover")}).on("mouseleave",function(){c.removeClass(b+"track-hover")})},_bindContainer:function(){var a=this,b=a.get("body"),c=a.get("container");a.get("container").on("mousewheel",function(d){var f=d.deltaY,e=l(b.css("top"));!(0<f&&0<=e||0>f&&e+b.outerHeight()<=c.outerHeight())&&
d.halt();f=a.get("step");a.scrollByDistance(0<d.deltaY?f:-f)})},_bindEvt:function(){this._bindContainer();this.get("allowArrow")&&(this._bindArrow("up"),this._bindArrow("down"));this._bindTrack();this._bindDrag();this._bindHotkey()},resize:function(a,b){this.get("container").css({width:a,height:b});this._setSize()},_setSize:function(){var a=this.get("body").outerHeight(),b=this.get("container").innerHeight(),c=this.get("arrowUp"),d=this.get("arrowDown"),f=this.get("track"),e=this.get("drag"),g=this.arrowUpHeight+
this.arrowDownHeight;a<=b||b<g?(this.get("body").css({top:0}),f.hide(),c&&c.hide(),d&&d.hide()):(f.show(),c&&c.show(),d&&d.show(),a=(b-g)*b/a,20>a&&(a=20),this.get("step")||this.set("step",Math.max(a/6,10)),f.css({height:b-g,top:this.arrowUpHeight}),e.css({height:a}))},_scrollBodyToPosition:function(a){var b=this.get("container"),c=this.get("body"),b=c.outerHeight()-b.innerHeight();0>b||(0<a&&(a=0),(0>a?-a:a)>b&&(a=-b),c.css("top",a))},scrollByDistance:function(a,b){this._scrollBodyToPosition(parseInt(this.get("body").css("top"))+
a);b||this._updateBar()},scrollByPercent:function(a,b){a=parseFloat(a,10);if(!isNaN(a)&&!(1<a||0>a))this._scrollBodyToPosition((this.get("body").outerHeight()-this.get("container").innerHeight())*-a),b||this._updateBar()},scrollToElement:function(a){a=k(a);a.length&&(this._scrollBodyToPosition(-(a.offset().top-this.get("body").offset().top)),this._updateBar())},_updateBar:function(){var a=this.get("drag"),b=this.get("track").innerHeight()-a.outerHeight(),c=this.get("body"),d=this.get("container"),
f=parseInt(c.css("top")),c=(0>f?-f:f)/(c.outerHeight()-d.innerHeight());a.css("top",c*b)}});return j},{requires:["node"]});
