KISSY.add("gallery/kscroll/1.0/index",function(j,n){function l(a,b){l.superclass.constructor.call(this,b);this._init(a)}var m=n.all;l.ATTRS={prefix:{value:"ks-"},duration:{value:0.1},easing:{value:"easeNone"},container:{},body:{},track:{},drag:{},arrowUp:{},allowArrow:{value:true},arrowDown:{},step:{}};j.extend(l,j.Base,{_init:function(a){var b="."+this.get("prefix");a=this._wrap(m(a));this.set("container",a);this.set("body",a.one(b+"body"));this.set("track",a.one(b+"track"));this.set("drag",this.get("track").one(b+
"drag"));if(this.get("allowArrow")){this.set("arrowUp",a.one(b+"arrowup"));this.arrowUpHeight=this.get("arrowUp").outerHeight();this.set("arrowDown",a.one(b+"arrowdown"));this.arrowDownHeight=this.get("arrowDown").outerHeight()}else this.arrowUpHeight=this.arrowDownHeight=0;this._bindEvt();this._setSize()},destroy:function(){var a=this.get("container");this.get("track");var b=this.get("arrowUp"),c=this.get("arrowDown"),d=a.children().item(0);b&&b.remove();c&&c.remove();d.insertBefore(a);a.remove();
d.css(this.__backup);d.removeClass(this.get("prefix")+"body")},_wrap:function(a){var b=this.get("prefix"),c=m("<div></div>");c.insertAfter(a).append(a);c.addClass(b+"container").css({position:"relative",overflow:"hidden",width:a.outerWidth(),height:a.outerHeight()});c.append(j.substitute('<div class="{prefix}track" style="position: absolute;right:0;"><div class="{prefix}drag" style="position: absolute;left:0;overflow:hidden;"><div class="{prefix}dragtop"></div><div class="{prefix}dragbottom"></div><div class="{prefix}dragcenter"></div></div></div>',
{prefix:b}));if(this.get("allowArrow")){c.append(j.substitute('<a href="javascript:void(\'scroll {type}\')" style="position: absolute;right:0;text-indent:-9999px;{style};" class="{prefix}arrow{type}">scroll {type}</a>',{type:"up",style:"top:0px;",prefix:b}));c.append(j.substitute('<a href="javascript:void(\'scroll {type}\')" style="position: absolute;right:0;text-indent:-9999px;{style};" class="{prefix}arrow{type}">scroll {type}</a>',{type:"down",style:"bottom:0px;",prefix:b}))}var d=a[0].style;this.__backup=
{position:d.position,top:d.top,left:d.left,width:d.width,height:d.height,overflow:d.overflow};a.css({position:"absolute",top:0,left:0,width:"100%",height:"auto",overflow:"visible"}).addClass(b+"body");return c},_bindArrow:function(a){var b=this,c=a.charAt(0).toUpperCase()+a.substring(1),d=0,g=null,f=b.get("prefix"),h=b.get("arrow"+c),k=function(){d+=1;var e=b.get("step"),i=300-d*25;b.scrollByDistance(a=="up"?e:-e);if(i<=30)i=30;g=setTimeout(function(){k()},i)};h.on("click",function(){var e=b.get("step");
b.scrollByDistance(a=="up"?e:-e)}).on("mousedown",function(){h.addClass(f+"arrow"+a+"-active");k()}).on("mouseup",function(){h.removeClass(f+"arrow"+a+"-active");d=0;clearTimeout(g)}).on("mouseleave",function(){h.removeClass(f+"arrow"+a+"-active");d=0;h.removeClass(f+"arrow"+a+"-hover");clearTimeout(g)}).on("mouseover",function(){h.addClass(f+"arrow"+a+"-hover")})},_bindDrag:function(){var a=m(document),b=this,c,d=b.get("prefix"),g=0,f=b.get("drag"),h=b.get("track"),k=function(e){var i=h.outerHeight(),
o=f.outerHeight();i=i-o;e=g+(e.pageY-c);if(e<0)e=0;if(e>i)e=i;f.css("top",e);b.scrollByPercent(e/i,1)};f.on("mouseenter",function(){f.addClass(d+"drag-hover")}).on("mouseleave",function(){f.removeClass(d+"drag-hover")}).on("click",function(e){e.stopPropagation()}).on("mousedown",function(e){f.addClass(d+"drag-active");g=parseInt(f.css("top"))||0;c=e.pageY;a.on("mousemove",k).on("mouseup",function(){f.removeClass(d+"drag-active");a.detach("mousemove",k);a.detach("mouseup",arguments.callee);c=0})})},
_bindTrack:function(){var a=this,b=a.get("prefix"),c=a.get("track");c.unselectable().on("click",function(d){a.scrollByPercent((d.pageY-c.offset().top)/c.outerHeight())}).on("mousedown",function(d){d.preventDefault()}).on("mouseenter",function(){c.addClass(b+"track-hover")}).on("mouseleave",function(){c.removeClass(b+"track-hover")})},_bindContainer:function(){var a=this;a.get("container").on("mousewheel",function(b){b.halt();var c=a.get("step");a.scrollByDistance(b.deltaY>0?c:-c)})},_bindEvt:function(){this._bindContainer();
if(this.get("allowArrow")){this._bindArrow("up");this._bindArrow("down")}this._bindTrack();this._bindDrag()},resize:function(a,b){this.get("container").css({width:a,height:b});this._setSize()},_setSize:function(){var a=this.get("body").outerHeight(),b=this.get("container").innerHeight(),c=this.get("arrowUp"),d=this.get("arrowDown"),g=this.get("track"),f=this.get("drag"),h=this.arrowUpHeight+this.arrowDownHeight;if(a<b||b<h){g.hide();c&&c.hide();d&&d.hide()}else{g.show();c&&c.show();d&&d.show();a=
(b-h)*b/a;if(a<20)a=20;this.get("step")||this.set("step",Math.max(a/6,10));g.css({height:b-h,top:this.arrowUpHeight});f.css({height:a})}},_scrollBodyToPosition:function(a){var b=this.get("container"),c=this.get("body");b=c.outerHeight()-b.innerHeight();if(!(b<0)){if(a>0)a=0;if((a<0?-a:a)>b)a=-b;c.css("top",a)}},scrollByDistance:function(a,b){this._scrollBodyToPosition(parseInt(this.get("body").css("top"))+a);b||this._updateBar()},scrollByPercent:function(a,b){a=parseFloat(a,10);if(!(isNaN(a)||a>1||
a<0)){this._scrollBodyToPosition((this.get("body").outerHeight()-this.get("container").innerHeight())*-a);b||this._updateBar()}},scrollToElement:function(a){a=m(a);if(a.length){this._scrollBodyToPosition(-(a.offset().top-this.get("body").offset().top));this._updateBar()}},_updateBar:function(){var a=this.get("drag"),b=this.get("track").innerHeight()-a.outerHeight(),c=this.get("body"),d=this.get("container"),g=parseInt(c.css("top"));c=(g<0?-g:g)/(c.outerHeight()-d.innerHeight());a.css("top",c*b)}});
return l},{requires:["node"]});
