KISSY.add("gallery/kcharts/1.0/barchart/index",function(f,l,t,o,u,p){var i=f.all,k=f.Event,m="ks-chart-default",q=m+"-canvas",h,r=function(b){this.init(b)};f.extend(r,l,{init:function(b){l.prototype.init.call(this,b);b={themeCls:m,autoRender:!0,colors:[],title:{content:"",css:{"text-align":"center","font-size":"16px"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px"},isShow:!0},xLabels:{isShow:!0,css:{}},yLabels:{isShow:!0,css:{}},xAxis:{isShow:!0,css:{color:"#eee"}},
yAxis:{isShow:!0,css:{},num:5},xGrids:{isShow:!0,css:{}},yGrids:{isShow:!0,css:{}},areas:{isShow:!0,css:{}},bars:{isShow:!0,css:{}},tip:{isShow:!0,template:"",css:{},anim:{easing:"easeOut",duration:0.3},offset:{x:0,y:0},boundryDetect:!0,alignX:"right",alignY:"bottom"}};this._bars={};this._finished=[];this._cfg=f.mix(b,this._cfg,p,p,!0);m=this._cfg.themeCls;this.color=h=new t;0<this._cfg.colors.length&&h.removeAllColors();for(var a in this._cfg.colors)h.setColor(this._cfg.colors[a]);this._cfg.autoRender&&
this.render(!0)},drawTitle:function(){var b=this.paper,a=m+"-title",c=this._cfg,d=0.6*this._innerContainer.y;!this._title&&c.title.isShow&&""!=c.title.content&&(this._title=b.rect(0,0,this._$ctnNode.width(),d).addClass(a).css(f.mix({"line-height":d+"px"},c.title.css)));this._title&&""!=c.title.content&&this._title.html(c.title.content)},drawSubTitle:function(){var b=this.paper,a=m+"-subtitle",c=this._cfg,d=this._innerContainer,e=0.4*d.y;!this._subTitle&&c.subTitle.isShow&&""!=c.subTitle.content&&
(this._subTitle=b.rect(0,0.6*d.y,this._$ctnNode.width(),e).addClass(a).css(f.mix({"line-height":e+"px"},c.subTitle.css)));this._subTitle&&""!=c.subTitle.content&&this._subTitle.html(c.subTitle.content)},drawBar:function(b,a,c,d,e,n){var g=this.paper,s=q+"-bars",h=this._innerContainer,j=this._cfg,b=Math.round(b),a=Math.round(a),c=Math.round(c),d=Math.round(d);if(j.anim)var i=j.anim.duration?f.isNumber(j.anim.duration)?j.anim.duration:0.5:0.5,j=j.anim.easing?j.anim.easing:"easeOut",b=g.rect(b,h.bl.y,
c,0).attr({posx:b,posy:a}).addClass(s).css(f.mix(this._cfg.bars.css,e)).animate({height:d,marginTop:a-h.y},i,j,function(){n&&n()});else b=g.rect(b,a,c,d).attr({posx:b,posy:a}).addClass(s).css(f.mix(this._cfg.bars.css,e));return b},getBarsPos:function(){var b=l.prototype.obj2Array(this._barPoints).length,a=this._pointsX[1].x-this._pointsX[0].x,b=0.6*a/(b+(b-1)/1),c=b+0.5*b/0.5,d=this._innerContainer.bl.y,a=(0.4*a-a)/2;this._barsPos={};for(var e in this._points){var n=[],g;for(g in this._points[e]){var f=
{},h=Math.abs(d-this._points[e][g].y);f.x=a+this._points[e][g].x;f.y=this._points[e][g].y;f.width=b;f.height=h;n.push(f)}a+=c;this._barsPos[e]=n}},drawBars:function(b){var a=this,c;for(c in a._barsPos){var d=[],e=[],f;for(f in a._barsPos[c]){var g=a._barsPos[c][f];e[f]=g;d[f]=a.drawBar(g.x,g.y,g.width,g.height,{background:h.getColor(c).DEFAULT},function(){a._finished.push(!0);b&&a._finished.length==a._cfg.series.length&&b()}).attr({barGroup:c,barIndex:f,defaultColor:h.getColor(c).DEFAULT,hoverColor:h.getColor(c).HOVER})}d=
{bars:d,posInfos:e,color:h.getColor(c)};a._bars[c]=d}return a._bars},drawGridsX:function(){for(var b=this._centerPoints,a=0,c=b.length;a<c;a++)this._gridsX.push(this.drawGridX(b[a]));return this._gridsX},drawGridX:function(b){var a=this._cfg.themeCls+"-gridsx";return this.htmlPaper.lineY(b.x,this._innerContainer.tl.y,this._innerContainer.height).addClass(a).css(this._cfg.xGrids.css)},drawGridY:function(b,a){var c=this._innerContainer.width,a=a||this._cfg.yGrids.css,d=this._cfg.themeCls+"-gridsy";
return this.htmlPaper.lineX(b.x,b.y,c).addClass(d).css(a)},drawGridsY:function(){for(var b=this._innerContainer.tl.x,a=this._pointsY,c=0,d=a.length;c<d;c++)this._gridsY[c]={"0":this.drawGridY({x:b,y:a[c].y}),num:this.coordNum[c]}},drawAreas:function(){for(var b=this._innerContainer.tl.y,a=this._points[0],c=a[1].x-a[0].x,d=this._innerContainer.height,e=this.htmlPaper,f=this._cfg.themeCls+"-areas",g=this._cfg.areas.css,h=0,i=a.length;h<i;h++)this._areas.push(e.rect(a[h].x-c/2,b,c,d).addClass(f).css(g))},
drawAxisX:function(){var b=this._innerContainer,a=b.bl,c=this._cfg.themeCls+"-axisx";return this._axisX=this.htmlPaper.lineX(a.x,a.y,b.width).addClass(c).css(this._cfg.xAxis.css||{})},drawAxisY:function(){var b=this._innerContainer,a=b.tl,c=this._cfg.themeCls+"-axisy";return this._axisY=this.htmlPaper.lineY(a.x,a.y,b.height).addClass(c).css(this._cfg.yAxis.css||{})},drawLabelsX:function(){var b=this._cfg.xAxis.text,a;for(a in b)this.drawLabelX(a,b[a])},drawLabelsY:function(){for(var b in this._pointsY)this._labelY[b]=
{"0":this.drawLabelY(b,this._pointsY[b].number),num:this._pointsY[b].number}},drawLabelX:function(b,a){var c=this.htmlPaper,d=this._pointsX,e=this._cfg.themeCls+"-xlabels";if(b<(d.length||0))return d=d[b],d[0]=c.text(d.x,d.y,"<span class="+e+">"+a+"</span>","center").css(this._cfg.xLabels.css),d[0]},drawLabelY:function(b,a){return this.htmlPaper.text(this._pointsY[b].x,this._pointsY[b].y,"<span class="+(this._cfg.themeCls+"-ylabels")+">"+a+"</span>","right","middle").css(this._cfg.yLabels.css)},renderTip:function(){var b=
this._cfg,a=this._innerContainer,b=f.mix(b.tip,{rootNode:this._$ctnNode,clsName:b.themeCls,boundry:b.tip.boundryDetect?{x:a.tl.x,y:a.tl.y,width:a.width,height:a.height}:{}});return this.tip=new u(b)},renderEvtLayout:function(){var b=this._innerContainer,a=this._points[0],c=this._points[0]&&this._points[0][1]?a[1].x-a[0].x:this._areas[0].width(),d=b.height,e=this._evtEls._areas=[];this._evtEls._bars=[];for(var f=this._evtEls.paper=new o(this._$ctnNode,{clsName:"ks-chart-evtlayout",prependTo:!1,width:b.width,
height:d,left:b.tl.x,top:b.tl.y}),g=0,h=a&&a.length;g<h;g++)e[g]=f.rect(a[g].x-c/2,b.tl.y,c,d).addClass("ks-chart-evtlayout-areas");for(g in this._barsPos){var b=[],i;for(i in this._barsPos[g])a=this._barsPos[g][i],b[i]=f.rect(a.x,a.y,a.width,a.height).addClass("ks-chart-evtlayout-bars").attr({barGroup:g,barIndex:i});this._evtEls._bars.push(b)}return f},clearEvtLayout:function(){if(this._evtEls._areas)for(var b in this._evtEls._areas)this._evtEls._areas[b].remove();if(this._evtEls._bars)for(b in this._evtEls._bars)for(var a in this._evtEls._bars[b])this._evtEls._bars[b][a].remove()},
render:function(b){var a=this,c=a._cfg,d=a._innerContainer,e=c.themeCls;b&&a._$ctnNode.html("");a.paper=new o(a._$ctnNode,{clsName:q,width:d.width,height:d.height,left:d.tl.x,top:d.tl.y});a._barPoints=a._points;a.getBarsPos();a.htmlPaper=new o(a._$ctnNode,{clsName:e});a.drawTitle();a.drawSubTitle();a.renderEvtLayout();c.tip.isShow&&a.renderTip();c.areas.isShow&&a.drawAreas();c.xGrids.isShow&&a.drawGridsX();c.yGrids.isShow&&a.drawGridsY();c.xAxis.isShow&&a.drawAxisX();c.yAxis.isShow&&a.drawAxisY();
c.xLabels.isShow&&a.drawLabelsX();c.yLabels.isShow&&a.drawLabelsY();a.drawBars(function(){f.log("finished");a.afterRender()});a.bindEvt();f.log(a)},bindEvt:function(){var b=this,a=b._cfg;k.detach(i(".ks-chart-evtlayout-bars",b._$ctnNode),"mouseenter");k.on(i(".ks-chart-evtlayout-bars",b._$ctnNode),"mouseenter",function(c){var d=i(c.currentTarget),c=d.attr("barIndex"),d=d.attr("barGroup");a.tip.isShow&&b.tipHandler(d,c);b.barChange(d,c)});k.detach(i(".ks-chart-evtlayout-bars",b._$ctnNode),"mouseleave");
k.on(i(".ks-chart-evtlayout-bars",b._$ctnNode),"mouseleave",function(a){var d=i(a.currentTarget),a=d.attr("barIndex"),d=d.attr("barGroup"),a=b._bars[d].bars[a];a.css({background:a.attr("defaultColor")})});k.detach(b._evtEls.paper.$paper,"mouseleave");k.on(b._evtEls.paper.$paper,"mouseleave",function(){b.tip&&b.tip.hide();b.paperLeave()})},paperLeave:function(){this.fire("paperLeave",this)},barChange:function(b,a){var c=this._bars[b];this.fire("barChange",f.mix({target:c.bars[a],currentTarget:c.bars[a],
barGroup:Math.round(b),barIndex:Math.round(a)},this._points[b][a]))},tipHandler:function(b,a){var c=this._cfg,d=this.tip,e=d.getInstance();dataInfo=this._points[b][a].dataInfo||{};$bar=this._bars[b].bars[a];defaultColor=$bar.attr("defaultColor");$bar.css({background:$bar.attr("hoverColor")});d.renderTemplate(this._cfg.tip.template,dataInfo);e.css(this.processAttr(c.tip.css,defaultColor));d.isVisable()?d.animateTo($bar.attr("posx"),$bar.attr("posy")):d.moveTo($bar.attr("posx"),$bar.attr("posy"))},
animateGridsAndLabels:function(){for(var b in this._labelY)this._labelY[b][0].remove(),this._gridsY[b][0].remove();this.drawGridsY();this.drawLabelsY()},processAttr:function(b,a){var c=f.clone(b),d;for(d in c)c[d]&&"string"==typeof c[d]&&(c[d]=c[d].replace("{COLOR}",a));return c},showBar:function(b){var a=this._innerContainer;l.prototype.recoveryData.call(this,b);this._barPoints[b]=this._points[b];this.animateGridsAndLabels();this.getBarsPos();f.log(this._barsPos);for(var c in this._bars)if(c!=b)for(var d in this._bars[c].bars)if(this._barsPos[c]){var e=
this._barsPos[c][d];e&&this._bars[c].bars[d].animate({height:e.height,width:e.width,marginTop:e.y-a.y,marginLeft:e.x-a.x},0.4,this._cfg.anim.easing,function(){});this._bars[c].bars[d].attr({posx:e.x,posy:e.y})}var a=[],i=[];for(d in this._barsPos[b])e=this._barsPos[b][d],a[d]=e,i[d]=this.drawBar(e.x,e.y,e.width,e.height,{background:h.getColor(b).DEFAULT}).attr({barGroup:b,barIndex:d,defaultColor:h.getColor(b).DEFAULT,hoverColor:h.getColor(b).HOVER});this._bars[b]={bars:i,posInfos:a,color:h.getColor(c)};
this.clearEvtLayout();this.renderEvtLayout();this.bindEvt();f.log(this)},hideBar:function(b){var a=this._innerContainer;l.prototype.removeData.call(this,b);delete this._barPoints[b];this.animateGridsAndLabels();this.getBarsPos();for(var c in this._bars[b].bars)this._bars[b].bars[c].remove();for(c in this._bars)if(c!=b)for(var d in this._bars[c].bars){var e=this._barsPos[c]?this._barsPos[c][d]:"";e&&this._bars[c].bars[d].animate({height:e.height,width:e.width,marginTop:e.y-a.y,marginLeft:e.x-a.x},
0.4,this._cfg.anim.easing,function(){});this._bars[c].bars[d].attr({posx:e.x,posy:e.y})}this.clearEvtLayout();this.renderEvtLayout();this.bindEvt();f.log(this)},afterRender:function(){this.fire("afterRender",this)},getPaper:function(){return this.paper},clear:function(){return this.paper.clear()}});return r},{requires:["../basechart/index","../tools/color/index","../tools/htmlpaper/index","../tip/index","./assets/kcharts-ui-core.css"]});
