KISSY.add("gallery/countdown/1.2/countdown",function(d,g){function b(a,e){if(!(this instanceof b))return new b(a,e);if(a=d.get(a))this.container=a,this.config=d.merge(b.Config,e),this._init()}var f=d.DOM;b.Config={effect:"normal",_varReg:/\$\{([\-\w]+)\}/g,_clock:["d",100,2,"h",24,2,"m",60,2,"s",60,2,"u",10,1]};d.augment(b,d.EventTarget,{_init:function(){var a=this,b=a.config,c=b._varReg,j=b._clock,h=a.container,i=[];this._notify=[];a.hands=i;a.frequency=1E3;c.lastIndex=0;h.innerHTML=h.innerHTML.replace(c,
function(b,e){if("u"===e||"s-ext"===e)a.frequency=100;var c="";"s-ext"===e?(i.push({type:"s"}),i.push({type:"u"}),c=a._html("","s","handlet")+a._html(".","","digital")+a._html("","u","handlet")):i.push({type:e});return a._html(c,e,"hand")});d.each(i,function(a){var b=a.type,e=100,c;a.node=d.one(h).one(".hand-"+b);for(c=j.length-3;-1<c&&b!==j[c];c-=3)e*=j[c+1];a.base=e;a.radix=j[c+1];a.bits=j[c+2]});a._getLeft();a._reflow();var k=a._reflow;a._reflow=function(){return k.apply(a,arguments)};g.add(a._reflow,
a.frequency);f.css(h,"display","block")},_getLeft:function(){var a=f.attr(this.container,"data-total");void 0===a&&(a=f.attr(this.container,"data-end")-d.now());void 0===a&&(a=f.attr(this.container,"data-time"));a=parseInt(a,10);this.left=a-a%this.frequency},_reflow:function(a){var b=this;b.left-=b.frequency*(a||0);d.each(b.hands,function(a){a.lastValue=a.value;a.value=Math.floor(b.left/a.base)%a.radix});b._repaint();b._notify[b.left]&&d.each(b._notify[b.left],function(a){a.call(b)});1>b.left&&g.remove(b._reflow);
return b},_repaint:function(){b.Effects[this.config.effect].paint.apply(this);this.fire("afterPaint")},_toDigitals:function(a,b){for(var a=0>a?0:a,c=[];b--;)c[b]=a%10,a=Math.floor(a/10);return c},_html:function(a,b,c){d.isArray(a)&&(a=a.join(""));switch(c){case "hand":b=c+" hand-"+b;break;case "handlet":b=c+" hand-"+b;break;case "digital":b="."===a?c+" "+c+"-point "+b:c+" "+c+"-"+a+" "+b}return'<s class="'+b+'">'+a+"</s>"},notify:function(a,b){var c=this._notify[a]||[];c.push(b);this._notify[a]=c;
return this}});return b},{requires:["./timer"]});
KISSY.add("gallery/countdown/1.2/effects",function(d,g){g.Effects={normal:{paint:function(){var b=this,f;d.each(b.hands,function(a){a.lastValue!==a.value&&(f="",d.each(b._toDigitals(a.value,a.bits),function(a){f+=b._html(a,"","digital")}),a.node.html(f))})}},slide:{paint:function(){var b=this,f,a,e,c;d.each(b.hands,function(d){if(d.lastValue!==d.value){f="";a=d.bits;e=b._toDigitals(d.value,a);for(c=void 0===d.lastValue?e:b._toDigitals(d.lastValue,a);a--;)f=c[a]!==e[a]?b._html([b._html(e[a],"","digital"),
b._html(c[a],"","digital")],"slide-wrap")+f:b._html(e[a],"","digital")+f;d.node.html(f)}});g.Effects.slide.afterPaint.apply(b)},afterPaint:function(){d.each(this.hands,function(b){if(b.lastValue!==b.value&&void 0!==b.lastValue){var b=b.node,d=b.one(".digital").height();b.css("height",d);b.all(".slide-wrap").css("top",-d).animate("top: 0",0.5,"easeIn")}})}},flip:{paint:function(){var b=this,f,a,e;d.each(b.hands,function(c){c.lastValue!==c.value&&(e=a=f="",d.each(b._toDigitals(c.value,c.bits),function(c){a+=
b._html(c,"","digital")}),void 0===c.lastValue?c.node.html(a):(a=b._html(a,"handlet"),d.each(b._toDigitals(c.lastValue,c.bits),function(a){e+=b._html(a,"","digital")}),f=b._html(e,"handlet mask"),e=b._html(e,"handlet"),c.node.html(a+e+f)))});g.Effects.flip.afterPaint.apply(b)},afterPaint:function(){d.each(this.hands,function(b){if(b.lastValue!==b.value&&void 0!==b.lastValue){var b=b.node,d=b.all(".handlet"),a=d.item(0),e=d.item(1),c=d.item(2),g=b.width(),h=b.height(),i=Math.floor(h/2);e.css({clip:"rect("+
i+"px, "+g+"px, "+h+"px, 0)"});c.css({overflow:"hidden",height:i+"px"});c.animate({top:i+"px",height:0},0.15,"easeNone",function(){c.html(a.html());c.css({top:0,height:i+"px",clip:"rect("+i+"px, "+g+"px, "+h+"px, 0)"});c.animate("height: "+h+"px",0.3,"bounceOut")})}})}}};return g},{requires:["./countdown"]});KISSY.add("gallery/countdown/1.2/index",function(d,g){return g},{requires:["./countdown","./effects"]});
KISSY.add("gallery/countdown/1.2/timer",function(d){function g(){for(;f.length;)f.shift()();var a=+new Date-g.nextTime,d=1+Math.floor(a/100),a=100-a%100;g.nextTime+=100*d;var c,j,h,i;h=0;for(i=b.length;h<i;h+=2)if(c=b[h+1],0===c)b[h](d);else{c+=2*d-1;j=Math.floor(c/20);if(0<j)b[h](j);b[h+1]=c%20+1}setTimeout(g,a)}var b=[],f=[];g.nextTime=+new Date;g();return{add:function(a,d){f.push(function(){b.push(a);b.push(1E3===d?1:0)})},remove:function(a){f.push(function(){-1!==d.indexOf(a,b)&&b.splice(d.indexOf(a,
b),2)})}}});
