KISSY.add("gallery/kcharts/1.1/dashboard/dashboard-ticks",function(b){function e(){e.superclass.constructor.apply(this,arguments);this.init()}b.extend(e,b.Base,{init:function(){var b=this.get("cfg"),j,f,d,h=b.r1||100,a=b.r2||105,g=b.R||110,c,k;j=this.get("dashboard");var r=this.get("paper"),l=j.get("cx"),e=j.get("cy"),i,q,m=[];i="";f=b.start||0;d=b.end||2*Math.PI;j=b.n||60;b=b.m||5;d=(d-f)/j;for(var o=0;o<=j;o+=1)0!=o%b&&(i=f+o*d,c=Math.cos(i),k=Math.sin(i),i=l+a*c,q=e+a*k,c=l+g*c,k=e+g*k,m.push("M",
i,q,"L",c,k));i=m.join(",");r.path(i);a=[];for(m=0;m<j;m+=b)i=f+m*d,c=Math.cos(i),k=Math.sin(i),i=l+h*c,q=e+h*k,c=l+g*c,k=e+g*k,a.push("M",i,q,"L",c,k);i=a.join(",");r.path(i).attr("stroke-width","2")}});return e});
KISSY.add("gallery/kcharts/1.1/dashboard/index",function(b,e,n,j,f){function d(){d.superclass.constructor.apply(this,arguments);var a=this.get("renderTo");b.isString(a)&&(a=b.get(a));var g=this.get("width"),c=this.get("height");this.paper=h(a,g,c);this.init()}var h=e;d.ATTRS={width:{value:400},height:{value:400},cx:{value:0},cy:{value:0}};b.extend(d,b.Base,{init:function(){var a=this.get("cx")||this.get("width")/2,g=this.get("cy")||this.get("width")/2;this.set("cx",a);this.set("cy",g);this.bindEvent();
var c,a=this.get("ticks"),g=this.get("pointer");c=this.get("background");b.isObject(c)?this.drawBg(c):b.isFunction(c)&&c.call(this);b.isObject(g)?this.drawPointer(g):b.isFunction(g)&&g.call(this);b.isObject(a)?this.drawTicks(a):b.isFunction(a)&&(this.ticks=a.call(this))},bindEvent:function(){},drawBg:function(a){a.src?this.drawPictureBg(a):this.drawVectorBg(a)},drawPointer:function(a){a.src?this.drawPicturePointer(a):this.drawVectorPointer(a)},drawVectorBg:function(){},drawPictureBg:function(a){var b=
a.src,c=this.paper,k=this.get("cx"),d=this.get("cy"),a=c.image(b,k-a.cx,d-a.cy,a.width,a.height);this.set("background",a);this.background=a},drawPicturePointer:function(a){var b,c,d,f;b=this.get("cx");c=this.get("cy");d=a.cx;f=a.cy;var e=this.paper,a=e.image(a.src,b-d,c-f,a.width,a.height);d=new j({pointer:a,dashboard:this,paper:e,cx:d,cy:f});this.set("pointer",d);this.pointer=d},drawVectorPointer:function(){this.get("vectorPointer");this.pointer=new n({dashboard:this,paper:this.paper})},drawTicks:function(a){this.ticks=
new f({dashboard:this,paper:this.paper,cfg:a})},pointTo:function(a,b){this.pointer&&this.pointer.pointTo(a,b)}});return d},{requires:["../raphael/index","./pointer","./pointer-pic","./dashboard-ticks"]});
KISSY.add("gallery/kcharts/1.1/dashboard/pointer-pic",function(b,e){function n(){n.superclass.constructor.apply(this,arguments);var b=this.get("pointer");this.get("paper");var f=this.get("dashboard"),d=this.get("cy"),e=this.get("cx"),a=f.get("cx"),f=f.get("cy");this.pointer=b;this.cx=d;this.cy=e;this.paperCx=a;this.paperCy=f}b.extend(n,e,{pointTo:function(b,f){var d=["r",b,this.paperCx,this.paperCy].join();f?this.pointer.animate({transform:d},f.ms,f.easing,f.callback):this.pointer.transform(d);return this}});
return n},{requires:["./pointer"]});
KISSY.add("gallery/kcharts/1.1/dashboard/pointer",function(b){function e(){e.superclass.constructor.apply(this,arguments)}b.extend(e,b.Base,{pointTo:function(e,j){var f=this.get("paper"),d=this,h=this.get("dashboard"),a=h.get("cx"),g=h.get("cy"),c=h.get("vectorPointer")||{};h.get("width");h.get("height");h={a:function(){var c=["r",e,a,g].join();if(!d.pointer){var h={},l,p=Math.asin(0.0625),h=b.merge({fill:"#000",stroke:"#000"},h);l=g-80;p=5*Math.cos(p);l=f.path(["M",a,l,"L",a+p,g-0.3125,"A",5,5,0,
1,1,a-p,g-0.3125,"Z"].join());l.attr(h);d.pointer=l}e&&d.pointer.animate({transform:c},j.ms,j.easing,j.callback)}};(c=h[c.theme]||h.a)&&c()}});return e});
