KISSY.add("gallery/grid/1.0/bar",function(d,r){function m(i){i=i||{};m.superclass.constructor.call(this,i);this._init()}var k=d.DOM,h=d.Node;d.extend(m,d.Base);d.augment(m,{CLS_BAR:"",_findItem:function(i){return k.hasClass(i,"bar-btn-container")?i:k.parent(i,".bar-btn-container")},_getBarTemplate:function(){return"<div></div>"},_init:function(){for(var i=this.get("items"),n=this.get("defaults"),e=null,f=null,j=0,b=i.length;j<b;j++){e=d.merge(n,i[j]);if(d.isUndefined(e.id))e.id=j;if(!e.isBarItem){(f=
r.types[e.type||"text"])||(f=r.types.text);i[j]=new f(e)}}this._initDOM();this._initEvent()},_initDOM:function(){var i=this._getBarTemplate(),n=this.get("renderTo");n=k.get("#"+n);var e=this.get("items");i=(new h(i)).appendTo(n);var f=(new h('<table style="border-spacing: 0;"><tr></tr></table>')).appendTo(i),j=k.get("tr",f[0]);this.set("bar",i);d.each(e,function(b,a){var c=j.insertCell(a);b.renderTo(c)});k.addClass(n,this.CLS_BAR);k.show(n)},_initEvent:function(){var i=this.get("items");d.each(i,
function(n){n.attachEvent()})}});return m},{requires:["./barItem"]});
KISSY.add("gallery/grid/1.0/barItem",function(d){function r(f){f+="";return f.charAt(0).toUpperCase()+f.substring(1)}function m(f){f=d.merge({isBarItem:true,css:""},f);d.mix(this,f);m.superclass.constructor.call(this,f);this._init()}function k(f){k.superclass.constructor.call(this,f)}function h(f){h.superclass.constructor.call(this,f)}function i(f){i.superclass.constructor.call(this,f)}function n(f){n.superclass.constructor.call(this,f)}function e(f){e.superclass.constructor.call(this,f)}d.extend(m,
d.Base);d.augment(m,{attachEvent:function(){var f=this.get("el");f&&this.handler&&f.on("click",this.handler)},renderTo:function(f){if(this.get("el"))return this.get("el");var j=this._getItemTemplate();f=(new d.Node(j)).appendTo(f);this.set("el",f);return f},_bindUI:function(){var f=this,j=f.__attrs,b,a;for(b in j)if(j.hasOwnProperty(b)){f.on("after"+r(b)+"Change",function(c){f[b]=c.newVal});a="_uiSet"+r(b);f[a]&&function(c,g){f.on("after"+r(c)+"Change",function(l){f[g](l.newVal,l)})}(b,a)}},_getItemTemplate:function(){return""},
_init:function(){this._bindUI()},destroy:function(){this.get("el").remove();this.detach();this.__attrVals={}}});d.extend(k,m);d.augment(k,{attachEvent:function(){var f=this.get("el");this.constructor.superclass.attachEvent.call(this);f&&f.on("mouseover",function(){f.hasClass("lp-item-disabled")||f.addClass("bar-item-over")}).on("mouseout",function(){f.removeClass("bar-item-over")})},_getItemTemplate:function(){return['<div id="',this.id,'" class="bar-btn-container ',this.disabled?"lp-item-disabled":
""," ",this.containerCss,'"><button class="bar-item-btn ',this.css,'" autocomplete="off" hidefocus="true" ',this.disabled?'disabled="disabled"':"",' type="button">',this.text,"</button></div>"].join("")},_uiSetDisabled:function(f){var j=this.get("el"),b=j.one("button");if(f){j.addClass("lp-item-disabled");b.attr("disabled","");j.removeClass("bar-item-over")}else{j.removeClass("lp-item-disabled");b.removeAttr("disabled")}}});d.extend(h,m);d.augment(h,{_getItemTemplate:function(){return['<div id="',
this.id,'"  class="pb-text-container',this.css,'">',this.text,"</div>"].join("")}});d.extend(i,m);d.augment(i,{_getItemTemplate:function(){return'<div class="bar-item-separator"></div>'}});d.extend(n,m);d.augment(n,{_getItemTemplate:function(){return['<div id="',this.id,'"  class="pb-text-container"><a class="',this.css,'" href = "',this.href,'">',this.text,"</a></div>"].join("")}});d.extend(e,m);d.augment(e,{_getItemTemplate:function(){return d.substitute(this.template,this)}});m.types={button:k,
text:h,link:n,custom:e,seperator:i};return m},{requires:[]});KISSY.add("gallery/grid/1.0/buttonBar",function(d,r){function m(k){k=this._formatConfig(k||{});m.superclass.constructor.call(this,k)}d.extend(m,r);d.augment(m,{CLS_BAR:"button-bar",_formatConfig:function(k){var h={renderTo:k.renderTo,items:[]};d.each(k.buttons||k.items,function(i){i=d.merge({type:"button"},i);h.items.push(i)});return h}});return m},{requires:["./bar"]});
KISSY.add("gallery/grid/1.0/calendar",function(d,r){var m=function(k,h){var i=new Date(h-0+k*864E5);i=i.getFullYear()+"/"+(i.getMonth()+1)+"/"+i.getDate();return new Date(i)};return function(k){var h=d.DOM,i=d.Event,n={};d.each(k,function(e){if(h.get(e.selector)){var f=d.one(e.selector);f.hasAttr("readonly")&&f.removeAttr("readonly");f.hasClass("ks-select-calendar")||f.addClass("ks-select-calendar");if(e.showTime)f.hasClass("calendar-time")||f.addClass("calendar-time");var j;f=e.showTime?"timeSelect":
"select";var b=e.showTime?"yyyy-mm-dd HH:MM:ss":"yyyy-mm-dd";j=e.min?m(e.min,new Date):e.min==0?new Date:null;var a=e.max?m(e.max,new Date):e.max==0?new Date:null;if(e.config)j=new r(e.selector,e.config);else{var c=Date.parse(h.val(e.selector).replace(/\-/g,"/"));j=new r(e.selector,{minDate:j,maxDate:a,selected:c?new Date(c):null,showTime:e.showTime,popup:true,triggerType:["click"]})}j.on(f,function(g){var l=h.get(e.selector);h.val(l,r.Date.format(g.date,b));this.hide();l.focus()});i.on(e.selector,
"valuechange",function(g){g.keyCode==8||g.keyCode==46||h.val(this,"")});n[e.selector]=j}});return n}},{requires:["calendar","calendar/assets/base.css"]});
KISSY.add("gallery/grid/1.0/editGrid",function(d,r,m){function k(e){k.superclass.constructor.call(this,e)}var h=d.DOM,i=d.UA,n=d.Node;d.extend(k,r,{clearError:function(){this.get("showError");this.cancelEdit()},cancelEdit:function(){var e=this.get("columns");d.each(e,function(f){(f=f.editor)&&!f.isHide()&&f.hide()})},hasError:function(){var e=false,f=null;f=null;if(this.get("showError")){f=this.get("tbody");e=!!d.one(f).one(".grid-error-cell")}if(!e){f=this.get("columns");d.each(f,function(j){if((j=
j.editor)&&!j.isHide()&&j.hasError()){e=true;return false}})}return e},setCellToEdit:function(e,f){var j=this._getCell(e,f),b=this._getEditor(f);h.hasClass(j,"grid-editable-cell")&&this._showEditor(b,j,e[f],e)},_attachEditEvent:function(e){var f=this,j=e.editor;j.on("change",f._getChangeEvent(e));j.on("hide",function(){f.set("editRecord",null);f.set("editor",null)})},_getChangeEvent:function(e){var f=this;return function(j){var b=j.value;j=j.record;var a=e.dataIndex,c=f.get("store");j[a]!==b&&c.setValue(j,
a,b)}},_addError:function(e,f){var j=e.one(".grid-body-cell-inner"),b=e.one(".grid-cell-error-icon"),a=['<span class="grid-cell-error-icon" title="',f,'"></span>'].join("");if(b)b.attr("title",f);else{j.addClass("grid-error-cell");(new n(a)).appendTo(j)}},_clearError:function(e){var f=e.one(".grid-body-cell-inner");e=e.one(".grid-cell-error-icon");f.removeClass("grid-error-cell");e&&e.remove()},_getEditor:function(e){var f=this.get("columns"),j=null;d.each(f,function(b){if(b.dataIndex===e){j=b.editor;
return false}});return j},_getCellTemplate:function(e,f,j,b,a){var c=f.dataIndex,g=f.width,l=f.showTip?'title = "'+(b||"")+'"':"",o=f.hide?"ks-hidden":"",p=f.editor;f=p?p.editableFun&&!p.editableFun(b,a)?"":"grid-editable-cell":"";b=this.get("showError")?p&&p.validator?p.validator(b,a):"":"";return['<td  class="grid-body-cell grid-body-td-',c," ",o," ",f,'" data-column-name="',c,'" colindex="',e,'" width="',g,'px"><div class="grid-body-cell-inner ',b?"grid-error-cell":"",'" style="width : ',g,'px"><span class="grid-body-cell-text " ',
l,">",j,"</span>",b?'<span class="grid-cell-error-icon" title="'+b+'"></span>':"","</div></td>"].join("")},_getTextEditorTemplate:function(e){e=e||80;return['<div class="lp-text-editor grid-editor" style="position : absolute; z-index : 1000; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;"><input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field" style="width : ',e,'px; height : 20px;">'].join("")},_getRowDataByCell:function(e){e=this._findRow(e);
return h.data(e,"row-element")},_getCell:function(e,f){var j=this._findRowByRecord(e);return d.one("."+("grid-body-td-"+f),j)},_getCellValue:function(e,f){var j=this._findRow(e);return(j=h.data(j,"row-element"))?j[f]:null},_hasEditor:function(e){return this.hasAttr("col"+e)},_hideEditor:function(e){e.css({visibility:"hidden",left:-1E4,top:-1E4})},_init:function(){k.superclass._init.call(this);var e=this,f=e.get("columns");d.each(f,function(j){var b=j.editor,a=null;if(!(!b||b.isEditor)){a=m.types[b.type||
"text"];j.editor=new a(b);e._attachEditEvent(j)}})},_initEvent:function(){var e=this;d.Event.on(document,"click",function(f){var j=e.get("editor"),b=f.target;!e._findCell(f.target)&&j&&!j.isHide()&&!j.hasError()&&!j.isContains(b)&&j.hide()});e.constructor.superclass._initEvent.call(e)},_initDataEvent:function(){var e=this;e.get("store").on("updaterecord",function(f){e._setRowValue(f.record)});e.on("rowremoved",function(f){var j=e.get("editRecord"),b=e.get("editor");j&&b&&j==f.data&&!b.isHide()&&b.hide()});
e.constructor.superclass._initDataEvent.call(this)},_rowClickEvent:function(e){var f=this._findCell(e),j=null,b=null,a=null;a=null;if(f){j=h.attr(f,"data-column-name");b=this._getEditor(j);(a=this.get("editor"))&&a!=b&&!a.isHide()&&!a.hasError()&&a.hide();if(j&&b){if(!b.isHide()&&b.hasError()){b._focus();return}if(a=this._getRowDataByCell(f)){if(!h.hasClass(f,"grid-editable-cell"))return;this.fire("beforeedit",{cell:f,field:j,data:a})!==false&&this._showEditor(b,f,a[j],a)}return}}this.constructor.superclass._rowClickEvent.call(this,
e)},_setRowValue:function(e){var f=this,j=f._findRowByRecord(e),b=f.get("columns");j&&d.each(b,function(a){var c=a.dataIndex,g=d.one("."+("grid-body-td-"+c),j),l=g.one(".grid-body-cell-text"),o=a.editor;o=o&&o.validator?o.validator(e[c],e):"";var p=null,q=f.get("showError");if(l){p=a.renderer?a.renderer(e[c],e):e[c];p=p===undefined?"":p;l.html(p);if(q)o?f._addError(g,o):f._clearError(g)}})},_showEditor:function(e,f,j,b){h.offset(f);var a=h.width(f);f=h.get(".grid-body-cell-inner",f);h.height(f);var c=
this.get("editor");c&&!c.isHide()&&!c.hasError()&&c.hide();this.set("editRecord",b);this.set("editor",e);i.ie==7?e.setWidth(a-4):e.setWidth(a-2);e.setValue(j,b);e.show({container:f,left:0,top:2})}});return k},{requires:["./grid","./gridEditor"]});
KISSY.add("gallery/grid/1.0/grid",function(d,r,m,k){function h(b){b=b||{};if(!b.renderTo)throw"please assign the id of rendered Dom!";b=d.merge(h.config,b);h.superclass.constructor.call(this,b);this.events=["beginappend","afterappend","beginshow","aftershow","rowremoved","rowcreated","beforepagechange","rowclick","cellclick","rowselected","rowunselected"];this._init()}var i=d.DOM,n=d.UA,e=d.Node,f="grid-body-cell",j="row-element";h.config={};d.extend(h,d.Base);d.augment(h,{appendData:function(b){var a=
this,c=[];a.fire("beginappend",{data:b});d.each(b,function(g,l){var o=a._createRow(g,l);c.push(o)});a.fire("afterappend",{rows:c,data:b})},addSummary:function(b){var a=this.get("tfoot");d.all(a.rows).remove();this._createSummaryRow(b)},clearData:function(){var b=this.get("tbody");this._setHeaderChecked(false);d.all(b.rows).remove()},clearSelection:function(){this._setAllRowsSelected(false)},filter:function(b,a){var c=this.get("tbody");c=d.makeArray(c.rows);var g=typeof a==="function"?a:function(l){return l===
a};d.each(c,function(l){var o=d.one(l);l=i.data(l,j);if(a===null)o.show();else!l||!g(l[b])?o.hide():o.show()})},getWidth:function(){return this.get("width")||this.get("gridEl").width()},getSelection:function(){var b=this.get("tbody");b=d.all(".grid-row-selected",b);var a=[];d.each(b,function(c){(c=i.data(c,j))&&a.push(c)});return a},getSelected:function(){var b=this.get("tbody");return(b=d.one(".grid-row-selected",b))?i.data(b,j):null},hideColumn:function(b){this._setColumnVisible(b,false)},setAllSelection:function(){this._setAllRowsSelected(true)},
setSelection:function(b,a){var c=this,g=c.get("tbody").rows;d.each(g,function(l){var o=i.data(l,j);o&&d.inArray(o[b],a)&&c._setRowSelected(l,true)})},setHeight:function(b){var a=this.get("gridEl"),c=25,g=this.get("body");g=d.one(g);a.height(b);if(this.get("tbar")){c+=27;if(this.get("tbar").buttons)c+=4}if(this.get("bbar"))c+=27;if(b-c>0){g.height(b-c);g.css("overflow-y","scroll")}},setWidth:function(b){var a=this.get("body"),c=this.get("gridEl"),g=this.get("forceFit");this.set("width",b);c.width(b);
d.one(a).width(b-2);c.children(".grid-view").width(b-2);g&&this._forceFitWidth();this._autoSetInnerWidth(b)},showColumn:function(b){this._setColumnVisible(b,true)},sort:function(b,a){var c,g=this.get("store"),l=a===1?"ASC":"DESC";c=typeof b==="string"?b:b.dataIndex;g?g.sort(c,l):this._localSort(c,a)},showData:function(b){var a=this;a.fire("beginshow");a.clearData();d.each(b,function(c,g){a._createRow(c,g)});a._afterShow();a.fire("aftershow")},removeData:function(b){var a=this,c=a.get("tbody");c=d.makeArray(c.rows);
d.each(c,function(g){var l=i.data(g,j);if(l&&d.inArray(l,b)){a.fire("rowremoved",{data:l,row:g});i.remove(g)}})},_addBodyEvent:function(b){var a=this,c=a.get("head"),g=a.get("body"),l=d.one(g);d.one(b).on("click",function(o){a._rowClickEvent(o.target)}).on("mouseover",function(o){a._rowOverEvent(o.target)}).on("mouseout",function(o){a._rowOutEvent(o.target)});l.on("scroll",function(){var o=l.scrollLeft();d.one(c).scrollLeft(o)})},_afterShow:function(){var b=this.get("tbody"),a=this.get("body"),c=
d.one(a),g;if(n.ie===6||n.ie===7){g=this.get("height");if(!g){g=c.width();a=a.scrollWidth;if(a>g){b=d.one(b).height();c.height(b+17)}else c.css("height","auto")}}},_createRow:function(b,a){var c=this.get("tbody"),g=this._getRowTemplate(a,b);c=(new e(g)).appendTo(c);g=c.getDOMNode();var l=g.lastChild;i.data(g,j,b);i.addClass(l,"lp-last");this.fire("rowcreated",{data:b,row:g});return c},_createSummaryRow:function(b){var a=this.get("tfoot");b=this._getSummaryTemplate(b);return(new e(b)).appendTo(a)},
_lookupByClass:function(b,a){if(i.hasClass(b,a))return b;return i.parent(b,"."+a)},_findRowByRecord:function(b){var a=this.get("tbody").rows,c=null;d.each(a,function(g){if(i.data(g,j)===b){c=g;return false}});return c},_findRow:function(b){return this._lookupByClass(b,"grid-row")},_findCell:function(b){return this._lookupByClass(b,f)},_forceFitColumns:function(b){var a=this.getWidth(),c=this.get("height"),g=0,l=0,o=this.get("checkable")?31:0,p=0,q=1,t=0,s=0;p=0;b=b||this.get("columns");s=b.length;
d.each(b,function(u){u.width=u.width||80;var v=u.originWidth||u.width;if(!u.hide){g+=v;l+=1}});p=l*2+2+o+(c?17:0);q=(a-p)/g;t=0;if(q!==1){d.each(b,function(u){if(!u.hide){u.originWidth=u.originWidth||u.width;u.width=Math.floor(u.originWidth*q);t+=u.width}});p=a-(t+p);if(s)b[s-1].width+=p}},_forceFitWidth:function(){var b=this,a=b.get("columns");b._forceFitColumns();d.each(a,function(c){b._setColumnWidth(c)})},_getCheckedCellTemplate:function(b,a){return['<td width="30px" align="center" class="',b,
" ",a,'"><div class="',a,'-inner"><span class="gwt-CheckBox"><input type="checkbox" class="grid-checkbox" tabindex="0"></span></div></td>'].join("")},_getColumn:function(b){var a=this.get("columns"),c=null;d.each(a,function(g){if(g.dataIndex==b){c=g;return false}});return c},_getRowTemplate:function(b,a){var c=this,g=c.get("columns"),l=b%2===0?"grid-row-odd":"grid-row-even",o=[],p=null;p=null;if(c.get("checkable")){p=c._getCheckedCellTemplate("grid-row-checked-column",f);o.push(p)}d.each(g,function(q,
t){var s=a[q.dataIndex],u=q.renderer?q.renderer(s,a):s;s=c._getCellTemplate(t,q,u,s,a);o.push(s)});return p=['<tr rowIndex="',b,'" class="grid-row ',l,'">',o.join(""),"</tr>"].join("")},_getSummaryTemplate:function(b){function a(q){return q>0?'<td class="'+f+'" colspan="'+q+'"></td>':""}var c=this,g=c.get("columns"),l=[],o=-1,p=-1;if(c.get("checkable"))p+=1;d.each(g,function(q,t){if(!q.hide){p+=1;if(q.summary){l.push(a(p-o-1));var s=b[q.dataIndex];s="\u603b\u8ba1\uff1a"+(q.renderer?q.renderer(s,b):s);s=c._getCellTemplate(t,
q,s,b);l.push(s);o=p}}});o!==p&&l.push(a(p-o));return rowTemplate=['<tr class="grid-row">',l.join(""),"</tr>"].join("")},_getCellTemplate:function(b,a,c,g){var l=a.dataIndex,o=a.width;return['<td  class="grid-body-cell grid-body-td-',l," ",a.hide?CLS_HIDDEN:"",'" data-column-name="',l,'" colindex="',b,'" width="',o,'px"><div class="grid-body-cell-inner" style="width : ',o,'px"><span class="grid-body-cell-text " ',a.showTip?'title = "'+(g||"")+'"':"",">",c,"</span></div></td>"].join("")},_getColumnsWidth:function(){var b=
this.get("columns"),a=0;if(this.get("checkable"))a+=31;d.each(b,function(c){c.hide||(a+=c.width+2)});return a},_init:function(){var b=this.get("gridId"),a=this.get("container"),c=this.get("renderTo"),g=null,l=g=g=null,o=null,p=null;g=0;var q=this.get("height");if(!a){a=i.get("#"+c);this.set("container",a)}if(!b){b=c+"grid";this.set("gridId",b)}g=['<div id="',b,'" class="grid-panel"><div id="',b+"tbar",'" class="grid-tbar" style="display : none;"></div><div class="grid-view"><div class="grid-header"><table  cellspacing="0" cellpadding="0" class="grid-table"><thead></thead></table></div><div class="grid-body grid-body-scroll"><table  cellspacing="0" cellpadding="0" class="grid-table"><tbody><tfoot></tfoot></tbody></table></div></div><div id="',
b+"bbar",'" class="grid-bbar" style="display : none;"></div></div>'].join("");g=new e(g);g.appendTo(a);this.set("gridEl",g);g=i.get(".grid-header",a);l=i.get(".grid-table",g);o=i.get(".grid-body",a);p=i.get(".grid-table",o);this.set("head",g);this.set("body",o);this.set("tbody",p.tBodies[0]);this.set("tfoot",p.tFoot);this.set("thead",l.tHead);this._initHeader();if(this._isAutoFitWidth()){g=this._getColumnsWidth();this.setWidth(g+2)}else{g=this.get("width");this.setWidth(g)}q&&this.setHeight(q);this._initListeners();
this._initPaggingBar();this._initData();this._initEvent()},_initEvent:function(){this._initHeaderEvent();this._initBodyEvent();this._initDataEvent();this._initPaggingBarEvent()},_initBodyEvent:function(){this._addBodyEvent(this.get("tbody"))},_initData:function(){var b=this.get("store"),a=this.get("loadMask"),c=this.get("gridEl");if(a){a=new k(c,{msg:"Loading..."});this.set("loadMask",a)}b&&b.autoLoad&&b.load()},_initDataEvent:function(){var b=this,a=b.get("store");if(a){a.on("beforeload",function(){var c=
b.get("loadMask");c&&c.show()});a.on("load",function(){var c=a.getResult(),g=b.get("loadMask");b.showData(c);g&&g.hide()});a.on("localsort",function(c){b._localSort(c.field,c.direction==="ASC"?1:-1)});a.on("addrecords",function(c){b.appendData(c.data)});a.on("removerecords",function(c){b.removeData(c.data)});a.on("exception",function(){var c=b.get("loadMask");c&&c.hide()})}},_initHeaderEvent:function(){var b=this,a=b.get("thead"),c=b.get("checkable"),g=d.all(".grid-header-th-inner",a);g.on("mouseover",
function(){d.one(this).parent().addClass("hover")}).on("mouseout",function(){d.one(this).parent().removeClass("hover")}).on("click",function(){var l=d.one(this),o=l.parent(),p=null,q=null,t=null;if(o.hasClass("sortable")){p=o.attr("data-column-name");q=l.hasClass("sorted-asc")?"sorted-desc":"sorted-asc";t=q==="sorted-asc"?1:-1;g.removeClass("sorted-asc").removeClass("sorted-desc");l.addClass(q);b.sort(p,t)}});c&&d.one(".grid-checkbox",a).on("click",function(){b._setAllRowsSelected(d.one(this).attr("checked"))})},
_initHeader:function(){var b=this.get("columns"),a=this.get("thead").insertRow(0),c=null;c=null;if(this.get("checkable")){c=this._getCheckedCellTemplate("grid-header-checked-column","grid-header-th");(new e(c)).appendTo(a)}d.each(b,function(g){g.width=g.width||80;var l=g.sortable?"sortable":"",o=g.width;g=['<th align="left" class="grid-header-th ',g.hide?CLS_HIDDEN:""," grid-header-column-",g.dataIndex," ",l,'" data-column-name="',g.dataIndex,'"><div class ="grid-header-th-inner ',g.cls,' "><span class="grid-header-inner-title">',
g.title,"</span>",l?'<span class="grid-header-sort-icon">&nbsp;</span>':"","</div></th>"].join("");g=new e(g);g.attr("width",o+"px");g.appendTo(a)});if(!this._isAutoFitWidth()){c=new e('<th class="grid-header-th grid-header-th-empty"><div class ="grid-header-th-inner"></div></th>');c.appendTo(a)}},_initListeners:function(){var b=this.get("listeners");if(b)for(var a in b)b.hasOwnProperty(a)&&this.on(a,b[a])},_setEmptyHeadCellWidth:function(b){var a=this.get("thead");if(a=d.one(".grid-header-th-empty",
a))if(b<=0)a.hide();else{a.attr("width",b+"px");a.show()}},_autoSetInnerWidth:function(){var b=this.get("thead"),a=this.get("tbody"),c=this.get("height"),g=this._getColumnsWidth(),l=0;l=this.get("forceFit");var o=this.getWidth();l=l?15:o<g+2?15:o-(g+2);if(l>0&&l<15)l=15;this._setEmptyHeadCellWidth(l);l=g+(l?l+2:0);d.one(b).parent().width(l);if(c&&!n.firefox)g-=17;d.one(a).parent().width(g)},_initPaggingBar:function(){function b(t,s){var u=d.merge(t,{renderTo:s});if(o&&!u.store)u.store=o;return new m(u)}
function a(t,s){var u=d.merge(t,{renderTo:s});return new r(u)}var c=this.get("gridId"),g=this.get("tbar"),l=this.get("bbar"),o=this.get("store"),p=0,q=null;q=q=q=null;if(g){if(g.pageSize){q=b(g,c+"tbar");this.set("tpaggingBar",q);p=g.pageSize}if(g.buttons){q=a(g,c+"tbar");this.set("tbuttonBar",q)}}if(l){q=b(l,c+"bbar");this.set("bpaggingBar",q);p=l.pageSize}if(p&&o){q=o.params;if(!q.start){q.start=0;q.pageIndex=0}if(!q.limit||q.limit!==p)q.limit=p}},_initPaggingBarEvent:function(){var b=this,a=b.get("tpaggingBar"),
c=b.get("bpaggingBar");a&&a.on("beforepagechange",function(g){b.fire("beforepagechange",g)});c&&c.on("beforepagechange",function(g){b.fire("beforepagechange",g)})},_isAutoFitWidth:function(){return!this.get("width")},_isRowSelected:function(b){return d.one(b).hasClass("grid-row-selected")},_localSort:function(b,a){function c(p,q){var t=i.data(p,j);return t?t[q]:""}var g=this.get("tbody"),l=this.get("store"),o=d.makeArray(g.rows);l?o.sort(function(p,q){var t=i.data(p,j),s=i.data(q,j);return l.compare(t,
s)}):o.sort(function(p,q){var t=c(p,b),s=c(q,b);if(t<s)return-a;if(t>s)return a;return 0});d.each(o,function(p){d.one(p).appendTo(g)})},_rowClickEvent:function(b){var a=this._findRow(b),c=this._findCell(b),g=this.get("checkable"),l=null;if(a){l=i.data(a,j);this.fire("rowclick",{data:l,row:a});c&&this.fire("cellclick",{data:l,row:a,cell:c,field:i.attr(c,"data-column-name"),domTarget:b});if(g)this._isRowSelected(a)?this._setRowSelected(a,false):this._setRowSelected(a,true);else{d.all(".grid-row-selected",
a.parentNode).removeClass("grid-row-selected");i.addClass(a,"grid-row-selected")}}},_rowOverEvent:function(b){(b=this._findRow(b))&&d.one(b).addClass("grid-row-over")},_rowOutEvent:function(b){(b=this._findRow(b))&&d.one(b).removeClass("grid-row-over")},_setColumnWidth:function(b,a){if(typeof b==="string")b=this._getColumn(b);var c=b.dataIndex,g=".grid-header-column-"+c;c=".grid-body-td-"+c;var l=this.get("thead"),o=this.get("tbody"),p=null;if(b.width!=a){if(a)b.width=a;else a=b.width;d.one(g,l).attr("width",
a+"px");p=d.all(c,o);p.each(function(q){q.attr("width",a+"px").children(".grid-body-cell-inner").width(a)})}},_setColumnVisible:function(b,a){if(typeof b==="string")b=this._getColumn(b);if(b){var c=b.dataIndex,g=this.get("forceFit"),l=".grid-header-column-"+c;c=".grid-body-td-"+c;var o=this.get("thead"),p=this.get("tbody");if(a){b.hide=false;d.one(l,o).removeClass(CLS_HIDDEN);d.all(c,p).removeClass(CLS_HIDDEN)}else{b.hide=true;d.one(l,o).addClass(CLS_HIDDEN);d.all(c,p).addClass(CLS_HIDDEN)}g&&this._forceFitWidth()}},
_setHeaderChecked:function(b){var a=this.get("thead");(a=d.one(".grid-checkbox",a))&&a.attr("checked",b)},_setRowSelected:function(b,a){d.one(b);var c=i.get(".grid-checkbox",b),g=i.data(b,j);if(i.hasClass(b,"grid-row-selected")!==a){if(c){if(i.attr(c,"disabled"))return;c.checked=a}if(a){i.addClass(b,"grid-row-selected");this.fire("rowselected",{data:g})}else{i.removeClass(b,"grid-row-selected");this._setHeaderChecked(false);this.fire("rowunselected",{data:g,row:b})}this.fire("rowselectchanged",{data:g,
row:b})}},_setAllRowsSelected:function(b){var a=this,c=a.get("tbody");d.each(c.rows,function(g){a._setRowSelected(g,b)})},destory:function(){}});return h},{requires:["./buttonBar","./paggingBar","./loadMask"]});
KISSY.add("gallery/grid/1.0/gridEditor",function(d,r){var m=d.DOM,k=d.Node,h=function(a){a=d.merge({isEditor:true},a);d.mix(this,a);h.superclass.constructor.call(this,a);this._init();this.events=["beforechange","change"]};d.extend(h,d.Base);d.augment(h,{CHANGE_EVENT:"blur",INIT_VALUE:"",hasError:function(){return this.get("el").hasClass("grid-error-editor")},hide:function(){var a=this.get("el");this._clearError();a.css({visibility:"hidden",left:-1E4,top:-1E4});this.fire("hide",{record:this.get("record"),
editor:this});this._setValue(this.INIT_VALUE);d.one("body").append(a)},getValue:function(){return this.get("editEl")?this._getValue():this.INIT_VALUE},isHide:function(){var a=this.get("el");return a.css("visibility")==="hidden"||a.width()==0},isContains:function(a){return this.get("el").contains(a)},setValue:function(a,c){this.set("record",c);if(editEl){this._setValue(a);this._validate(a,c)}},show:function(a){var c=this.get("el"),g=a.container;g&&d.one(g).append(c);c.css({visibility:"visible",left:a.left,
top:a.top});this._focus();this.fire("show",{record:this.get("record"),editor:this})},setWidth:function(a){this.get("editEl").width(a)},setHeight:function(a){this.get("editEl").height(a)},_basicValidator:function(a){if(this.required&&(a===undefined||a===null||d.trim(a.toString())===""))return"\u4e0d\u80fd\u4e3a\u7a7a";return""},_basicFormat:function(a){if(!(a===undefined||d.trim(a.toString())===""))return a},_clearError:function(){var a=this.get("el"),c=a.one(".grid-error-editor-icon");a.removeClass("grid-error-editor");
c.attr("title","")},_focus:function(){this.get("editEl")[0].focus()},_getTemplate:function(){return'<input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_getEditElemnt:function(){var a=this.get("el").children();if(a.length)return d.one(a[0]);return null},_getValue:function(a){a=a||this.get("editEl");return a.val()},_init:function(){this._initDom();this._initEvent();this._initHideEvent()},
_initDom:function(){var a=null;a=['<div class="grid-editor" style="position : absolute; z-index : 1000; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;">',this._getTemplate(),"</div>"].join("");var c=this.get("container")||m.get("body");a=(new k(a)).appendTo(c);this.set("container",c);this.set("el",a);editEl=this._getEditElemnt();this.set("editEl",editEl)},_initEvent:function(){var a=this,c=a.get("el"),g=a.get("editEl");c.on("click",function(l){l.stopPropagation()});g.on(a.CHANGE_EVENT,
function(l){var o=d.one(this);a._valueChange(o)||l.preventDefault()})},_initHideEvent:function(){},_valueChange:function(a,c){var g=this.get("record"),l=null;c=c||this._getValue(a);l=this._validate(c,g);c=this._basicFormat(c);c=this.format?this.format(c):c;if(l){this.fire("change",{value:c,record:g});return true}return false},_setError:function(a){var c=this.get("el"),g=c.one(".grid-error-editor-icon");c.addClass("grid-error-editor");g.attr("title",a)},_setValue:function(a,c){c=c||this.get("editEl");
c.val(a)},_validate:function(a,c){var g=null,l=true;(l=(g=this._basicValidator(a)||this.validator&&this.validator(a,c))?false:true)?this._clearError():this._setError(g);return l},destroy:function(){this.get("el").remove();this.detach();this.__attrVals={}}});var i=function(a){i.superclass.constructor.call(this,a)};d.extend(i,h);d.augment(i,{_basicFormat:function(a){if(a)a=a.replace(/\</g,"&lt;").replace(/\>/,"&gt;").replace(/\"/,"&quot;");return a},_setValue:function(a,c){if(a)a=a.replace(/&lt;/g,
"<").replace(/&gt;/g,">").replace(/&quot;/g,'"');this.constructor.superclass._setValue.call(this,a,c)}});var n=function(a){n.superclass.constructor.call(this,a)};d.extend(n,h);d.augment(n,{_basicFormat:function(a){if(!(a===undefined||d.trim(a.toString())===""))return parseFloat(a)},_basicValidator:function(a){var c=this.constructor.superclass._basicValidator.call(this,a);if(!c&&a&&isNaN(a))c="\u8bf7\u8f93\u5165\u6570\u5b57";return c}});var e=function(a){e.superclass.constructor.call(this,a)};d.extend(e,h);d.augment(e,{CHANGE_EVENT:"change",
INIT_VALUE:false,setHeight:function(){},_getTemplate:function(){return'<input type="checkbox" name="" class="lp-form-checkbox-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_getValue:function(a){a=a||this.get("editEl");return a.attr("checked")?true:false},_setValue:function(a,c){c=c||this.get("editEl");c.attr("checked",a)}});var f=function(a){f.superclass.constructor.call(this,a)};d.extend(f,h);d.augment(f,{_getTemplate:function(){return'<select class="lp-form-select-field lp-editor-field"  style="height : 20px;"></select><s class="grid-error-editor-icon"></s>'},
_initDom:function(){this.constructor.superclass._initDom.call(this);var a=this,c=a.get("editEl"),g=a.items;a.required||a._createItem("\u8bf7\u9009\u62e9",a.INIT_VALUE,c);if(d.isArray(g))d.each(g,function(o){a._createItem(o.name,o.value,c)});else for(var l in g)g.hasOwnProperty(l)&&a._createItem(g[l],l,c)},_createItem:function(a,c,g){(new k('<option value="'+c+'">'+a+"</option>")).appendTo(g)}});var j=function(a){j.superclass.constructor.call(this,a)};d.extend(j,h);d.augment(j,{CHANGE_EVENT:"select",isContains:function(a){return this.constructor.superclass.isContains.call(this,
a)||d.one(a).parent(".ks-cal-box")},setHeight:function(){},setWidth:function(a){this.constructor.superclass.setWidth.call(this,a-15)},_basicFormat:function(a){return(new Date(a)).getTime()},_getTemplate:function(){return'<input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_init:function(){var a=this;d.use("gallery/grid/1.0/calendar",function(c,g){a.set("Calendar",g);a.constructor.superclass._init.call(a)})},
_initDom:function(){this.constructor.superclass._initDom.call(this);var a=this.get("editEl"),c=this.get("Calendar"),g="grid-date"+d.guid(),l=null;a.attr("id",g);l=new c([{selector:"#"+g}]);this.set("datepicker",l["#"+g])},_initEvent:function(){var a=this,c=a.get("datepicker");a.get("el");a.get("editEl").on("change",function(){d.log("change")});c.on(a.CHANGE_EVENT,function(g){a._valueChange(null,g.date)})},_setValue:function(a,c){c=c||this.get("editEl");var g=r.Format.dateRenderer(a),l=this.get("datepicker");
c.val(g);a&&a!==this.INIT_VALUE&&l.render({selected:new Date(a),date:new Date(a)})},_getValue:function(a){if(a)return a.date;else d.log("error")}});var b=function(a){b.superclass.constructor.call(this,a)};d.extend(b,h);d.augment(b,{hide:function(){this.get("hideEvent");this._isSelectShow()&&this._hideSelect();this.constructor.superclass.hide.call(this)},isContains:function(a){return this.constructor.superclass.isContains.call(this,a)||d.one(a).parent(".lp-multiple-wrap")},setValue:function(a,c){a=
a||[];this.constructor.superclass.setValue.call(this,a,c)},setWidth:function(a){this.constructor.superclass.setWidth.call(this,a-17)},setHeight:function(){},_createItem:function(a,c,g){(new k('<li class="multiple-item"> <input class="multiple-item-checkbox"  type="checkbox" name="'+c+'" />'+a+"</li>")).appendTo(g)},_getSelectOffset:function(){var a=this.get("editEl"),c=a.offset();c.top+=a.height()+2;return c},_getText:function(a){a=a||this._getValue();var c=this.items,g=this.get("renderer");if(!g){g=
r.Format.multipleItemsRenderer(c);this.set("renderer",g)}return g(a)},_getValue:function(){var a=[],c=this.get("listEl").all(".multiple-item-checkbox");d.each(c,function(g){g.checked&&a.push(g.name)});return a},_getTemplate:function(){return'<input type="text" readonly = "true" name=""autocomplete="off" size="20" class="lp-form-multiple-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_hideSelect:function(){this.get("selectEl").css({visibility:"hidden",left:-1E4,
top:-1E4})},_isSelectShow:function(){var a=this.get("selectEl");return a.css("visibility")!=="hidden"&&a.width()!=0},_initDom:function(){this.constructor.superclass._initDom.call(this);var a=this;a.get("editEl");var c=a.get("items"),g=(new k('<div class="lp-multiple-wrap"  style="position : absolute; z-index : 1200; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;"><ul class="multiple-list ks-clear"></ul><div class="multiple-footer" style="text-align:center"><span class="x-btn x-btn-default-small"><button autocomplete="off" hidefocus="true" type="button" style="width:74px;"><span class="x-btn-inner">\u786e\u8ba4</span></button></span></div></div>')).appendTo("body"),
l=g.one(".multiple-list"),o=g.one("button");a.set("selectEl",g);a.set("listEl",l);a.set("btnEl",o);if(d.isArray(c))d.each(c,function(q){a._createItem(q.name,q.value,l)});else for(var p in c)c.hasOwnProperty(p)&&a._createItem(c[p],p,l)},_initEvent:function(){var a=this,c=a.get("listEl"),g=a.get("editEl"),l=a.get("btnEl");g.on("click",function(o){o.stopPropagation();a._toggleSelect()});c.on("click",function(o){o.stopPropagation()});l.on("click",function(o){o.stopPropagation();o=a.getValue();a._setText(a._getText(o));
a._hideSelect();a._valueChange(g,o)})},_setText:function(a){this.get("editEl").val(a)},_setSelectValue:function(a){var c=this.get("listEl").all(".multiple-item-checkbox");c.attr("checked",false);c=d.filter(c,function(g){return d.inArray(g.name,a)});d.all(c).attr("checked","checked")},_setValue:function(a){this._setText(this._getText(a));this._setSelectValue(a)},_showSelect:function(a){var c=this.get("selectEl");a=a||this._getSelectOffset();c.css({visibility:"visible",left:a.left,top:a.top})},_toggleSelect:function(){this._isSelectShow()?
this._hideSelect():this._showSelect()}});h.types={text:i,number:n,check:e,select:f,date:j,multipleSelect:b};return h},{requires:["./util"]});KISSY.add("gallery/grid/1.0/index",function(d,r,m,k,h,i){return{Util:r,Store:m,Grid:k,EditGrid:h,LoadMask:i}},{requires:["./util","./store","./grid","./editGrid","./loadMask"]});
KISSY.add("gallery/grid/1.0/loadMask",function(d,r){var m=function(k,h){this.el=k;m.superclass.constructor.call(this,h);this._init()};d.extend(m,d.Base);d.augment(m,{msg:"Loading...",msgCls:"x-mask-loading",disabled:false,_init:function(){this.msg=this.get("msg")||this.msg},disable:function(){this.disabled=true},enable:function(){this.disabled=false},onLoad:function(){r.unmaskElement(this.el)},onBeforeLoad:function(){this.disabled||r.maskElement(this.el,this.msg,this.msgCls)},show:function(){this.onBeforeLoad()},
hide:function(){this.onLoad()},destroy:function(){this.el=null}});return m},{requires:["./util"]});
KISSY.add("gallery/grid/1.0/paggingBar",function(d,r){function m(h){h=this._formatConfig(h||{});d.mix(this,{start:0,end:0,totalCount:0,curPage:1,totalPage:1});m.superclass.constructor.call(this,h)}var k=d.DOM;d.extend(m,r);d.augment(m,{CLS_BAR:"pagging-bar",_afterStoreLoad:function(h,i){var n=this.get("pageSize"),e=0,f=0,j=0,b=1,a=1;e=i?i.start||0:0;j=h.getTotalCount();f=j-e>n?e+h.getCount():j;a=parseInt((j+n-1)/n,10);a=a>0?a:1;b=parseInt(e/n,10)+1;this.start=e;this.end=f;this.totalCount=j;this.curPage=
b;this.totalPage=a;this._setAllButtonsState();this._setNumberPages()},_getBarTemplate:function(){return'<div class="fr"></div>'},_getButtonConfig:function(h,i,n,e){var f=this;return{id:h,type:"button",css:i,text:e,containerCss:e?"bar-btn-custom":"",disabled:!!n,handler:function(j){j=f._findItem(j.target);var b=d.one("button",j);k.hasClass(j,"lp-item-disabled")||f._pageAction(b)}}},_getPageInfoConfig:function(){return{type:"custom",template:'<span class="pb-text-container">\u7b2c</span><span class="pb-input-container"><input type="text" autocomplete="off" class="pb-item-input" size="20" name="inputItem"></span><span class="pb-text-container pb-total-page">\u9875 \u5171 0 \u9875</span>'}},
_getCountInfoConfig:function(){return{type:"custom",template:'<div class="pb-text-container">\u5171 <span class="pb-total-count">0</span> \u6761\u8bb0\u5f55</div>'}},_formatConfig:function(h){var i=[];h=d.merge(h,{items:i});i.push(this._getButtonConfig("btnfirst","pb-page-first",true));i.push(this._getButtonConfig("btnpre","pb-page-prev",true));i.push({type:"seperator"});i.push(this._getPageInfoConfig());i.push({type:"seperator"});i.push(this._getButtonConfig("btnnext","pb-page-next",true));i.push(this._getButtonConfig("btnlast",
"pb-page-last",true));i.push(this._getButtonConfig("btnok","pb-page-ok",false,"\u8df3\u8f6c"));i.push({type:"seperator"});i.push(this._getCountInfoConfig());return h},_initEvent:function(){this.constructor.superclass._initEvent.call(this);var h=this,i=h.get("store"),n=h.get("bar");i&&i.on("load",function(e){h._afterStoreLoad(i,e)});n.one(".pb-item-input").on("keyup",function(e){e.stopPropagation();if(e.keyCode===13){e=d.one(this);var f=parseInt(e.val(),10);h._isPageAllowRedirect(f)?h.skipToPage(f):e.val(h.curPage)}})},
_isPageAllowRedirect:function(h){return h&&h>0&&h<=this.totalPage&&h!==this.curPage},_pageAction:function(h){var i=1;if(h.hasClass("pb-page-first"))i=1;else if(h.hasClass("pb-page-next"))i=this.curPage+1;else if(h.hasClass("pb-page-prev"))i=this.curPage-1;else if(h.hasClass("pb-page-last"))i=this.totalPage;else if(h.hasClass("pb-page-ok")){h=this.get("bar").one(".pb-item-input");i=parseInt(h.val(),10);if(this._isPageAllowRedirect(i))i=i;else{h.val(this.curPage);return}}this.skipToPage(i)},skipToPage:function(h){var i=
this.get("store"),n=this.get("pageSize"),e=h-1,f=e*n;h=this.fire("beforepagechange",{from:this.curPage,to:h});i&&h!==false&&i.load({start:f,limit:n,pageIndex:e})},_setAllButtonsState:function(){function h(e,f){d.each(n,function(j){d.inArray(j.id,e)&&j.set("disabled",!f)})}var i=this.get("store"),n=this.get("items");i&&h(["btnpre","btnnext","btnfirst","btnlast","btnok"],true);this.curPage===1&&h(["btnpre","btnfirst"],false);this.curPage===this.totalPage&&h(["btnnext","btnlast"],false)},_setNumberPages:function(){var h=
this.get("bar"),i=h.one(".pb-item-input"),n=h.one(".pb-total-page");h=h.one(".pb-total-count");var e=null;if(i&&n){i.val(this.curPage);e="\u9875 \u5171 "+this.totalPage+" \u9875";n.text(e)}h&&h.text(this.totalCount)}});return m},{requires:["./bar"]});
KISSY.add("gallery/grid/1.0/store",function(d){function r(m){m=m||{};m=d.merge({root:"rows",totalProperty:"results",dataType:"json",autoLoad:false,sortInfo:{field:"",direction:"ASC"},proxy:{method:"post"},params:{},remoteSort:false,matchFunction:function(k,h){return k==h},compareFunction:function(k,h){if(k==undefined)k="";if(h==undefined)h="";if(d.isString(k))return k.localeCompare(h);return k>h?1:k===h?0:-1}},m);d.mix(this,m,{hasLoad:false,resultRows:[],rowCount:0,totalCount:0});this.events=["load",
"beforeload","beforeProcessLoad","addrecords","exception","removerecords","updaterecord","localsort"];this._init()}d.augment(r,d.EventTarget);d.augment(r,{add:function(m,k,h){var i=this,n=[];h=h||i._getDefaultMatch();d.isArray(m)||(m=[m]);d.each(m,function(e){if(!k||!i.contains(e,h)){i._addRecord(e);n.push(e)}});i.fire("addrecords",{data:n})},compare:function(m,k,h,i){var n=1;h=h||this.sortInfo.field;i=i||this.sortInfo.direction;if(!h||!i)return 1;n=i==="ASC"?1:-1;return this.compareFunction(m[h],
k[h])*n},contains:function(m,k){return this.findIndexBy(m,k)!==-1},findIndexBy:function(m,k){var h=-1,i=this.resultRows;k=k||_self._getDefaultMatch();if(d.isUndefined(m)||d.isNull(m))return-1;d.each(i,function(n,e){if(k(m,n)){h=e;return false}});return h},find:function(m,k){var h=null;d.each(this.resultRows,function(i){if(i[name]===k){h=i;return false}});return h},findAll:function(m,k){var h=[];d.each(this.resultRows,function(i){i[name]===k&&h.push(i)});return h},load:function(m){this._loadData(m)},
getResult:function(){return this.resultRows},getCount:function(){return this.resultRows.length},getTotalCount:function(){return this.totalCount},remove:function(m,k){var h=this,i=[];k=k||h._getDefaultMatch();d.isArray(m)||(m=[m]);d.each(m,function(n){n=h.findIndexBy(n,k);n=h._removeAt(n);i.push(n)});h.fire("removerecords",{data:i})},setResult:function(m){this.resultRows=m=m||[];this.totalCount=this.rowCount=m.length;this.fire("load",this.oldParams)},setValue:function(m,k,h,i){var n=m;if(i){i=this._getDefaultMatch();
m=this.findIndexBy(m,i);if(m>=0)n=this.resultRows[m]}n[k]=h;this.fire("updaterecord",{record:n,field:k,value:h})},sort:function(m,k){this.sortInfo.field=m||this.sortInfo.field;this.sortInfo.direction=k||this.sortInfo.direction;if(this.remoteSort)this.load();else{this._sortData(m,k);this.fire("localsort",{field:m,direction:k})}},update:function(m,k){var h=m;if(k){var i=this._getDefaultMatch();i=this.findIndexBy(m,i);if(i>=0)h=this.resultRows[i]}h=d.mix(h,m);this.fire("updaterecord",{record:h})},_addRecord:function(m,
k){var h=this.resultRows;if(d.isUndefined(k))k=h.length;h[k]=m},_loadData:function(m){var k=this,h=m||{};k.fire("beforeload");h=d.merge(k.oldParams,k.sortInfo,h);k.oldParams=h;m=k.proxy.method==="post"?h:h?d.param(h):"";d.ajax({cache:false,url:k.proxy.url,dataType:k.dataType,type:k.proxy.method,data:m,success:function(i){k.fire("beforeProcessLoad",{data:i});var n=[],e=0,f=0;if(i.hasError){e=e;f=f;k.resultRows=n;k.rowCount=e;k.totalCount=f;k.fire("exception",{error:i.error})}else{if(k.dataType==="json")if(d.isArray(i)){n=
i;f=e=n.length}else if(i!=null){(n=i[k.root])||(n=[]);e=n.length;f=parseInt(i[k.totalProperty])}i=e;f=f;k.resultRows=n;k.rowCount=i;k.totalCount=f;k.remoteSort||k._sortData();k.fire("load",h)}},error:function(i,n,e){k.resultRows=[];k.rowCount=0;k.totalCount=0;k.fire("exception",{error:n,responseText:e.responseText,XMLHttpRequest:i})}})},_removeAt:function(m){if(!(m<0)){var k=this.resultRows,h=k[m];k.splice(m,1);return h}},_sortData:function(m,k){var h=this;m=m||h.sortInfo.field;k=k||h.sortInfo.direction;
m&&k&&h.resultRows.sort(function(i,n){return h.compare(i,n,m,k)})},_getDefaultMatch:function(){return this.matchFunction},_init:function(){this.oldParams=this.params||{};if(!this.proxy.url)this.proxy.url=this.url;this.resultRows=[]}});return r},{requires:[]});
KISSY.add("gallery/grid/1.0/util",function(d,r){var m=d.DOM,k=d.Event,h=window,i=d.UA,n={};d.mix(n,{mask:function(){function e(){g&&clearTimeout(g);g=setTimeout(f,300)}function f(){var l=m.viewportHeight();c.height(b>l?b:l)}var j=d.one("body"),b=j.height(),a=m.viewportHeight();a=b>a?b:a;var c=n.maskElement(j);c.height(a);k.on(h,"resize",e);c.data("reszieFunc",e);var g=null},unmask:function(){var e=d.one("body"),f=e.children(".lp-el-mask"),j=f.data("reszieFunc");if(j){k.remove(h,"resize",j);f.data("reszieFunc",
null)}n.unmaskElement(e)},maskElement:function(e,f,j){e=d.one(e);var b=e.getDOMNode(),a=d.one(".lp-el-mask",b);if(!a){a=d.one(m.create('<div class="lp-el-mask"></div>')).appendTo(b);e.addClass("x-masked-relative x-masked");i.ie==6&&a.height(e.height());if(f){f=['<div class="lp-el-mask-msg"><div>',f,"</div></div>"].join("");f=d.one(m.create(f)).appendTo(b);j&&f.addClass(j);try{var c=(e.width()-f.width())/2,g=(e.height()-f.height())/2;f.css({left:c,top:g})}catch(l){d.log("width error!")}}}return a},
unmaskElement:function(e){e=d.one(e);e.getDOMNode();var f=e.children(".lp-el-mask-msg"),j=e.children(".lp-el-mask");f&&f.remove();j&&j.remove();e.removeClass("x-masked-relative x-masked")}});n.Format=function(){return{dateRenderer:function(e){if(!e)return"";try{var f=new Date(e)}catch(j){return""}if(!f||!f.getFullYear)return"";return r.Date.format(e,"yyyy-mm-dd")},datetimeRenderer:function(e){if(!e)return"";try{var f=new Date(e)}catch(j){return""}if(!f||!f.getFullYear)return"";return r.Date.format(e,
"yyyy-mm-dd HH:MM:ss")},cutTextRenderer:function(e){return function(f){f=f||"";if(f.toString().length>e)return f.toString().substring(0,e)+"...";return f}},enumRenderer:function(e){return function(f){return e[f]||""}},multipleItemsRenderer:function(e){var f=n.Format.enumRenderer(e);return function(j){if(!j)return"";var b=[];if(d.isArray(j))j=j.toString().split(",");d.each(j,function(a){b.push(f(a))});return b.join(",")}}}}();n.FormHelpr={serialize:function(e){return d.param(n.FormHelpr.serializeToObject(e))},
serializeToObject:function(e){e=d.makeArray(e.elements);e=d.filter(e,function(b){return(b.id||b.name)&&!b.disabled&&(this.checked||/select|textarea/i.test(b.nodeName)||/text|hidden|password/i.test(b.type))});var f=[];d.each(e,function(b){var a=d.one(b).val();(a=a==null?null:d.isArray(a)?d.map(a,function(c){return{name:b.name||b.id,value:c}}):{name:b.name||b.id,value:a})&&f.push(a)});var j={};d.each(f,function(b){var a=j[b.name];if(a)if(d.isArray(a))a.push(b.value);else{var c=[];c.push(a);c.push(b.value);
j[b.name]=c}else j[b.name]=b.value});return j}};return n},{requires:["calendar"]});
