KISSY.add("gallery/form/1.1/uploader/auth/base",function(d,n,m){function j(a,c){c=d.merge({uploader:a},c);j.superclass.constructor.call(this,c);this._init()}var g=g||d;d.mix(j,{event:{ERROR:"error"}});d.extend(j,m,{_init:function(){var a=this,c=a.get("uploader"),b=c.get("queue");if(c==""){g.log("[uploader-auth]:uploader不可以为空！");return false}a._setSwfButtonExt();b.on("add",function(f){f=f.file;a.testAllowExt(f);a.testMaxSize(f);a.testRepeat(f)});b.on("remove",function(f){f.file.status=="success"&&
a.testMax()});c.on("success",function(){a.testMax()});c.on("error",function(){c.set("isAllowUpload",true)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(a){return this.get("rules")[a]},isUploaderType:function(a){var c=this.get("uploader").get("type");return a==c},testRequire:function(){var a=this.get("uploader").get("urlsInput").get("urls"),c=this.getRule("require"),b=c?c[0]:false;a=a.length>0;if(!b)return true;if(!a){d.log("[uploader-auth]:"+c[1]);this.fire(j.event.ERROR,
{rule:"require",msg:c[1],value:b})}return a},testAllowExt:function(a){function c(i){i=i.split(".");return i[i.length-1]}if(!d.isObject(a))return false;var b=a.name,f=this.getRule("allowExts"),e=[],h;if(!d.isArray(f))return false;e=this._getExts(f[0].ext);h=function(i){var k=false,l;d.each(e,function(o){l=RegExp("^.+."+o+"$");if(l.test(i))return k=true});return k}(b);if(!h){b=c(b);b=d.substitute(f[1],{ext:b});this._stopUpload(a,b);this.fire(j.event.ERROR,{rule:"allowExts",msg:b,value:f[0]})}return h},
testMax:function(){var a=this.get("uploader"),c=a.get("queue").getFiles("success").length,b=this.getRule("max");if(b){var f=a.get("button");if(c=c<b[0]){f.set("disabled",false);a.set("isAllowUpload",true)}else{f.set("disabled",true);a.set("isAllowUpload",false);this.fire(j.event.ERROR,{rule:"max",msg:b[1],value:b[0]})}return c}},testMaxSize:function(a){var c=a.size,b=this.getRule("maxSize");if(b){var f=Number(b[0])*1E3;c=c<=f;if(!c){f=d.substitute(b[1],{maxSize:d.convertByteSize(f),size:a.textSize});
this._stopUpload(a,f);this.fire(j.event.ERROR,{rule:"maxSize",msg:f,value:b[0]})}return c}},testRepeat:function(a){if(!d.isObject(a))return false;var c=this,b=a.name,f=c.getRule("allowRepeat");if(f){var e=f[0],h=f[1],i=c.get("uploader").get("queue").getFiles("success"),k=false;if(e)return false;d.each(i,function(l){if(l.name==b){c._stopUpload(a,h);c.fire(j.event.ERROR,{rule:"allowRepeat",msg:h,value:f[0]});return k=true}});return k}},_setSwfButtonExt:function(){var a=this.get("uploader"),c=this.getRule("allowExts");
a=a.get("button");if(!this.isUploaderType("flash")||!d.isArray(c))return false;a.set("fileFilters",c[0]);return this},_getExts:function(a){if(!d.isString(a))return false;var c=a.split(";"),b=[],f=/^\*\./;d.each(c,function(e){e=e.replace(f,"");b.push(e.toUpperCase())});d.each(b,function(e){c.push(e)});return c},_stopUpload:function(a,c){d.isString(c)||(c="");var b=this.get("uploader").get("queue"),f=b.getFileIndex(a.id);b.fileStatus(f,b.constructor.status.ERROR,{msg:c})}},{ATTRS:{uploader:{value:""},
rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"不支持{ext}格式的文件上传！"],require:[false,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[false,"该文件已经存在！"]}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/base",function(d,n,m,j,g,a,c){function b(e){b.superclass.constructor.call(this,e)}var f=m.all;d.mix(b,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});d.extend(b,
n,{render:function(){var e=this.get("serverConfig"),h=this.getUploadType(this.get("type")),i=h.event,k;if(!h)return false;this.set("urlsInput",this._renderUrlsInput());this._renderQueue();k=this._renderButton();this.get("type")==b.type.FLASH&&d.mix(e,{swfUploader:k.get("swfUploader")});e=new h(e);e.on(i.SUCCESS,this._uploadCompleteHanlder,this);i.PROGRESS&&e.on(i.PROGRESS,this._uploadProgressHandler,this);e.on(i.STOP,this._uploadStopHanlder,this);this.set("uploadType",e);this.fire(b.event.RENDER);
return this},upload:function(e){if(!d.isNumber(e))return false;var h=this.get("uploadType"),i=this.get("type"),k=this.get("queue"),l=k.get("files")[e],o;if(!d.isPlainObject(l)){d.log("[uploader]:队列中不存在id为"+e+"的文件");return false}if(this.get("curUploadIndex")!=""){alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！");return false}o=l.input.id||l.input;if(i=="ajax")o=l.data;if(l.status==="error")return false;this.fire(b.event.START,{index:e,file:l});if(!this.get("isAllowUpload"))return false;this.set("curUploadIndex",
e);k.fileStatus(e,b.status.START);h.upload(o)},cancel:function(e){var h=this.get("uploadType"),i=this.get("queue"),k=b.status,l=i.fileStatus(e);if(d.isNumber(e)&&l!=k.SUCCESS)i.fileStatus(e,k.CANCEL);else{h.stop();this._continueUpload()}return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(e){if(!d.isString(e))e=b.status.WAITING;this.set("uploadFilesStatus",e);this._uploaderStatusFile(e);return this},_uploaderStatusFile:function(e){e=this.get("queue").getIndexs(e);
if(!e.length){this.set("uploadFilesStatus","");this.fire(b.event.UPLOAD_FILES);return false}this.upload(e[0]);return this},isSupportAjax:function(){var e=false;try{if(FormData)e=true}catch(h){e=false}return e},isSupportFlash:function(){var e=d.UA.fpv();return d.isArray(e)&&e.length>0},getUploadType:function(e){var h=this,i=b.type,k;if(e==i.AUTO)e=[i.AJAX,i.IFRAME];if(d.isArray(e)&&e.length>0)d.each(e,function(l){if(k=h._getType(l))return false});else k=h._getType(e);return k},_getType:function(e){var h=
b.type,i=this.isSupportAjax(),k=this.isSupportFlash();switch(e){case h.IFRAME:h=g;break;case h.AJAX:h=i&&a||false;break;case h.FLASH:h=k&&c||false;break;default:d.log("[uploader]:type参数不合法");return false}h&&d.log("[uploader]:使用"+e+"上传方式");this.set("type",e);return h},_renderButton:function(){var e=this.get("button");if(!d.isObject(e)){d.log("[uploader]:button参数不合法！");return false}e.on("change",this._select,this);e.render();return e},_renderQueue:function(){var e=this.get("queue"),h=this.get("urlsInput");
if(!d.isObject(e)){d.log("[uploader]:queue参数不合法");return false}e.set("uploader",this);e.on("remove",function(i){h.remove(i.file.sUrl)});return e},_select:function(e){var h=this,i=h.get("autoUpload"),k=h.get("queue"),l=h.get("curUploadIndex"),o=e.files;d.each(o,function(p){if(!p.size)p.size=0;if(!p.name)p.name=p.fileName||"";p.input=e.input||p});h.fire(b.event.SELECT,{files:o});if(!h.get("isAllowUpload"))return false;k.add(o,function(){l==""&&i&&h.uploadFiles()})},_renderUrlsInput:function(){var e=
this.get("button").get("target"),h=this.get("urlsInputName");e=new j(e,{name:h});e.render();return e},_uploadCompleteHanlder:function(e){e=e.result;var h,i=b.event,k=this.get("queue"),l=this.get("curUploadIndex");if(!d.isObject(e))return false;k.updateFile(l,{result:e});h=Number(e.status);if(h===1){k.fileStatus(l,b.status.SUCCESS);this._success(e.data);this.fire(i.SUCCESS,{index:l,file:k.getFile(l),result:e})}else{k.fileStatus(l,b.status.ERROR,{msg:e.msg||e.message||"",result:e});this.fire(i.ERROR,
{status:h,result:e})}this.set("curUploadIndex","");this.fire(i.COMPLETE,{index:l,file:k.getFile(l),result:e});this._continueUpload()},_uploadStopHanlder:function(){var e=this.get("queue"),h=this.get("curUploadIndex");e.fileStatus(h,b.status.CANCEL);this.set("curUploadIndex","");this.fire(b.event.CANCEL,{index:h})},_continueUpload:function(){var e=this.get("uploadFilesStatus");e!=""&&this._uploaderStatusFile(e)},_uploadProgressHandler:function(e){var h=this.get("queue"),i=this.get("curUploadIndex"),
k=h.getFile(i);d.mix(e,{file:k});h.fileStatus(i,b.status.PROGRESS,e);this.fire(b.event.PROGRESS,e)},_success:function(e){if(!d.isObject(e))return false;e=e.url;var h=this.get("urlsInput"),i=this.get("curUploadIndex"),k=this.get("queue");if(!d.isString(e)||!d.isObject(h))return false;k.updateFile(i,{sUrl:e});h.add(e)},restore:function(){var e=this.get("queue"),h=this.get("restoreHook");h=f(h);var i=[];if(!h.length)return false;i=d.JSON.parse(h.html());if(!i.length)return false;d.each(i,function(k){k=
e.add(k);var l=k.id,o=e.getFileIndex(l);e.fileStatus(o,"success",{index:o,id:l,file:k})})}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:b.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:true},autoUpload:{value:true},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""},restoreHook:{value:""}}});d.convertByteSize=function(e){var h=-1;do{e/=1024;h++}while(e>99);return Math.max(e,
0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][h]};return b},{requires:["base","node","./urlsInput","./type/iframe","./type/ajax","./type/flash","flash"]});
KISSY.add("gallery/form/1.1/uploader/button/base",function(d,n,m){function j(a,c){c=d.merge({target:g(a)},c);j.superclass.constructor.call(this,c)}var g=n.all;d.mix(j,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(a){return a.replace(/.*(\/|\\)/,"")}});d.extend(j,m,{render:function(){var a=this.get("target");if(this.fire(j.event.beforeRender)===false){d.log("[Uploader-Button] button render was prevented.");
return false}else{if(a==null){d.log("[Uploader-Button] Cannot find target!");return false}this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(j.event.afterRender);return this}},show:function(){this.get("target").show();this.fire(j.event.afterShow);return j},hide:function(){this.get("target").hide();this.fire(j.event.afterHide);return j},reset:function(){var a=this.get("inputContainer");g(a).remove();this.set("inputContainer","");this.set("fileInput",
"");this._createInput();return this},_createInput:function(){var a=this.get("target"),c=this.get("name"),b=this.get("tpl");if(!d.isString(c)||!d.isString(b)){d.log("[Uploader-Button] No name or tpl specified.");return false}c=d.substitute(b,{name:c});c=g(c);g(c).appendTo(a);a=g(c).children("input");g(a).on("change",this._changeHandler,this);this.set("fileInput",a);this.set("inputContainer",c);return c},_changeHandler:function(a){var c=this.get("fileInput"),b=g(c).val();a=a.target.files;var f=[];if(b==
""){d.log("[Uploader-Button] No file selected.");return false}a?d.each(a,function(e){d.isObject(e)&&f.push({name:e.name,type:e.type,size:e.size,data:e})}):f.push({name:j.getFileName(b)});this.fire(j.event.CHANGE,{files:f,input:c.getDOMNode()});this.reset()},_setDisabled:function(a){var c=this.get("cls").disabled,b=this.get("target"),f=this.get("fileInput");if(!b.length||!d.isBoolean(a))return false;if(a){b.addClass(c);g(f).hide()}else{b.removeClass(c);g(f).show()}return a},_setMultiple:function(a){var c=
this.get("fileInput");if(!c.length)return false;a&&c.attr("multiple","multiple")||c.removeAttr("multiple");return a}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(a){this.get("fileInput")&&g(this.get("fileInput")).attr("name",a);return a}},disabled:{value:false,setter:function(a){this._setDisabled(a);return a}},
multiple:{value:true,setter:function(a){this._setMultiple(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/button/swfButton",function(d,n,m,j){function g(c,b){b=d.merge({target:a(c)},b);g.superclass.constructor.call(this,b)}var a=n.all;d.mix(g,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});d.extend(g,m,{render:function(){var c=this,b=c.get("target"),f,e=c.get("multiple"),h=c.get("fileFilters");b.css("position","relative");c.set("swfWrapper",c._createSwfWrapper());c._setFlashSizeConfig();
f=c._initSwfUploader();f.on("contentReady",function(){f.browse(e,h);c._bindBtnEvent();f.on("fileSelect",c._changeHandler,c);c._setDisabled(c.get("disabled"));c.fire(g.event.RENDER)},c)},_createSwfWrapper:function(){var c=this.get("target"),b=this.get("tpl"),f=this.get("swfWrapperId")!=""&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+d.guid();b=d.substitute(b,{id:f});this.set("swfWrapperId",f);return a(b).appendTo(c)},_initSwfUploader:function(){var c=this.get("flash"),b=this.get("swfWrapperId"),
f;try{f=new j(b,c);this.set("swfUploader",f)}catch(e){}return f},_bindBtnEvent:function(){var c=this,b=g.event,f=c.get("swfUploader");if(!f)return false;d.each(b,function(e){f.on(e,function(){c.fire(e)},c)});return c},_setFlashSizeConfig:function(){var c=this.get("flash"),b=this.get("target");d.mix(c.attrs,{width:b.width(),height:b.height()});this.set("flash",c)},_changeHandler:function(c){this.fire(g.event.CHANGE,{files:c.fileList})},_setDisabled:function(c){var b=this.get("swfUploader"),f=this.get("cls").disabled,
e=this.get("target"),h=this.get("swfWrapper");if(!b||!d.isBoolean(c))return false;if(c){e.addClass(f);h.hide()}else{e.removeClass(f);h.show()}return c}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:true,setter:function(c){var b=this.get("swfUploader");b&&b.multifile(c);return c}},fileFilters:{value:[],setter:function(c){var b=this.get("swfUploader");b&&
d.isArray(c)&&b.filter(c);return c}},disabled:{value:false,setter:function(c){this.get("swfUploader")&&this._setDisabled(c);return c}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.1/uploader/plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:true,btn:true}},swfUploader:{value:""}}});return g},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.1/uploader/index",function(d,n,m,j,g,a,c){function b(i,k,l){l=d.mix(d.form.parseConfig(i),l);b.superclass.constructor.call(this,l);this.set("buttonTarget",i);this.set("queueTarget",k);this.set("uploaderConfig",l);this._init()}var f=m.all,e={CONFIG:"data-config",BUTTON_CONFIG:"data-button-config",THEME_CONFIG:"data-theme-config",AUTH:"data-auth"},h=["default","imageUploader"];d.namespace("form");d.form.parseConfig=function(i,k){var l={},o,p=k||e.CONFIG;o=f(i).attr(p);if(!d.isString(o))return{};
try{l=d.JSON.parse(o)}catch(q){d.log("[uploaderRender]:请检查"+i+"上"+p+"属性内的json格式是否符合规范！")}return l};d.extend(b,n,{_init:function(){var i=this,k=i.get("uploaderConfig"),l=i.get("name"),o=i._initButton(),p;i.set("button",o);i._initThemes(function(q){p=q.get("queue");d.mix(k.serverConfig,{fileDataName:l});d.mix(k,{button:o,queue:p});var r=new j(k);r.render();i.set("uploader",r);q.set("uploader",r);q.set("button",o);q.set("auth",i._auth());q._UploaderRender(function(){r.restore();q.afterUploaderRender(r);
d.later(function(){i.fire("init",{uploader:r})})})})},_initButton:function(){var i=this.get("buttonTarget"),k=d.form.parseConfig(i,e.BUTTON_CONFIG),l=this.get("name"),o=this.get("type");k=d.merge({name:l},k);return o!="flash"&&new g(i,k)||new a(i)},_initThemes:function(i){var k=this,l=k.get("theme"),o=k.get("buttonTarget"),p=d.form.parseConfig(o,e.THEME_CONFIG);l=k._getThemeName(l);d.use(l,function(q,r){var s=k.get("queueTarget");q.mix(p,{queueTarget:s});s=new r(p);i&&i.call(k,s)})},_getThemeName:function(i){var k=
i;d.each(h,function(l){if(l==i)k="gallery/form/1.1/uploader/themes/"+i});k+="/index";return k},_auth:function(){var i=this.get("buttonTarget"),k=this.get("uploader"),l="";if(f(i).attr(e.AUTH)){i=d.form.parseConfig(i,e.AUTH);l=new c(k,{rules:i});k.set("auth",l)}return l}},{ATTRS:{theme:{value:"gallery/form/1.1/uploader/themes/default"},buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""},auth:{value:""}}});return b},{requires:["base",
"node","./base","./button/base","./button/swfButton","./auth/base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/ajbridge",function(d,n){function m(b,f,e){b=b.replace(j,"");f=n._normalize(f||{});var h=this;b=j+b;var i=function(k){if(k.status<1)h.fire("failed",{data:k});else{d.mix(h,k);if(!k.dynamic||!f.src)h.activate()}};f.id=f.id||d.guid(g);m.instances[f.id]=h;if(f.src){f.params.allowscriptaccess="always";f.params.flashvars=d.merge(f.params.flashvars,{jsEntry:c,swfID:f.id})}if(e)h.__args=[b,f,i];else d.later(n.add,a,false,n,[b,f,i])}var j="#",g="ks-ajb-",
a=100,c="KISSY.AJBridge.eventHandler";d.app(m,{version:"1.0.15",instances:{},eventHandler:function(b,f){var e=m.instances[b];e&&e.__eventHandler(b,f)},augment:function(b,f){if(d.isString(f))f=[f];d.isArray(f)&&d.each(f,function(e){b.prototype[e]=function(){try{return this.callSWF(e,d.makeArray(arguments))}catch(h){this.fire("error",{message:h})}}})}});d.augment(m,d.EventTarget,{init:function(){if(this.__args){n.add.apply(n,this.__args);this.__args=null;delete this.__args}},__eventHandler:function(b,
f){var e=f.type;f.id=b;switch(e){case "log":d.log(f.message);break;default:this.fire(e,f)}},callSWF:function(b,f){f=f||[];try{if(this.swf[b])return this.swf[b].apply(this.swf,f)}catch(e){var h="";if(f.length!==0)h="'"+f.join("','")+"'";return(new Function("self","return self.swf."+b+"("+h+");"))(this)}}});m.augment(m,["activate","getReady","getCoreVersion"]);return window.AJBridge=d.AJBridge=m},{requires:["flash"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/uploader",function(d,n,m){function j(g,a){a=a||{};var c={};d.each(["ds","dsp","btn","hand"],function(b){if(b in a)c[b]=a[b]});a.params=a.params||{};a.params.flashvars=d.merge(a.params.flashvars,c);j.superclass.constructor.call(this,g,a)}d.extend(j,m);m.augment(j,["setFileFilters","filter","setAllowMultipleFiles","multifile","browse","upload","uploadAll","cancel","getFile","removeFile","lock","unlock","setBtnMode","useHand","clear"]);j.version=
"1.0.1";m.Uploader=j;return m.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add("gallery/form/1.1/uploader/plugins/filedrop/filedrop",function(d,n,m){var j=n.all,g=d.UA,a=function(b){a.superclass.constructor.call(this,b);this.set("mode",c())},c=function(){if(g.webkit>=7||g.firefox>=3.6)return"supportDrop";if(g.ie)return"notSupportDropIe";if(g.webkit<7||g.firefox<3.6)return"notSupportDrop"};d.mix(a,{event:{AFTER_DROP:"afterdrop"}});d.extend(a,m,{render:function(){var b=this.get("mode"),f=this.get("uploader");if(b!="supportDrop"){d.log("该浏览器不支持拖拽上传！");return false}if(!f){d.log("缺少Uploader的实例！");
return false}b=this._createDropArea();b.length&&b.on("click",this._clickHandler,this);console.log("after randeer");this.fire("afterRender",{buttonTarget:this.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var b=this,f=j(b.get("target")),e=b.get("mode");e=d.substitute(b.get("tpl")[e],{name:b.get("name")});e=j(e);var h=e.all(".J_ButtonWrap");e.appendTo(f);e.on("dragover",function(i){i.stopPropagation();
i.preventDefault()});e.on("drop",function(i){i.stopPropagation();i.preventDefault();b._dropHandler(i)});b.set("dropContainer",e);b.set("buttonWrap",h);b._setStyle();return e},_setStyle:function(){var b=this.get("dropContainer");if(!b.length)return false;b.parent().css("position","relative");b.css({position:"absolute",top:"0",left:"0",width:"100%",height:"100%",zIndex:"1000"})},_clickHandler:function(b){j(b.target);this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(b){var f=
a.event;b=b.originalEvent.dataTransfer.files;var e=[],h=this.get("uploader");if(!b.length||h=="")return false;d.each(b,function(i){d.isObject(i)&&e.push({name:i.name,type:i.type,size:i.size,data:i})});this.fire(f.AFTER_DROP,{files:e});h._select({files:e})},_setDisabled:function(){}},{ATTRS:{target:{value:""},uploader:{value:""},dropContainer:{value:""},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>直接拖拽图片到这里，</p><p class="J_ButtonWrap">或者</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐使用chrome浏览器或firefox浏览器</p></div>',
notSupportDrop:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐升级您的浏览器</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:false,setter:function(b){this._setDisabled(b);return b}},cls:{disabled:"drop-area-disabled"}}});return a},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/preview/preview",function(d,n){function m(e,h){if(!e)return false;if(c!="filter")e.src=h||f;else{e.src=f;if(h){h=h.replace(/[)'"%]/g,function(i){return escape(escape(i))});e.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+h+"')";e.zoom=1}}return true}function j(e){this.config=d.mix({maxWidth:40,maxHeight:40},e);d.log(a+"Preview initialized. The preview mode is "+c)}var g=document,a="[Plugin: Preview] ",c=function(){var e=
"";if(typeof window.FileReader==="undefined")switch(d.UA.shell){case "firefox":e="domfile";break;case "ie":switch(d.UA.ie){case 6:e="simple";break;default:e="filter"}}else e="html5";return e}(),b={check:"check",success:"success",showed:"showed",error:"error"},f=d.UA.ie<8?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";d.augment(j,d.EventTarget,{preview:function(e,h){e=n.get(e);h=n.get(h);var i=this,k=function(){i.fire(b.getData,
{data:i.data,mode:c});if(h){m(h,i.data);i.fire(b.showed,{img:h})}};i.data=undefined;if(e){d.log(a+"One file selected. Getting data...");switch(c){case "domfile":i.data=e.files[0].getAsDataURL();break;case "filter":e.select();try{i.data=g.selection.createRange().text}catch(l){d.log(a+"Get image data error, the error is: ");d.log(l,"dir")}finally{g.selection.empty()}if(!i.data)i.data=e.value;break;case "html5":var o=new FileReader;o.onload=function(p){i.data=p.target.result;k()};o.onerror=function(){d.log(a+
"File Reader Error. Your browser may not fully support html5 file api","warning");i.fire(b.error)};e.files&&o.readAsDataURL(e.files[0]);break;default:i.data=e.value}if(i.data)k();else if(c!="html5"){d.log(a+"Retrive Data error.");m(h);i.fire(b.error)}}else d.log(a+"File Input Element does not exists.");return i.data}});return j},{requires:["dom","event"]});
KISSY.add("gallery/form/1.1/uploader/plugins/progressBar/progressBar",function(d,n,m){function j(a,c){c=d.merge({wrapper:g(a)},c);j.superclass.constructor.call(this,c)}var g=n.all;d.mix(j,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});d.extend(j,m,{render:function(){var a=this.get("wrapper"),c=this.get("width");if(!a.length)return false;
a.addClass(j.cls.PROGRESS_BAR).width(c);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(j.event.RENDER)},show:function(){var a=this;a.get("wrapper").fadeIn(a.get("duration"),function(){a.set("visible",true);a.fire(j.event.SHOW,{visible:true})})},hide:function(){var a=this;a.get("wrapper").fadeOut(a.get("duration"),function(){a.set("visible",false);a.fire(j.event.HIDE,{visible:false})})},_create:function(){var a=this.get("wrapper"),c=this.get("value"),b=this.get("tpl");
c=d.substitute(b,{value:c});a.html("");return g(c).appendTo(a)},_addAttr:function(){var a=this.get("wrapper"),c=this.get("value");a.attr("role","progressbar");a.attr("aria-valuemin",0);a.attr("aria-valuemax",100);a.attr("aria-valuenow",c);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(a){var c=this,b=c.get("wrapper"),f=c.get("bar"),e=c.get("speed"),h;if(a>100)a=100;if(a<0)a=0;h=b.width()*(a/100);f.animate({width:h+"px"},e,"none",function(){b.attr("aria-valuenow",
a);f.attr("data-value",a);c.fire(j.event.CHANGE,{value:a,width:h})});return a}},visible:{value:true},duration:{value:0.3},tpl:{value:j.tpl.DEFAULT},speed:{value:0.2}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/queue",function(d,n,m){function j(g){j.superclass.constructor.call(this,g)}d.mix(j,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",
SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});d.extend(j,m,{add:function(g,a){var c=this,b={};if(g.length>0){b=[];d.each(g,function(f){b.push(c._addFile(f))})}else b=c._addFile(g);a&&a.call(c);return b},_addFile:function(g,a){if(!d.isObject(g)){d.log("[uploader-queue]:_addFile()参数file不合法！");return false}var c=this._setAddFileData(g),b=this.getFileIndex(c.id),f=this.get("fnAdd");if(d.isFunction(f))c=
f(b,c);this.fire(j.event.ADD,{index:b,file:c,uploader:this.get("uploader")});a&&a.call(this,b,c);return c},remove:function(g,a){var c=this.get("files"),b;if(d.isString(g))g=this.getFileIndex(g);b=c[g];if(!d.isObject(b)){d.log("[uploader-queue]:remove()不存在index为"+g+"的文件数据");return false}c=d.filter(c,function(f,e){return e!==g});this.set("files",c);this.fire(j.event.REMOVE,{index:g,file:b});a&&a.call(this,g,b);return b},clear:function(){function g(){c=a.get("files");if(!c.length){a.fire(j.event.CLEAR);
return false}a.remove(0,function(){g()})}var a=this,c;g()},fileStatus:function(g,a,c){if(!d.isNumber(g)||!d.isString(a))return false;var b=this.getFile(g),f=this.get("theme"),e;if(!b||!f)return false;if(b.status==a)return this;this.updateFile(g,{status:a});e="_"+a+"Handler";if(d.isFunction(f[e])){c=d.merge({uploader:this.get("uploader"),index:g,file:b,id:b.id},c);f[e].call(f,c)}this.fire(j.event.FILE_STATUS,{index:g,status:a,args:c,file:b});return this},getFile:function(g){if(!d.isNumber(g))return false;
g=this.get("files")[g];if(!d.isPlainObject(g)){d.log("getFile():文件数据为空！");g={}}return g},getFileIndex:function(g){var a=this.get("files"),c=-1;d.each(a,function(b,f){if(b.id==g){c=f;return true}});return c},updateFile:function(g,a){if(!d.isNumber(g))return false;if(!d.isObject(a)){d.log("[uploader-queue]:updateFile()的data参数有误！");return false}var c=this.get("files"),b=this.getFile(g);if(!b)return false;d.mix(b,a);c[g]=b;this.set("files",c);this.fire(j.event.UPDATE_FILE,{index:g,file:b});return b},
getIndexs:function(g){var a=this.get("files"),c,b=[];if(!a.length)return b;d.each(a,function(f,e){if(d.isObject(f)){c=f.status;c==g&&b.push(e)}});return b},getFiles:function(g){var a=this.get("files"),c=[];if(!a.length)return[];d.each(a,function(b){b&&b.status==g&&c.push(b)});return c},_setAddFileData:function(g){var a=this.get("files");if(!d.isObject(g)){d.log("[uploader-queue]:_updateFileData()参数file不合法！");return false}if(!g.id)g.id=d.guid(j.FILE_ID_PREFIX);if(g.size)g.textSize=d.convertByteSize(g.size);
g.status="";a.push(g);return g}},{ATTRS:{fnAdd:{value:""},files:{value:[]},uploader:{value:""},theme:{value:""}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/theme",function(d,n,m,j){function g(b){g.superclass.constructor.call(this,b);this._LoaderCss();this._init()}var a=n.all,c={BUTTON:"-button",QUEUE:"-queue"};d.extend(g,m,{afterUploaderRender:function(){},_getStatusWrapper:function(b){return b.children(".J_FileStatus")},displayFile:function(b,f,e){var h=this,i=h.get("duration");if(!f||!f.length)return false;f[b&&"fadeIn"||"fadeOut"](i,function(){e&&e.call(h)})},_waitingHandler:function(){},_startHandler:function(){},
_progressHandler:function(){},_successHandler:function(){},_errorHandler:function(){},_restoreHandler:function(){},_init:function(){this._initQueue()},_UploaderRender:function(b){this._addThemeCssName();this._loadPlugins(b)},_addThemeCssName:function(){var b=this.get("name"),f=this.get("queue"),e=a(this.get("queueTarget")),h=this.get("button");if(b==""||!f||!e.length)return false;e.addClass(b+c.QUEUE);if(!h)return false;h.get("target").addClass(b+c.BUTTON)},_initQueue:function(){var b=this,f=new j({fnAdd:function(e,
h){return b._addCallback(e,h)}});f.set("theme",b);b.set("queue",f);f.on("add",b._addFileHandler,b);f.on("remove",b._removeFileHandler,b);f.on("statusChange",function(e){b._setStatusVisibility(e)});return f},_LoaderCss:function(){var b=this.get("isUseCss"),f=this.get("cssUrl");if(!b)return false;d.use(f,function(){d.log(f+"加载成功！")})},_addCallback:function(b,f){var e=this.get("queue"),h=this._appendFileDom(f);e.updateFile(b,{target:h,statusWrapper:this._getStatusWrapper(h)});e.fileStatus(b,j.status.WAITING);
this.displayFile(true,h);this._bindTriggerEvent(b,f);return e.getFile(b)},_removeFileHandler:function(b){this.displayFile(false,b.file.target)},_bindTriggerEvent:function(b,f){var e=this.get("queue"),h=this.get("uploader"),i=f.id,k=a(".J_Upload_"+i),l=a(".J_Cancel_"+i),o=a(".J_Del_"+i);k.on("click",function(p){p.preventDefault();if(!d.isObject(h))return false;h.upload(b)});l.on("click",function(p){p.preventDefault();h.cancel(b)});o.on("click",function(p){p.preventDefault();e.remove(i)})},_setStatusVisibility:function(b){var f=
b.file.statusWrapper;b=b.file.status;if(!f||!f.length){d.log("状态容器层不存在！");return false}f.children(".status").hide();f.children("."+b+"-status").show()},_appendFileDom:function(b){var f=this.get("fileTpl"),e=a(this.get("queueTarget"));if(!e.length)return false;f=d.substitute(f,b);return a(f).hide().appendTo(e).data("data-file",b)},_loadPlugins:function(b){var f=this,e=f.get("plugins"),h=f.get("oPlugin"),i=[];if(!e.length)return false;d.each(e,function(k){i.push("gallery/form/1.1/uploader/plugins/"+
k+"/"+k)});d.use(i.join(","),function(){d.each(arguments,function(k,l){if(l>=1)h[e[l-1]]=k});f.set("oPlugin",h);b&&b.call(f,h)})}},{ATTRS:{name:{value:""},isUseCss:{value:true},cssUrl:{value:""},fileTpl:{value:""},plugins:{value:[]},oPlugin:{value:{}},queueTarget:{value:""},duration:{value:0.3},queue:{value:""},uploader:{value:""},button:{value:""},auth:{value:""}}});return g},{requires:["node","base","./queue"]});
KISSY.add("gallery/form/1.1/uploader/type/ajax",function(d,n,m){function j(g){j.superclass.constructor.call(this,g);this._setFormData()}d.mix(j,{event:d.merge(m.event,{PROGRESS:"progress"})});d.extend(j,m,{upload:function(g){if(!g){d.log("[uploader-AjaxType]:upload()，fileData参数有误！");return false}this._addFileData(g);this.send();return this},stop:function(){var g=this.get("xhr");if(!d.isObject(g)){d.log("[uploader-AjaxType]:stop()，io值错误！");return false}g.abort();this.fire(j.event.STOP);return this},
send:function(){var g=this,a=g.get("action"),c=g.get("formData"),b=new XMLHttpRequest;b.upload.addEventListener("progress",function(f){g.fire(j.event.PROGRESS,{loaded:f.loaded,total:f.total})});b.onload=function(){var f={};try{f=d.JSON.parse(b.responseText)}catch(e){d.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}g.fire(j.event.SUCCESS,{result:f})};b.open("POST",a,true);b.send(c);g._setFormData();g.set("xhr",b);return g},_setFormData:function(){try{this.set("formData",new FormData);this._processData()}catch(g){d.log("[uploader-AjaxType]:something error when reset FormData.");
d.log(g,"dir")}},_processData:function(){var g=this.get("data"),a=this.get("formData");d.each(g,function(c,b){a.append(b,c)});this.set("formData",a)},_addFileData:function(g){if(!d.isObject(g)){d.log("[uploader-AjaxType]:_addFileData()，file参数有误！");return false}var a=this.get("formData"),c=this.get("fileDataName");a.append(c,g);this.set("formData",a)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:false,cache:false,dataType:"json",contentType:false}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return j},{requires:["node","./base"]});KISSY.add("gallery/form/1.1/uploader/type/base",function(d,n,m){function j(g){j.superclass.constructor.call(this,g)}d.mix(j,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});d.extend(j,m,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/flash",function(d,n,m){function j(g){j.superclass.constructor.call(this,g);this._init()}d.mix(j,{event:d.merge(m.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});d.extend(j,m,{_init:function(){var g=this,a=g.get("swfUploader");if(!a){d.log("[uploader-FlashType]:swfUploader对象为空！");return false}a.on("contentReady",function(){g.fire(j.event.SWF_READY)},g);a.on("uploadStart",g._uploadStartHandler,g);a.on("uploadProgress",g._uploadProgressHandler,g);a.on("uploadCompleteData",
g._uploadCompleteDataHandler,g);a.on("uploadError",g._uploadErrorHandler,g)},upload:function(g){var a=this.get("swfUploader"),c=this.get("action"),b=this.get("data");this.set("uploadingId",g);a.upload(g,c,"POST",b);return this},stop:function(){var g=this.get("swfUploader"),a=this.get("uploadingId");if(a!=""){g.cancel(a);this.fire(j.event.STOP,{id:a})}return this},_uploadStartHandler:function(g){this.fire(j.event.START,{file:g.file})},_uploadProgressHandler:function(g){d.mix(g,{loaded:g.bytesLoaded,
total:g.bytesTotal});this.fire(j.event.PROGRESS,{loaded:g.loaded,total:g.total})},_uploadCompleteDataHandler:function(g){var a;try{a=JSON.parse(g.data)}catch(c){d.log("[uploader-FlashType]:json数据格式不合法！");this.fire(j.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(j.event.SUCCESS,{result:a})},_uploadErrorHandler:function(g){this.set("uploadingId","");this.fire(j.event.ERROR,{msg:g.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return j},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/type/iframe",function(d,n,m){function j(a){j.superclass.constructor.call(this,a)}var g=n.all;d.mix(j,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:d.mix(m.event,{CREATE:"create",REMOVE:"remove"})});
d.extend(j,m,{upload:function(a){a=g(a);if(!a.length)return false;this.fire(j.event.START,{input:a});this.set("fileInput",a);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(j.event.STOP);this.fire(j.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(a){if(!d.isObject(a)||d.isEmptyObject(a)){d.log("[uploader-iframeType]:data参数不是对象或者为空！");return false}var c="",b=this.get("tpl").HIDDEN_INPUT;
if(!d.isString(b))return false;for(var f in a)c+=d.substitute(b,{name:f,value:a[f]});return c},_createIframe:function(){var a=this.get("id"),c=this.get("tpl"),b=c.IFRAME,f=this.get("iframe");if(!d.isEmptyObject(f))return f;if(!d.isString(b)){d.log("[uploader-iframeType]:iframe的模板不合法！");return false}if(!d.isString(a)){d.log("[uploader-iframeType]:id必须存在且为字符串类型！");return false}a=d.substitute(c.IFRAME,{id:a});a=g(a);a.on("load",this._iframeLoadHandler,this);g("body").append(a);this.set("iframe",a);return a},
_iframeLoadHandler:function(a){var c=a.target;a=j.event.ERROR;c=c.contentDocument||window.frames[c.id].document;if(!c||!c.body){this.fire(a,{msg:"服务器端返回数据有问题！"});return false}c=c.body.innerHTML;d.log("[uploader-iframeType]:服务器端输出:"+c);if(c=="")return false;try{c=JSON.parse(c)}catch(b){d.log("[uploader-iframeType]:json数据格式不合法！");this.fire(a,{msg:"数据："+c+"不是合法的json数据"})}this.fire(j.event.SUCCESS,{result:c});this._remove()},_createForm:function(){var a=this.get("id"),c=this.get("tpl").FORM,b=this.get("data"),
f=this.get("action"),e=this.get("fileInput"),h="";if(!d.isString(c)){d.log("[uploader-iframeType]:form模板不合法！");return false}if(!d.isObject(b)){d.log("[uploader-iframeType]:data参数不合法！");return false}if(!d.isString(f)){d.log("[uploader-iframeType]:action参数不合法！");return false}b=this.dataToHidden(b);if(b=="")return false;h=d.substitute(c,{action:f,target:a,hiddenInputs:b});a=g(h).append(e);g("body").append(a);this.set("form",a);return a},_create:function(){var a=this._createIframe(),c=this._createForm();
this.fire(j.event.CREATE,{iframe:a,form:c})},_remove:function(){var a=this.get("form");this.get("iframe");a.remove();this.reset("form");this.fire(j.event.REMOVE,{form:a})}},{ATTRS:{tpl:{value:j.tpl},id:{value:"ks-uploader-iframe-"+d.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return j},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/urlsInput",function(d,n,m){function j(a,c){j.superclass.constructor.call(this,c);this.set("wrapper",g(a))}var g=n.all;d.mix(j,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});d.extend(j,m,{render:function(){var a=this.get("wrapper"),c=this.get("name");c=document.getElementsByName(c)[0];if(!d.isObject(a)){d.log("[uploader-urlsInput]:container参数不合法！");return false}if(c){d.log("[uploader-urlsInput]:urls input found");this.set("input",g(c))}else this._create();
return this},add:function(a){if(!d.isString(a)){d.log("[uploader-urlsInput]:add()的url参数不合法！");return false}var c=this.get("urls"),b=this.isExist(a);if(c[0]=="")c=[];if(b){d.log("[uploader-urlsInput]:add()，文件路径已经存在！");return this}c.push(a);this.set("urls",c);this._val();return this},remove:function(a){if(!a)return false;var c=this.get("urls"),b=this.isExist(a),f=RegExp(a);if(!b){d.log("[uploader-urlsInput]:remove()，不存在该文件路径！");return false}c=d.filter(c,function(e){return!f.test(e)});this.set("urls",
c);this._val();return c},parse:function(){var a=this.get("input");if(a){a=g(a).val();var c=this.get("split");a=a.split(c);this.set("urls",a);return a}else{d.log("[uploader-urlsInput]:cannot find urls input.");return[]}},_val:function(){var a=this.get("urls"),c=this.get("input"),b=this.get("split");a=a.join(b);c.val(a);return a},isExist:function(a){var c=false,b=this.get("urls"),f=RegExp(a);if(!b.length)return false;d.each(b,function(e){if(f.test(e))return c=true});return c},_create:function(){var a=
this.get("wrapper"),c=this.get("tpl"),b=this.get("name"),f=this.get("urls");if(!a||a.length<=0){d.log("[uploader-urlsInput]:UrlsInput container not specified!","warn");return false}if(!d.isString(c)||!d.isString("name")){d.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！");return false}c=g(d.substitute(c,{name:b,value:f}));a.append(c);this.set("input",c);d.log("[uploader-urlsInput]:input created.");return c}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:j.TPL},split:{value:",",setter:function(a){this._val();
return a}},input:{value:""},wrapper:{value:""}}});return j},{requires:["node","base"]});
