KISSY.add("gallery/form/1.1/uploader/auth/base",function(e,m,l){function h(a,b){b=e.merge({uploader:a},b);h.superclass.constructor.call(this,b);this._init()}var i=i||e;e.mix(h,{event:{ERROR:"error"}});e.extend(h,l,{_init:function(){var a=this,b=a.get("uploader"),d=b.get("queue");if(b==""){i.log("[uploader-auth]:uploader不可以为空！");return false}a._setSwfButtonExt();d.on("add",function(c){c=c.file;a.testAllowExt(c);a.testMaxSize(c);a.testRepeat(c)});d.on("remove",function(c){c.file.status.get("curType")==
"success"&&a.testMax()});b.on("success",function(){a.testMax()});b.on("error",function(){b.set("isAllowUpload",true)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(a){return this.get("rules")[a]},isUploaderType:function(a){var b=this.get("uploader").get("type");return a==b},testRequire:function(){var a=this.get("uploader").get("urlsInput").get("urls"),b=this.getRule("require"),d=b?b[0]:false;a=a.length>0;if(!d)return true;if(!a){e.log("[uploader-auth]:"+b[1]);this.fire(h.event.ERROR,
{rule:"require",msg:b[1],value:d})}return a},testAllowExt:function(a){function b(j){j=j.split(".");return j[j.length-1]}if(!e.isObject(a))return false;var d=a.name,c=this.getRule("allowExts"),f=[],g;if(!e.isArray(c))return false;f=this._getExts(c[0].ext);g=function(j){var k=false,n;e.each(f,function(o){n=RegExp("^.+."+o+"$");if(n.test(j))return k=true});return k}(d);if(!g){d=b(d);d=e.substitute(c[1],{ext:d});this._stopUpload(a,d);this.fire(h.event.ERROR,{rule:"allowExts",msg:d,value:c[0]})}return g},
testMax:function(){var a=this.get("uploader"),b=a.get("queue").getFiles("success").length,d=this.getRule("max");if(d){var c=a.get("button");if(b=b<d[0]){c.set("disabled",false);a.set("isAllowUpload",true)}else{c.set("disabled",true);a.set("isAllowUpload",false);this.fire(h.event.ERROR,{rule:"max",msg:d[1],value:d[0]})}return b}},testMaxSize:function(a){var b=a.size,d=this.getRule("maxSize");if(d){var c=Number(d[0])*1E3;b=b<=c;if(!b){c=e.substitute(d[1],{maxSize:e.convertByteSize(c),size:a.textSize});
this._stopUpload(a,c);this.fire(h.event.ERROR,{rule:"maxSize",msg:c,value:d[0]})}return b}},testRepeat:function(a){if(!e.isObject(a))return false;var b=this,d=a.name,c=b.getRule("allowRepeat");if(c){var f=c[0],g=c[1],j=b.get("uploader").get("queue").getFiles("success"),k=false;if(f)return false;e.each(j,function(n){if(n.name==d){b._stopUpload(a,g);b.fire(h.event.ERROR,{rule:"allowRepeat",msg:g,value:c[0]});return k=true}});return k}},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.getRule("allowExts");
a=a.get("button");if(!this.isUploaderType("flash")||!e.isArray(b))return false;a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!e.isString(a))return false;var b=a.split(";"),d=[],c=/^\*\./;e.each(b,function(f){f=f.replace(c,"");d.push(f.toUpperCase())});e.each(d,function(f){b.push(f)});return b},_stopUpload:function(a,b){e.isString(b)||(b="");var d=this.get("uploader").get("queue"),c=d.getFileIndex(a.id);d.fileStatus(c,d.constructor.status.ERROR,{msg:b})}},{ATTRS:{uploader:{value:""},
rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"不支持{ext}格式的文件上传！"],require:[false,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[false,"该文件已经存在！"]}}}});return h},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/base",function(e,m,l,h,i,a,b){function d(c){d.superclass.constructor.call(this,c)}e.mix(d,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});e.extend(d,m,{render:function(){var c=
this.get("serverConfig"),f=this.getUploadType(this.get("type")),g=f.event,j;if(!f)return false;this.set("urlsInput",this._renderUrlsInput());this._renderQueue();j=this._renderButton();this._restore();this.get("type")==d.type.FLASH&&e.mix(c,{swfUploader:j.get("swfUploader")});c=new f(c);c.on(g.SUCCESS,this._uploadCompleteHanlder,this);g.PROGRESS&&c.on(g.PROGRESS,this._uploadProgressHandler,this);c.on(g.STOP,this._uploadStopHanlder,this);this.set("uploadType",c);this.fire(d.event.RENDER);return this},
upload:function(c){if(!e.isNumber(c))return false;var f=this.get("uploadType"),g=this.get("queue"),j=g.get("files")[c],k;if(!e.isPlainObject(j)){e.log("[uploader]:队列中不存在id为"+c+"的文件");return false}if(this.get("curUploadIndex")!=""){alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！");return false}k=j.input.id||j.input;if(j.status==="error")return false;this.fire(d.event.START,{index:c,file:j});if(!this.get("isAllowUpload"))return false;this.set("curUploadIndex",c);g.fileStatus(c,d.status.START);
f.upload(k)},cancel:function(c){var f=this.get("uploadType"),g=this.get("queue"),j=d.status,k=g.fileStatus(c);if(e.isNumber(c)&&k!=j.SUCCESS)g.fileStatus(c,j.CANCEL);else{f.stop();this._continueUpload()}return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(c){if(!e.isString(c))c=d.status.WAITING;this.set("uploadFilesStatus",c);this._uploaderStatusFile(c);return this},_uploaderStatusFile:function(c){c=this.get("queue").getIndexs(c);if(!c.length){this.set("uploadFilesStatus",
"");this.fire(d.event.UPLOAD_FILES);return false}this.upload(c[0]);return this},isSupportAjax:function(){var c=false;try{if(FormData)c=true}catch(f){c=false}return c},isSupportFlash:function(){var c=e.UA.fpv();return e.isArray(c)&&c.length>0},getUploadType:function(c){var f=this,g=d.type,j;if(c==g.AUTO)c=[g.AJAX,g.IFRAME];if(e.isArray(c)&&c.length>0)e.each(c,function(k){if(j=f._getType(k))return false});else j=f._getType(c);return j},_getType:function(c){var f=d.type,g=this.isSupportAjax(),j=this.isSupportFlash();
switch(c){case f.IFRAME:f=i;break;case f.AJAX:f=g&&a||false;break;case f.FLASH:f=j&&b||false;break;default:e.log("[uploader]:type参数不合法");return false}f&&e.log("[uploader]:使用"+c+"上传方式");this.set("type",c);return f},_renderButton:function(){var c=this.get("button");if(!e.isObject(c)){e.log("[uploader]:button参数不合法！");return false}c.on("change",this._select,this);c.render();return c},_renderQueue:function(){var c=this.get("queue"),f=this.get("urlsInput");if(!e.isObject(c)){e.log("[uploader]:queue参数不合法");
return false}c.set("uploader",this);c.on("remove",function(g){f.remove(g.file.sUrl)});c.render();return c},_select:function(c){var f=this,g=f.get("autoUpload"),j=f.get("queue"),k=f.get("curUploadIndex"),n=c.files;e.each(n,function(o){if(!o.size)o.size=0;if(!o.name)o.name=o.fileName||"";o.input=c.input||o});f.fire(d.event.SELECT,{files:n});if(!f.get("isAllowUpload"))return false;j.add(n,function(){k==""&&g&&f.uploadFiles()})},_renderUrlsInput:function(){var c=this.get("button").get("target"),f=this.get("urlsInputName");
c=new h(c,{name:f});c.render();return c},_uploadCompleteHanlder:function(c){c=c.result;var f,g=d.event,j=this.get("queue"),k=this.get("curUploadIndex");if(!e.isObject(c))return false;j.updateFile(k,{result:c});f=Number(c.status);if(f===1){j.fileStatus(k,d.status.SUCCESS);this._success(c.data);this.fire(g.SUCCESS,{index:k,file:j.getFile(k),result:c})}else{j.fileStatus(k,d.status.ERROR,{msg:c.msg||c.message||"",result:c});this.fire(g.ERROR,{status:f,result:c})}this.set("curUploadIndex","");this.fire(g.COMPLETE,
{index:k,file:j.getFile(k),result:c});this._continueUpload()},_uploadStopHanlder:function(){var c=this.get("queue"),f=this.get("curUploadIndex");c.fileStatus(f,d.status.CANCEL);this.set("curUploadIndex","");this.fire(d.event.CANCEL,{index:f})},_continueUpload:function(){var c=this.get("uploadFilesStatus");c!=""&&this._uploaderStatusFile(c)},_uploadProgressHandler:function(c){var f=this.get("queue"),g=this.get("curUploadIndex"),j=f.getFile(g);e.mix(c,{file:j});f.fileStatus(g,d.status.PROGRESS,c);this.fire(d.event.PROGRESS,
c)},_success:function(c){if(!e.isObject(c))return false;c=c.url;var f=this.get("urlsInput"),g=this.get("curUploadIndex"),j=this.get("queue");if(!e.isString(c)||!e.isObject(f))return false;j.updateFile(g,{sUrl:c});f.add(c)},_restore:function(){var c=this.get("urlsInput").parse();c&&c.length>0&&this.get("queue").restore(c)}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:d.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:true},autoUpload:{value:true},
urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""}}});e.convertByteSize=function(c){var f=-1;do{c/=1024;f++}while(c>99);return Math.max(c,0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][f]};return d},{requires:["base","node","./urlsInput","./type/iframe","./type/ajax","./type/flash","flash"]});
KISSY.add("gallery/form/1.1/uploader/button/base",function(e,m,l){function h(a,b){b=e.merge({target:i(a)},b);h.superclass.constructor.call(this,b)}var i=m.all;e.mix(h,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(a){return a.replace(/.*(\/|\\)/,"")}});e.extend(h,l,{render:function(){var a=this.get("target");if(this.fire(h.event.beforeRender)===false){e.log("[Uploader-Button] button render was prevented.");
return false}else{if(a==null){e.log("[Uploader-Button] Cannot find target!");return false}this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(h.event.afterRender);return this}},show:function(){this.get("target").show();this.fire(h.event.afterShow);return h},hide:function(){this.get("target").hide();this.fire(h.event.afterHide);return h},reset:function(){var a=this.get("inputContainer");i(a).remove();this.set("inputContainer","");this.set("fileInput",
"");this._createInput();return this},_createInput:function(){var a=this.get("target"),b=this.get("name"),d=this.get("tpl");if(!e.isString(b)||!e.isString(d)){e.log("[Uploader-Button] No name or tpl specified.");return false}b=e.substitute(d,{name:b});b=i(b);i(b).appendTo(a);a=i(b).children("input");i(a).on("change",this._changeHandler,this);this.set("fileInput",a);this.set("inputContainer",b);return b},_changeHandler:function(a){var b=this.get("fileInput"),d=i(b).val();a=a.target.files;var c=[];if(d==
""){e.log("[Uploader-Button] No file selected.");return false}a?e.each(a,function(f){e.isObject(f)&&c.push({name:f.name,type:f.type,size:f.size})}):c.push({name:h.getFileName(d)});this.fire(h.event.CHANGE,{files:c,input:b.getDOMNode()});this.reset()},_setDisabled:function(a){var b=this.get("cls").disabled,d=this.get("target"),c=this.get("fileInput");if(!d.length||!e.isBoolean(a))return false;if(a){d.addClass(b);i(c).hide()}else{d.removeClass(b);i(c).show()}return a},_setMultiple:function(a){var b=
this.get("fileInput");if(!b.length)return false;a&&b.attr("multiple","multiple")||b.removeAttr("multiple");return a}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(a){this.get("fileInput")&&i(this.get("fileInput")).attr("name",a);return a}},disabled:{value:false,setter:function(a){this._setDisabled(a);return a}},
multiple:{value:false,setter:function(a){this._setMultiple(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}}}});return h},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/button/swfButton",function(e,m,l,h){function i(b,d){d=e.merge({target:a(b)},d);i.superclass.constructor.call(this,d)}var a=m.all;e.mix(i,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});e.extend(i,l,{render:function(){var b=this,d=b.get("target"),c,f=b.get("multiple"),g=b.get("fileFilters");d.css("position","relative");b.set("swfWrapper",b._createSwfWrapper());b._setFlashSizeConfig();
c=b._initSwfUploader();c.on("contentReady",function(){c.browse(f,g);b._bindBtnEvent();c.on("fileSelect",b._changeHandler,b);b._setDisabled(b.get("disabled"));b.fire(i.event.RENDER)},b)},_createSwfWrapper:function(){var b=this.get("target"),d=this.get("tpl"),c=this.get("swfWrapperId")!=""&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+e.guid();d=e.substitute(d,{id:c});this.set("swfWrapperId",c);return a(d).appendTo(b)},_initSwfUploader:function(){var b=this.get("flash"),d=this.get("swfWrapperId"),
c;try{c=new h(d,b);this.set("swfUploader",c)}catch(f){}return c},_bindBtnEvent:function(){var b=this,d=i.event,c=b.get("swfUploader");if(!c)return false;e.each(d,function(f){c.on(f,function(){b.fire(f)},b)});return b},_setFlashSizeConfig:function(){var b=this.get("flash"),d=this.get("target");e.mix(b.attrs,{width:d.width(),height:d.height()});this.set("flash",b)},_changeHandler:function(b){this.fire(i.event.CHANGE,{files:b.fileList})},_setDisabled:function(b){var d=this.get("swfUploader"),c=this.get("cls").disabled,
f=this.get("target"),g=this.get("swfWrapper");if(!d||!e.isBoolean(b))return false;if(b){f.addClass(c);g.hide()}else{f.removeClass(c);g.show()}return b}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:true,setter:function(b){var d=this.get("swfUploader");d&&d.multifile(b);return b}},fileFilters:{value:[],setter:function(b){var d=this.get("swfUploader");d&&
e.isArray(b)&&d.filter(b);return b}},disabled:{value:false,setter:function(b){this.get("swfUploader")&&this._setDisabled(b);return b}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.1/uploader/plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:true,btn:true}},swfUploader:{value:""}}});return i},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.1/uploader/index",function(e,m,l,h,i,a,b){function d(g,j,k){k=e.mix(e.parseConfig(g),k);d.superclass.constructor.call(this,k);this.set("buttonTarget",g);this.set("queueTarget",j);this.set("uploaderConfig",k);this._init()}var c=l.all,f={CONFIG:"data-config",BUTTON_CONFIG:"data-button-config",THEME_CONFIG:"data-theme-config",AUTH:"data-auth"};e.parseConfig=function(g,j){var k={},n,o=j||f.CONFIG;n=c(g).attr(o);if(!e.isString(n))return{};try{k=e.JSON.parse(n)}catch(p){e.log("[uploaderRender]:请检查"+
g+"上"+o+"属性内的json格式是否符合规范！")}return k};e.extend(d,m,{_init:function(){var g=this,j=g.get("uploaderConfig"),k=g.get("name"),n=g._initButton(),o;g.set("button",n);g._initThemes(function(p){o=p.get("queue");e.mix(j.serverConfig,{fileDataName:k});e.mix(j,{button:n,queue:o});var q=new h(j);q.render();g.set("uploader",q);p.set("uploader",q);p.set("button",n);var r=g._auth();p.set("auth",r);p.afterUploaderRender&&p.afterUploaderRender(q);g.fire("init",{uploader:q})})},_initButton:function(){var g=this.get("buttonTarget"),
j=e.parseConfig(g,f.BUTTON_CONFIG),k=this.get("name"),n=this.get("type");j=e.merge({name:k},j);return n!="flash"&&new i(g,j)||new a(g)},_initThemes:function(g){var j=this,k=j.get("theme"),n=j.get("buttonTarget"),o=e.parseConfig(n,f.THEME_CONFIG);e.use(k+"/index",function(p,q){var r=j.get("queueTarget");p.mix(o,{queueTarget:r});r=new q(o);g&&g.call(j,r)})},_auth:function(){var g=this.get("buttonTarget"),j=this.get("uploader"),k="";if(c(g).attr(f.AUTH)){g=e.parseConfig(g,f.AUTH);k=new b(j,{rules:g});
j.set("auth",k)}return k}},{ATTRS:{theme:{value:"gallery/form/1.1/uploader/themes/default"},buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""},auth:{value:""}}});return d},{requires:["base","node","./base","./button/base","./button/swfButton","./auth/base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/ajbridge",function(e,m){function l(d,c,f){d=d.replace(h,"");c=m._normalize(c||{});var g=this;d=h+d;var j=function(k){if(k.status<1)g.fire("failed",{data:k});else{e.mix(g,k);if(!k.dynamic||!c.src)g.activate()}};c.id=c.id||e.guid(i);l.instances[c.id]=g;if(c.src){c.params.allowscriptaccess="always";c.params.flashvars=e.merge(c.params.flashvars,{jsEntry:b,swfID:c.id})}if(f)g.__args=[d,c,j];else e.later(m.add,a,false,m,[d,c,j])}var h="#",i="ks-ajb-",
a=100,b="KISSY.AJBridge.eventHandler";e.app(l,{version:"1.0.15",instances:{},eventHandler:function(d,c){var f=l.instances[d];f&&f.__eventHandler(d,c)},augment:function(d,c){if(e.isString(c))c=[c];e.isArray(c)&&e.each(c,function(f){d.prototype[f]=function(){try{return this.callSWF(f,e.makeArray(arguments))}catch(g){this.fire("error",{message:g})}}})}});e.augment(l,e.EventTarget,{init:function(){if(this.__args){m.add.apply(m,this.__args);this.__args=null;delete this.__args}},__eventHandler:function(d,
c){var f=c.type;c.id=d;switch(f){case "log":e.log(c.message);break;default:this.fire(f,c)}},callSWF:function(d,c){c=c||[];try{if(this.swf[d])return this.swf[d].apply(this.swf,c)}catch(f){var g="";if(c.length!==0)g="'"+c.join("','")+"'";return(new Function("self","return self.swf."+d+"("+g+");"))(this)}}});l.augment(l,["activate","getReady","getCoreVersion"]);return window.AJBridge=e.AJBridge=l},{requires:["flash"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/uploader",function(e,m,l){function h(i,a){a=a||{};var b={};e.each(["ds","dsp","btn","hand"],function(d){if(d in a)b[d]=a[d]});a.params=a.params||{};a.params.flashvars=e.merge(a.params.flashvars,b);h.superclass.constructor.call(this,i,a)}e.extend(h,l);l.augment(h,["setFileFilters","filter","setAllowMultipleFiles","multifile","browse","upload","uploadAll","cancel","getFile","removeFile","lock","unlock","setBtnMode","useHand","clear"]);h.version=
"1.0.1";l.Uploader=h;return l.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add("gallery/form/1.1/uploader/plugins/filedrop/filedrop",function(e,m,l){var h=m.all,i=e.UA,a=function(d){a.superclass.constructor.call(this,d);this.set("mode",b())},b=function(){if(i.webkit>=7||i.firefox>=3.6)return"supportDrop";if(UQ.ie)return"notSupportDropIe";if(i.webkit<7||i.firefox<3.6)return"notSupportDrop"};e.mix(a,{event:{AFTER_DROP:"afterdrop"}});e.extend(a,l,{render:function(){this._createDropArea();console.log("after randeer");this.fire("afterRender",{buttonTarget:this.get("buttonWrap")})},
show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var d=this,c=h(d.get("target")),f=d.get("mode");f=e.substitute(d.get("tpl")[f],{name:d.get("name")});f=h(f);var g=f.all(".J_ButtonWrap");f.insertAfter(c);f.on("dragover",function(j){j.stopPropagation();j.preventDefault()});f.on("drop",function(j){j.stopPropagation();j.preventDefault();d._dropHandler(j)});d.set("dropContainer",f);d.set("buttonWrap",g)},_dropHandler:function(d){console.log("handler");
var c=a.event;d=d.originalEvent.dataTransfer.files;var f=[];if(d.lenght!=0){e.each(d,function(g){e.isObject(g)&&f.push({name:g.name,type:g.type,size:g.size,input:{files:[g]}})});this.fire(c.AFTER_DROP,{files:f})}},_setDisabled:function(){}},{ATTRS:{target:{value:null},fileInput:{value:""},dropContainer:{value:""},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>直接拖拽图片到这里，</p><p class="J_ButtonWrap">或者</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐使用chrome浏览器或firefox浏览器</p></div>',
notSupportDrop:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐升级您的浏览器</p></div>'}},btnTpl:{value:'<input type="file" name="dropFile" hidefoucs="true" class="file-input" />'},name:{value:"",setter:function(){}},disabled:{value:false,setter:function(d){this._setDisabled(d);return d}},cls:{disabled:"drop-area-disabled"}}});return a},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/preview/preview",function(e,m){function l(f,g){if(!f)return false;if(b!="filter")f.src=g||c;else{f.src=c;if(g){g=g.replace(/[)'"%]/g,function(j){return escape(escape(j))});f.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+g+"')";f.zoom=1}}return true}function h(f){this.config=e.mix({maxWidth:40,maxHeight:40},f);e.log(a+"Preview initialized. The preview mode is "+b)}var i=document,a="[Plugin: Preview] ",b=function(){var f=
"";if(typeof window.FileReader==="undefined")switch(e.UA.shell){case "firefox":f="domfile";break;case "ie":switch(e.UA.ie){case 6:f="simple";break;default:f="filter"}}else f="html5";return f}(),d={check:"check",success:"success",showed:"showed",error:"error"},c=e.UA.ie<8?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";e.augment(h,e.EventTarget,{preview:function(f,g){f=m.get(f);g=m.get(g);var j=this,k=function(){j.fire(d.getData,
{data:j.data,mode:b});if(g){l(g,j.data);j.fire(d.showed,{img:g})}};j.data=undefined;if(f){e.log(a+"One file selected. Getting data...");switch(b){case "domfile":j.data=f.files[0].getAsDataURL();break;case "filter":f.select();try{j.data=i.selection.createRange().text}catch(n){e.log(a+"Get image data error, the error is: ");e.log(n,"dir")}finally{i.selection.empty()}if(!j.data)j.data=f.value;break;case "html5":var o=new FileReader;o.onload=function(p){j.data=p.target.result;k()};o.onerror=function(){e.log(a+
"File Reader Error. Your browser may not fully support html5 file api","warning");j.fire(d.error)};o.readAsDataURL(f.files[0]);break;default:j.data=f.value}if(j.data)k();else if(b!="html5"){e.log(a+"Retrive Data error.");l(g);j.fire(d.error)}}else e.log(a+"File Input Element does not exists.");return j.data}});return h},{requires:["dom","event"]});
KISSY.add("gallery/form/1.1/uploader/plugins/progressBar/progressBar",function(e,m,l){function h(a,b){b=e.merge({wrapper:i(a)},b);h.superclass.constructor.call(this,b)}var i=m.all;e.mix(h,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});e.extend(h,l,{render:function(){var a=this.get("wrapper"),b=this.get("width");if(!a.length)return false;
a.addClass(h.cls.PROGRESS_BAR).width(b);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(h.event.RENDER)},show:function(){var a=this;a.get("wrapper").fadeIn(a.get("duration"),function(){a.set("visible",true);a.fire(h.event.SHOW,{visible:true})})},hide:function(){var a=this;a.get("wrapper").fadeOut(a.get("duration"),function(){a.set("visible",false);a.fire(h.event.HIDE,{visible:false})})},_create:function(){var a=this.get("wrapper"),b=this.get("value"),d=this.get("tpl");
b=e.substitute(d,{value:b});a.html("");return i(b).appendTo(a)},_addAttr:function(){var a=this.get("wrapper"),b=this.get("value");a.attr("role","progressbar");a.attr("aria-valuemin",0);a.attr("aria-valuemax",100);a.attr("aria-valuenow",b);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(a){var b=this,d=b.get("wrapper"),c=b.get("bar"),f=b.get("speed"),g;if(a>100)a=100;if(a<0)a=0;g=d.width()*(a/100);c.animate({width:g+"px"},f,"none",function(){d.attr("aria-valuenow",
a);c.attr("data-value",a);b.fire(h.event.CHANGE,{value:a,width:g})});return a}},visible:{value:true},duration:{value:0.3},tpl:{value:h.tpl.DEFAULT},speed:{value:0.2}}});return h},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/queue",function(e,m,l){function h(a,b){h.superclass.constructor.call(this,b);this.set("target",i(a))}var i=m.all;e.mix(h,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{RENDER:"render",ADD_DATA:"addData",ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",
RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});e.extend(h,l,{render:function(){this.get("target").addClass(h.cls.QUEUE);this.fire(h.event.RENDER);return this},add:function(a,b){var d=this,c=h.event;if(a.length>0){d._addFiles(a,function(){b&&b.call(d);d.fire(c.ADD_FILES,{files:a})});return false}else return d._addFile(a,
function(f,g){b&&b.call(d,f,g)})},_addFile:function(a,b){if(!e.isObject(a)){e.log("[uploader-queue]:_addFile()参数file不合法！");return false}var d=this,c=d.get("duration"),f=d._setAddFileData(a),g=d.getFileIndex(f.id);d.fileStatus(g,h.status.WAITING);f.target.fadeIn(c,function(){d.fire(h.event.ADD,{index:g,file:f,target:f.target,uploader:d.get("uploader")});b&&b.call(d,g,f)});return f},_addFiles:function(a,b){function d(f){if(f===a.length){b&&b.call(this);return false}c._addFile(a[f],function(){f++;d(f)})}
if(!a.length){e.log("[uploader-queue]:_addFiles()参数files不合法！");return false}var c=this;d(0)},remove:function(a,b){var d=this,c=d.get("files"),f,g,j=d.get("duration");if(e.isString(a))a=d.getFileIndex(a);f=c[a];if(!e.isObject(f)){e.log("[uploader-queue]:remove()不存在index为"+a+"的文件数据");return false}g=f.target;g.fadeOut(j,function(){g.remove();d.fire(h.event.REMOVE,{index:a,file:f});b&&b.call(d,a,f)});c=e.filter(c,function(k,n){return n!==a});d.set("files",c);return f},clear:function(){function a(){d=
b.get("files");if(!d.length){b.fire(h.event.CLEAR);return false}b.remove(0,function(){a()})}var b=this,d;a()},restore:function(a){var b=this,d=[];a&&a.length>0&&e.each(a,function(c,f){var g=c.split("|"),j="";if(g.length>1){c=g[1];j=g[0]}if(c){g=b._setAddFileData({input:null,name:j,sUrl:c,size:"",type:""});f=b.getFileIndex(g.id);b.fileStatus(f,h.status.RESTORE);i(g.target).show();d[f]=g}});b.fire(h.event.RESTORE,{files:d})},fileStatus:function(a,b,d){if(!e.isNumber(a)||!e.isString(b))return false;
var c=this.getFile(a),f=this.get("theme"),g;if(!c||!f)return false;if(c.status==b)return this;this.updateFile(a,{status:b});g="_"+b+"Handler";if(e.isFunction(f[g])){d=e.merge({uploader:this.get("uploader"),index:a,file:c,id:c.id},d);f[g].call(f,d)}this.fire(h.event.FILE_STATUS,{index:a,status:b,args:d,file:c});return this},getFile:function(a){if(!e.isNumber(a))return false;a=this.get("files")[a];e.isPlainObject(a)||(a=false);return a},getFileIndex:function(a){var b=this.get("files"),d=-1;e.each(b,
function(c,f){if(c.id==a){d=f;return true}});return d},updateFile:function(a,b){if(!e.isNumber(a))return false;if(!e.isObject(b)){e.log("[uploader-queue]:updateFile()的data参数有误！");return false}var d=this.get("files"),c=this.getFile(a);if(!c)return false;e.mix(c,b);d[a]=c;this.set("files",d);this.fire(h.event.UPDATE_FILE,{index:a,file:c});return c},getIndexs:function(a){var b=this.get("files"),d,c=[];if(!b.length)return c;e.each(b,function(f,g){if(e.isObject(f)){d=f.status;d==a&&c.push(g)}});return c},
getFiles:function(a){var b=this.get("files"),d=[];if(!b.length)return[];e.each(b,function(c){c&&c.status==a&&d.push(c)});return d},_setAddFileData:function(a){var b=this.get("files");if(!e.isObject(a)){e.log("[uploader-queue]:_updateFileData()参数file不合法！");return false}if(!a.id)a.id=e.guid(h.FILE_ID_PREFIX);if(a.size)a.textSize=e.convertByteSize(a.size);a.target=this._appendFileHtml(a);a.status="";b.push(a);this.fire(h.event.ADD_DATA,{file:a,index:b.length-1});return a},_appendFileHtml:function(a){var b=
this.get("target"),d=this.get("tpl");d=e.substitute(d,a);return i(d).hide().appendTo(b).data("data-file",a)}},{ATTRS:{tpl:{value:h.tpl.DEFAULT},duration:{value:0.3},target:{value:""},files:{value:[]},uploader:{value:""},theme:{value:""}}});return h},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/theme",function(e,m,l,h){function i(b){i.superclass.constructor.call(this,b);this._LoaderCss();this._init()}var a=m.all;e.extend(i,l,{_init:function(){var b=this._initQueue(),d=this.get("name");if(d!=""){b=b.get("target");b.length&&b.addClass(d+"-queue")}},_initQueue:function(){var b=this,d=b.get("queueTarget"),c,f={tpl:b.get("fileTpl")};e.mix(f,e.parseConfig(d,"data-queue-config"));c=new h(d,f);c.set("theme",b);b.set("queue",c);c.on("addData",function(g){c.updateFile(g.index,
{statusWrapper:b._getStatusWrapper(g.file.target)})});c.on("add",function(g){b._addFileHandler(g)});c.on("statusChange",function(g){b._setStatusVisibility(g)});return c},_getStatusWrapper:function(b){return b.children(".J_FileStatus")},_LoaderCss:function(){var b=this.get("isUseCss"),d=this.get("cssUrl");b&&e.use(d,function(){e.log(d+"加载成功！")})},afterUploaderRender:function(){},_addFileHandler:function(b){var d=this.get("queue"),c=b.uploader,f=b.index,g=b.file.id,j=a(".J_Upload_"+g),k=a(".J_Cancel_"+
g),n=a(".J_Del_"+g);j.on("click",function(o){o.preventDefault();if(!e.isObject(c))return false;c.upload(f)});k.on("click",function(o){o.preventDefault();c.cancel(f)});n.on("click",function(){b.preventDefault();d.remove(g)})},_setStatusVisibility:function(b){var d=b.file.statusWrapper;b=b.file.status;d.length||e.log("状态容器层不存在！");d.children(".status").hide();d.children("."+b+"-status").show()},_waitingHandler:function(){},_startHandler:function(){},_progressHandler:function(){},_successHandler:function(){},
_errorHandler:function(){},_restoreHandler:function(){}},{ATTRS:{name:{value:""},isUseCss:{value:true},cssUrl:{value:""},fileTpl:{value:""},queueTarget:{value:""},queue:{value:""},auth:{value:""}}});return i},{requires:["node","base","./queue"]});
KISSY.add("gallery/form/1.1/uploader/type/ajax",function(e,m,l){function h(a){h.superclass.constructor.call(this,a);this._setFormData()}var i=m.all;e.mix(h,{event:e.merge(l.event,{PROGRESS:"progress"})});e.extend(h,l,{upload:function(a){if(!a){e.log("[uploader-AjaxType]:upload()，fileInput参数有误！");return false}var b=a.files;if(!b.length){e.log("[uploader-AjaxType]:upload()，不存在要上传的文件！");return false}this._addFileData(a,b[0]);this.send();return this},stop:function(){var a=this.get("xhr");if(!e.isObject(a)){e.log("[uploader-AjaxType]:stop()，io值错误！");
return false}a.abort();this.fire(h.event.STOP);return this},send:function(){var a=this,b=a.get("action"),d=a.get("formData"),c=new XMLHttpRequest;c.upload.addEventListener("progress",function(f){a.fire(h.event.PROGRESS,{loaded:f.loaded,total:f.total})});c.onload=function(){var f={};try{f=e.JSON.parse(c.responseText)}catch(g){e.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}a.fire(h.event.SUCCESS,{result:f})};c.open("POST",b,true);c.send(d);a._setFormData();a.set("xhr",c);return a},_setFormData:function(){try{this.set("formData",
new FormData);this._processData()}catch(a){e.log("[uploader-AjaxType]:something error when reset FormData.");e.log(a,"dir")}},_processData:function(){var a=this.get("data"),b=this.get("formData");e.each(a,function(d,c){b.append(c,d)});this.set("formData",b)},_addFileData:function(a,b){if(!e.isObject(b)){e.log("[uploader-AjaxType]:_addFileData()，file参数有误！");return false}var d=this.get("formData"),c=this.get("fileDataName");if(c==""){c=i(a).attr("name");this.set("fileDataName",c)}d.append(c,b);this.set("formData",
d)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:false,cache:false,dataType:"json",contentType:false}},xhr:{value:""},fileDataName:{value:""},form:{value:{}},fileInput:{value:""}}});return h},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/type/base",function(e,m,l){function h(i){h.superclass.constructor.call(this,i)}e.mix(h,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});e.extend(h,l,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return h},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/flash",function(e,m,l){function h(i){h.superclass.constructor.call(this,i);this._init()}e.mix(h,{event:e.merge(l.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});e.extend(h,l,{_init:function(){var i=this,a=i.get("swfUploader");if(!a){e.log("[uploader-FlashType]:swfUploader对象为空！");return false}a.on("contentReady",function(){i.fire(h.event.SWF_READY)},i);a.on("uploadStart",i._uploadStartHandler,i);a.on("uploadProgress",i._uploadProgressHandler,i);a.on("uploadCompleteData",
i._uploadCompleteDataHandler,i);a.on("uploadError",i._uploadErrorHandler,i)},upload:function(i){var a=this.get("swfUploader"),b=this.get("action"),d=this.get("data");this.set("uploadingId",i);a.upload(i,b,"POST",d);return this},stop:function(){var i=this.get("swfUploader"),a=this.get("uploadingId");if(a!=""){i.cancel(a);this.fire(h.event.STOP,{id:a})}return this},_uploadStartHandler:function(i){this.fire(h.event.START,{file:i.file})},_uploadProgressHandler:function(i){e.mix(i,{loaded:i.bytesLoaded,
total:i.bytesTotal});this.fire(h.event.PROGRESS,{loaded:i.loaded,total:i.total})},_uploadCompleteDataHandler:function(i){var a;try{a=JSON.parse(i.data)}catch(b){e.log("[uploader-FlashType]:json数据格式不合法！");this.fire(h.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(h.event.SUCCESS,{result:a})},_uploadErrorHandler:function(i){this.set("uploadingId","");this.fire(h.event.ERROR,{msg:i.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return h},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/type/iframe",function(e,m,l){function h(a){h.superclass.constructor.call(this,a)}var i=m.all;e.mix(h,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:e.mix(l.event,{CREATE:"create",REMOVE:"remove"})});
e.extend(h,l,{upload:function(a){a=i(a);if(!a.length)return false;this.fire(h.event.START,{input:a});this.set("fileInput",a);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(h.event.STOP);this.fire(h.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(a){if(!e.isObject(a)||e.isEmptyObject(a)){e.log("[uploader-iframeType]:data参数不是对象或者为空！");return false}var b="",d=this.get("tpl").HIDDEN_INPUT;
if(!e.isString(d))return false;for(var c in a)b+=e.substitute(d,{name:c,value:a[c]});return b},_createIframe:function(){var a=this.get("id"),b=this.get("tpl"),d=b.IFRAME,c=this.get("iframe");if(!e.isEmptyObject(c))return c;if(!e.isString(d)){e.log("[uploader-iframeType]:iframe的模板不合法！");return false}if(!e.isString(a)){e.log("[uploader-iframeType]:id必须存在且为字符串类型！");return false}a=e.substitute(b.IFRAME,{id:a});a=i(a);a.on("load",this._iframeLoadHandler,this);i("body").append(a);this.set("iframe",a);return a},
_iframeLoadHandler:function(a){var b=a.target;a=h.event.ERROR;b=b.contentDocument||window.frames[b.id].document;if(!b||!b.body){this.fire(a,{msg:"服务器端返回数据有问题！"});return false}b=b.body.innerHTML;e.log("[uploader-iframeType]:服务器端输出:"+b);if(b=="")return false;try{b=JSON.parse(b)}catch(d){e.log("[uploader-iframeType]:json数据格式不合法！");this.fire(a,{msg:"数据："+b+"不是合法的json数据"})}this.fire(h.event.SUCCESS,{result:b});this._remove()},_createForm:function(){var a=this.get("id"),b=this.get("tpl").FORM,d=this.get("data"),
c=this.get("action"),f=this.get("fileInput"),g="";if(!e.isString(b)){e.log("[uploader-iframeType]:form模板不合法！");return false}if(!e.isObject(d)){e.log("[uploader-iframeType]:data参数不合法！");return false}if(!e.isString(c)){e.log("[uploader-iframeType]:action参数不合法！");return false}d=this.dataToHidden(d);if(d=="")return false;g=e.substitute(b,{action:c,target:a,hiddenInputs:d});a=i(g).append(f);i("body").append(a);this.set("form",a);return a},_create:function(){var a=this._createIframe(),b=this._createForm();
this.fire(h.event.CREATE,{iframe:a,form:b})},_remove:function(){var a=this.get("form");this.get("iframe");a.remove();this.reset("form");this.fire(h.event.REMOVE,{form:a})}},{ATTRS:{tpl:{value:h.tpl},id:{value:"ks-uploader-iframe-"+e.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return h},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/urlsInput",function(e,m,l){function h(a,b){h.superclass.constructor.call(this,b);this.set("wrapper",i(a))}var i=m.all;e.mix(h,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});e.extend(h,l,{render:function(){var a=this.get("wrapper"),b=this.get("name");b=document.getElementsByName(b)[0];if(!e.isObject(a)){e.log("[uploader-urlsInput]:container参数不合法！");return false}if(b){e.log("[uploader-urlsInput]:urls input found");this.set("input",i(b))}else this._create();
return this},add:function(a){if(!e.isString(a)){e.log("[uploader-urlsInput]:add()的url参数不合法！");return false}var b=this.get("urls"),d=this.isExist(a);if(b[0]=="")b=[];if(d){e.log("[uploader-urlsInput]:add()，文件路径已经存在！");return this}b.push(a);this.set("urls",b);this._val();return this},remove:function(a){if(!a)return false;var b=this.get("urls"),d=this.isExist(a),c=RegExp(a);if(!d){e.log("[uploader-urlsInput]:remove()，不存在该文件路径！");return false}b=e.filter(b,function(f){return!c.test(f)});this.set("urls",
b);this._val();return b},parse:function(){var a=this.get("input");if(a){a=i(a).val();var b=this.get("split");a=a.split(b);this.set("urls",a);return a}else{e.log("[uploader-urlsInput]:cannot find urls input.");return[]}},_val:function(){var a=this.get("urls"),b=this.get("input"),d=this.get("split");a=a.join(d);b.val(a);return a},isExist:function(a){var b=false,d=this.get("urls"),c=RegExp(a);if(!d.length)return false;e.each(d,function(f){if(c.test(f))return b=true});return b},_create:function(){var a=
this.get("wrapper"),b=this.get("tpl"),d=this.get("name"),c=this.get("urls");if(!a||a.length<=0){e.log("[uploader-urlsInput]:UrlsInput container not specified!","warn");return false}if(!e.isString(b)||!e.isString("name")){e.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！");return false}b=i(e.substitute(b,{name:d,value:c}));a.append(b);this.set("input",b);e.log("[uploader-urlsInput]:input created.");return b}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:h.TPL},split:{value:",",setter:function(a){this._val();
return a}},input:{value:""},wrapper:{value:""}}});return h},{requires:["node","base"]});
