KISSY.add("gallery/form/1.1/uploader/auth/base",function(d,o,n){function i(b,a){a=d.merge({uploader:b},a);i.superclass.constructor.call(this,a);this._init()}var f=f||d;d.mix(i,{event:{ERROR:"error"}});d.extend(i,n,{_init:function(){var b=this,a=b.get("uploader"),c=a.get("queue");if(a==""){f.log("[uploader-auth]:uploader不可以为空！");return false}b._setSwfButtonExt();c.on("add",function(g){g=g.file;b.testAllowExt(g);b.testMaxSize(g);b.testRepeat(g)});c.on("remove",function(g){g.file.status=="success"&&
b.testMax()});a.on("success",function(){b.testMax()});a.on("error",function(){a.set("isAllowUpload",true)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(b){return this.get("rules")[b]},isUploaderType:function(b){var a=this.get("uploader").get("type");return b==a},testRequire:function(){var b=this.get("uploader").get("urlsInput").get("urls"),a=this.getRule("require"),c=a?a[0]:false;b=b.length>0;if(!c)return true;if(!b){d.log("[uploader-auth]:"+a[1]);this.fire(i.event.ERROR,
{rule:"require",msg:a[1],value:c})}return b},testAllowExt:function(b){function a(k){k=k.split(".");return k[k.length-1]}if(!d.isObject(b))return false;var c=b.name,g=this.getRule("allowExts"),e=[],h;if(!d.isArray(g))return false;e=this._getExts(g[0].ext);h=function(k){var j=false,l;d.each(e,function(m){l=RegExp("^.+."+m+"$");if(l.test(k))return j=true});return j}(c);if(!h){c=a(c);c=d.substitute(g[1],{ext:c});this._stopUpload(b,c);this.fire(i.event.ERROR,{rule:"allowExts",msg:c,value:g[0]})}return h},
testMax:function(){var b=this.get("uploader"),a=b.get("queue").getFiles("success").length,c=this.getRule("max");if(c){var g=b.get("button");if(a=a<c[0]){g.set("disabled",false);b.set("isAllowUpload",true)}else{g.set("disabled",true);b.set("isAllowUpload",false);this.fire(i.event.ERROR,{rule:"max",msg:c[1],value:c[0]})}return a}},testMaxSize:function(b){var a=b.size,c=this.getRule("maxSize");if(c){var g=Number(c[0])*1E3;a=a<=g;if(!a){g=d.substitute(c[1],{maxSize:d.convertByteSize(g),size:b.textSize});
this._stopUpload(b,g);this.fire(i.event.ERROR,{rule:"maxSize",msg:g,value:c[0]})}return a}},testRepeat:function(b){if(!d.isObject(b))return false;var a=this,c=b.name,g=a.getRule("allowRepeat");if(g){var e=g[0],h=g[1],k=a.get("uploader").get("queue").getFiles("success"),j=false;if(e)return false;d.each(k,function(l){if(l.name==c){a._stopUpload(b,h);a.fire(i.event.ERROR,{rule:"allowRepeat",msg:h,value:g[0]});return j=true}});return j}},_setSwfButtonExt:function(){var b=this.get("uploader"),a=this.getRule("allowExts");
b=b.get("button");if(!this.isUploaderType("flash")||!d.isArray(a))return false;b.set("fileFilters",a[0]);return this},_getExts:function(b){if(!d.isString(b))return false;var a=b.split(";"),c=[],g=/^\*\./;d.each(a,function(e){e=e.replace(g,"");c.push(e.toUpperCase())});d.each(c,function(e){a.push(e)});return a},_stopUpload:function(b,a){d.isString(a)||(a="");var c=this.get("uploader").get("queue"),g=c.getFileIndex(b.id);c.fileStatus(g,c.constructor.status.ERROR,{msg:a})}},{ATTRS:{uploader:{value:""},
rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"不支持{ext}格式的文件上传！"],require:[false,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[false,"该文件已经存在！"]}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/base",function(d,o,n,i,f,b,a){function c(e){c.superclass.constructor.call(this,e)}var g=n.all;d.mix(c,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});d.extend(c,
o,{render:function(){var e=this.get("serverConfig"),h=this.getUploadType(this.get("type")),k=h.event,j;if(!h)return false;this.set("urlsInput",this._renderUrlsInput());this._renderQueue();j=this._renderButton();this.get("type")==c.type.FLASH&&d.mix(e,{swfUploader:j.get("swfUploader")});e=new h(e);e.on(k.SUCCESS,this._uploadCompleteHanlder,this);k.PROGRESS&&e.on(k.PROGRESS,this._uploadProgressHandler,this);e.on(k.STOP,this._uploadStopHanlder,this);this.set("uploadType",e);this.fire(c.event.RENDER);
return this},upload:function(e){if(!d.isNumber(e))return false;var h=this.get("uploadType"),k=this.get("type"),j=this.get("queue"),l=j.get("files")[e],m;if(!d.isPlainObject(l)){d.log("[uploader]:队列中不存在id为"+e+"的文件");return false}if(this.get("curUploadIndex")!=""){alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！");return false}m=l.input.id||l.input;if(k=="ajax")m=l.data;if(l.status==="error")return false;this.fire(c.event.START,{index:e,file:l});if(!this.get("isAllowUpload"))return false;this.set("curUploadIndex",
e);j.fileStatus(e,c.status.START);h.upload(m)},cancel:function(e){var h=this.get("uploadType"),k=this.get("queue"),j=c.status,l=k.fileStatus(e);if(d.isNumber(e)&&l!=j.SUCCESS)k.fileStatus(e,j.CANCEL);else{h.stop();this._continueUpload()}return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(e){if(!d.isString(e))e=c.status.WAITING;this.set("uploadFilesStatus",e);this._uploaderStatusFile(e);return this},_uploaderStatusFile:function(e){e=this.get("queue").getIndexs(e);
if(!e.length){this.set("uploadFilesStatus","");this.fire(c.event.UPLOAD_FILES);return false}this.upload(e[0]);return this},isSupportAjax:function(){var e=false;try{if(FormData)e=true}catch(h){e=false}return e},isSupportFlash:function(){var e=d.UA.fpv();return d.isArray(e)&&e.length>0},getUploadType:function(e){var h=this,k=c.type,j;if(e==k.AUTO)e=[k.AJAX,k.IFRAME];if(d.isArray(e)&&e.length>0)d.each(e,function(l){if(j=h._getType(l))return false});else j=h._getType(e);return j},_getType:function(e){var h=
c.type,k=this.isSupportAjax(),j=this.isSupportFlash();switch(e){case h.IFRAME:h=f;break;case h.AJAX:h=k&&b||false;break;case h.FLASH:h=j&&a||false;break;default:d.log("[uploader]:type参数不合法");return false}h&&d.log("[uploader]:使用"+e+"上传方式");this.set("type",e);return h},_renderButton:function(){var e=this.get("button");if(!d.isObject(e)){d.log("[uploader]:button参数不合法！");return false}e.on("change",this._select,this);e.render();return e},_renderQueue:function(){var e=this.get("queue"),h=this.get("urlsInput");
if(!d.isObject(e)){d.log("[uploader]:queue参数不合法");return false}e.set("uploader",this);e.on("remove",function(k){h.remove(k.file.sUrl)});return e},_select:function(e){var h=this,k=h.get("autoUpload"),j=h.get("queue"),l=h.get("curUploadIndex"),m=e.files;d.each(m,function(p){if(!p.size)p.size=0;if(!p.name)p.name=p.fileName||"";p.input=e.input||p});h.fire(c.event.SELECT,{files:m});if(!h.get("isAllowUpload"))return false;j.add(m,function(){l==""&&k&&h.uploadFiles()})},_renderUrlsInput:function(){var e=
this.get("button").get("target"),h=this.get("urlsInputName");e=new i(e,{name:h});e.render();return e},_uploadCompleteHanlder:function(e){e=e.result;var h,k=c.event,j=this.get("queue"),l=this.get("curUploadIndex");if(!d.isObject(e))return false;j.updateFile(l,{result:e});h=Number(e.status);if(h===1){j.fileStatus(l,c.status.SUCCESS);this._success(e.data);this.fire(k.SUCCESS,{index:l,file:j.getFile(l),result:e})}else{j.fileStatus(l,c.status.ERROR,{msg:e.msg||e.message||"",result:e});this.fire(k.ERROR,
{status:h,result:e})}this.set("curUploadIndex","");this.fire(k.COMPLETE,{index:l,file:j.getFile(l),result:e});this._continueUpload()},_uploadStopHanlder:function(){var e=this.get("queue"),h=this.get("curUploadIndex");e.fileStatus(h,c.status.CANCEL);this.set("curUploadIndex","");this.fire(c.event.CANCEL,{index:h})},_continueUpload:function(){var e=this.get("uploadFilesStatus");e!=""&&this._uploaderStatusFile(e)},_uploadProgressHandler:function(e){var h=this.get("queue"),k=this.get("curUploadIndex"),
j=h.getFile(k);d.mix(e,{file:j});h.fileStatus(k,c.status.PROGRESS,e);this.fire(c.event.PROGRESS,e)},_success:function(e){if(!d.isObject(e))return false;e=e.url;var h=this.get("urlsInput"),k=this.get("curUploadIndex"),j=this.get("queue");if(!d.isString(e)||!d.isObject(h))return false;j.updateFile(k,{sUrl:e});h.add(e)},restore:function(e){var h=this.get("queue"),k=this.get("urlsInput");e||(e=this._getRestoreData());if(!e.length)return false;d.each(e,function(j){if(!j.sUrl&&j.result)j.sUrl=j.result.data.url;
var l=h.add(j),m=l.id,p=h.getFileIndex(m);k.add(j.sUrl);h.fileStatus(p,"success",{index:p,id:m,file:l})})},_getRestoreData:function(){var e=this.get("restoreHook");e=g(e);if(!e.length)return[];return d.JSON.parse(e.html())}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:c.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:true},autoUpload:{value:true},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""},
restoreHook:{value:""}}});d.convertByteSize=function(e){var h=-1;do{e/=1024;h++}while(e>99);return Math.max(e,0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][h]};return c},{requires:["base","node","./urlsInput","./type/iframe","./type/ajax","./type/flash","flash"]});
KISSY.add("gallery/form/1.1/uploader/button/base",function(d,o,n){function i(b,a){a=d.merge({target:f(b)},a);i.superclass.constructor.call(this,a)}var f=o.all;d.mix(i,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(b){return b.replace(/.*(\/|\\)/,"")}});d.extend(i,n,{render:function(){var b=this.get("target");if(this.fire(i.event.beforeRender)===false){d.log("[Uploader-Button] button render was prevented.");
return false}else{if(b==null){d.log("[Uploader-Button] Cannot find target!");return false}this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(i.event.afterRender);return this}},show:function(){this.get("target").show();this.fire(i.event.afterShow);return i},hide:function(){this.get("target").hide();this.fire(i.event.afterHide);return i},reset:function(){var b=this.get("inputContainer");f(b).remove();this.set("inputContainer","");this.set("fileInput",
"");this._createInput();return this},_createInput:function(){var b=this.get("target"),a=this.get("name"),c=this.get("tpl");if(!d.isString(a)||!d.isString(c)){d.log("[Uploader-Button] No name or tpl specified.");return false}a=d.substitute(c,{name:a});a=f(a);f(a).appendTo(b);b=f(a).children("input");f(b).on("change",this._changeHandler,this);this.set("fileInput",b);this.set("inputContainer",a);return a},_changeHandler:function(b){var a=this.get("fileInput"),c=f(a).val();b=b.target.files;var g=[];if(c==
""){d.log("[Uploader-Button] No file selected.");return false}b?d.each(b,function(e){d.isObject(e)&&g.push({name:e.name,type:e.type,size:e.size,data:e})}):g.push({name:i.getFileName(c)});this.fire(i.event.CHANGE,{files:g,input:a.getDOMNode()});this.reset()},_setDisabled:function(b){var a=this.get("cls").disabled,c=this.get("target"),g=this.get("fileInput");if(!c.length||!d.isBoolean(b))return false;if(b){c.addClass(a);f(g).hide()}else{c.removeClass(a);f(g).show()}return b},_setMultiple:function(b){var a=
this.get("fileInput");if(!a.length)return false;b&&a.attr("multiple","multiple")||a.removeAttr("multiple");return b}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(b){this.get("fileInput")&&f(this.get("fileInput")).attr("name",b);return b}},disabled:{value:false,setter:function(b){this._setDisabled(b);return b}},
multiple:{value:true,setter:function(b){this._setMultiple(b);return b}},cls:{value:{disabled:"uploader-button-disabled"}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/button/swfButton",function(d,o,n,i){function f(a,c){c=d.merge({target:b(a)},c);f.superclass.constructor.call(this,c)}var b=o.all;d.mix(f,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});d.extend(f,n,{render:function(){var a=this,c=a.get("target"),g,e=a.get("multiple"),h=a.get("fileFilters");c.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
g=a._initSwfUploader();g.on("contentReady",function(){g.browse(e,h);a._bindBtnEvent();g.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(f.event.RENDER)},a)},_createSwfWrapper:function(){var a=this.get("target"),c=this.get("tpl"),g=this.get("swfWrapperId")!=""&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+d.guid();c=d.substitute(c,{id:g});this.set("swfWrapperId",g);return b(c).appendTo(a)},_initSwfUploader:function(){var a=this.get("flash"),c=this.get("swfWrapperId"),
g;try{g=new i(c,a);this.set("swfUploader",g)}catch(e){}return g},_bindBtnEvent:function(){var a=this,c=f.event,g=a.get("swfUploader");if(!g)return false;d.each(c,function(e){g.on(e,function(){a.fire(e)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),c=this.get("target");d.mix(a.attrs,{width:c.width(),height:c.height()});this.set("flash",a)},_changeHandler:function(a){this.fire(f.event.CHANGE,{files:a.fileList})},_setDisabled:function(a){var c=this.get("swfUploader"),g=this.get("cls").disabled,
e=this.get("target"),h=this.get("swfWrapper");if(!c||!d.isBoolean(a))return false;if(a){e.addClass(g);h.hide()}else{e.removeClass(g);h.show()}return a}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:true,setter:function(a){var c=this.get("swfUploader");c&&c.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var c=this.get("swfUploader");c&&
d.isArray(a)&&c.filter(a);return a}},disabled:{value:false,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.1/uploader/plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:true,btn:true}},swfUploader:{value:""}}});return f},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.1/uploader/index",function(d,o,n,i,f,b,a,c){function g(j,l,m){m=d.mix(d.form.parseConfig(j),m);g.superclass.constructor.call(this,m);this.set("buttonTarget",j);this.set("queueTarget",l);this.set("uploaderConfig",m);this._init()}var e=n.all,h={CONFIG:"data-config",BUTTON_CONFIG:"data-button-config",THEME_CONFIG:"data-theme-config",AUTH:"data-auth"},k=["default","imageUploader"];d.namespace("form");d.form.parseConfig=function(j,l){var m={},p,r=l||h.CONFIG;p=e(j).attr(r);if(!d.isString(p))return{};
try{m=d.JSON.parse(p)}catch(s){d.log("[uploaderRender]:请检查"+j+"上"+r+"属性内的json格式是否符合规范！")}return m};d.extend(g,o,{_init:function(){var j=this,l=j._initButton(),m=j._initQueue(),p=j._initUploader(l,m),r=j._auth(),s={uploader:p,button:l,queue:m,auth:r},t=j.get("theme");j.set("button",l);t==""?j.fire("init",s):j._initThemes(function(q){q.set("uploader",p);q.set("button",l);q.set("queue",m);q.set("auth",r);q._UploaderRender(function(){p.restore();q.afterUploaderRender(p);j.fire("init",s)})})},_initUploader:function(j,
l){var m=this.get("uploaderConfig"),p=this.get("name");d.mix(m.serverConfig,{fileDataName:p});d.mix(m,{button:j,queue:l});m=new i(m);m.render();this.set("uploader",m);return m},_initButton:function(){var j=this.get("buttonTarget"),l=d.form.parseConfig(j,h.BUTTON_CONFIG),m=this.get("name"),p=this.get("type");l=d.merge({name:m},l);return p!="flash"&&new f(j,l)||new b(j)},_initQueue:function(){return new c},_initThemes:function(j){var l=this,m=l.get("theme"),p=l.get("buttonTarget"),r=d.form.parseConfig(p,
h.THEME_CONFIG);m=l._getThemeName(m);d.use(m,function(s,t){var q=l.get("queueTarget");s.mix(r,{queueTarget:q});q=new t(r);j&&j.call(l,q)})},_getThemeName:function(j){var l=j;d.each(k,function(m){if(m==j)l="gallery/form/1.1/uploader/themes/"+j});l+="/index";return l},_auth:function(){var j=this.get("buttonTarget"),l=this.get("uploader"),m="";if(e(j).attr(h.AUTH)){j=d.form.parseConfig(j,h.AUTH);m=new a(l,{rules:j});l.set("auth",m)}return m}},{ATTRS:{theme:{value:"gallery/form/1.1/uploader/themes/default"},
buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""}}});return g},{requires:["base","node","./base","./button/base","./button/swfButton","./auth/base","./queue"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/ajbridge",function(d,o){function n(c,g,e){c=c.replace(i,"");g=o._normalize(g||{});var h=this;c=i+c;var k=function(j){if(j.status<1)h.fire("failed",{data:j});else{d.mix(h,j);if(!j.dynamic||!g.src)h.activate()}};g.id=g.id||d.guid(f);n.instances[g.id]=h;if(g.src){g.params.allowscriptaccess="always";g.params.flashvars=d.merge(g.params.flashvars,{jsEntry:a,swfID:g.id})}if(e)h.__args=[c,g,k];else d.later(o.add,b,false,o,[c,g,k])}var i="#",f="ks-ajb-",
b=100,a="KISSY.AJBridge.eventHandler";d.app(n,{version:"1.0.15",instances:{},eventHandler:function(c,g){var e=n.instances[c];e&&e.__eventHandler(c,g)},augment:function(c,g){if(d.isString(g))g=[g];d.isArray(g)&&d.each(g,function(e){c.prototype[e]=function(){try{return this.callSWF(e,d.makeArray(arguments))}catch(h){this.fire("error",{message:h})}}})}});d.augment(n,d.EventTarget,{init:function(){if(this.__args){o.add.apply(o,this.__args);this.__args=null;delete this.__args}},__eventHandler:function(c,
g){var e=g.type;g.id=c;switch(e){case "log":d.log(g.message);break;default:this.fire(e,g)}},callSWF:function(c,g){g=g||[];try{if(this.swf[c])return this.swf[c].apply(this.swf,g)}catch(e){var h="";if(g.length!==0)h="'"+g.join("','")+"'";return(new Function("self","return self.swf."+c+"("+h+");"))(this)}}});n.augment(n,["activate","getReady","getCoreVersion"]);return window.AJBridge=d.AJBridge=n},{requires:["flash"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/uploader",function(d,o,n){function i(f,b){b=b||{};var a={};d.each(["ds","dsp","btn","hand"],function(c){if(c in b)a[c]=b[c]});b.params=b.params||{};b.params.flashvars=d.merge(b.params.flashvars,a);i.superclass.constructor.call(this,f,b)}d.extend(i,n);n.augment(i,["setFileFilters","filter","setAllowMultipleFiles","multifile","browse","upload","uploadAll","cancel","getFile","removeFile","lock","unlock","setBtnMode","useHand","clear"]);i.version=
"1.0.1";n.Uploader=i;return n.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add("gallery/form/1.1/uploader/plugins/filedrop/filedrop",function(d,o,n){var i=o.all,f=d.UA,b=function(c){b.superclass.constructor.call(this,c);this.set("mode",a())},a=function(){if(f.webkit>=7||f.firefox>=3.6)return"supportDrop";if(f.ie)return"notSupportDropIe";if(f.webkit<7||f.firefox<3.6)return"notSupportDrop"};d.mix(b,{event:{AFTER_DROP:"afterdrop"}});d.extend(b,n,{render:function(){var c=this.get("mode"),g=this.get("uploader");if(c!="supportDrop"){d.log("该浏览器不支持拖拽上传！");return false}if(!g){d.log("缺少Uploader的实例！");
return false}c=this._createDropArea();c.length&&c.on("click",this._clickHandler,this);console.log("after randeer");this.fire("afterRender",{buttonTarget:this.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var c=this,g=i(c.get("target")),e=c.get("mode");e=d.substitute(c.get("tpl")[e],{name:c.get("name")});e=i(e);var h=e.all(".J_ButtonWrap");e.appendTo(g);e.on("dragover",function(k){k.stopPropagation();
k.preventDefault()});e.on("drop",function(k){k.stopPropagation();k.preventDefault();c._dropHandler(k)});c.set("dropContainer",e);c.set("buttonWrap",h);c._setStyle();return e},_setStyle:function(){var c=this.get("dropContainer");if(!c.length)return false;c.parent().css("position","relative");c.css({position:"absolute",top:"0",left:"0",width:"100%",height:"100%",zIndex:"1000"})},_clickHandler:function(c){i(c.target);this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(c){var g=
b.event;c=c.originalEvent.dataTransfer.files;var e=[],h=this.get("uploader");if(!c.length||h=="")return false;d.each(c,function(k){d.isObject(k)&&e.push({name:k.name,type:k.type,size:k.size,data:k})});this.fire(g.AFTER_DROP,{files:e});h._select({files:e})},_setDisabled:function(){}},{ATTRS:{target:{value:""},uploader:{value:""},dropContainer:{value:""},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>直接拖拽图片到这里，</p><p class="J_ButtonWrap">或者</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐使用chrome浏览器或firefox浏览器</p></div>',
notSupportDrop:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐升级您的浏览器</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:false,setter:function(c){this._setDisabled(c);return c}},cls:{disabled:"drop-area-disabled"}}});return b},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/preview/preview",function(d,o){function n(e,h){if(!e)return false;if(a!="filter")e.src=h||g;else{e.src=g;if(h){h=h.replace(/[)'"%]/g,function(k){return escape(escape(k))});e.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+h+"')";e.zoom=1}}return true}function i(e){this.config=d.mix({maxWidth:40,maxHeight:40},e);d.log(b+"Preview initialized. The preview mode is "+a)}var f=document,b="[Plugin: Preview] ",a=function(){var e=
"";if(typeof window.FileReader==="undefined")switch(d.UA.shell){case "firefox":e="domfile";break;case "ie":switch(d.UA.ie){case 6:e="simple";break;default:e="filter"}}else e="html5";return e}(),c={check:"check",success:"success",showed:"showed",error:"error"},g=d.UA.ie<8?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";d.augment(i,d.EventTarget,{preview:function(e,h){e=o.get(e);h=o.get(h);var k=this,j=function(){k.fire(c.getData,
{data:k.data,mode:a});if(h){n(h,k.data);k.fire(c.showed,{img:h})}};k.data=undefined;if(e){d.log(b+"One file selected. Getting data...");switch(a){case "domfile":k.data=e.files[0].getAsDataURL();break;case "filter":e.select();try{k.data=f.selection.createRange().text}catch(l){d.log(b+"Get image data error, the error is: ");d.log(l,"dir")}finally{f.selection.empty()}if(!k.data)k.data=e.value;break;case "html5":var m=new FileReader;m.onload=function(p){k.data=p.target.result;j()};m.onerror=function(){d.log(b+
"File Reader Error. Your browser may not fully support html5 file api","warning");k.fire(c.error)};e.files&&m.readAsDataURL(e.files[0]);break;default:k.data=e.value}if(k.data)j();else if(a!="html5"){d.log(b+"Retrive Data error.");n(h);k.fire(c.error)}}else d.log(b+"File Input Element does not exists.");return k.data}});return i},{requires:["dom","event"]});
KISSY.add("gallery/form/1.1/uploader/plugins/progressBar/progressBar",function(d,o,n){function i(b,a){a=d.merge({wrapper:f(b)},a);i.superclass.constructor.call(this,a)}var f=o.all;d.mix(i,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});d.extend(i,n,{render:function(){var b=this.get("wrapper"),a=this.get("width");if(!b.length)return false;
b.addClass(i.cls.PROGRESS_BAR).width(a);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(i.event.RENDER)},show:function(){var b=this;b.get("wrapper").fadeIn(b.get("duration"),function(){b.set("visible",true);b.fire(i.event.SHOW,{visible:true})})},hide:function(){var b=this;b.get("wrapper").fadeOut(b.get("duration"),function(){b.set("visible",false);b.fire(i.event.HIDE,{visible:false})})},_create:function(){var b=this.get("wrapper"),a=this.get("value"),c=this.get("tpl");
a=d.substitute(c,{value:a});b.html("");return f(a).appendTo(b)},_addAttr:function(){var b=this.get("wrapper"),a=this.get("value");b.attr("role","progressbar");b.attr("aria-valuemin",0);b.attr("aria-valuemax",100);b.attr("aria-valuenow",a);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(b){var a=this,c=a.get("wrapper"),g=a.get("bar"),e=a.get("speed"),h;if(b>100)b=100;if(b<0)b=0;h=c.width()*(b/100);g.animate({width:h+"px"},e,"none",function(){c.attr("aria-valuenow",
b);g.attr("data-value",b);a.fire(i.event.CHANGE,{value:b,width:h})});return b}},visible:{value:true},duration:{value:0.3},tpl:{value:i.tpl.DEFAULT},speed:{value:0.2}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/queue",function(d,o,n){function i(f){i.superclass.constructor.call(this,f)}d.mix(i,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",
SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});d.extend(i,n,{add:function(f,b){var a=this,c={};if(f.length>0){c=[];d.each(f,function(g){c.push(a._addFile(g))})}else c=a._addFile(f);b&&b.call(a);return c},_addFile:function(f,b){if(!d.isObject(f)){d.log("[uploader-queue]:_addFile()参数file不合法！");return false}var a=this._setAddFileData(f),c=this.getFileIndex(a.id),g=this.get("fnAdd");if(d.isFunction(g))a=
g(c,a);this.fire(i.event.ADD,{index:c,file:a,uploader:this.get("uploader")});b&&b.call(this,c,a);return a},remove:function(f,b){var a=this.get("files"),c;if(d.isString(f))f=this.getFileIndex(f);c=a[f];if(!d.isObject(c)){d.log("[uploader-queue]:remove()不存在index为"+f+"的文件数据");return false}a=d.filter(a,function(g,e){return e!==f});this.set("files",a);this.fire(i.event.REMOVE,{index:f,file:c});b&&b.call(this,f,c);return c},clear:function(){function f(){a=b.get("files");if(!a.length){b.fire(i.event.CLEAR);
return false}b.remove(0,function(){f()})}var b=this,a;f()},fileStatus:function(f,b,a){if(!d.isNumber(f)||!d.isString(b))return false;var c=this.getFile(f),g=this.get("theme"),e;if(!c||!g)return false;if(c.status==b)return this;this.updateFile(f,{status:b});e="_"+b+"Handler";if(d.isFunction(g[e])){a=d.merge({uploader:this.get("uploader"),index:f,file:c,id:c.id},a);g[e].call(g,a)}this.fire(i.event.FILE_STATUS,{index:f,status:b,args:a,file:c});return this},getFile:function(f){if(!d.isNumber(f))return false;
f=this.get("files")[f];if(!d.isPlainObject(f)){d.log("getFile():文件数据为空！");f={}}return f},getFileIndex:function(f){var b=this.get("files"),a=-1;d.each(b,function(c,g){if(c.id==f){a=g;return true}});return a},updateFile:function(f,b){if(!d.isNumber(f))return false;if(!d.isObject(b)){d.log("[uploader-queue]:updateFile()的data参数有误！");return false}var a=this.get("files"),c=this.getFile(f);if(!c)return false;d.mix(c,b);a[f]=c;this.set("files",a);this.fire(i.event.UPDATE_FILE,{index:f,file:c});return c},
getIndexs:function(f){var b=this.get("files"),a,c=[];if(!b.length)return c;d.each(b,function(g,e){if(d.isObject(g)){a=g.status;a==f&&c.push(e)}});return c},getFiles:function(f){var b=this.get("files"),a=[];if(!b.length)return[];d.each(b,function(c){c&&c.status==f&&a.push(c)});return a},_setAddFileData:function(f){var b=this.get("files");if(!d.isObject(f)){d.log("[uploader-queue]:_updateFileData()参数file不合法！");return false}if(!f.id)f.id=d.guid(i.FILE_ID_PREFIX);if(f.size)f.textSize=d.convertByteSize(f.size);
f.status="";b.push(f);return f}},{ATTRS:{fnAdd:{value:""},files:{value:[]},uploader:{value:""},theme:{value:""}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/theme",function(d,o,n){function i(a){i.superclass.constructor.call(this,a);this._LoaderCss()}var f=o.all,b={BUTTON:"-button",QUEUE:"-queue"};d.extend(i,n,{afterUploaderRender:function(){},_getStatusWrapper:function(a){return a.children(".J_FileStatus")},displayFile:function(a,c,g){var e=this,h=e.get("duration");if(!c||!c.length)return false;c[a&&"fadeIn"||"fadeOut"](h,function(){g&&g.call(e)})},_waitingHandler:function(){},_startHandler:function(){},_progressHandler:function(){},
_successHandler:function(){},_errorHandler:function(){},_restoreHandler:function(){},_UploaderRender:function(a){this._initQueue();this._addThemeCssName();this._loadPlugins(a)},_addThemeCssName:function(){var a=this.get("name"),c=this.get("queue"),g=f(this.get("queueTarget")),e=this.get("button");if(a==""||!c||!g.length)return false;g.addClass(a+b.QUEUE);if(!e)return false;e.get("target").addClass(a+b.BUTTON)},_initQueue:function(){var a=this,c=a.get("queue");c.set("fnAdd",function(g,e){return a._addCallback(g,
e)});c.set("theme",a);c.on("add",a._addFileHandler,a);c.on("remove",a._removeFileHandler,a);c.on("statusChange",function(g){a._setStatusVisibility(g)});return c},_LoaderCss:function(){var a=this.get("isUseCss"),c=this.get("cssUrl");if(!a)return false;d.use(c,function(){d.log(c+"加载成功！")})},_addCallback:function(a,c){var g=this.get("queue"),e=this._appendFileDom(c);g.updateFile(a,{target:e,statusWrapper:this._getStatusWrapper(e)});g.fileStatus(a,"waiting");this.displayFile(true,e);this._bindTriggerEvent(a,
c);return g.getFile(a)},_removeFileHandler:function(a){this.displayFile(false,a.file.target)},_bindTriggerEvent:function(a,c){var g=this.get("queue"),e=this.get("uploader"),h=c.id,k=f(".J_Upload_"+h),j=f(".J_Cancel_"+h),l=f(".J_Del_"+h);k.on("click",function(m){m.preventDefault();if(!d.isObject(e))return false;e.upload(a)});j.on("click",function(m){m.preventDefault();e.cancel(a)});l.on("click",function(m){m.preventDefault();g.remove(h)})},_setStatusVisibility:function(a){var c=a.file.statusWrapper;
a=a.file.status;if(!c||!c.length){d.log("状态容器层不存在！");return false}c.children(".status").hide();c.children("."+a+"-status").show()},_appendFileDom:function(a){var c=this.get("fileTpl"),g=f(this.get("queueTarget"));if(!g.length)return false;c=d.substitute(c,a);return f(c).hide().appendTo(g).data("data-file",a)},_loadPlugins:function(a){var c=this,g=c.get("plugins"),e=c.get("oPlugin"),h=[];if(!g.length)return false;d.each(g,function(k){h.push("gallery/form/1.1/uploader/plugins/"+k+"/"+k)});d.use(h.join(","),
function(){d.each(arguments,function(k,j){if(j>=1)e[g[j-1]]=k});c.set("oPlugin",e);a&&a.call(c,e)})}},{ATTRS:{name:{value:""},isUseCss:{value:true},cssUrl:{value:""},fileTpl:{value:""},plugins:{value:[]},oPlugin:{value:{}},queueTarget:{value:""},duration:{value:0.3},queue:{value:""},uploader:{value:""},button:{value:""},auth:{value:""}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/ajax",function(d,o,n){function i(f){i.superclass.constructor.call(this,f)}d.mix(i,{event:d.merge(n.event,{PROGRESS:"progress"})});d.extend(i,n,{upload:function(f){if(!f){d.log("[uploader-AjaxType]:upload()，fileData参数有误！");return false}this._setFormData();this._addFileData(f);this.send();return this},stop:function(){var f=this.get("xhr");if(!d.isObject(f)){d.log("[uploader-AjaxType]:stop()，io值错误！");return false}f.abort();this.fire(i.event.STOP);return this},
send:function(){var f=this,b=f.get("action"),a=f.get("formData"),c=new XMLHttpRequest;c.upload.addEventListener("progress",function(g){f.fire(i.event.PROGRESS,{loaded:g.loaded,total:g.total})});c.onload=function(){var g={};try{g=d.JSON.parse(c.responseText)}catch(e){d.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}f.fire(i.event.SUCCESS,{result:g})};c.open("POST",b,true);c.send(a);f._setFormData();f.set("xhr",c);return f},_setFormData:function(){try{this.set("formData",new FormData);this._processData()}catch(f){d.log("[uploader-AjaxType]:something error when reset FormData.");
d.log(f,"dir")}},_processData:function(){var f=this.get("data"),b=this.get("formData");d.each(f,function(a,c){b.append(c,a)});this.set("formData",b)},_addFileData:function(f){if(!d.isObject(f)){d.log("[uploader-AjaxType]:_addFileData()，file参数有误！");return false}var b=this.get("formData"),a=this.get("fileDataName");b.append(a,f);this.set("formData",b)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:false,cache:false,dataType:"json",contentType:false}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return i},{requires:["node","./base"]});KISSY.add("gallery/form/1.1/uploader/type/base",function(d,o,n){function i(f){i.superclass.constructor.call(this,f)}d.mix(i,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});d.extend(i,n,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/flash",function(d,o,n){function i(f){i.superclass.constructor.call(this,f);this._init()}d.mix(i,{event:d.merge(n.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});d.extend(i,n,{_init:function(){var f=this,b=f.get("swfUploader");if(!b){d.log("[uploader-FlashType]:swfUploader对象为空！");return false}b.on("contentReady",function(){f.fire(i.event.SWF_READY)},f);b.on("uploadStart",f._uploadStartHandler,f);b.on("uploadProgress",f._uploadProgressHandler,f);b.on("uploadCompleteData",
f._uploadCompleteDataHandler,f);b.on("uploadError",f._uploadErrorHandler,f)},upload:function(f){var b=this.get("swfUploader"),a=this.get("action"),c=this.get("data");this.set("uploadingId",f);b.upload(f,a,"POST",c);return this},stop:function(){var f=this.get("swfUploader"),b=this.get("uploadingId");if(b!=""){f.cancel(b);this.fire(i.event.STOP,{id:b})}return this},_uploadStartHandler:function(f){this.fire(i.event.START,{file:f.file})},_uploadProgressHandler:function(f){d.mix(f,{loaded:f.bytesLoaded,
total:f.bytesTotal});this.fire(i.event.PROGRESS,{loaded:f.loaded,total:f.total})},_uploadCompleteDataHandler:function(f){var b;try{b=JSON.parse(f.data)}catch(a){d.log("[uploader-FlashType]:json数据格式不合法！");this.fire(i.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(i.event.SUCCESS,{result:b})},_uploadErrorHandler:function(f){this.set("uploadingId","");this.fire(i.event.ERROR,{msg:f.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return i},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/type/iframe",function(d,o,n){function i(b){i.superclass.constructor.call(this,b)}var f=o.all;d.mix(i,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:d.mix(n.event,{CREATE:"create",REMOVE:"remove"})});
d.extend(i,n,{upload:function(b){b=f(b);if(!b.length)return false;this.fire(i.event.START,{input:b});this.set("fileInput",b);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(i.event.STOP);this.fire(i.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(b){if(!d.isObject(b)||d.isEmptyObject(b)){d.log("[uploader-iframeType]:data参数不是对象或者为空！");return false}var a="",c=this.get("tpl").HIDDEN_INPUT;
if(!d.isString(c))return false;for(var g in b)a+=d.substitute(c,{name:g,value:b[g]});return a},_createIframe:function(){var b=this.get("id"),a=this.get("tpl"),c=a.IFRAME,g=this.get("iframe");if(!d.isEmptyObject(g))return g;if(!d.isString(c)){d.log("[uploader-iframeType]:iframe的模板不合法！");return false}if(!d.isString(b)){d.log("[uploader-iframeType]:id必须存在且为字符串类型！");return false}b=d.substitute(a.IFRAME,{id:b});b=f(b);b.on("load",this._iframeLoadHandler,this);f("body").append(b);this.set("iframe",b);return b},
_iframeLoadHandler:function(b){var a=b.target;b=i.event.ERROR;a=a.contentDocument||window.frames[a.id].document;if(!a||!a.body){this.fire(b,{msg:"服务器端返回数据有问题！"});return false}a=a.body.innerHTML;d.log("[uploader-iframeType]:服务器端输出:"+a);if(a=="")return false;try{a=JSON.parse(a)}catch(c){d.log("[uploader-iframeType]:json数据格式不合法！");this.fire(b,{msg:"数据："+a+"不是合法的json数据"})}this.fire(i.event.SUCCESS,{result:a});this._remove()},_createForm:function(){var b=this.get("id"),a=this.get("tpl").FORM,c=this.get("data"),
g=this.get("action"),e=this.get("fileInput"),h="";if(!d.isString(a)){d.log("[uploader-iframeType]:form模板不合法！");return false}if(!d.isObject(c)){d.log("[uploader-iframeType]:data参数不合法！");return false}if(!d.isString(g)){d.log("[uploader-iframeType]:action参数不合法！");return false}c=this.dataToHidden(c);if(c=="")return false;h=d.substitute(a,{action:g,target:b,hiddenInputs:c});b=f(h).append(e);f("body").append(b);this.set("form",b);return b},_create:function(){var b=this._createIframe(),a=this._createForm();
this.fire(i.event.CREATE,{iframe:b,form:a})},_remove:function(){var b=this.get("form");this.get("iframe");b.remove();this.reset("form");this.fire(i.event.REMOVE,{form:b})}},{ATTRS:{tpl:{value:i.tpl},id:{value:"ks-uploader-iframe-"+d.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return i},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/urlsInput",function(d,o,n){function i(b,a){i.superclass.constructor.call(this,a);this.set("wrapper",f(b))}var f=o.all;d.mix(i,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});d.extend(i,n,{render:function(){var b=this.get("wrapper"),a=this.get("name");a=document.getElementsByName(a)[0];if(!d.isObject(b)){d.log("[uploader-urlsInput]:container参数不合法！");return false}if(a){d.log("[uploader-urlsInput]:urls input found");this.set("input",f(a))}else this._create();
return this},add:function(b){if(!d.isString(b)){d.log("[uploader-urlsInput]:add()的url参数不合法！");return false}var a=this.get("urls"),c=this.isExist(b);if(a[0]=="")a=[];if(c){d.log("[uploader-urlsInput]:add()，文件路径已经存在！");return this}a.push(b);this.set("urls",a);this._val();return this},remove:function(b){if(!b)return false;var a=this.get("urls"),c=this.isExist(b),g=RegExp(b);if(!c){d.log("[uploader-urlsInput]:remove()，不存在该文件路径！");return false}a=d.filter(a,function(e){return!g.test(e)});this.set("urls",
a);this._val();return a},parse:function(){var b=this.get("input");if(b){b=f(b).val();var a=this.get("split");b=b.split(a);this.set("urls",b);return b}else{d.log("[uploader-urlsInput]:cannot find urls input.");return[]}},_val:function(){var b=this.get("urls"),a=this.get("input"),c=this.get("split");b=b.join(c);a.val(b);return b},isExist:function(b){var a=false,c=this.get("urls"),g=RegExp(b);if(!c.length)return false;d.each(c,function(e){if(g.test(e))return a=true});return a},_create:function(){var b=
this.get("wrapper"),a=this.get("tpl"),c=this.get("name"),g=this.get("urls");if(!b||b.length<=0){d.log("[uploader-urlsInput]:UrlsInput container not specified!","warn");return false}if(!d.isString(a)||!d.isString("name")){d.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！");return false}a=f(d.substitute(a,{name:c,value:g}));b.append(a);this.set("input",a);d.log("[uploader-urlsInput]:input created.");return a}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:i.TPL},split:{value:",",setter:function(b){this._val();
return b}},input:{value:""},wrapper:{value:""}}});return i},{requires:["node","base"]});
