KISSY.ready(function(c){var g=c.get("#tpl").innerHTML,j=[];c.all("#container");for(var h=0;15>h;++h)j.push(c.all(g));c.io.setupConfig({xdr:{subDomain:{proxy:"/crossdomain.htm"}}});document.domain="taobao.com";c.use("waterfallx, template",function(c,k,h){var f=0;wf=new k.Loader({colWidth:290,diff:200,container:"#container",load:function(a,e){c.io.get("http://zhoubian.taobao.com/GetAddressAuctionNew.htm?t=1354520492506233&p=1&cidLevels=50020808,1|50020611,1|50020485,1|50020579,1|50025705,1|21,1|50020332,1|50020857,1|50008164,1|27,1|50016348,1|50016349,1|50018004,1|14,1|50012082,1|11,1|1101,1|50023904,1|50011972,1|50018222,1|50007218,1|1512,1|&level=&cidLevels=50020808,1|50020611,1|50020485,1|50020579,1|50025705,1|21,1|50020332,1|50020857,1|50008164,1|27,1|50016348,1|50016349,1|50018004,1|14,1|50012082,1|11,1|1101,1|50023904,1|50011972,1|50018222,1|50007218,1|1512,1|&addressHashKey=0&parentHashKey=1770651072&orderType=&buyType=1&isShowAllCidOrTags=false",
{nextPage:f},function(a){var d=[];c.each(a.groupToAucList[0].aucInfoList,function(a){a.picUrl="http://img03.taobaocdn.com/imgextra/"+a.picUrl;d.push(c.all(h(g).render(a)))});wf[f%2?"addItems":"preAddItems"](d);wf.__loading=0;6<++f&&e();console.log("nextPage",f)},"json")}})})});KISSY.add("gallery/waterfallx/1.0/index",function(c,g){return g},{requires:["./waterfallx"]});
KISSY.add("waterfallx/base",function(c){function g(a,e,b,d){var m={},g=0,f;a.length>g?f=setTimeout(function(){var c=+new Date;do{var m=a[g++];e.call(b,m)}while(a.length>g&&50>+new Date-c);a.length>g?f=setTimeout(arguments.callee,25):d&&d.call(b,a)},25):d&&c.later(d,0,!1,b,a);m.stop=function(){clearTimeout(f)};return m}function j(a,e,b){if(a){var d=null,c=null,g="append",a=k(a),f=this._colItems,h=f.length,j=Number.MAX_VALUE,i=0;b?"preadd"==b?(c=this._preItems,g="prepend",c.push(a),a.attr("data-waterfall-index",
-c.length)):d=this.config.addjustEffect:(c=this._items,d=this.config.effect,a.attr("data-waterfall-index",c.length)&&c.push(a));for(b=0;b<h;b++)c=f[b].outerHeight(!0),c<j&&(j=c,i=b);d&&d.effect?(f[i][g](a),a.hide(),e&&e(),a[d.effect](d.duration,0,d.easing)):(f[i].append(a),e&&e());return a}e&&e()}function h(){var a=this._containerRegion;a&&this.container.width()===a||(this._calculate()===this._colItems.length?this._adjustMargin():this.adjust())}function l(a){a.container&&(this.config=c.merge({align:"center",
minColCount:1,effect:{effect:"fadeIn",duration:1}},a),this.container=k(a.container),this._colItems=[],this._preItems=[],this._items=[],this._init())}var k=c.Node.all,i=c.DOM,f=c.Env.host||window;c.augment(l,c.Event.Target,{_init:function(){i.addStyleSheet(".ks-waterfall-col{ display: inline-block; vertical-align:top;*display: inline; *zoom: 1}","ks-waterfallx");this._createColumnItems();this.addItems(this.container.all(".ks-waterfall"));this.__onResize=c.buffer(h,50,this);k(f).on("resize",this.__onResize)},
_calculate:function(){var a=this.config,e=this.container.width();a.colWidth||(a.colWidth=e);a=Math.max(parseInt(e/a.colWidth),a.minColCount);this._containerRegion=e;return a},_createColumnItems:function(){for(var a=this.config,e=this._colItems,b=this._calculate(),d=e.length-1;-1<d;--d)e[d].remove();e.length=b;for(d=0;d<b;++d)e[d]=k("<div>").addClass("ks-waterfall-col").appendTo(this.container),e[d].width(a.colWidth);this._adjustMargin()},_adjustMargin:function(){var a=this.config,e=a.align,b=this._colItems,
d=b.length,a="left"===e?0:Math.max(this.container.width()-d*a.colWidth,0),a=a/d;"center"===e&&(a/=2);b[0].css("marginLeft",a+"px")},_deleteItem:function(a){a=+a.attr("data-waterfall-index");0>a?this._preItems[-(a+1)]=null:this._items[a]=null}},{addItems:function(a,e){var b=this;b._adder=g(a,j,b,function(){b._adder=0;e&&e.call(b);b.fire("addComplete",{items:a})});return b._adder},preAddItems:function(a,e){var b=this;b._adder=g(a,function(a){j.call(b,a,null,"preadd")},b,function(){b._adder=0;e&&e.call(b);
b.fire("addComplete",{items:a})});return b._adder},isAdding:function(){return!!this._adder},removeItem:function(a,e){var e=e||{},a=k(a),b=e.effect,d=e.callback,c=this;e.callback=function(){c._deleteItem(a);a.remove();d&&d.call(c)};b?a.animate({effect:b.effect},b.duration,b.easing,e.callback):e.callback()},destroy:function(){k(f).detach("resize",this.__onResize)},isAdjusting:function(){return!!this._adjuster},adjust:function(a){function e(){--i;0>=i&&(b._adjuster=0,a&&a.call(b),b.fire("adjustComplete",
{items:d}))}c.log("waterfall:adjust");var b=this,d=this._items=this._preItems.concat(this._items);b.isAdjusting()&&(b._adjuster.stop(),b._adjuster=0);this._preItems=[];for(var f=0,h=d.length;f<h;)d[f]?k(d[f]).stop(!0).attr("data-waterfall-index",f++):(d.splice(f,1),--h);b._createColumnItems();var i=d.length;return b._adjuster=g(d,function(a){j.call(b,a,e,true)})},adjustItem:function(){}});return l});
KISSY.add("waterfallx/loader",function(c,g,j){function h(){h.superclass.constructor.apply(this,arguments);this.config.diff||(this.config.diff=0)}function l(){c.log("waterfall:doScroll");!this.__loading&&this.__started&&(this.isAdjusting()?(console.log(this.isAdjusting()),this.__onScroll()):this.config.diff+i(f).scrollTop()+i(f).height()>this.container.outerHeight(!0)&&(c.log("waterfall:loading"),k.call(this)))}function k(){function a(a,c){b.__loading=0;b.addItems(a,c)}function c(){b.end()}var b=this;
b.__loading=1;var d=b.config.load;d&&d(a,c)}var i=g.all,f=c.Env.host||window;c.extend(h,j,{_init:function(){h.superclass._init.apply(this,arguments);this.__onScroll=c.buffer(l,50,this);this.__onScroll();this.start()},start:function(){this.__started||(i(f).on("scroll",this.__onScroll),this.__started=1)},end:function(){i(f).detach("scroll",this.__onScroll);self.__started=0},pause:function(){this.end()},resume:function(){this.start()},destroy:function(){h.superclass.destroy.apply(this,arguments);i(f).detach("scroll",
this.__onScroll);this.__started=0}});return h},{requires:["node","./base"]});KISSY.add("waterfallx",function(c,g,j){g.Loader=j;return g},{requires:["waterfallx/base","waterfallx/loader"]});
