KISSY.add("gallery/waterfallx/1.0/waterfallx",function(f,h){return h},{requires:["./waterfallx"]});
KISSY.add("gallery/waterfallx/1.0/base",function(f){function h(a,c,b,d){var e={},n=0,i;a.length>n?i=setTimeout(function(){var e=+new Date;do{var f=a[n++];c.call(b,f)}while(a.length>n&&50>+new Date-e);a.length>n?i=setTimeout(arguments.callee,25):d&&d.call(b,a)},25):d&&f.later(d,0,!1,b,a);e.stop=function(){clearTimeout(i)};return e}function j(a,c,b){if(a){var d=null,e=null,f="append",a=k(a),i=this._colItems,h=i.length,g=Number.MAX_VALUE,j=0;b?"preadd"==b?(e=this._preItems,f="prepend",e.push(a),a.attr("data-waterfall-index",
-e.length)):d=this.config.addjustEffect:(e=this._items,d=this.config.effect,a.attr("data-waterfall-index",e.length)&&e.push(a));for(b=0;b<h;b++)e=i[b].outerHeight(!0),e<g&&(g=e,j=b);d&&d.effect?(i[j][f](a),a.hide(),c&&c(),a[d.effect](d.duration,0,d.easing)):(i[j].append(a),c&&c());return a}c&&c()}function l(){var a=this._containerRegion;a&&this.container.width()===a||(this._calculate()===this._colItems.length?this._adjustMargin():this.adjust())}function o(a){a.container&&(this.config=f.merge({align:"center",
minColCount:1,effect:{effect:"fadeIn",duration:1}},a),this.container=k(a.container),this._colItems=[],this._preItems=[],this._items=[],this._init())}var k=f.Node.all,m=f.DOM,g=f.Env.host||window;f.augment(o,f.Event.Target,{_init:function(){m.addStyleSheet(".ks-waterfall-col{ display: inline-block; vertical-align:top;*display: inline; *zoom: 1}","ks-waterfallx");this._createColumnItems();this.addItems(this.container.all(".ks-waterfall"));this.__onResize=f.buffer(l,50,this);k(g).on("resize",this.__onResize)},
_calculate:function(){var a=this.config,c=this.container.width();a.colWidth||(a.colWidth=c);a=Math.max(parseInt(c/a.colWidth),a.minColCount);this._containerRegion=c;return a},_createColumnItems:function(){for(var a=this.config,c=this._colItems,b=this._calculate(),d=c.length-1;-1<d;--d)c[d].remove();c.length=b;for(d=0;d<b;++d)c[d]=k("<div>").addClass("ks-waterfall-col").appendTo(this.container),c[d].width(a.colWidth);this._adjustMargin()},_adjustMargin:function(){var a=this.config,c=a.align,b=this._colItems,
d=b.length,a="left"===c?0:Math.max(this.container.width()-d*a.colWidth,0),a=a/d;"center"===c&&(a/=2);b[0].css("marginLeft",a+"px")},_deleteItem:function(a){a=+a.attr("data-waterfall-index");0>a?this._preItems[-(a+1)]=null:this._items[a]=null}},{addItems:function(a,c){var b=this;b._adder=h(a,j,b,function(){b._adder=0;c&&c.call(b);b.fire("addComplete",{items:a})});return b._adder},preAddItems:function(a,c){var b=this;b._adder=h(a,function(a){j.call(b,a,null,"preadd")},b,function(){b._adder=0;c&&c.call(b);
b.fire("addComplete",{items:a})});return b._adder},isAdding:function(){return!!this._adder},removeItem:function(a,c){var c=c||{},a=k(a),b=c.effect,d=c.callback,e=this;c.callback=function(){e._deleteItem(a);a.remove();d&&d.call(e)};b?a.animate({effect:b.effect},b.duration,b.easing,c.callback):c.callback()},destroy:function(){k(g).detach("resize",this.__onResize)},isAdjusting:function(){return!!this._adjuster},adjust:function(a){function c(){--i;0>=i&&(b._adjuster=0,a&&a.call(b),b.fire("adjustComplete",
{items:d}))}f.log("waterfall:adjust");var b=this,d=this._items=this._preItems.concat(this._items);b.isAdjusting()&&(b._adjuster.stop(),b._adjuster=0);this._preItems=[];for(var e=0,g=d.length;e<g;)d[e]?k(d[e]).stop(!0).attr("data-waterfall-index",e++):(d.splice(e,1),--g);b._createColumnItems();var i=d.length;return b._adjuster=h(d,function(a){j.call(b,a,c,true)})},adjustItem:function(){}});return o});
KISSY.add("gallery/waterfallx/1.0/loader",function(f,h,j){function l(){l.superclass.constructor.apply(this,arguments);this.config.diff||(this.config.diff=0)}function o(){f.log("waterfall:doScroll");!this.__loading&&this.__started&&(this.isAdjusting()?this.__onScroll():this.config.diff+m(g).scrollTop()+m(g).height()>=this.container.outerHeight(!0)&&(f.log("waterfall:loading"),k.call(this)))}function k(){function a(a,c){b.__loading=0;b.addItems(a,c)}function c(){b.end()}var b=this;b.__loading=1;var d=
b.config.load;d&&d(a,c)}var m=h.all,g=f.Env.host||window;f.extend(l,j,{_init:function(){l.superclass._init.apply(this,arguments);this.__onScroll=f.buffer(o,50,this);this.__onScroll();this.start()},start:function(){this.__started||(m(g).on("scroll",this.__onScroll),this.__started=1)},end:function(){m(g).detach("scroll",this.__onScroll);self.__started=0},pause:function(){this.end()},resume:function(){this.start()},destroy:function(){l.superclass.destroy.apply(this,arguments);m(g).detach("scroll",this.__onScroll);
this.__started=0}});return l},{requires:["node","./base"]});KISSY.add("gallery/waterfallx/1.0/waterfallx",function(f,h,j){h.Loader=j;return h},{requires:["gallery/waterfallx/1.0/base","gallery/waterfallx/1.0/loader"]});
