KISSY.add("gallery/form/1.0/uploader/auth/base",function(d,n,l){function i(c,a){a=d.merge({uploader:c},a);i.superclass.constructor.call(this,a);this._init()}var h=h||d;d.mix(i,{event:{ERROR:"error"}});d.extend(i,l,{_init:function(){var c=this,a=c.get("uploader"),e=a.get("queue");if(a==""){h.log("[uploader-auth]:uploader不可以为空！");return false}c._setSwfButtonExt();e.on("add",function(b){b=b.file;c.testAllowExt(b);c.testMaxSize(b);c.testRepeat(b)});e.on("remove",function(b){b.file.status.get("curType")==
"success"&&c.testMax()});a.on("success",function(){c.testMax()});a.on("error",function(){a.set("isAllowUpload",true)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(c){return this.get("rules")[c]},isUploaderType:function(c){var a=this.get("uploader").get("type");return c==a},testRequire:function(){var c=this.get("uploader").get("urlsInput").get("urls"),a=this.getRule("require"),e=a?a[0]:false;c=c.length>0;if(!e)return true;if(!c){d.log("[uploader-auth]:"+a[1]);this.fire(i.event.ERROR,
{rule:"require",msg:a[1],value:e})}return c},testAllowExt:function(c){function a(j){j=j.split(".");return j[j.length-1]}if(!d.isObject(c))return false;var e=c.name,b=this.getRule("allowExts"),g=[],f;if(!d.isArray(b))return false;g=this._getExts(b[0].ext);f=function(j){var k=false,o;d.each(g,function(m){o=RegExp("^.+."+m+"$");if(o.test(j))return k=true});return k}(e);if(!f){e=a(e);e=d.substitute(b[1],{ext:e});this._stopUpload(c,e);this.fire(i.event.ERROR,{rule:"allowExts",msg:e,value:b[0]})}return f},
testMax:function(){var c=this.get("uploader"),a=c.get("queue").getFiles("success").length,e=this.getRule("max");if(e){var b=c.get("button");if(a=a<e[0]){b.set("disabled",false);c.set("isAllowUpload",true)}else{b.set("disabled",true);c.set("isAllowUpload",false);this.fire(i.event.ERROR,{rule:"max",msg:e[1],value:e[0]})}return a}},testMaxSize:function(c){var a=c.size,e=this.getRule("maxSize");if(e){var b=Number(e[0])*1E3;a=a<=b;if(!a){b=d.substitute(e[1],{maxSize:d.convertByteSize(b),size:c.textSize});
this._stopUpload(c,b);this.fire(i.event.ERROR,{rule:"maxSize",msg:b,value:e[0]})}return a}},testRepeat:function(c){if(!d.isObject(c))return false;var a=this,e=c.name,b=a.getRule("allowRepeat");if(b){var g=b[0],f=b[1],j=a.get("uploader").get("queue").getFiles("success"),k=false;if(g)return false;d.each(j,function(o){if(o.name==e){a._stopUpload(c,f);a.fire(i.event.ERROR,{rule:"allowRepeat",msg:f,value:b[0]});return k=true}});return k}},_setSwfButtonExt:function(){var c=this.get("uploader"),a=this.getRule("allowExts");
c=c.get("button");if(!this.isUploaderType("flash")||!d.isArray(a))return false;c.set("fileFilters",a[0]);return this},_getExts:function(c){if(!d.isString(c))return false;var a=c.split(";"),e=[],b=/^\*\./;d.each(a,function(g){g=g.replace(b,"");e.push(g.toUpperCase())});d.each(e,function(g){a.push(g)});return a},_stopUpload:function(c,a){d.isString(a)||(a="");var e=this.get("uploader").get("queue"),b=e.getFileIndex(c.id);e.fileStatus(b,e.constructor.status.ERROR,{msg:a})}},{ATTRS:{uploader:{value:""},
rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"不支持{ext}格式的文件上传！"],require:[false,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[false,"该文件已经存在！"]}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/base",function(d,n,l,i,h,c,a){function e(b){e.superclass.constructor.call(this,b)}d.mix(e,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{}});d.extend(e,n,{render:function(){var b=this.get("serverConfig"),g=this.getUploadType(this.get("type")),f=g.event,j;if(!g)return false;
this.set("urlsInput",this._renderUrlsInput());this._renderQueue();j=this._renderButton();this.get("type")==e.type.FLASH&&d.mix(b,{swfUploader:j.get("swfUploader")});b=new g(b);b.on(f.SUCCESS,this._uploadCompleteHanlder,this);f.PROGRESS&&b.on(f.PROGRESS,this._uploadProgressHandler,this);b.on(f.STOP,this._uploadStopHanlder,this);this.set("uploadType",b);this.fire(e.event.RENDER);return this},upload:function(b){if(!d.isNumber(b))return false;var g=this.get("uploadType"),f=this.get("queue"),j=f.get("files")[b],
k;if(!d.isPlainObject(j)){d.log("[uploader]:队列中不存在id为"+b+"的文件");return false}if(this.get("curUploadIndex")!=""){alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！");return false}k=j.input.id||j.input;if(f.fileStatus(b).get("curType")==="error")return false;this.fire(e.event.START,{index:b,file:j});if(!this.get("isAllowUpload"))return false;this.set("curUploadIndex",b);f.fileStatus(b,e.status.START);g.upload(k)},cancel:function(b){var g=this.get("uploadType"),f=this.get("queue"),j=e.status,k=f.fileStatus(b);
if(d.isNumber(b)&&k!=j.SUCCESS)f.fileStatus(b,j.CANCEL);else{g.stop();this._continueUpload()}return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(b){if(!d.isString(b))b=e.status.WAITING;this.set("uploadFilesStatus",b);this._uploaderStatusFile(b);return this},_uploaderStatusFile:function(b){b=this.get("queue").getIndexs(b);if(!b.length){this.set("uploadFilesStatus","");this.fire(e.event.UPLOAD_FILES);return false}this.upload(b[0]);return this},
isSupportAjax:function(){var b=false;try{if(FormData)b=true}catch(g){b=false}return b},isSupportFlash:function(){var b=d.UA.fpv();return d.isArray(b)&&b.length>0},getUploadType:function(b){var g=this,f=e.type,j;if(b==f.AUTO)b=[f.AJAX,f.IFRAME];if(d.isArray(b)&&b.length>0)d.each(b,function(k){if(j=g._getType(k))return false});else j=g._getType(b);return j},_getType:function(b){var g=e.type,f=this.isSupportAjax(),j=this.isSupportFlash();switch(b){case g.IFRAME:g=h;break;case g.AJAX:g=f&&c||false;break;
case g.FLASH:g=j&&a||false;break;default:d.log("[uploader]:type参数不合法");return false}g&&d.log("[uploader]:使用"+b+"上传方式");this.set("type",b);return g},_renderButton:function(){var b=this.get("button");if(!d.isObject(b)){d.log("[uploader]:button参数不合法！");return false}b.on("change",this._select,this);b.render();return b},_renderQueue:function(){var b=this.get("queue"),g=this.get("urlsInput");if(!d.isObject(b)){d.log("[uploader]:queue参数不合法");return false}b.set("uploader",this);b.on(b.constructor.event.REMOVE,
function(f){g.remove(f.file.sUrl)});b.render();e.status=b.constructor.status;return b},_select:function(b){var g=this,f=g.get("autoUpload"),j=g.get("queue"),k=g.get("curUploadIndex"),o=b.files;d.each(o,function(m){if(!m.size)m.size=0;if(!m.name)m.name=m.fileName||"";m.input=b.input||m});g.fire(e.event.SELECT,{files:o});if(!g.get("isAllowUpload"))return false;j.add(o,function(){k==""&&f&&g.uploadFiles()})},_renderUrlsInput:function(){var b=this.get("button").target,g=this.get("urlsInputName");b=new i(b,
{name:g});b.render();return b},_uploadCompleteHanlder:function(b){b=b.result;var g,f=e.event,j=this.get("queue"),k=this.get("curUploadIndex");if(!d.isObject(b))return false;if(g=b.status){j.fileStatus(k,e.status.SUCCESS);this._success(b.data);this.fire(f.SUCCESS,{index:k,file:j.getFile(k)})}else{j.fileStatus(k,e.status.ERROR,{msg:b.msg||""});this.fire(f.ERROR,{status:g})}this.set("curUploadIndex","");this.fire(f.COMPLETE,{index:k,file:j.getFile(k)});this._continueUpload()},_uploadStopHanlder:function(){var b=
this.get("queue"),g=this.get("curUploadIndex");b.fileStatus(g,e.status.CANCEL);this.set("curUploadIndex","");this.fire(e.event.CANCEL,{index:g})},_continueUpload:function(){var b=this.get("uploadFilesStatus");b!=""&&this._uploaderStatusFile(b)},_uploadProgressHandler:function(b){var g=this.get("queue"),f=this.get("curUploadIndex"),j=g.getFile(f);d.mix(b,{file:j});g.fileStatus(f,e.status.PROGRESS,b);this.fire(e.event.PROGRESS,b)},_success:function(b){if(!d.isObject(b))return false;b=b.url;var g=this.get("urlsInput"),
f=this.get("curUploadId"),j=this.get("queue");if(!d.isString(b)||!d.isObject(g))return false;j.updateFile(f,{sUrl:b});g.add(b)}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:e.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:true},autoUpload:{value:true},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""}}});d.convertByteSize=function(b){var g=-1;do{b/=1024;g++}while(b>99);return Math.max(b,
0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][g]};return e},{requires:["base","node","./urlsInput","./type/iframe","./type/ajax","./type/flash","flash"]});
KISSY.add("gallery/form/1.0/uploader/button/base",function(d,n,l){function i(c,a){a=d.merge({target:h(c)},a);i.superclass.constructor.call(this,a)}var h=n.all;d.mix(i,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(c){return c.replace(/.*(\/|\\)/,"")}});d.extend(i,l,{render:function(){var c=this.get("target");if(this.fire(i.event.beforeRender)===false){d.log("[AjaxUploader-Button] button render was prevented.");
return false}else{if(c==null){d.log("[AjaxUploader-Button] Cannot find target!");return false}this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(i.event.afterRender);return this}},show:function(){this.get("target").show();this.fire(i.event.afterShow);return i},hide:function(){this.get("target").hide();this.fire(i.event.afterHide);return i},reset:function(){var c=this.get("inputContainer");h(c).remove();this.set("inputContainer","");this.set("fileInput",
"");this._createInput();return this},_createInput:function(){var c=this.get("target"),a=this.get("name"),e=this.get("tpl");if(!d.isString(a)||!d.isString(e)){d.log("[AjaxUploader-Button] No name or tpl specified.");return false}a=d.substitute(e,{name:a});a=h(a);h(a).appendTo(c);c=h(a).children("input");h(c).on("change",this._changeHandler,this);this.set("fileInput",c);this.set("inputContainer",a);return a},_changeHandler:function(c){var a=this.get("fileInput"),e=h(a).val();c=c.target.files;var b=
[];if(e==""){d.log("[AjaxUploader-Button] No file selected.");return false}c?d.each(c,function(g){d.isObject(g)&&b.push({name:g.name,type:g.type,size:g.size})}):b.push({name:i.getFileName(e)});this.fire(i.event.CHANGE,{files:b,input:a.getDOMNode()});this.reset()},_setDisabled:function(c){var a=this.get("cls").disabled,e=this.get("target"),b=this.get("fileInput");if(!e.length||!d.isBoolean(c))return false;if(c){e.addClass(a);h(b).hide()}else{e.removeClass(a);h(b).show()}return c},_setMultiple:function(c){var a=
this.get("fileInput");if(!a.length)return false;c&&a.attr("multiple","multiple")||a.removeAttr("multiple");return c}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(c){this.get("fileInput")&&h(this.get("fileInput")).attr("name",c);return c}},disabled:{value:false,setter:function(c){this._setDisabled(c);return c}},
multiple:{value:true,setter:function(c){this._setMultiple(c);return c}},cls:{value:{disabled:"uploader-button-disabled"}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/button/swfButton",function(d,n,l,i){function h(a,e){e=d.merge({target:c(a)},e);h.superclass.constructor.call(this,e)}var c=n.all;d.mix(h,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});d.extend(h,l,{render:function(){var a=this,e=a.get("target"),b,g=a.get("multiple"),f=a.get("fileFilters");e.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
b=a._initSwfUploader();b.on("contentReady",function(){b.browse(g,f);a._bindBtnEvent();b.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(h.event.RENDER)},a)},_createSwfWrapper:function(){var a=this.get("target"),e=this.get("tpl"),b=this.get("swfWrapperId")!=""&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+d.guid();e=d.substitute(e,{id:b});this.set("swfWrapperId",b);return c(e).appendTo(a)},_initSwfUploader:function(){var a=this.get("flash"),e=this.get("swfWrapperId"),
b;try{b=new i(e,a);this.set("swfUploader",b)}catch(g){}return b},_bindBtnEvent:function(){var a=this,e=h.event,b=a.get("swfUploader");if(!b)return false;d.each(e,function(g){b.on(g,function(){a.fire(g)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),e=this.get("target");d.mix(a.attrs,{width:e.width(),height:e.height()});this.set("flash",a)},_changeHandler:function(a){this.fire(h.event.CHANGE,{files:a.fileList})},_setDisabled:function(a){var e=this.get("swfUploader"),b=this.get("cls").disabled,
g=this.get("target"),f=this.get("swfWrapper");if(!e||!d.isBoolean(a))return false;if(a){g.addClass(b);f.hide()}else{g.removeClass(b);f.show()}return a}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:true,setter:function(a){var e=this.get("swfUploader");e&&e.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var e=this.get("swfUploader");e&&
d.isArray(a)&&e.filter(a);return a}},disabled:{value:false,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"../plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:true,btn:true}},swfUploader:{value:""}}});return h},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.0/uploader/index",function(d,n,l,i,h,c,a){function e(f,j,k){k=d.mix(d.parseConfig(f),k);e.superclass.constructor.call(this,k);this.set("buttonTarget",f);this.set("queueTarget",j);this.set("uploaderConfig",k);this._init()}var b=l.all,g={CONFIG:"data-config",BUTTON_CONFIG:"data-button-config",THEME_CONFIG:"data-theme-config",AUTH:"data-auth"};d.parseConfig=function(f,j){var k={},o,m=j||g.CONFIG;o=b(f).attr(m);if(!d.isString(o))return{};try{k=d.JSON.parse(o)}catch(p){d.log("[uploaderRender]:请检查"+
f+"上"+m+"属性内的json格式是否符合规范！")}return k};d.extend(e,n,{_init:function(){var f=this,j=f.get("uploaderConfig"),k=f._initButton(),o;f.set("button",k);f._initThemes(function(m){o=m.get("queue");d.mix(j,{button:k,queue:o});var p=new i(j);p.render();f.set("uploader",p);m.afterUploaderRender&&m.afterUploaderRender(p);f._auth();f.fire("init",{uploader:p})})},_initButton:function(){var f=this.get("buttonTarget"),j=d.parseConfig(f,g.BUTTON_CONFIG),k=this.get("name"),o=this.get("type");j=d.merge({name:k},j);return o!=
"flash"&&new h(f,j)||new c(f)},_initThemes:function(f){var j=this,k=j.get("theme"),o=j.get("buttonTarget"),m=d.parseConfig(o,g.THEME_CONFIG);d.use(k+"/index",function(p,q){var r=j.get("queueTarget");p.mix(m,{queueTarget:r});r=new q(m);f&&f.call(j,r)})},_auth:function(){var f=this.get("buttonTarget"),j=this.get("uploader");if(b(f).attr(g.AUTH)){f=d.parseConfig(f,g.AUTH);f=new a(j,{rules:f});j.set("auth",f)}}},{ATTRS:{theme:{value:"gallery/form/1.0/uploader/themes/default"},buttonTarget:{value:""},
queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""},auth:{value:""}}});return e},{requires:["base","node","./base","./button/base","./button/swfButton","./auth/base"]});
KISSY.add("gallery/form/1.0/uploader/plugins/ajbridge/ajbridge",function(d,n){function l(e,b,g){e=e.replace(i,"");b=n._normalize(b||{});var f=this;e=i+e;var j=function(k){if(k.status<1)f.fire("failed",{data:k});else{d.mix(f,k);if(!k.dynamic||!b.src)f.activate()}};b.id=b.id||d.guid(h);l.instances[b.id]=f;if(b.src){b.params.allowscriptaccess="always";b.params.flashvars=d.merge(b.params.flashvars,{jsEntry:a,swfID:b.id})}if(g)f.__args=[e,b,j];else d.later(n.add,c,false,n,[e,b,j])}var i="#",h="ks-ajb-",
c=100,a="KISSY.AJBridge.eventHandler";d.app(l,{version:"1.0.15",instances:{},eventHandler:function(e,b){var g=l.instances[e];g&&g.__eventHandler(e,b)},augment:function(e,b){if(d.isString(b))b=[b];d.isArray(b)&&d.each(b,function(g){e.prototype[g]=function(){try{return this.callSWF(g,d.makeArray(arguments))}catch(f){this.fire("error",{message:f})}}})}});d.augment(l,d.EventTarget,{init:function(){if(this.__args){n.add.apply(n,this.__args);this.__args=null;delete this.__args}},__eventHandler:function(e,
b){var g=b.type;b.id=e;switch(g){case "log":d.log(b.message);break;default:this.fire(g,b)}},callSWF:function(e,b){b=b||[];try{if(this.swf[e])return this.swf[e].apply(this.swf,b)}catch(g){var f="";if(b.length!==0)f="'"+b.join("','")+"'";return(new Function("self","return self.swf."+e+"("+f+");"))(this)}}});l.augment(l,["activate","getReady","getCoreVersion"]);return window.AJBridge=d.AJBridge=l},{requires:["flash"]});
KISSY.add("gallery/form/1.0/uploader/plugins/ajbridge/uploader",function(d,n,l){function i(h,c){c=c||{};var a={};d.each(["ds","dsp","btn","hand"],function(e){if(e in c)a[e]=c[e]});c.params=c.params||{};c.params.flashvars=d.merge(c.params.flashvars,a);i.superclass.constructor.call(this,h,c)}d.extend(i,l);l.augment(i,["setFileFilters","filter","setAllowMultipleFiles","multifile","browse","upload","uploadAll","cancel","getFile","removeFile","lock","unlock","setBtnMode","useHand","clear"]);i.version=
"1.0.1";l.Uploader=i;return l.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add(function(d){function n(h){var c={mode:"filter",maxWidth:40,maxHeight:40,onError:function(){return 1},preview:true,destroy:true};this.event={check:"check",show:"show",error:"error"};if(typeof window.FileReader==="undefined")switch(d.UA.shell){case "firefox":c.mode="domfile";break;case "ie":switch(d.UA.ie){case 6:c.mode="simple";break;default:c.mode="filter"}break;default:c.mode="simple";c.preview=false}else c.mode="html5";this.config=d.mix(c,h);d.log(i+"Preview initialized.")}var l=d.DOM,
i="[Plugin: Preview] ";d.augment(n,d.EventTarget,{preview:function(h,c){function a(){switch(f.config.mode){case "filter":f.file.select();k=g;try{return j.selection.createRange().text}catch(m){d.log("[UploadPreview] Get image data error, the error is: ");d.log(m,"dir")}finally{j.selection.empty()}break;case "domfile":k=b;return f.file.files[0].getAsDataURL();case "html5":var p=new FileReader;p.onload=function(q){e(q.target.result)};p.onerror=function(){d.log("[UploadPreview] File Reader Error. Your browser may not fully support html5 file api",
"warning")};p.readAsDataURL(f.file.files[0]);return false;case "remote":k=remotePreview;d.log("[UploadPreview] This function is not supported right now.");break;default:k=b;return f.file.value}}function e(m,p,q){f.img.src=m;if(p>1&&q>1){var r=Math.min(1,Math.max(0,f.config.maxWidth)/p||1,Math.max(0,f.config.maxHeight)/q||1);f.img.style.width=Math.round(p*r)+"px";f.img.style.height=Math.round(q*r)+"px";f.img.setAttribute("data-ratio",r)}l.attr(f.img,"data-ks-imagezoom",f.config.mode=="filter"?f.data:
m);f.fire(f.event.show)}function b(){e(f.data)}function g(){if(!f.preload){f.preload=document.createElement("div");l.css(f.preload,{visibility:"hidden",position:"absolute",left:"-9999px",top:"-9999px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='image')"});var m=document.body;m.insertBefore(f.preload,m.childNodes[0]);m=null}f.data=f.data.replace(/[)'"%]/g,function(q){return escape(escape(q))});d.log("[UploadPreview] This escaped data is "+f.data);try{f.preload.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=
f.data}catch(p){f._error("[UploadPreview] Filter error")}f.img.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src=\""+f.data+'")';f.img.zoom=1;f.img.setAttribute("data-ks-imagezoom",f.data);e(f.TRANSPARENT,f.preload.offsetWidth,f.preload.offsetHeight)}var f=this,j=document,k;f.file=h;f.img=c;f.preload=null;f.data=null;f.TRANSPARENT=d.UA.ie==6||d.UA.ie==7?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";
if(f.file){d.log("[UploadPreview] One file selected. Using "+f.config.mode+" mode to preview.");if(f.fire(f.event.check)!==false){var o=a();d.log("[UploadPreview] Get data done. The data is "+o);if(o&&o!==f.data){f.data=o;o=null;k()}}else d.log("[UploadPreview] Check error.")}},setConfig:function(h){self.config=d.mix(self.config,h)},destroy:function(){if(this._upload){this._upload.dispose();this._upload=null}this.file=this.img=this.data=this.preload=null},_error:function(h){d.log(h)}});return n});
KISSY.add("gallery/form/1.0/uploader/plugins/preview/preview",function(d,n){function l(g,f){if(a!="filter")g.src=f;else{g.src=b;f=f.replace(/[)'"%]/g,function(j){return escape(escape(j))});g.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src=\""+f+'")';g.zoom=1}return true}function i(g){this.config=d.mix({maxWidth:40,maxHeight:40},g);d.log(c+"Preview initialized. The preview mode is "+a)}var h=document,c="[Plugin: Preview] ",a=function(){var g="";if(typeof window.FileReader===
"undefined")switch(d.UA.shell){case "firefox":g="domfile";break;case "ie":switch(d.UA.ie){case 6:g="simple";break;default:g="filter"}}else g="html5";return g}(),e={check:"check",success:"success",showed:"showed",error:"error"},b=d.UA.ie<8?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";d.augment(i,d.EventTarget,{preview:function(g,f){g=n.get(g);f=n.get(f);var j=this,k=function(){j.fire(e.getData,{data:j.data,mode:a});
if(f){l(f,j.data);j.fire(e.showed,{img:f})}};j.data=undefined;if(g){d.log(c+"One file selected. Getting data...");switch(a){case "domfile":j.data=g.files[0].getAsDataURL();break;case "filter":g.select();try{j.data=h.selection.createRange().text}catch(o){d.log(c+"Get image data error, the error is: ");d.log(o,"dir")}finally{h.selection.empty()}break;case "html5":var m=new FileReader;m.onload=function(p){j.data=p.target.result;k()};m.onerror=function(){d.log(c+"File Reader Error. Your browser may not fully support html5 file api",
"warning");j.fire(e.error)};m.readAsDataURL(g.files[0]);break;default:j.data=g.value}if(j.data)k();else if(a!="html5"){d.log(c+"Retrive Data error.");j.fire(e.error)}}else d.log(c+"File Input Element does not exists.");return j.data}});return i},{requires:["dom","event"]});
KISSY.add("gallery/form/1.0/uploader/plugins/progressBar/progressBar",function(d,n,l){function i(c,a){a=d.merge({wrapper:h(c)},a);i.superclass.constructor.call(this,a)}var h=n.all;d.mix(i,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});d.extend(i,l,{render:function(){var c=this.get("wrapper"),a=this.get("width");if(!c.length)return false;
c.addClass(i.cls.PROGRESS_BAR).width(a);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(i.event.RENDER)},show:function(){var c=this;c.get("wrapper").fadeIn(c.get("duration"),function(){c.set("visible",true);c.fire(i.event.SHOW,{visible:true})})},hide:function(){var c=this;c.get("wrapper").fadeOut(c.get("duration"),function(){c.set("visible",false);c.fire(i.event.HIDE,{visible:false})})},_create:function(){var c=this.get("wrapper"),a=this.get("value"),e=this.get("tpl");
a=d.substitute(e,{value:a});c.html("");return h(a).appendTo(c)},_addAttr:function(){var c=this.get("wrapper"),a=this.get("value");c.attr("role","progressbar");c.attr("aria-valuemin",0);c.attr("aria-valuemax",100);c.attr("aria-valuenow",a);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(c){var a=this,e=a.get("wrapper"),b=a.get("bar"),g=a.get("speed"),f;if(c>100)c=100;if(c<0)c=0;f=e.width()*(c/100);b.animate({width:f+"px"},g,"none",function(){e.attr("aria-valuenow",
c);b.attr("data-value",c);a.fire(i.event.CHANGE,{value:c,width:f})});return c}},visible:{value:true},duration:{value:0.3},tpl:{value:i.tpl.DEFAULT},speed:{value:0.2}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/queue/base",function(d,n,l,i){function h(a,e){h.superclass.constructor.call(this,e);this.set("target",c(a))}var c=n.all;d.mix(h,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{RENDER:"render",ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"fileStatus",UPDATE_FILE:"updateFile"},
status:i.type,cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});d.extend(h,l,{render:function(){this.get("target").addClass(h.cls.QUEUE);this.fire(h.event.RENDER);return this},add:function(a,e){var b=this,g=h.event;if(a.length>0){b._addFiles(a,function(){e&&e.call(b);b.fire(g.ADD_FILES,{files:a})});return false}else return b._addFile(a,function(f,j){e&&e.call(b,f,j)})},_addFile:function(a,e){if(!d.isObject(a)){d.log("[uploader-queue]:_addFile()参数file不合法！");return false}var b=
this,g=b.get("duration"),f=b._setAddFileData(a),j=b.getFileIndex(f.id);b.fileStatus(j,h.status.WAITING);f.target.fadeIn(g,function(){b.fire(h.event.ADD,{index:j,file:f,target:f.target});e&&e.call(b,j,f)});return f},_addFiles:function(a,e){function b(f){if(f===a.length){e&&e.call(this);return false}g._addFile(a[f],function(){f++;b(f)})}if(!a.length){d.log("[uploader-queue]:_addFiles()参数files不合法！");return false}var g=this;b(0)},remove:function(a,e){var b=this,g=b.get("files"),f,j,k=b.get("duration");
if(d.isString(a))a=b.getFileIndex(a);f=g[a];if(!d.isObject(f)){d.log("[uploader-queue]:remove()不存在index为"+a+"的文件数据");return false}j=f.target;j.fadeOut(k,function(){j.remove();b.fire(h.event.REMOVE,{index:a,file:f});e&&e.call(b,a,f)});g=d.filter(g,function(o,m){return m!==a});b.set("files",g);return f},clear:function(){function a(){b=e.get("files");if(!b.length){e.fire(h.event.CLEAR);return false}e.remove(0,function(){a()})}var e=this,b;a()},fileStatus:function(a,e,b){if(!d.isNumber(a))return false;
var g=this.getFile(a);if(!d.isPlainObject(g))return false;g=g.status;e&&g.change(e,b);this.fire(h.event.FILE_STATUS,{index:a,status:e});return g},getFile:function(a){if(!d.isNumber(a))return false;a=this.get("files")[a];d.isPlainObject(a)||(a=false);return a},getFileIndex:function(a){var e=this.get("files"),b=-1;d.each(e,function(g,f){if(g.id==a){b=f;return true}});return b},updateFile:function(a,e){if(!d.isNumber(a))return false;if(!d.isObject(e)){d.log("[uploader-queue]:updateFile()的data参数有误！");
return false}var b=this.get("files"),g=this.getFile(a);if(!g)return false;d.mix(g,e);b[a]=g;this.set("files",b);this.fire(h.event.UPDATE_FILE,{index:a,file:g});return g},getIndexs:function(a){var e=this.get("files"),b,g=[];if(!e.length)return g;d.each(e,function(f,j){if(d.isObject(f)){b=f.status;b.get("curType")==a&&g.push(j)}});return g},getFiles:function(a){var e=this.get("files"),b,g=[];if(!e.length)return[];d.each(e,function(f){if(f){b=f.status;b.get("curType")==a&&g.push(f)}});return g},_setAddFileData:function(a){var e=
this.get("files"),b=this.get("uploader");if(!d.isObject(a)){d.log("[uploader-queue]:_updateFileData()参数file不合法！");return false}if(!a.id)a.id=d.guid(h.FILE_ID_PREFIX);if(a.size)a.textSize=i.convertByteSize(a.size);a.target=this._appendFileHtml(a);a.status=this._renderStatus(a);d.isObject(b)&&a.status.set("uploader",b);e.push(a);return a},_appendFileHtml:function(a){var e=this.get("target"),b=this.get("tpl");b=d.substitute(b,a);return c(b).hide().appendTo(e).data("data-file",a)},_renderStatus:function(a){var e=
a.target,b=h.hook.STATUS,g=this.get("statusConfig");if(!e.length)return false;e=e.children(b);d.mix(g,{queue:this,file:a});return new i(e,g)}},{ATTRS:{tpl:{value:h.tpl.DEFAULT},duration:{value:0.3},target:{value:""},files:{value:[]},statusConfig:{value:{}},uploader:{value:""}}});return h},{requires:["node","base","./status"]});
KISSY.add("gallery/form/1.0/uploader/queue/status",function(d,n,l,i){function h(a,e){e=d.merge({target:c(a)},e);h.superclass.constructor.call(this,e)}var c=n.all;d.mix(h,{type:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error"},convertByteSize:function(a){var e=-1;do{a/=1024;e++}while(a>99);return Math.max(a,0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][e]}});d.extend(h,l,{change:function(a,e){if(!d.isString(a))return false;var b;if(!this.isSupport(a)){d.log("[queue-status]:status参数为"+
a+"，不支持的状态类型");return false}e||(e={});(b=this["_"+a])&&b.call(this,e);this.set("curType",a);return this},isSupport:function(a){if(!d.isString(a))return false;var e=false;d.each(h.type,function(b){if(a==b)return e=true});return e},_changeDom:function(a){var e=this.get("target");e.html("");return c(a).appendTo(e)},_waiting:function(){var a=this.get("tpl").waiting,e=this.get("uploader"),b=this.get("queue"),g=this.get("file").id,f=b.getFileIndex(g);this._changeDom(a).children(".J_Upload").on("click",
function(j){j.preventDefault();if(!d.isObject(e))return false;e.upload(f)})},_start:function(){var a=this.get("tpl").start,e=this.get("target"),b=this.get("uploader"),g=b.get("type");if(!d.isString(a))return false;a=this._changeDom(a);a.children(".J_UploadCancel").on("click",function(f){f.preventDefault();if(!d.isObject(b))return false;b.cancel()});if(g=="ajax"||g=="flash"){g=a.children(".J_ProgressBar");g=new i(g);g.render();this.set("progressBar",g)}e.parent().addClass("current-upload-file")},_progress:function(a){a=
Math.ceil(a.loaded/a.total)*100;var e=this.get("progressBar");if(!e)return false;e.set("value",a)},_success:function(){var a=this,e=a.get("tpl").success,b=a.get("target"),g=a.get("queue"),f=a.get("file").id,j=a.get("progressBar"),k=a.get("target"),o,m,p;if(!d.isString(e))return false;d.isObject(j)&&j.set("value",100);d.later(function(){if(d.isObject(j))m=k.children().children(".J_ProgressBar").clone(true);o=a._changeDom(e);m&&o.prepend(m);p=o.children(".J_FileDel");p.on("click",function(q){q.preventDefault();
g.remove(f)})},300);b.parent().removeClass("current-upload-file")},_cancel:function(){var a=this.get("tpl").cancel,e=this.get("uploader");a=this._changeDom(a).children(".J_ReUpload");var b=this.get("file").id;a.on("click",function(g){g.preventDefault();if(!d.isObject(e))return false;e.upload(b)})},_error:function(a){d.isObject(a)||(a={msg:"文件上传失败！"});var e=this.get("tpl").error;a=this._changeDom(d.substitute(e,a)).children(".J_FileDel");var b=this.get("queue"),g=this.get("file").id;a.on("click",function(f){f.preventDefault();
b.remove(g)})}},{ATTRS:{target:{value:""},tpl:{value:{waiting:'<div class="waiting-status">等待上传，<a href="#Upload" class="J_Upload">点此上传</a> </div>',start:'<div class="start-status clearfix"><div class="f-l  J_ProgressBar uploader-progress"><img class="loading" src="http://img01.taobaocdn.com/tps/i1/T1F5tVXjRfXXXXXXXX-16-16.gif" alt="loading" /></div> <a class="f-l J_UploadCancel upload-cancel" href="#uploadCancel">取消</a></div> ',success:' <div class="success-status"><a href="#fileDel" class="J_FileDel">删除</a></div>',
cancel:'<div class="cancel-status">已经取消上传，<a href="#reUpload" class="J_ReUpload">点此重新上传</a> </div>',error:'<div class="error-status upload-error">{msg}<a href="#fileDel" class="J_FileDel">点此删除</a></div>'}},queue:{value:""},uploader:{value:""},file:{value:{}},curType:{value:""},progressBar:{value:""}}});return h},{requires:["node","base","../plugins/progressBar/progressBar"]});
KISSY.add("gallery/form/1.0/uploader/type/ajax",function(d,n,l){function i(c){i.superclass.constructor.call(this,c);try{this.set("formData",new FormData)}catch(a){}this._processData()}var h=n.all;d.mix(i,{event:d.merge(l.event,{PROGRESS:"progress"})});d.extend(i,l,{upload:function(c){if(!c){d.log("[uploader-AjaxType]:upload()，fileInput参数有误！");return false}var a=c.files;if(!a.length){d.log("[uploader-AjaxType]:upload()，不存在要上传的文件！");return false}this._addFileData(c,a[0]);this.send();return this},stop:function(){var c=
this.get("xhr");if(!d.isObject(c)){d.log("[uploader-AjaxType]:stop()，io值错误！");return false}c.abort();this.fire(i.event.STOP);return this},send:function(){var c=this,a=c.get("action"),e=c.get("formData"),b=new XMLHttpRequest;b.upload.addEventListener("progress",function(g){c.fire(i.event.PROGRESS,{loaded:g.loaded,total:g.total})});b.onload=function(){var g={};try{g=d.JSON.parse(b.responseText)}catch(f){d.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}c.fire(i.event.SUCCESS,{result:g})};b.open("POST",
a,true);b.send(e);c.set("xhr",b);return c},_processData:function(){var c=this.get("data"),a=this.get("formData");d.each(c,function(e,b){a.append(b,e)});this.set("formData",a)},_addFileData:function(c,a){if(!d.isObject(a)){d.log("[uploader-AjaxType]:_addFileData()，file参数有误！");return false}var e=this.get("formData"),b=this.get("fileDataName");if(b==""){b=h(c).attr("name");this.set("fileDataName",b)}e.append(b,a);this.set("formData",e)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:false,
cache:false,dataType:"json",contentType:false}},xhr:{value:""},fileDataName:{value:""},form:{value:{}},fileInput:{value:""}}});return i},{requires:["node","./base"]});KISSY.add("gallery/form/1.0/uploader/type/base",function(d,n,l){function i(h){i.superclass.constructor.call(this,h)}d.mix(i,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});d.extend(i,l,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return i},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/type/flash",function(d,n,l){function i(h){i.superclass.constructor.call(this,h);this._init()}d.mix(i,{event:d.merge(l.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});d.extend(i,l,{_init:function(){var h=this,c=h.get("swfUploader");if(!c){d.log("[uploader-FlashType]:swfUploader对象为空！");return false}c.on("contentReady",function(){h.fire(i.event.SWF_READY)},h);c.on("uploadStart",h._uploadStartHandler,h);c.on("uploadProgress",h._uploadProgressHandler,h);c.on("uploadCompleteData",
h._uploadCompleteDataHandler,h);c.on("uploadError",h._uploadErrorHandler,h)},upload:function(h){var c=this.get("swfUploader"),a=this.get("action"),e=this.get("data");this.set("uploadingId",h);c.upload(h,a,"POST",e);return this},stop:function(){var h=this.get("swfUploader"),c=this.get("uploadingId");if(c!=""){h.cancel(c);this.fire(i.event.STOP,{id:c})}return this},_uploadStartHandler:function(h){this.fire(i.event.START,{file:h.file})},_uploadProgressHandler:function(h){d.mix(h,{loaded:h.bytesLoaded,
total:h.bytesTotal});this.fire(i.event.PROGRESS,{loaded:h.loaded,total:h.total})},_uploadCompleteDataHandler:function(h){var c;try{c=JSON.parse(h.data)}catch(a){d.log("[uploader-FlashType]:json数据格式不合法！");this.fire(i.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(i.event.SUCCESS,{result:c})},_uploadErrorHandler:function(h){this.set("uploadingId","");this.fire(i.event.ERROR,{msg:h.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return i},{requires:["node","./base"]});
KISSY.add("gallery/form/1.0/uploader/type/iframe",function(d,n,l){function i(c){i.superclass.constructor.call(this,c)}var h=n.all;d.mix(i,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:d.mix(l.event,{CREATE:"create",REMOVE:"remove"})});
d.extend(i,l,{upload:function(c){c=h(c);if(!c.length)return false;this.fire(i.event.START,{input:c});this.set("fileInput",c);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(i.event.STOP);this.fire(i.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(c){if(!d.isObject(c)||d.isEmptyObject(c)){d.log("[uploader-iframeType]:data参数不是对象或者为空！");return false}var a="",e=this.get("tpl").HIDDEN_INPUT;
if(!d.isString(e))return false;for(var b in c)a+=d.substitute(e,{name:b,value:c[b]});return a},_createIframe:function(){var c=this.get("id"),a=this.get("tpl"),e=a.IFRAME,b=this.get("iframe");if(!d.isEmptyObject(b))return b;if(!d.isString(e)){d.log("[uploader-iframeType]:iframe的模板不合法！");return false}if(!d.isString(c)){d.log("[uploader-iframeType]:id必须存在且为字符串类型！");return false}c=d.substitute(a.IFRAME,{id:c});c=h(c);c.on("load",this._iframeLoadHandler,this);h("body").append(c);this.set("iframe",c);return c},
_iframeLoadHandler:function(c){var a=c.target;c=i.event.ERROR;a=a.contentDocument||window.frames[a.id].document;if(!a||!a.body){this.fire(c,{msg:"服务器端返回数据有问题！"});return false}a=a.body.innerHTML;d.log("[uploader-iframeType]:服务器端输出:"+a);if(a=="")return false;try{a=JSON.parse(a)}catch(e){d.log("[uploader-iframeType]:json数据格式不合法！");this.fire(c,{msg:"数据："+a+"不是合法的json数据"})}this.fire(i.event.SUCCESS,{result:a});this._remove()},_createForm:function(){var c=this.get("id"),a=this.get("tpl").FORM,e=this.get("data"),
b=this.get("action"),g=this.get("fileInput"),f="";if(!d.isString(a)){d.log("[uploader-iframeType]:form模板不合法！");return false}if(!d.isObject(e)){d.log("[uploader-iframeType]:data参数不合法！");return false}if(!d.isString(b)){d.log("[uploader-iframeType]:action参数不合法！");return false}e=this.dataToHidden(e);if(e=="")return false;f=d.substitute(a,{action:b,target:c,hiddenInputs:e});c=h(f).append(g);h("body").append(c);this.set("form",c);return c},_create:function(){var c=this._createIframe(),a=this._createForm();
this.fire(i.event.CREATE,{iframe:c,form:a})},_remove:function(){var c=this.get("form");this.get("iframe");c.remove();this.reset("form");this.fire(i.event.REMOVE,{form:c})}},{ATTRS:{tpl:{value:i.tpl},id:{value:"ks-uploader-iframe-"+d.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return i},{requires:["node","./base"]});
KISSY.add("gallery/form/1.0/uploader/urlsInput",function(d,n,l){function i(c,a){i.superclass.constructor.call(this,a);this.set("wrapper",h(c))}var h=n.all;d.mix(i,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});d.extend(i,l,{render:function(){var c=this.get("wrapper"),a=this.get("name");a=document.getElementsByName(a)[0];if(!d.isObject(c)){d.log("[uploader-urlsInput]:container参数不合法！");return false}a?this.set("input",h(a)):this._create()},add:function(c){if(!d.isString(c)){d.log("[uploader-urlsInput]:add()的url参数不合法！");
return false}var a=this.get("urls");if(this.isExist(c)){d.log("[uploader-urlsInput]:add()，文件路径已经存在！");return this}a.push(c);this.set("urls",a);this._val();return this},remove:function(c){var a=this.get("urls");if(!this.isExist(c)){d.log("[uploader-urlsInput]:remove()，不存在该文件路径！");return false}a=d.filter(a,function(e){return e!=c});this.set("urls",a);this._val();return a},_val:function(){var c=this.get("urls"),a=this.get("input"),e=this.get("split");c=c.join(e);a.val(c);return c},isExist:function(c){var a=
false,e=this.get("urls");if(!e.length)return false;d.each(e,function(b){if(b==c)return a=true});return a},_create:function(){var c=this.get("wrapper"),a=this.get("tpl"),e=this.get("name"),b=this.get("urls");if(!d.isString(a)||!d.isString("name")){d.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！");return false}a=h(d.substitute(a,{name:e,value:b}));c.append(a);this.set("input",a);return a}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:i.TPL},split:{value:",",setter:function(c){this._val();
return c}},input:{value:""},wrapper:{value:""}}});return i},{requires:["node","base"]});
