KISSY.add("gallery/form/1.0/uploader/auth/base",function(e,m,l){function j(c,a){a=e.merge({uploader:c},a);j.superclass.constructor.call(this,a);this._init()}var h=h||e;e.mix(j,{event:{ERROR:"error"}});e.extend(j,l,{_init:function(){var c=this,a=c.get("uploader"),d=a.get("queue");if(a==""){h.log("[uploader-auth]:uploader不可以为空！");return false}c._setSwfButtonExt();d.on("add",function(b){b=b.file;c.testAllowExt(b);c.testMaxSize(b);c.testRepeat(b)});d.on("remove",function(b){b.file.status.get("curType")==
"success"&&c.testMax()});a.on("success",function(){c.testMax()});a.on("error",function(){a.set("isAllowUpload",true)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(c){return this.get("rules")[c]},isUploaderType:function(c){var a=this.get("uploader").get("type");return c==a},testRequire:function(){var c=this.get("uploader").get("urlsInput").get("urls"),a=this.getRule("require"),d=a?a[0]:false;c=c.length>0;if(!d)return true;if(!c){e.log("[uploader-auth]:"+a[1]);this.fire(j.event.ERROR,
{rule:"require",msg:a[1],value:d})}return c},testAllowExt:function(c){function a(i){i=i.split(".");return i[i.length-1]}if(!e.isObject(c))return false;var d=c.name,b=this.getRule("allowExts"),f=[],g;if(!e.isArray(b))return false;f=this._getExts(b[0].ext);g=function(i){var k=false,o;e.each(f,function(n){o=RegExp("^.+."+n+"$");if(o.test(i))return k=true});return k}(d);if(!g){d=a(d);d=e.substitute(b[1],{ext:d});this._stopUpload(c,d);this.fire(j.event.ERROR,{rule:"allowExts",msg:d,value:b[0]})}return g},
testMax:function(){var c=this.get("uploader"),a=c.get("queue").getFiles("success").length,d=this.getRule("max");if(d){var b=c.get("button");if(a=a<d[0]){b.set("disabled",false);c.set("isAllowUpload",true)}else{b.set("disabled",true);c.set("isAllowUpload",false);this.fire(j.event.ERROR,{rule:"max",msg:d[1],value:d[0]})}return a}},testMaxSize:function(c){var a=c.size,d=this.getRule("maxSize");if(d){var b=Number(d[0])*1E3;a=a<=b;if(!a){b=e.substitute(d[1],{maxSize:e.convertByteSize(b),size:c.textSize});
this._stopUpload(c,b);this.fire(j.event.ERROR,{rule:"maxSize",msg:b,value:d[0]})}return a}},testRepeat:function(c){if(!e.isObject(c))return false;var a=this,d=c.name,b=a.getRule("allowRepeat");if(b){var f=b[0],g=b[1],i=a.get("uploader").get("queue").getFiles("success"),k=false;if(f)return false;e.each(i,function(o){if(o.name==d){a._stopUpload(c,g);a.fire(j.event.ERROR,{rule:"allowRepeat",msg:g,value:b[0]});return k=true}});return k}},_setSwfButtonExt:function(){var c=this.get("uploader"),a=this.getRule("allowExts");
c=c.get("button");if(!this.isUploaderType("flash")||!e.isArray(a))return false;c.set("fileFilters",a[0]);return this},_getExts:function(c){if(!e.isString(c))return false;var a=c.split(";"),d=[],b=/^\*\./;e.each(a,function(f){f=f.replace(b,"");d.push(f.toUpperCase())});e.each(d,function(f){a.push(f)});return a},_stopUpload:function(c,a){e.isString(a)||(a="");var d=this.get("uploader").get("queue"),b=d.getFileIndex(c.id);d.fileStatus(b,d.constructor.status.ERROR,{msg:a})}},{ATTRS:{uploader:{value:""},
rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"不支持{ext}格式的文件上传！"],require:[false,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[false,"该文件已经存在！"]}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/base",function(e,m,l,j,h,c,a){function d(b){d.superclass.constructor.call(this,b)}e.mix(d,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{}});e.extend(d,m,{render:function(){var b=this.get("serverConfig"),f=this.getUploadType(this.get("type")),g=f.event,i;if(!f)return false;
this.set("urlsInput",this._renderUrlsInput());this._renderQueue();i=this._renderButton();this._restore();this.get("type")==d.type.FLASH&&e.mix(b,{swfUploader:i.get("swfUploader")});b=new f(b);b.on(g.SUCCESS,this._uploadCompleteHanlder,this);g.PROGRESS&&b.on(g.PROGRESS,this._uploadProgressHandler,this);b.on(g.STOP,this._uploadStopHanlder,this);this.set("uploadType",b);this.fire(d.event.RENDER);return this},upload:function(b){if(!e.isNumber(b))return false;var f=this.get("uploadType"),g=this.get("queue"),
i=g.get("files")[b],k;if(!e.isPlainObject(i)){e.log("[uploader]:队列中不存在id为"+b+"的文件");return false}if(this.get("curUploadIndex")!=""){alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！");return false}k=i.input.id||i.input;if(g.fileStatus(b).get("curType")==="error")return false;this.fire(d.event.START,{index:b,file:i});if(!this.get("isAllowUpload"))return false;this.set("curUploadIndex",b);g.fileStatus(b,d.status.START);f.upload(k)},cancel:function(b){var f=this.get("uploadType"),g=this.get("queue"),
i=d.status,k=g.fileStatus(b);if(e.isNumber(b)&&k!=i.SUCCESS)g.fileStatus(b,i.CANCEL);else{f.stop();this._continueUpload()}return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(b){if(!e.isString(b))b=d.status.WAITING;this.set("uploadFilesStatus",b);this._uploaderStatusFile(b);return this},_uploaderStatusFile:function(b){b=this.get("queue").getIndexs(b);if(!b.length){this.set("uploadFilesStatus","");this.fire(d.event.UPLOAD_FILES);return false}this.upload(b[0]);
return this},isSupportAjax:function(){var b=false;try{if(FormData)b=true}catch(f){b=false}return b},isSupportFlash:function(){var b=e.UA.fpv();return e.isArray(b)&&b.length>0},getUploadType:function(b){var f=this,g=d.type,i;if(b==g.AUTO)b=[g.AJAX,g.IFRAME];if(e.isArray(b)&&b.length>0)e.each(b,function(k){if(i=f._getType(k))return false});else i=f._getType(b);return i},_getType:function(b){var f=d.type,g=this.isSupportAjax(),i=this.isSupportFlash();switch(b){case f.IFRAME:f=h;break;case f.AJAX:f=g&&
c||false;break;case f.FLASH:f=i&&a||false;break;default:e.log("[uploader]:type参数不合法");return false}f&&e.log("[uploader]:使用"+b+"上传方式");this.set("type",b);return f},_renderButton:function(){var b=this.get("button");if(!e.isObject(b)){e.log("[uploader]:button参数不合法！");return false}b.on("change",this._select,this);b.render();return b},_renderQueue:function(){var b=this.get("queue"),f=this.get("urlsInput");if(!e.isObject(b)){e.log("[uploader]:queue参数不合法");return false}b.set("uploader",this);b.on(b.constructor.event.REMOVE,
function(g){f.remove(g.file.sUrl)});b.render();d.status=b.constructor.status;return b},_select:function(b){var f=this,g=f.get("autoUpload"),i=f.get("queue"),k=f.get("curUploadIndex"),o=b.files;e.each(o,function(n){if(!n.size)n.size=0;if(!n.name)n.name=n.fileName||"";n.input=b.input||n});f.fire(d.event.SELECT,{files:o});if(!f.get("isAllowUpload"))return false;i.add(o,function(){k==""&&g&&f.uploadFiles()})},_renderUrlsInput:function(){var b=this.get("button").get("target"),f=this.get("urlsInputName");
b=new j(b,{name:f});b.render();return b},_uploadCompleteHanlder:function(b){b=b.result;var f,g=d.event,i=this.get("queue"),k=this.get("curUploadIndex");if(!e.isObject(b))return false;i.updateFile(k,{result:b});f=Number(b.status);if(f===1){i.fileStatus(k,d.status.SUCCESS);this._success(b.data);this.fire(g.SUCCESS,{index:k,file:i.getFile(k),result:b})}else{i.fileStatus(k,d.status.ERROR,{msg:b.msg||b.message||""});this.fire(g.ERROR,{status:f,result:b})}this.set("curUploadIndex","");this.fire(g.COMPLETE,
{index:k,file:i.getFile(k),result:b});this._continueUpload()},_uploadStopHanlder:function(){var b=this.get("queue"),f=this.get("curUploadIndex");b.fileStatus(f,d.status.CANCEL);this.set("curUploadIndex","");this.fire(d.event.CANCEL,{index:f})},_continueUpload:function(){var b=this.get("uploadFilesStatus");b!=""&&this._uploaderStatusFile(b)},_uploadProgressHandler:function(b){var f=this.get("queue"),g=this.get("curUploadIndex"),i=f.getFile(g);e.mix(b,{file:i});f.fileStatus(g,d.status.PROGRESS,b);this.fire(d.event.PROGRESS,
b)},_success:function(b){if(!e.isObject(b))return false;b=b.url;var f=this.get("urlsInput"),g=this.get("curUploadIndex"),i=this.get("queue");if(!e.isString(b)||!e.isObject(f))return false;i.updateFile(g,{sUrl:b});f.add(b)},_restore:function(){var b=this.get("urlsInput").parse();b&&b.length>0&&this.get("queue").restore(b)}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:d.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:true},autoUpload:{value:true},
urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""}}});e.convertByteSize=function(b){var f=-1;do{b/=1024;f++}while(b>99);return Math.max(b,0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][f]};return d},{requires:["base","node","./urlsInput","./type/iframe","./type/ajax","./type/flash","flash"]});
KISSY.add("gallery/form/1.0/uploader/button/base",function(e,m,l){function j(c,a){a=e.merge({target:h(c)},a);j.superclass.constructor.call(this,a)}var h=m.all;e.mix(j,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(c){return c.replace(/.*(\/|\\)/,"")}});e.extend(j,l,{render:function(){var c=this.get("target");if(this.fire(j.event.beforeRender)===false){e.log("[AjaxUploader-Button] button render was prevented.");
return false}else{if(c==null){e.log("[AjaxUploader-Button] Cannot find target!");return false}this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(j.event.afterRender);return this}},show:function(){this.get("target").show();this.fire(j.event.afterShow);return j},hide:function(){this.get("target").hide();this.fire(j.event.afterHide);return j},reset:function(){var c=this.get("inputContainer");h(c).remove();this.set("inputContainer","");this.set("fileInput",
"");this._createInput();return this},_createInput:function(){var c=this.get("target"),a=this.get("name"),d=this.get("tpl");if(!e.isString(a)||!e.isString(d)){e.log("[AjaxUploader-Button] No name or tpl specified.");return false}a=e.substitute(d,{name:a});a=h(a);h(a).appendTo(c);c=h(a).children("input");h(c).on("change",this._changeHandler,this);this.set("fileInput",c);this.set("inputContainer",a);return a},_changeHandler:function(c){var a=this.get("fileInput"),d=h(a).val();c=c.target.files;var b=
[];if(d==""){e.log("[AjaxUploader-Button] No file selected.");return false}c?e.each(c,function(f){e.isObject(f)&&b.push({name:f.name,type:f.type,size:f.size})}):b.push({name:j.getFileName(d)});this.fire(j.event.CHANGE,{files:b,input:a.getDOMNode()});this.reset()},_setDisabled:function(c){var a=this.get("cls").disabled,d=this.get("target"),b=this.get("fileInput");if(!d.length||!e.isBoolean(c))return false;if(c){d.addClass(a);h(b).hide()}else{d.removeClass(a);h(b).show()}return c},_setMultiple:function(c){var a=
this.get("fileInput");if(!a.length)return false;c&&a.attr("multiple","multiple")||a.removeAttr("multiple");return c}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(c){this.get("fileInput")&&h(this.get("fileInput")).attr("name",c);return c}},disabled:{value:false,setter:function(c){this._setDisabled(c);return c}},
multiple:{value:true,setter:function(c){this._setMultiple(c);return c}},cls:{value:{disabled:"uploader-button-disabled"}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/button/swfButton",function(e,m,l,j){function h(a,d){d=e.merge({target:c(a)},d);h.superclass.constructor.call(this,d)}var c=m.all;e.mix(h,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});e.extend(h,l,{render:function(){var a=this,d=a.get("target"),b,f=a.get("multiple"),g=a.get("fileFilters");d.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
b=a._initSwfUploader();b.on("contentReady",function(){b.browse(f,g);a._bindBtnEvent();b.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(h.event.RENDER)},a)},_createSwfWrapper:function(){var a=this.get("target"),d=this.get("tpl"),b=this.get("swfWrapperId")!=""&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+e.guid();d=e.substitute(d,{id:b});this.set("swfWrapperId",b);return c(d).appendTo(a)},_initSwfUploader:function(){var a=this.get("flash"),d=this.get("swfWrapperId"),
b;try{b=new j(d,a);this.set("swfUploader",b)}catch(f){}return b},_bindBtnEvent:function(){var a=this,d=h.event,b=a.get("swfUploader");if(!b)return false;e.each(d,function(f){b.on(f,function(){a.fire(f)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),d=this.get("target");e.mix(a.attrs,{width:d.width(),height:d.height()});this.set("flash",a)},_changeHandler:function(a){this.fire(h.event.CHANGE,{files:a.fileList})},_setDisabled:function(a){var d=this.get("swfUploader"),b=this.get("cls").disabled,
f=this.get("target"),g=this.get("swfWrapper");if(!d||!e.isBoolean(a))return false;if(a){f.addClass(b);g.hide()}else{f.removeClass(b);g.show()}return a}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:true,setter:function(a){var d=this.get("swfUploader");d&&d.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var d=this.get("swfUploader");d&&
e.isArray(a)&&d.filter(a);return a}},disabled:{value:false,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.0/uploader/plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:true,btn:true}},swfUploader:{value:""}}});return h},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.0/uploader/index",function(e,m,l,j,h,c,a){function d(g,i,k){k=e.mix(e.parseConfig(g),k);d.superclass.constructor.call(this,k);this.set("buttonTarget",g);this.set("queueTarget",i);this.set("uploaderConfig",k);this._init()}var b=l.all,f={CONFIG:"data-config",BUTTON_CONFIG:"data-button-config",THEME_CONFIG:"data-theme-config",AUTH:"data-auth"};e.parseConfig=function(g,i){var k={},o,n=i||f.CONFIG;o=b(g).attr(n);if(!e.isString(o))return{};try{k=e.JSON.parse(o)}catch(p){e.log("[uploaderRender]:请检查"+
g+"上"+n+"属性内的json格式是否符合规范！")}return k};e.extend(d,m,{_init:function(){var g=this,i=g.get("uploaderConfig"),k=g._initButton(),o;g.set("button",k);g._initThemes(function(n){o=n.get("queue");e.mix(i,{button:k,queue:o});var p=new j(i);p.render();g.set("uploader",p);n.afterUploaderRender&&n.afterUploaderRender(p);g._auth();g.fire("init",{uploader:p})})},_initButton:function(){var g=this.get("buttonTarget"),i=e.parseConfig(g,f.BUTTON_CONFIG),k=this.get("name"),o=this.get("type");i=e.merge({name:k},i);return o!=
"flash"&&new h(g,i)||new c(g)},_initThemes:function(g){var i=this,k=i.get("theme"),o=i.get("buttonTarget"),n=e.parseConfig(o,f.THEME_CONFIG);e.use(k+"/index",function(p,q){var r=i.get("queueTarget");p.mix(n,{queueTarget:r});r=new q(n);g&&g.call(i,r)})},_auth:function(){var g=this.get("buttonTarget"),i=this.get("uploader");if(b(g).attr(f.AUTH)){g=e.parseConfig(g,f.AUTH);g=new a(i,{rules:g});i.set("auth",g)}}},{ATTRS:{theme:{value:"gallery/form/1.0/uploader/themes/default"},buttonTarget:{value:""},
queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""},auth:{value:""}}});return d},{requires:["base","node","./base","./button/base","./button/swfButton","./auth/base"]});
KISSY.add("gallery/form/1.0/uploader/plugins/ajbridge/ajbridge",function(e,m){function l(d,b,f){d=d.replace(j,"");b=m._normalize(b||{});var g=this;d=j+d;var i=function(k){if(k.status<1)g.fire("failed",{data:k});else{e.mix(g,k);if(!k.dynamic||!b.src)g.activate()}};b.id=b.id||e.guid(h);l.instances[b.id]=g;if(b.src){b.params.allowscriptaccess="always";b.params.flashvars=e.merge(b.params.flashvars,{jsEntry:a,swfID:b.id})}if(f)g.__args=[d,b,i];else e.later(m.add,c,false,m,[d,b,i])}var j="#",h="ks-ajb-",
c=100,a="KISSY.AJBridge.eventHandler";e.app(l,{version:"1.0.15",instances:{},eventHandler:function(d,b){var f=l.instances[d];f&&f.__eventHandler(d,b)},augment:function(d,b){if(e.isString(b))b=[b];e.isArray(b)&&e.each(b,function(f){d.prototype[f]=function(){try{return this.callSWF(f,e.makeArray(arguments))}catch(g){this.fire("error",{message:g})}}})}});e.augment(l,e.EventTarget,{init:function(){if(this.__args){m.add.apply(m,this.__args);this.__args=null;delete this.__args}},__eventHandler:function(d,
b){var f=b.type;b.id=d;switch(f){case "log":e.log(b.message);break;default:this.fire(f,b)}},callSWF:function(d,b){b=b||[];try{if(this.swf[d])return this.swf[d].apply(this.swf,b)}catch(f){var g="";if(b.length!==0)g="'"+b.join("','")+"'";return(new Function("self","return self.swf."+d+"("+g+");"))(this)}}});l.augment(l,["activate","getReady","getCoreVersion"]);return window.AJBridge=e.AJBridge=l},{requires:["flash"]});
KISSY.add("gallery/form/1.0/uploader/plugins/ajbridge/uploader",function(e,m,l){function j(h,c){c=c||{};var a={};e.each(["ds","dsp","btn","hand"],function(d){if(d in c)a[d]=c[d]});c.params=c.params||{};c.params.flashvars=e.merge(c.params.flashvars,a);j.superclass.constructor.call(this,h,c)}e.extend(j,l);l.augment(j,["setFileFilters","filter","setAllowMultipleFiles","multifile","browse","upload","uploadAll","cancel","getFile","removeFile","lock","unlock","setBtnMode","useHand","clear"]);j.version=
"1.0.1";l.Uploader=j;return l.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add("gallery/form/1.0/uploader/plugins/preview/preview",function(e,m){function l(f,g){if(!f)return false;if(a!="filter")f.src=g||b;else{f.src=b;if(g){g=g.replace(/[)'"%]/g,function(i){return escape(escape(i))});f.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src=\""+g+'")';f.zoom=1}}return true}function j(f){this.config=e.mix({maxWidth:40,maxHeight:40},f);e.log(c+"Preview initialized. The preview mode is "+a)}var h=document,c="[Plugin: Preview] ",a=function(){var f=
"";if(typeof window.FileReader==="undefined")switch(e.UA.shell){case "firefox":f="domfile";break;case "ie":switch(e.UA.ie){case 6:f="simple";break;default:f="filter"}}else f="html5";return f}(),d={check:"check",success:"success",showed:"showed",error:"error"},b=e.UA.ie<8?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";e.augment(j,e.EventTarget,{preview:function(f,g){f=m.get(f);g=m.get(g);var i=this,k=function(){i.fire(d.getData,
{data:i.data,mode:a});if(g){l(g,i.data);i.fire(d.showed,{img:g})}};i.data=undefined;if(f){e.log(c+"One file selected. Getting data...");switch(a){case "domfile":i.data=f.files[0].getAsDataURL();break;case "filter":f.select();try{i.data=h.selection.createRange().text}catch(o){e.log(c+"Get image data error, the error is: ");e.log(o,"dir")}finally{h.selection.empty()}if(!i.data)i.data=f.value;break;case "html5":var n=new FileReader;n.onload=function(p){i.data=p.target.result;k()};n.onerror=function(){e.log(c+
"File Reader Error. Your browser may not fully support html5 file api","warning");i.fire(d.error)};n.readAsDataURL(f.files[0]);break;default:i.data=f.value}if(i.data)k();else if(a!="html5"){e.log(c+"Retrive Data error.");l(g);i.fire(d.error)}}else e.log(c+"File Input Element does not exists.");return i.data}});return j},{requires:["dom","event"]});
KISSY.add("gallery/form/1.0/uploader/plugins/progressBar/progressBar",function(e,m,l){function j(c,a){a=e.merge({wrapper:h(c)},a);j.superclass.constructor.call(this,a)}var h=m.all;e.mix(j,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});e.extend(j,l,{render:function(){var c=this.get("wrapper"),a=this.get("width");if(!c.length)return false;
c.addClass(j.cls.PROGRESS_BAR).width(a);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(j.event.RENDER)},show:function(){var c=this;c.get("wrapper").fadeIn(c.get("duration"),function(){c.set("visible",true);c.fire(j.event.SHOW,{visible:true})})},hide:function(){var c=this;c.get("wrapper").fadeOut(c.get("duration"),function(){c.set("visible",false);c.fire(j.event.HIDE,{visible:false})})},_create:function(){var c=this.get("wrapper"),a=this.get("value"),d=this.get("tpl");
a=e.substitute(d,{value:a});c.html("");return h(a).appendTo(c)},_addAttr:function(){var c=this.get("wrapper"),a=this.get("value");c.attr("role","progressbar");c.attr("aria-valuemin",0);c.attr("aria-valuemax",100);c.attr("aria-valuenow",a);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(c){var a=this,d=a.get("wrapper"),b=a.get("bar"),f=a.get("speed"),g;if(c>100)c=100;if(c<0)c=0;g=d.width()*(c/100);b.animate({width:g+"px"},f,"none",function(){d.attr("aria-valuenow",
c);b.attr("data-value",c);a.fire(j.event.CHANGE,{value:c,width:g})});return c}},visible:{value:true},duration:{value:0.3},tpl:{value:j.tpl.DEFAULT},speed:{value:0.2}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/queue/base",function(e,m,l,j){function h(a,d){h.superclass.constructor.call(this,d);this.set("target",c(a))}var c=m.all;e.mix(h,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{RENDER:"render",ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"fileStatus",UPDATE_FILE:"updateFile",RESTORE:"restore"},
status:j.type,cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});e.extend(h,l,{render:function(){this.get("target").addClass(h.cls.QUEUE);this.fire(h.event.RENDER);return this},add:function(a,d){var b=this,f=h.event;if(a.length>0){b._addFiles(a,function(){d&&d.call(b);b.fire(f.ADD_FILES,{files:a})});return false}else return b._addFile(a,function(g,i){d&&d.call(b,g,i)})},_addFile:function(a,d){if(!e.isObject(a)){e.log("[uploader-queue]:_addFile()参数file不合法！");return false}var b=
this,f=b.get("duration"),g=b._setAddFileData(a),i=b.getFileIndex(g.id);b.fileStatus(i,h.status.WAITING);g.target.fadeIn(f,function(){b.fire(h.event.ADD,{index:i,file:g,target:g.target});d&&d.call(b,i,g)});return g},_addFiles:function(a,d){function b(g){if(g===a.length){d&&d.call(this);return false}f._addFile(a[g],function(){g++;b(g)})}if(!a.length){e.log("[uploader-queue]:_addFiles()参数files不合法！");return false}var f=this;b(0)},remove:function(a,d){var b=this,f=b.get("files"),g,i,k=b.get("duration");
if(e.isString(a))a=b.getFileIndex(a);g=f[a];if(!e.isObject(g)){e.log("[uploader-queue]:remove()不存在index为"+a+"的文件数据");return false}i=g.target;i.fadeOut(k,function(){i.remove();b.fire(h.event.REMOVE,{index:a,file:g});d&&d.call(b,a,g)});f=e.filter(f,function(o,n){return n!==a});b.set("files",f);return g},clear:function(){function a(){b=d.get("files");if(!b.length){d.fire(h.event.CLEAR);return false}d.remove(0,function(){a()})}var d=this,b;a()},restore:function(a){var d=this,b=[];a&&a.length>0&&e.each(a,
function(f,g){var i=f.split("|"),k="";if(i.length>1){f=i[1];k=i[0]}if(f){i=d._setAddFileData({input:null,name:k,sUrl:f,size:"",type:""});g=d.getFileIndex(i.id);d.fileStatus(g,h.status.RESTORE);c(i.target).show();i.status.set("curType",h.status.SUCCESS);b[g]=i}});d.fire(h.event.RESTORE,{files:b})},fileStatus:function(a,d,b){if(!e.isNumber(a))return false;var f=this.getFile(a);if(!e.isPlainObject(f))return false;f=f.status;d&&f.change(d,b);this.fire(h.event.FILE_STATUS,{index:a,status:d});return f},
getFile:function(a){if(!e.isNumber(a))return false;a=this.get("files")[a];e.isPlainObject(a)||(a=false);return a},getFileIndex:function(a){var d=this.get("files"),b=-1;e.each(d,function(f,g){if(f.id==a){b=g;return true}});return b},updateFile:function(a,d){if(!e.isNumber(a))return false;if(!e.isObject(d)){e.log("[uploader-queue]:updateFile()的data参数有误！");return false}var b=this.get("files"),f=this.getFile(a);if(!f)return false;e.mix(f,d);b[a]=f;this.set("files",b);this.fire(h.event.UPDATE_FILE,{index:a,
file:f});return f},getIndexs:function(a){var d=this.get("files"),b,f=[];if(!d.length)return f;e.each(d,function(g,i){if(e.isObject(g)){b=g.status;b.get("curType")==a&&f.push(i)}});return f},getFiles:function(a){var d=this.get("files"),b,f=[];if(!d.length)return[];e.each(d,function(g){if(g){b=g.status;b.get("curType")==a&&f.push(g)}});return f},_setAddFileData:function(a){var d=this.get("files"),b=this.get("uploader");if(!e.isObject(a)){e.log("[uploader-queue]:_updateFileData()参数file不合法！");return false}if(!a.id)a.id=
e.guid(h.FILE_ID_PREFIX);if(a.size)a.textSize=j.convertByteSize(a.size);a.target=this._appendFileHtml(a);a.status=this._renderStatus(a);e.isObject(b)&&a.status.set("uploader",b);d.push(a);return a},_appendFileHtml:function(a){var d=this.get("target"),b=this.get("tpl");b=e.substitute(b,a);return c(b).hide().appendTo(d).data("data-file",a)},_renderStatus:function(a){var d=a.target,b=h.hook.STATUS,f=this.get("statusConfig");if(!d.length)return false;d=d.children(b);e.mix(f,{queue:this,file:a});return new j(d,
f)}},{ATTRS:{tpl:{value:h.tpl.DEFAULT},duration:{value:0.3},target:{value:""},files:{value:[]},statusConfig:{value:{}},uploader:{value:""}}});return h},{requires:["node","base","./status"]});
KISSY.add("gallery/form/1.0/uploader/queue/status",function(e,m,l,j){function h(a,d){d=e.merge({target:c(a)},d);h.superclass.constructor.call(this,d)}var c=m.all;e.mix(h,{type:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},convertByteSize:function(a){var d=-1;do{a/=1024;d++}while(a>99);return Math.max(a,0.1).toFixed(1)+["kB","MB","GB","TB","PB","EB"][d]}});e.extend(h,l,{change:function(a,d){if(!e.isString(a))return false;var b;
if(!this.isSupport(a)){e.log("[queue-status]:status参数为"+a+"，不支持的状态类型");return false}d||(d={});(b=this["_"+a])&&b.call(this,d);this.set("curType",a);return this},isSupport:function(a){if(!e.isString(a))return false;var d=false;e.each(h.type,function(b){if(a==b)return d=true});return d},_changeDom:function(a){var d=this.get("target");d.html("");return c(a).appendTo(d)},_waiting:function(){var a=this.get("tpl").waiting,d=this.get("uploader"),b=this.get("queue"),f=this.get("file").id,g=b.getFileIndex(f);
this._changeDom(a).children(".J_Upload").on("click",function(i){i.preventDefault();if(!e.isObject(d))return false;d.upload(g)})},_start:function(){var a=this.get("tpl").start,d=this.get("target"),b=this.get("uploader"),f=b.get("type");if(!e.isString(a))return false;a=this._changeDom(a);a.children(".J_UploadCancel").on("click",function(g){g.preventDefault();if(!e.isObject(b))return false;b.cancel()});if(f=="ajax"||f=="flash"){f=a.children(".J_ProgressBar");f=new j(f);f.render();this.set("progressBar",
f)}d.parent().addClass("current-upload-file")},_progress:function(a){a=Math.ceil(a.loaded/a.total)*100;var d=this.get("progressBar");if(!d)return false;d.set("value",a)},_success:function(){var a=this,d=a.get("tpl").success,b=a.get("target"),f=a.get("queue"),g=a.get("file").id,i=a.get("progressBar"),k=a.get("target"),o,n,p;if(!e.isString(d))return false;e.isObject(i)&&i.set("value",100);e.later(function(){if(e.isObject(i))n=k.children().children(".J_ProgressBar").clone(true);o=a._changeDom(d);n&&
o.prepend(n);p=o.children(".J_FileDel");p.on("click",function(q){q.preventDefault();f.remove(g)})},300);b.parent().removeClass("current-upload-file")},_restore:function(){this._success()},_cancel:function(){var a=this.get("tpl").cancel,d=this.get("uploader");a=this._changeDom(a).children(".J_ReUpload");var b=this.get("file").id;a.on("click",function(f){f.preventDefault();if(!e.isObject(d))return false;d.upload(b)})},_error:function(a){e.isObject(a)||(a={msg:"文件上传失败！"});var d=this.get("tpl").error;
a=this._changeDom(e.substitute(d,a)).children(".J_FileDel");var b=this.get("queue"),f=this.get("file").id;a.on("click",function(g){g.preventDefault();b.remove(f)})}},{ATTRS:{target:{value:""},tpl:{value:{waiting:'<div class="waiting-status">等待上传，<a href="#Upload" class="J_Upload">点此上传</a> </div>',start:'<div class="start-status clearfix"><div class="f-l  J_ProgressBar uploader-progress"><img class="loading" src="http://img01.taobaocdn.com/tps/i1/T1F5tVXjRfXXXXXXXX-16-16.gif" alt="loading" /></div> <a class="f-l J_UploadCancel upload-cancel" href="#uploadCancel">取消</a></div> ',
success:' <div class="success-status"><a href="#fileDel" class="J_FileDel">删除</a></div>',cancel:'<div class="cancel-status">已经取消上传，<a href="#reUpload" class="J_ReUpload">点此重新上传</a> </div>',error:'<div class="error-status upload-error">{msg}<a href="#fileDel" class="J_FileDel">删除</a></div>'}},queue:{value:""},uploader:{value:""},file:{value:{}},curType:{value:""},progressBar:{value:""}}});return h},{requires:["node","base","../plugins/progressBar/progressBar"]});
KISSY.add("gallery/form/1.0/uploader/type/ajax",function(e,m,l){function j(c){j.superclass.constructor.call(this,c);this._setFormData()}var h=m.all;e.mix(j,{event:e.merge(l.event,{PROGRESS:"progress"})});e.extend(j,l,{upload:function(c){if(!c){e.log("[uploader-AjaxType]:upload()，fileInput参数有误！");return false}var a=c.files;if(!a.length){e.log("[uploader-AjaxType]:upload()，不存在要上传的文件！");return false}this._addFileData(c,a[0]);this.send();return this},stop:function(){var c=this.get("xhr");if(!e.isObject(c)){e.log("[uploader-AjaxType]:stop()，io值错误！");
return false}c.abort();this.fire(j.event.STOP);return this},send:function(){var c=this,a=c.get("action"),d=c.get("formData"),b=new XMLHttpRequest;b.upload.addEventListener("progress",function(f){c.fire(j.event.PROGRESS,{loaded:f.loaded,total:f.total})});b.onload=function(){var f={};try{f=e.JSON.parse(b.responseText)}catch(g){e.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}c.fire(j.event.SUCCESS,{result:f})};b.open("POST",a,true);b.send(d);c._setFormData();c.set("xhr",b);return c},_setFormData:function(){try{this.set("formData",
new FormData);this._processData()}catch(c){e.log("[uploader-AjaxType]:something error when reset FormData.");e.log(c,"dir")}},_processData:function(){var c=this.get("data"),a=this.get("formData");e.each(c,function(d,b){a.append(b,d)});this.set("formData",a)},_addFileData:function(c,a){if(!e.isObject(a)){e.log("[uploader-AjaxType]:_addFileData()，file参数有误！");return false}var d=this.get("formData"),b=this.get("fileDataName");if(b==""){b=h(c).attr("name");this.set("fileDataName",b)}d.append(b,a);this.set("formData",
d)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:false,cache:false,dataType:"json",contentType:false}},xhr:{value:""},fileDataName:{value:""},form:{value:{}},fileInput:{value:""}}});return j},{requires:["node","./base"]});
KISSY.add("gallery/form/1.0/uploader/type/base",function(e,m,l){function j(h){j.superclass.constructor.call(this,h)}e.mix(j,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});e.extend(j,l,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return j},{requires:["node","base"]});
KISSY.add("gallery/form/1.0/uploader/type/flash",function(e,m,l){function j(h){j.superclass.constructor.call(this,h);this._init()}e.mix(j,{event:e.merge(l.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});e.extend(j,l,{_init:function(){var h=this,c=h.get("swfUploader");if(!c){e.log("[uploader-FlashType]:swfUploader对象为空！");return false}c.on("contentReady",function(){h.fire(j.event.SWF_READY)},h);c.on("uploadStart",h._uploadStartHandler,h);c.on("uploadProgress",h._uploadProgressHandler,h);c.on("uploadCompleteData",
h._uploadCompleteDataHandler,h);c.on("uploadError",h._uploadErrorHandler,h)},upload:function(h){var c=this.get("swfUploader"),a=this.get("action"),d=this.get("data");this.set("uploadingId",h);c.upload(h,a,"POST",d);return this},stop:function(){var h=this.get("swfUploader"),c=this.get("uploadingId");if(c!=""){h.cancel(c);this.fire(j.event.STOP,{id:c})}return this},_uploadStartHandler:function(h){this.fire(j.event.START,{file:h.file})},_uploadProgressHandler:function(h){e.mix(h,{loaded:h.bytesLoaded,
total:h.bytesTotal});this.fire(j.event.PROGRESS,{loaded:h.loaded,total:h.total})},_uploadCompleteDataHandler:function(h){var c;try{c=JSON.parse(h.data)}catch(a){e.log("[uploader-FlashType]:json数据格式不合法！");this.fire(j.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(j.event.SUCCESS,{result:c})},_uploadErrorHandler:function(h){this.set("uploadingId","");this.fire(j.event.ERROR,{msg:h.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return j},{requires:["node","./base"]});
KISSY.add("gallery/form/1.0/uploader/type/iframe",function(e,m,l){function j(c){j.superclass.constructor.call(this,c)}var h=m.all;e.mix(j,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:e.mix(l.event,{CREATE:"create",REMOVE:"remove"})});
e.extend(j,l,{upload:function(c){c=h(c);if(!c.length)return false;this.fire(j.event.START,{input:c});this.set("fileInput",c);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(j.event.STOP);this.fire(j.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(c){if(!e.isObject(c)||e.isEmptyObject(c)){e.log("[uploader-iframeType]:data参数不是对象或者为空！");return false}var a="",d=this.get("tpl").HIDDEN_INPUT;
if(!e.isString(d))return false;for(var b in c)a+=e.substitute(d,{name:b,value:c[b]});return a},_createIframe:function(){var c=this.get("id"),a=this.get("tpl"),d=a.IFRAME,b=this.get("iframe");if(!e.isEmptyObject(b))return b;if(!e.isString(d)){e.log("[uploader-iframeType]:iframe的模板不合法！");return false}if(!e.isString(c)){e.log("[uploader-iframeType]:id必须存在且为字符串类型！");return false}c=e.substitute(a.IFRAME,{id:c});c=h(c);c.on("load",this._iframeLoadHandler,this);h("body").append(c);this.set("iframe",c);return c},
_iframeLoadHandler:function(c){var a=c.target;c=j.event.ERROR;a=a.contentDocument||window.frames[a.id].document;if(!a||!a.body){this.fire(c,{msg:"服务器端返回数据有问题！"});return false}a=a.body.innerHTML;e.log("[uploader-iframeType]:服务器端输出:"+a);if(a=="")return false;try{a=JSON.parse(a)}catch(d){e.log("[uploader-iframeType]:json数据格式不合法！");this.fire(c,{msg:"数据："+a+"不是合法的json数据"})}this.fire(j.event.SUCCESS,{result:a});this._remove()},_createForm:function(){var c=this.get("id"),a=this.get("tpl").FORM,d=this.get("data"),
b=this.get("action"),f=this.get("fileInput"),g="";if(!e.isString(a)){e.log("[uploader-iframeType]:form模板不合法！");return false}if(!e.isObject(d)){e.log("[uploader-iframeType]:data参数不合法！");return false}if(!e.isString(b)){e.log("[uploader-iframeType]:action参数不合法！");return false}d=this.dataToHidden(d);if(d=="")return false;g=e.substitute(a,{action:b,target:c,hiddenInputs:d});c=h(g).append(f);h("body").append(c);this.set("form",c);return c},_create:function(){var c=this._createIframe(),a=this._createForm();
this.fire(j.event.CREATE,{iframe:c,form:a})},_remove:function(){var c=this.get("form");this.get("iframe");c.remove();this.reset("form");this.fire(j.event.REMOVE,{form:c})}},{ATTRS:{tpl:{value:j.tpl},id:{value:"ks-uploader-iframe-"+e.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return j},{requires:["node","./base"]});
KISSY.add("gallery/form/1.0/uploader/urlsInput",function(e,m,l){function j(c,a){j.superclass.constructor.call(this,a);this.set("wrapper",h(c))}var h=m.all;e.mix(j,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});e.extend(j,l,{render:function(){var c=this.get("wrapper"),a=this.get("name");a=document.getElementsByName(a)[0];if(!e.isObject(c)){e.log("[uploader-urlsInput]:container参数不合法！");return false}if(a){e.log("[uploader-urlsInput]:urls input found");this.set("input",h(a))}else this._create()},
add:function(c){if(!e.isString(c)){e.log("[uploader-urlsInput]:add()的url参数不合法！");return false}var a=this.get("urls"),d=this.isExist(c);if(a[0]=="")a=[];if(d){e.log("[uploader-urlsInput]:add()，文件路径已经存在！");return this}a.push(c);this.set("urls",a);this._val();return this},remove:function(c){if(!c)return false;var a=this.get("urls"),d=this.isExist(c),b=RegExp(c);if(!d){e.log("[uploader-urlsInput]:remove()，不存在该文件路径！");return false}a=e.filter(a,function(f){return!b.test(f)});this.set("urls",a);this._val();
return a},parse:function(){var c=this.get("input");if(c){c=h(c).val();var a=this.get("split");c=c.split(a);this.set("urls",c);return c}else{e.log("[uploader-urlsInput]:cannot find urls input.");return[]}},_val:function(){var c=this.get("urls"),a=this.get("input"),d=this.get("split");c=c.join(d);a.val(c);return c},isExist:function(c){var a=false,d=this.get("urls"),b=RegExp(c);if(!d.length)return false;e.each(d,function(f){if(b.test(f))return a=true});return a},_create:function(){var c=this.get("wrapper"),
a=this.get("tpl"),d=this.get("name"),b=this.get("urls");if(!c||c.length<=0){e.log("[uploader-urlsInput]:UrlsInput container not specified!","warn");return false}if(!e.isString(a)||!e.isString("name")){e.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！");return false}a=h(e.substitute(a,{name:d,value:b}));c.append(a);this.set("input",a);e.log("[uploader-urlsInput]:input created.");return a}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:j.TPL},split:{value:",",setter:function(c){this._val();
return c}},input:{value:""},wrapper:{value:""}}});return j},{requires:["node","base"]});
