KISSY.add("gallery/mustache/1.0/index",function(h,g){return g},{requires:["./mustache"]});
KISSY.add("gallery/mustache/1.0/mustache",function(){return function(){var h={},g=function(){};g.prototype={otag:"{{",ctag:"}}",pragmas:{},buffer:[],pragmas_implemented:{"IMPLICIT-ITERATOR":!0},context:{},render:function(a,b,c,d){d||(this.context=b,this.buffer=[]);if(this.includes("",a)){var a=this.render_pragmas(a),e=this.render_section(a,b,c);!1===e&&(e=this.render_tags(a,b,c,d));if(d)return e;this.sendLines(e)}else{if(d)return a;this.send(a)}},send:function(a){""!==a&&this.buffer.push(a)},sendLines:function(a){if(a)for(var a=
a.split("\n"),b=0;b<a.length;b++)this.send(a[b])},render_pragmas:function(a){if(!this.includes("%",a))return a;var b=this,c=this.getCachedRegex("render_pragmas",function(a,b){return RegExp(a+"%([\\w-]+) ?([\\w]+=[\\w]+)?"+b,"g")});return a.replace(c,function(a,c,i){if(!b.pragmas_implemented[c])throw{message:"This implementation of mustache doesn't understand the '"+c+"' pragma"};b.pragmas[c]={};i&&(a=i.split("="),b.pragmas[c][a[0]]=a[1]);return""})},render_partial:function(a,b,c){a=this.trim(a);if(!c||
void 0===c[a])throw{message:"unknown_partial '"+a+"'"};return"object"!=typeof b[a]?this.render(c[a],b,c,!0):this.render(c[a],b[a],c,!0)},render_section:function(a,b,c){if(!this.includes("#",a)&&!this.includes("^",a))return!1;var d=this,e=this.getCachedRegex("render_section",function(a,b){return RegExp("^([\\s\\S]*?)"+a+"(\\^|\\#)\\s*(.+)\\s*"+b+"\n*([\\s\\S]*?)"+a+"\\/\\s*\\3\\s*"+b+"\\s*([\\s\\S]*)$","g")});return a.replace(e,function(a,e,g,f,j,k){var a=e?d.render_tags(e,b,c,!0):"",k=k?d.render(k,
b,c,!0):"",l,f=d.find(f,b);"^"===g?l=!f||d.is_array(f)&&0===f.length?d.render(j,b,c,!0):"":"#"===g&&(l=d.is_array(f)?d.map(f,function(a){return d.render(j,d.create_context(a),c,!0)}).join(""):d.is_object(f)?d.render(j,d.create_context(f),c,!0):"function"===typeof f?f.call(b,j,function(a){return d.render(a,b,c,!0)}):f?d.render(j,b,c,!0):"");return a+l+k})},render_tags:function(a,b,c,d){for(var e=this,i=function(){return e.getCachedRegex("render_tags",function(a,b){return RegExp(a+"(=|!|>|\\{|%)?([^\\/#\\^]+?)\\1?"+
b+"+","g")})},g=i(),h=function(a,d,f){switch(d){case "!":return"";case "=":return e.set_delimiters(f),g=i(),"";case ">":return e.render_partial(f,b,c);case "{":return e.find(f,b);default:return e.escape(e.find(f,b))}},a=a.split("\n"),f=0;f<a.length;f++)a[f]=a[f].replace(g,h,this),d||this.send(a[f]);if(d)return a.join("\n")},set_delimiters:function(a){a=a.split(" ");this.otag=this.escape_regex(a[0]);this.ctag=this.escape_regex(a[1])},escape_regex:function(a){arguments.callee.sRE||(arguments.callee.sRE=
RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)","g"));return a.replace(arguments.callee.sRE,"\\$1")},find:function(a,b){function c(a){return!1===a||0===a||a}var a=this.trim(a),d;if(a.match(/([a-z_]+)\./ig)){var e=this.walk_context(a,b);c(e)&&(d=e)}else c(b[a])?d=b[a]:c(this.context[a])&&(d=this.context[a]);return"function"===typeof d?d.apply(b):void 0!==d?d:""},walk_context:function(a,b){for(var c=a.split("."),d=void 0!=b[c[0]]?b:this.context,e=d[c.shift()];void 0!=e&&0<c.length;)d=
e,e=e[c.shift()];return"function"===typeof e?e.apply(d):e},includes:function(a,b){return-1!=b.indexOf(this.otag+a)},escape:function(a){return(""+(null===a?"":a)).replace(/&(?!\w+;)|["'<>\\]/g,function(a){switch(a){case "&":return"&amp;";case '"':return"&quot;";case "'":return"&#39;";case "<":return"&lt;";case ">":return"&gt;";default:return a}})},create_context:function(a){if(this.is_object(a))return a;var b=".";this.pragmas["IMPLICIT-ITERATOR"]&&(b=this.pragmas["IMPLICIT-ITERATOR"].iterator);var c=
{};c[b]=a;return c},is_object:function(a){return a&&"object"==typeof a},is_array:function(a){return"[object Array]"===Object.prototype.toString.call(a)},trim:function(a){return a.replace(/^\s*|\s*$/g,"")},map:function(a,b){if("function"==typeof a.map)return a.map(b);for(var c=[],d=a.length,e=0;e<d;e++)c.push(b(a[e]));return c},getCachedRegex:function(a,b){var c=h[this.otag];c||(c=h[this.otag]={});var d=c[this.ctag];d||(d=c[this.ctag]={});(c=d[a])||(c=d[a]=b(this.otag,this.ctag));return c}};return{name:"mustache.js",
version:"0.4.0-dev",to_html:function(a,b,c,d){var e=new g;d&&(e.send=d);e.render(a,b||{},c);if(!d)return e.buffer.join("\n")}}}().to_html});
