KISSY.add("gallery/grid/1.0/bar",function(a,m){function h(a){a=a||{};h.superclass.constructor.call(this,a);this._init()}var e=a.DOM,b=a.Node;a.extend(h,a.Base);a.augment(h,{CLS_BAR:"",_findItem:function(a){return e.hasClass(a,"bar-btn-container")?a:e.parent(a,".bar-btn-container")},_getBarTemplate:function(){return"<div></div>"},_init:function(){for(var b=this.get("items"),e=this.get("defaults"),g=null,l=null,i=0,f=b.length;i<f;i++)if(g=a.merge(e,b[i]),a.isUndefined(g.id)&&(g.id=i),!g.isBarItem)(l=
m.types[g.type||"text"])||(l=m.types.text),b[i]=new l(g);this._initDOM();this._initEvent()},_initDOM:function(){var d=this._getBarTemplate(),h=this.get("renderTo"),h=e.get("#"+h),g=this.get("items"),d=(new b(d)).appendTo(h),l=(new b('<table style="border-spacing: 0;"><tr></tr></table>')).appendTo(d),i=e.get("tr",l[0]);this.set("bar",d);a.each(g,function(f,c){var k=i.insertCell(c);f.renderTo(k)});e.addClass(h,this.CLS_BAR);e.show(h)},_initEvent:function(){var b=this.get("items");a.each(b,function(a){a.attachEvent()})}});
return h},{requires:["./barItem"]});
KISSY.add("gallery/grid/1.0/barItem",function(a){function m(a){a+="";return a.charAt(0).toUpperCase()+a.substring(1)}function h(g){g=a.merge({isBarItem:!0,css:""},g);a.mix(this,g);h.superclass.constructor.call(this,g);this._init()}function e(a){e.superclass.constructor.call(this,a)}function b(a){b.superclass.constructor.call(this,a)}function d(a){d.superclass.constructor.call(this,a)}function j(a){j.superclass.constructor.call(this,a)}function g(a){g.superclass.constructor.call(this,a)}a.extend(h,
a.Base);a.augment(h,{attachEvent:function(){var a=this.get("el");if(a&&this.handler)a.on("click",this.handler)},renderTo:function(g){if(this.get("el"))return this.get("el");var b=this._getItemTemplate(),g=(new a.Node(b)).appendTo(g);this.set("el",g);return g},_bindUI:function(){var a=this,g=a.__attrs,f,c;for(f in g)g.hasOwnProperty(f)&&(a.on("after"+m(f)+"Change",function(c){a[f]=c.newVal}),c="_uiSet"+m(f),a[c]&&function(c,f){a.on("after"+m(c)+"Change",function(c){a[f](c.newVal,c)})}(f,c))},_getItemTemplate:function(){return""},
_init:function(){this._bindUI()},destroy:function(){this.get("el").remove();this.detach();this.__attrVals={}}});a.extend(e,h);a.augment(e,{attachEvent:function(){var a=this.get("el");this.constructor.superclass.attachEvent.call(this);if(a)a.on("mouseover",function(){a.hasClass("lp-item-disabled")||a.addClass("bar-item-over")}).on("mouseout",function(){a.removeClass("bar-item-over")})},_getItemTemplate:function(){return['<div id="',this.id,'" class="bar-btn-container ',this.disabled?"lp-item-disabled":
""," ",this.containerCss,'"><button class="bar-item-btn ',this.css,'" autocomplete="off" hidefocus="true" ',this.disabled?'disabled="disabled"':"",' type="button">',this.text,"</button></div>"].join("")},_uiSetDisabled:function(a){var g=this.get("el"),f=g.one("button");a?(g.addClass("lp-item-disabled"),f.attr("disabled",""),g.removeClass("bar-item-over")):(g.removeClass("lp-item-disabled"),f.removeAttr("disabled"))}});a.extend(b,h);a.augment(b,{_getItemTemplate:function(){return['<div id="',this.id,
'"  class="pb-text-container',this.css,'">',this.text,"</div>"].join("")}});a.extend(d,h);a.augment(d,{_getItemTemplate:function(){return'<div class="bar-item-separator"></div>'}});a.extend(j,h);a.augment(j,{_getItemTemplate:function(){return['<div id="',this.id,'"  class="pb-text-container"><a class="',this.css,'" href = "',this.href,'">',this.text,"</a></div>"].join("")}});a.extend(g,h);a.augment(g,{_getItemTemplate:function(){return a.substitute(this.template,this)}});h.types={button:e,text:b,
link:j,custom:g,seperator:d};return h},{requires:[]});KISSY.add("gallery/grid/1.0/buttonBar",function(a,m){function h(a){a=this._formatConfig(a||{});h.superclass.constructor.call(this,a)}a.extend(h,m);a.augment(h,{CLS_BAR:"button-bar",_formatConfig:function(e){var b={renderTo:e.renderTo,items:[]};a.each(e.buttons||e.items,function(d){d=a.merge({type:"button"},d);b.items.push(d)});return b}});return h},{requires:["./bar"]});
KISSY.add("gallery/grid/1.0/calendar",function(a,m){var h=function(a,b){var d=new Date(b-0+864E5*a),d=d.getFullYear()+"/"+(d.getMonth()+1)+"/"+d.getDate();return new Date(d)};return function(e){var b=a.DOM,d=a.Event,j={};a.each(e,function(g){if(b.get(g.selector)){var l=a.one(g.selector);l.hasAttr("readonly")&&l.removeAttr("readonly");l.hasClass("ks-select-calendar")||l.addClass("ks-select-calendar");g.showTime&&(l.hasClass("calendar-time")||l.addClass("calendar-time"));var i,l=g.showTime?"timeSelect":
"select",f=g.showTime?"yyyy-mm-dd HH:MM:ss":"yyyy-mm-dd";i=g.min?h(g.min,new Date):0==g.min?new Date:null;var c=g.max?h(g.max,new Date):0==g.max?new Date:null;if(g.config)i=new m(g.selector,g.config);else{var k=Date.parse(b.val(g.selector).replace(/\-/g,"/"));i=new m(g.selector,{minDate:i,maxDate:c,selected:k?new Date(k):null,showTime:g.showTime,popup:!0,triggerType:["click"]})}i.on(l,function(c){var a=b.get(g.selector);b.val(a,m.Date.format(c.date,f));this.hide();a.focus()});d.on(g.selector,"valuechange",
function(c){8==c.keyCode||46==c.keyCode||b.val(this,"")});j[g.selector]=i}});return j}},{requires:["calendar","calendar/assets/base.css"]});
KISSY.add("gallery/grid/1.0/editGrid",function(a,m,h){function e(a){e.superclass.constructor.call(this,a)}var b=a.DOM,d=a.UA,j=a.Node;a.extend(e,m,{clearError:function(){this.get("showError");this.cancelEdit()},cancelEdit:function(){var g=this.get("columns");a.each(g,function(a){(a=a.editor)&&!a.isHide()&&a.hide()})},hasError:function(){var g=!1,b=null,b=null;this.get("showError")&&(b=this.get("tbody"),g=!!a.one(b).one(".grid-error-cell"));g||(b=this.get("columns"),a.each(b,function(a){if((a=a.editor)&&
!a.isHide()&&a.hasError()){g=true;return false}}));return g},setCellToEdit:function(a,d){var i=this._getCell(a,d),f=this._getEditor(d);b.hasClass(i,"grid-editable-cell")&&this._showEditor(f,i,a[d],a)},_attachEditEvent:function(a){var b=this,d=a.editor;d.on("change",b._getChangeEvent(a));d.on("hide",function(){b.set("editRecord",null);b.set("editor",null)})},_getChangeEvent:function(a){var b=this;return function(d){var f=d.value,d=d.record,c=a.dataIndex,k=b.get("store");d[c]!==f&&k.setValue(d,c,f)}},
_addError:function(a,b){var d=a.one(".grid-body-cell-inner"),f=a.one(".grid-cell-error-icon"),c=['<span class="grid-cell-error-icon" title="',b,'"></span>'].join("");f?f.attr("title",b):(d.addClass("grid-error-cell"),(new j(c)).appendTo(d))},_clearError:function(a){var b=a.one(".grid-body-cell-inner"),a=a.one(".grid-cell-error-icon");b.removeClass("grid-error-cell");a&&a.remove()},_getEditor:function(g){var b=this.get("columns"),d=null;a.each(b,function(a){if(a.dataIndex===g)return d=a.editor,!1});
return d},_getCellTemplate:function(a,b,d,f,c){var k=b.dataIndex,n=b.width,e=b.showTip?'title = "'+(f||"")+'"':"",h=b.hide?"ks-hidden":"",j=b.editor,b=j?j.editableFun&&!j.editableFun(f,c)?"":"grid-editable-cell":"",f=this.get("showError")?j&&j.validator?j.validator(f,c):"":"";return['<td  class="grid-body-cell grid-body-td-',k," ",h," ",b,'" data-column-name="',k,'" colindex="',a,'" width="',n,'px"><div class="grid-body-cell-inner ',f?"grid-error-cell":"",'" style="width : ',n,'px"><span class="grid-body-cell-text " ',
e,">",d,"</span>",f?'<span class="grid-cell-error-icon" title="'+f+'"></span>':"","</div></td>"].join("")},_getTextEditorTemplate:function(a){return['<div class="lp-text-editor grid-editor" style="position : absolute; z-index : 1000; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;"><input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field" style="width : ',a||80,'px; height : 20px;">'].join("")},_getRowDataByCell:function(a){a=this._findRow(a);
return b.data(a,"row-element")},_getCell:function(b,d){var e=this._findRowByRecord(b);return a.one(".grid-body-td-"+d,e)},_getCellValue:function(a,d){var e=this._findRow(a);return(e=b.data(e,"row-element"))?e[d]:null},_hasEditor:function(a){return this.hasAttr("col"+a)},_hideEditor:function(a){a.css({visibility:"hidden",left:-1E4,top:-1E4})},_init:function(){e.superclass._init.call(this);var b=this,d=b.get("columns");a.each(d,function(a){var f=a.editor,c=null;f&&!f.isEditor&&(c=h.types[f.type||"text"],
a.editor=new c(f),b._attachEditEvent(a))})},_initEvent:function(){var b=this;a.Event.on(document,"click",function(a){var d=b.get("editor"),f=a.target;!b._findCell(a.target)&&d&&!d.isHide()&&!d.hasError()&&!d.isContains(f)&&d.hide()});b.constructor.superclass._initEvent.call(b)},_initDataEvent:function(){var a=this;a.get("store").on("updaterecord",function(b){a._setRowValue(b.record)});a.on("rowremoved",function(b){var d=a.get("editRecord"),f=a.get("editor");d&&f&&d==b.data&&!f.isHide()&&f.hide()});
a.constructor.superclass._initDataEvent.call(this)},_rowClickEvent:function(a){var d=this._findCell(a),e=null,f=null,c=null,c=null;if(d&&(e=b.attr(d,"data-column-name"),f=this._getEditor(e),(c=this.get("editor"))&&c!=f&&!c.isHide()&&!c.hasError()&&c.hide(),e&&f)){if(!f.isHide()&&f.hasError()){f._focus();return}if(c=this._getRowDataByCell(d)){if(!b.hasClass(d,"grid-editable-cell"))return;!1!==this.fire("beforeedit",{cell:d,field:e,data:c})&&this._showEditor(f,d,c[e],c)}return}this.constructor.superclass._rowClickEvent.call(this,
a)},_setRowValue:function(b){var d=this,e=d._findRowByRecord(b),f=d.get("columns");e&&a.each(f,function(c){var f=c.dataIndex,n=a.one(".grid-body-td-"+f,e),h=n.one(".grid-body-cell-text"),o=c.editor,o=o&&o.validator?o.validator(b[f],b):"",j=null,p=d.get("showError");h&&(j=c.renderer?c.renderer(b[f],b):b[f],h.html(void 0===j?"":j),p&&(o?d._addError(n,o):d._clearError(n)))})},_showEditor:function(a,e,h,f){b.offset(e);var c=b.width(e),e=b.get(".grid-body-cell-inner",e);b.height(e);var k=this.get("editor");
k&&!k.isHide()&&!k.hasError()&&k.hide();this.set("editRecord",f);this.set("editor",a);7==d.ie?a.setWidth(c-4):a.setWidth(c-2);a.setValue(h,f);a.show({container:e,left:0,top:2})}});return e},{requires:["./grid","./gridEditor"]});
KISSY.add("gallery/grid/1.0/grid",function(a,m,h,e){function b(f){f=f||{};if(!f.renderTo)throw"please assign the id of rendered Dom!";f=a.merge(b.config,f);b.superclass.constructor.call(this,f);this.events="beginappend,afterappend,beginshow,aftershow,rowremoved,rowcreated,beforepagechange,rowclick,cellclick,rowselected,rowunselected".split(",");this._init()}var d=a.DOM,j=a.UA,g=a.Node,l="grid-body-cell",i="row-element";b.config={};a.extend(b,a.Base);a.augment(b,{appendData:function(f){var c=this,
k=[];c.fire("beginappend",{data:f});a.each(f,function(a,f){var b=c._createRow(a,f);k.push(b)});c.fire("afterappend",{rows:k,data:f})},addSummary:function(f){var c=this.get("tfoot");a.all(c.rows).remove();this._createSummaryRow(f)},clearData:function(){var f=this.get("tbody");this._setHeaderChecked(!1);a.all(f.rows).remove()},clearSelection:function(){this._setAllRowsSelected(!1)},filter:function(f,c){var k=this.get("tbody"),k=a.makeArray(k.rows),b="function"===typeof c?c:function(a){return a===c};
a.each(k,function(k){var g=a.one(k),k=d.data(k,i);null===c?g.show():!k||!b(k[f])?g.hide():g.show()})},getWidth:function(){return this.get("width")||this.get("gridEl").width()},getSelection:function(){var f=this.get("tbody"),f=a.all(".grid-row-selected",f),c=[];a.each(f,function(a){(a=d.data(a,i))&&c.push(a)});return c},getSelected:function(){var f=this.get("tbody");return(f=a.one(".grid-row-selected",f))?d.data(f,i):null},hideColumn:function(a){this._setColumnVisible(a,!1)},setAllSelection:function(){this._setAllRowsSelected(!0)},
setSelection:function(f,c){var k=this,b=k.get("tbody").rows;a.each(b,function(b){var n=d.data(b,i);n&&a.inArray(n[f],c)&&k._setRowSelected(b,!0)})},setHeight:function(f){var c=this.get("gridEl"),k=25,b=this.get("body"),b=a.one(b);c.height(f);this.get("tbar")&&(k+=27,this.get("tbar").buttons&&(k+=4));this.get("bbar")&&(k+=27);0<f-k&&(b.height(f-k),b.css("overflow-y","scroll"))},setWidth:function(f){var c=this.get("body"),k=this.get("gridEl"),b=this.get("forceFit");this.set("width",f);k.width(f);a.one(c).width(f-
2);k.children(".grid-view").width(f-2);b&&this._forceFitWidth();this._autoSetInnerWidth(f)},showColumn:function(a){this._setColumnVisible(a,!0)},sort:function(a,c){var k,b=this.get("store");k="string"===typeof a?a:a.dataIndex;b?b.sort(k,1===c?"ASC":"DESC"):this._localSort(k,c)},showData:function(f){var c=this;c.fire("beginshow");c.clearData();a.each(f,function(a,f){c._createRow(a,f)});c._afterShow();c.fire("aftershow")},removeData:function(f){var c=this,k=c.get("tbody"),k=a.makeArray(k.rows);a.each(k,
function(k){var b=d.data(k,i);b&&a.inArray(b,f)&&(c.fire("rowremoved",{data:b,row:k}),d.remove(k))})},_addBodyEvent:function(f){var c=this,k=c.get("head"),b=c.get("body"),d=a.one(b);a.one(f).on("click",function(a){c._rowClickEvent(a.target)}).on("mouseover",function(a){c._rowOverEvent(a.target)}).on("mouseout",function(a){c._rowOutEvent(a.target)});d.on("scroll",function(){var c=d.scrollLeft();a.one(k).scrollLeft(c)})},_afterShow:function(){var f=this.get("tbody"),c=this.get("body"),k=a.one(c),b;
if(6===j.ie||7===j.ie)b=this.get("height"),b||(b=k.width(),c=c.scrollWidth,c>b?(f=a.one(f).height(),k.height(f+17)):k.css("height","auto"))},_createRow:function(a,c){var b=this.get("tbody"),n=this._getRowTemplate(c,a),b=(new g(n)).appendTo(b),n=b.getDOMNode(),e=n.lastChild;d.data(n,i,a);d.addClass(e,"lp-last");this.fire("rowcreated",{data:a,row:n});return b},_createSummaryRow:function(a){var c=this.get("tfoot"),a=this._getSummaryTemplate(a);return(new g(a)).appendTo(c)},_lookupByClass:function(a,
c){return d.hasClass(a,c)?a:d.parent(a,"."+c)},_findRowByRecord:function(f){var c=this.get("tbody").rows,b=null;a.each(c,function(c){if(d.data(c,i)===f)return b=c,!1});return b},_findRow:function(a){return this._lookupByClass(a,"grid-row")},_findCell:function(a){return this._lookupByClass(a,l)},_forceFitColumns:function(f){var c=this.getWidth(),b=this.get("height"),d=0,g=0,e=this.get("checkable")?31:0,h=0,j=1,l=0,i=0,f=f||this.get("columns"),i=f.length;a.each(f,function(c){c.width=c.width||80;var a=
c.originWidth||c.width;c.hide||(d+=a,g+=1)});h=2*g+2+e+(b?17:0);j=(c-h)/d;l=0;1!==j&&(a.each(f,function(c){c.hide||(c.originWidth=c.originWidth||c.width,c.width=Math.floor(c.originWidth*j),l+=c.width)}),i&&(f[i-1].width+=c-(l+h)))},_forceFitWidth:function(){var f=this,c=f.get("columns");f._forceFitColumns();a.each(c,function(c){f._setColumnWidth(c)})},_getCheckedCellTemplate:function(a,c){return['<td width="30px" align="center" class="',a," ",c,'"><div class="',c,'-inner"><span class="gwt-CheckBox"><input type="checkbox" class="grid-checkbox" tabindex="0"></span></div></td>'].join("")},
_getColumn:function(f){var c=this.get("columns"),b=null;a.each(c,function(c){if(c.dataIndex==f)return b=c,!1});return b},_getRowTemplate:function(f,c){var b=this,d=b.get("columns"),g=0===f%2?"grid-row-odd":"grid-row-even",e=[],h=null,h=null;b.get("checkable")&&(h=b._getCheckedCellTemplate("grid-row-checked-column",l),e.push(h));a.each(d,function(a,f){var d=c[a.dataIndex],g=a.renderer?a.renderer(d,c):d,d=b._getCellTemplate(f,a,g,d,c);e.push(d)});return h=['<tr rowIndex="',f,'" class="grid-row ',g,
'">',e.join(""),"</tr>"].join("")},_getSummaryTemplate:function(f){function c(c){return 0<c?'<td class="'+l+'" colspan="'+c+'"></td>':""}var b=this,d=b.get("columns"),g=[],e=-1,h=-1;b.get("checkable")&&(h+=1);a.each(d,function(a,d){if(!a.hide&&(h+=1,a.summary)){g.push(c(h-e-1));var n=f[a.dataIndex],n="\u603b\u8ba1\uff1a"+(a.renderer?a.renderer(n,f):n),n=b._getCellTemplate(d,a,n,f);g.push(n);e=h}});e!==h&&g.push(c(h-e));return rowTemplate=['<tr class="grid-row">',g.join(""),"</tr>"].join("")},_getCellTemplate:function(a,
c,b,d){var g=c.dataIndex,e=c.width;return['<td  class="grid-body-cell grid-body-td-',g," ",c.hide?CLS_HIDDEN:"",'" data-column-name="',g,'" colindex="',a,'" width="',e,'px"><div class="grid-body-cell-inner" style="width : ',e,'px"><span class="grid-body-cell-text " ',c.showTip?'title = "'+(d||"")+'"':"",">",b,"</span></div></td>"].join("")},_getColumnsWidth:function(){var b=this.get("columns"),c=0;this.get("checkable")&&(c+=31);a.each(b,function(a){a.hide||(c+=a.width+2)});return c},_init:function(){var a=
this.get("gridId"),c=this.get("container"),b=this.get("renderTo"),e=null,h=e=e=null,j=null,l=null,e=0,i=this.get("height");c||(c=d.get("#"+b),this.set("container",c));a||(a=b+"grid",this.set("gridId",a));e=['<div id="',a,'" class="grid-panel"><div id="',a+"tbar",'" class="grid-tbar" style="display : none;"></div><div class="grid-view"><div class="grid-header"><table  cellspacing="0" cellpadding="0" class="grid-table"><thead></thead></table></div><div class="grid-body grid-body-scroll"><table  cellspacing="0" cellpadding="0" class="grid-table"><tbody><tfoot></tfoot></tbody></table></div></div><div id="',
a+"bbar",'" class="grid-bbar" style="display : none;"></div></div>'].join("");e=new g(e);e.appendTo(c);this.set("gridEl",e);e=d.get(".grid-header",c);h=d.get(".grid-table",e);j=d.get(".grid-body",c);l=d.get(".grid-table",j);this.set("head",e);this.set("body",j);this.set("tbody",l.tBodies[0]);this.set("tfoot",l.tFoot);this.set("thead",h.tHead);this._initHeader();this._isAutoFitWidth()?(e=this._getColumnsWidth(),this.setWidth(e+2)):(e=this.get("width"),this.setWidth(e));i&&this.setHeight(i);this._initListeners();
this._initPaggingBar();this._initData();this._initEvent()},_initEvent:function(){this._initHeaderEvent();this._initBodyEvent();this._initDataEvent();this._initPaggingBarEvent()},_initBodyEvent:function(){this._addBodyEvent(this.get("tbody"))},_initData:function(){var a=this.get("store"),c=this.get("loadMask"),b=this.get("gridEl");c&&(c=new e(b,{msg:"Loading..."}),this.set("loadMask",c));a&&a.autoLoad&&a.load()},_initDataEvent:function(){var a=this,c=a.get("store");c&&(c.on("beforeload",function(){var c=
a.get("loadMask");c&&c.show()}),c.on("load",function(){var b=c.getResult(),d=a.get("loadMask");a.showData(b);d&&d.hide()}),c.on("localsort",function(c){a._localSort(c.field,"ASC"===c.direction?1:-1)}),c.on("addrecords",function(c){a.appendData(c.data)}),c.on("removerecords",function(c){a.removeData(c.data)}),c.on("exception",function(){var c=a.get("loadMask");c&&c.hide()}))},_initHeaderEvent:function(){var b=this,c=b.get("thead"),d=b.get("checkable"),g=a.all(".grid-header-th-inner",c);g.on("mouseover",
function(){a.one(this).parent().addClass("hover")}).on("mouseout",function(){a.one(this).parent().removeClass("hover")}).on("click",function(){var c=a.one(this),d=c.parent(),k=null,e=null,h=null;d.hasClass("sortable")&&(k=d.attr("data-column-name"),e=c.hasClass("sorted-asc")?"sorted-desc":"sorted-asc",h="sorted-asc"===e?1:-1,g.removeClass("sorted-asc").removeClass("sorted-desc"),c.addClass(e),b.sort(k,h))});if(d)a.one(".grid-checkbox",c).on("click",function(){b._setAllRowsSelected(a.one(this).attr("checked"))})},
_initHeader:function(){var b=this.get("columns"),c=this.get("thead").insertRow(0),d=null,d=null;this.get("checkable")&&(d=this._getCheckedCellTemplate("grid-header-checked-column","grid-header-th"),(new g(d)).appendTo(c));a.each(b,function(a){a.width=a.width||80;var b=a.sortable?"sortable":"",f=a.width,a=['<th align="left" class="grid-header-th ',a.hide?CLS_HIDDEN:""," grid-header-column-",a.dataIndex," ",b,'" data-column-name="',a.dataIndex,'"><div class ="grid-header-th-inner ',a.cls,' "><span class="grid-header-inner-title">',
a.title,"</span>",b?'<span class="grid-header-sort-icon">&nbsp;</span>':"","</div></th>"].join(""),a=new g(a);a.attr("width",f+"px");a.appendTo(c)});this._isAutoFitWidth()||(d=new g('<th class="grid-header-th grid-header-th-empty"><div class ="grid-header-th-inner"></div></th>'),d.appendTo(c))},_initListeners:function(){var a=this.get("listeners");if(a)for(var c in a)if(a.hasOwnProperty(c))this.on(c,a[c])},_setEmptyHeadCellWidth:function(b){var c=this.get("thead");if(c=a.one(".grid-header-th-empty",
c))0>=b?c.hide():(c.attr("width",b+"px"),c.show())},_autoSetInnerWidth:function(){var b=this.get("thead"),c=this.get("tbody"),d=this.get("height"),g=this._getColumnsWidth(),e=this.get("forceFit"),h=this.getWidth(),e=e?15:h<g+2?15:h-(g+2);0<e&&15>e&&(e=15);this._setEmptyHeadCellWidth(e);a.one(b).parent().width(g+(e?e+2:0));d&&!j.firefox&&(g-=17);a.one(c).parent().width(g)},_initPaggingBar:function(){function b(c,f){var d=a.merge(c,{renderTo:f});j&&!d.store&&(d.store=j);return new h(d)}function c(c,
b){var d=a.merge(c,{renderTo:b});return new m(d)}var d=this.get("gridId"),g=this.get("tbar"),e=this.get("bbar"),j=this.get("store"),l=0,i=null,i=i=i=null;if(g&&(g.pageSize&&(i=b(g,d+"tbar"),this.set("tpaggingBar",i),l=g.pageSize),g.buttons))i=c(g,d+"tbar"),this.set("tbuttonBar",i);e&&(i=b(e,d+"bbar"),this.set("bpaggingBar",i),l=e.pageSize);if(l&&j&&(i=j.params,i.start||(i.start=0,i.pageIndex=0),!i.limit||i.limit!==l))i.limit=l},_initPaggingBarEvent:function(){var a=this,c=a.get("tpaggingBar"),b=a.get("bpaggingBar");
if(c)c.on("beforepagechange",function(c){a.fire("beforepagechange",c)});if(b)b.on("beforepagechange",function(c){a.fire("beforepagechange",c)})},_isAutoFitWidth:function(){return!this.get("width")},_isRowSelected:function(b){return a.one(b).hasClass("grid-row-selected")},_localSort:function(b,c){function g(c,a){var b=d.data(c,i);return b?b[a]:""}var e=this.get("tbody"),h=this.get("store"),j=a.makeArray(e.rows);h?j.sort(function(c,a){var b=d.data(c,i),f=d.data(a,i);return h.compare(b,f)}):j.sort(function(a,
d){var e=g(a,b),h=g(d,b);return e<h?-c:e>h?c:0});a.each(j,function(c){a.one(c).appendTo(e)})},_rowClickEvent:function(b){var c=this._findRow(b),g=this._findCell(b),e=this.get("checkable"),h=null;c&&(h=d.data(c,i),this.fire("rowclick",{data:h,row:c}),g&&this.fire("cellclick",{data:h,row:c,cell:g,field:d.attr(g,"data-column-name"),domTarget:b}),e?this._isRowSelected(c)?this._setRowSelected(c,!1):this._setRowSelected(c,!0):(a.all(".grid-row-selected",c.parentNode).removeClass("grid-row-selected"),d.addClass(c,
"grid-row-selected")))},_rowOverEvent:function(b){(b=this._findRow(b))&&a.one(b).addClass("grid-row-over")},_rowOutEvent:function(b){(b=this._findRow(b))&&a.one(b).removeClass("grid-row-over")},_setColumnWidth:function(b,c){"string"===typeof b&&(b=this._getColumn(b));var d=b.dataIndex,g=".grid-header-column-"+d,d=".grid-body-td-"+d,e=this.get("thead"),h=this.get("tbody"),j=null;b.width!=c&&(c?b.width=c:c=b.width,a.one(g,e).attr("width",c+"px"),j=a.all(d,h),j.each(function(a){a.attr("width",c+"px").children(".grid-body-cell-inner").width(c)}))},
_setColumnVisible:function(b,c){"string"===typeof b&&(b=this._getColumn(b));if(b){var d=b.dataIndex,g=this.get("forceFit"),e=".grid-header-column-"+d,d=".grid-body-td-"+d,h=this.get("thead"),j=this.get("tbody");c?(b.hide=!1,a.one(e,h).removeClass(CLS_HIDDEN),a.all(d,j).removeClass(CLS_HIDDEN)):(b.hide=!0,a.one(e,h).addClass(CLS_HIDDEN),a.all(d,j).addClass(CLS_HIDDEN));g&&this._forceFitWidth()}},_setHeaderChecked:function(b){var c=this.get("thead");(c=a.one(".grid-checkbox",c))&&c.attr("checked",b)},
_setRowSelected:function(b,c){a.one(b);var g=d.get(".grid-checkbox",b),e=d.data(b,i);if(d.hasClass(b,"grid-row-selected")!==c){if(g){if(d.attr(g,"disabled"))return;g.checked=c}c?(d.addClass(b,"grid-row-selected"),this.fire("rowselected",{data:e})):(d.removeClass(b,"grid-row-selected"),this._setHeaderChecked(!1),this.fire("rowunselected",{data:e,row:b}));this.fire("rowselectchanged",{data:e,row:b})}},_setAllRowsSelected:function(b){var c=this,d=c.get("tbody");a.each(d.rows,function(a){c._setRowSelected(a,
b)})},destory:function(){}});return b},{requires:["./buttonBar","./paggingBar","./loadMask"]});
KISSY.add("gallery/grid/1.0/gridEditor",function(a,m){var h=a.DOM,e=a.Node,b=function(c){c=a.merge({isEditor:!0},c);a.mix(this,c);b.superclass.constructor.call(this,c);this._init();this.events=["beforechange","change"]};a.extend(b,a.Base);a.augment(b,{CHANGE_EVENT:"blur",INIT_VALUE:"",hasError:function(){return this.get("el").hasClass("grid-error-editor")},hide:function(){var c=this.get("el");this._clearError();c.css({visibility:"hidden",left:-1E4,top:-1E4});this.fire("hide",{record:this.get("record"),
editor:this});this._setValue(this.INIT_VALUE);a.one("body").append(c)},getValue:function(){return this.get("editEl")?this._getValue():this.INIT_VALUE},isHide:function(){var c=this.get("el");return"hidden"===c.css("visibility")||0==c.width()},isContains:function(c){return this.get("el").contains(c)},setValue:function(c,a){this.set("record",a);editEl&&(this._setValue(c),this._validate(c,a))},show:function(c){var b=this.get("el"),d=c.container;d&&a.one(d).append(b);b.css({visibility:"visible",left:c.left,
top:c.top});this._focus();this.fire("show",{record:this.get("record"),editor:this})},setWidth:function(c){this.get("editEl").width(c)},setHeight:function(c){this.get("editEl").height(c)},_basicValidator:function(c){return this.required&&(void 0===c||null===c||""===a.trim(c.toString()))?"\u4e0d\u80fd\u4e3a\u7a7a":""},_basicFormat:function(c){return void 0===c||""===a.trim(c.toString())?void 0:c},_clearError:function(){var c=this.get("el"),a=c.one(".grid-error-editor-icon");c.removeClass("grid-error-editor");a.attr("title",
"")},_focus:function(){this.get("editEl")[0].focus()},_getTemplate:function(){return'<input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_getEditElemnt:function(){var c=this.get("el").children();return c.length?a.one(c[0]):null},_getValue:function(c){c=c||this.get("editEl");return c.val()},_init:function(){this._initDom();this._initEvent();this._initHideEvent()},_initDom:function(){var c=
null,c=['<div class="grid-editor" style="position : absolute; z-index : 1000; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;">',this._getTemplate(),"</div>"].join(""),a=this.get("container")||h.get("body"),c=(new e(c)).appendTo(a);this.set("container",a);this.set("el",c);editEl=this._getEditElemnt();this.set("editEl",editEl)},_initEvent:function(){var c=this,b=c.get("el"),d=c.get("editEl");b.on("click",function(c){c.stopPropagation()});d.on(c.CHANGE_EVENT,function(b){var d=
a.one(this);c._valueChange(d)||b.preventDefault()})},_initHideEvent:function(){},_valueChange:function(c,a){var b=this.get("record"),d=null,a=a||this._getValue(c),d=this._validate(a,b),a=this._basicFormat(a),a=this.format?this.format(a):a;return d?(this.fire("change",{value:a,record:b}),!0):!1},_setError:function(c){var a=this.get("el"),b=a.one(".grid-error-editor-icon");a.addClass("grid-error-editor");b.attr("title",c)},_setValue:function(c,a){a=a||this.get("editEl");a.val(c)},_validate:function(c,
a){var b=null,d=!0;(d=(b=this._basicValidator(c)||this.validator&&this.validator(c,a))?!1:!0)?this._clearError():this._setError(b);return d},destroy:function(){this.get("el").remove();this.detach();this.__attrVals={}}});var d=function(c){d.superclass.constructor.call(this,c)};a.extend(d,b);a.augment(d,{_basicFormat:function(c){c&&(c=c.replace(/\</g,"&lt;").replace(/\>/,"&gt;").replace(/\"/,"&quot;"));return c},_setValue:function(c,a){c&&(c=c.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,
'"'));this.constructor.superclass._setValue.call(this,c,a)}});var j=function(a){j.superclass.constructor.call(this,a)};a.extend(j,b);a.augment(j,{_basicFormat:function(c){return void 0===c||""===a.trim(c.toString())?void 0:parseFloat(c)},_basicValidator:function(a){var b=this.constructor.superclass._basicValidator.call(this,a);!b&&a&&isNaN(a)&&(b="\u8bf7\u8f93\u5165\u6570\u5b57");return b}});var g=function(a){g.superclass.constructor.call(this,a)};a.extend(g,b);a.augment(g,{CHANGE_EVENT:"change",INIT_VALUE:!1,setHeight:function(){},
_getTemplate:function(){return'<input type="checkbox" name="" class="lp-form-checkbox-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_getValue:function(a){a=a||this.get("editEl");return a.attr("checked")?!0:!1},_setValue:function(a,b){b=b||this.get("editEl");b.attr("checked",a)}});var l=function(a){l.superclass.constructor.call(this,a)};a.extend(l,b);a.augment(l,{_getTemplate:function(){return'<select class="lp-form-select-field lp-editor-field"  style="height : 20px;"></select><s class="grid-error-editor-icon"></s>'},
_initDom:function(){this.constructor.superclass._initDom.call(this);var c=this,b=c.get("editEl"),d=c.items;c.required||c._createItem("\u8bf7\u9009\u62e9",c.INIT_VALUE,b);if(a.isArray(d))a.each(d,function(a){c._createItem(a.name,a.value,b)});else for(var g in d)d.hasOwnProperty(g)&&c._createItem(d[g],g,b)},_createItem:function(a,b,d){(new e('<option value="'+b+'">'+a+"</option>")).appendTo(d)}});var i=function(a){i.superclass.constructor.call(this,a)};a.extend(i,b);a.augment(i,{CHANGE_EVENT:"select",isContains:function(c){return this.constructor.superclass.isContains.call(this,
c)||a.one(c).parent(".ks-cal-box")},setHeight:function(){},setWidth:function(a){this.constructor.superclass.setWidth.call(this,a-15)},_basicFormat:function(a){return(new Date(a)).getTime()},_getTemplate:function(){return'<input type="text" name=""autocomplete="off" size="20" class="lp-form-text-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_init:function(){var c=this;a.use("gallery/grid/1.0/calendar",function(a,b){c.set("Calendar",b);c.constructor.superclass._init.call(c)})},
_initDom:function(){this.constructor.superclass._initDom.call(this);var c=this.get("editEl"),b=this.get("Calendar"),d="grid-date"+a.guid(),g=null;c.attr("id",d);g=new b([{selector:"#"+d}]);this.set("datepicker",g["#"+d])},_initEvent:function(){var c=this,b=c.get("datepicker");c.get("el");c.get("editEl").on("change",function(){a.log("change")});b.on(c.CHANGE_EVENT,function(a){c._valueChange(null,a.date)})},_setValue:function(a,b){var b=b||this.get("editEl"),d=m.Format.dateRenderer(a),g=this.get("datepicker");
b.val(d);a&&a!==this.INIT_VALUE&&g.render({selected:new Date(a),date:new Date(a)})},_getValue:function(c){if(c)return c.date;a.log("error")}});var f=function(a){f.superclass.constructor.call(this,a)};a.extend(f,b);a.augment(f,{hide:function(){this.get("hideEvent");this._isSelectShow()&&this._hideSelect();this.constructor.superclass.hide.call(this)},isContains:function(c){return this.constructor.superclass.isContains.call(this,c)||a.one(c).parent(".lp-multiple-wrap")},setValue:function(a,b){a=a||[];
this.constructor.superclass.setValue.call(this,a,b)},setWidth:function(a){this.constructor.superclass.setWidth.call(this,a-17)},setHeight:function(){},_createItem:function(a,b,d){(new e('<li class="multiple-item"> <input class="multiple-item-checkbox"  type="checkbox" name="'+b+'" />'+a+"</li>")).appendTo(d)},_getSelectOffset:function(){var a=this.get("editEl"),b=a.offset();b.top+=a.height()+2;return b},_getText:function(a){var a=a||this._getValue(),b=this.items,d=this.get("renderer");d||(d=m.Format.multipleItemsRenderer(b),
this.set("renderer",d));return d(a)},_getValue:function(){var c=[],b=this.get("listEl").all(".multiple-item-checkbox");a.each(b,function(a){a.checked&&c.push(a.name)});return c},_getTemplate:function(){return'<input type="text" readonly = "true" name=""autocomplete="off" size="20" class="lp-form-multiple-field lp-editor-field"  style="height : 20px;"><s class="grid-error-editor-icon"></s>'},_hideSelect:function(){this.get("selectEl").css({visibility:"hidden",left:-1E4,top:-1E4})},_isSelectShow:function(){var a=
this.get("selectEl");return"hidden"!==a.css("visibility")&&0!=a.width()},_initDom:function(){this.constructor.superclass._initDom.call(this);var c=this;c.get("editEl");var b=c.get("items"),d=(new e('<div class="lp-multiple-wrap"  style="position : absolute; z-index : 1200; visibility : hidden; left : -10000px; top : -10000px; overflow : auto;"><ul class="multiple-list ks-clear"></ul><div class="multiple-footer" style="text-align:center"><span class="x-btn x-btn-default-small"><button autocomplete="off" hidefocus="true" type="button" style="width:74px;"><span class="x-btn-inner">\u786e\u8ba4</span></button></span></div></div>')).appendTo("body"),
g=d.one(".multiple-list"),f=d.one("button");c.set("selectEl",d);c.set("listEl",g);c.set("btnEl",f);if(a.isArray(b))a.each(b,function(a){c._createItem(a.name,a.value,g)});else for(var h in b)b.hasOwnProperty(h)&&c._createItem(b[h],h,g)},_initEvent:function(){var a=this,b=a.get("listEl"),d=a.get("editEl"),g=a.get("btnEl");d.on("click",function(b){b.stopPropagation();a._toggleSelect()});b.on("click",function(a){a.stopPropagation()});g.on("click",function(b){b.stopPropagation();b=a.getValue();a._setText(a._getText(b));
a._hideSelect();a._valueChange(d,b)})},_setText:function(a){this.get("editEl").val(a)},_setSelectValue:function(c){var b=this.get("listEl").all(".multiple-item-checkbox");b.attr("checked",!1);b=a.filter(b,function(b){return a.inArray(b.name,c)});a.all(b).attr("checked","checked")},_setValue:function(a){this._setText(this._getText(a));this._setSelectValue(a)},_showSelect:function(a){var b=this.get("selectEl"),a=a||this._getSelectOffset();b.css({visibility:"visible",left:a.left,top:a.top})},_toggleSelect:function(){this._isSelectShow()?
this._hideSelect():this._showSelect()}});b.types={text:d,number:j,check:g,select:l,date:i,multipleSelect:f};return b},{requires:["./util"]});KISSY.add("gallery/grid/1.0/index",function(a,m,h,e,b,d){return{Util:m,Store:h,Grid:e,EditGrid:b,LoadMask:d}},{requires:["./util","./store","./grid","./editGrid","./loadMask"]});
KISSY.add("gallery/grid/1.0/loadMask",function(a,m){var h=function(a,b){this.el=a;h.superclass.constructor.call(this,b);this._init()};a.extend(h,a.Base);a.augment(h,{msg:"Loading...",msgCls:"x-mask-loading",disabled:!1,_init:function(){this.msg=this.get("msg")||this.msg},disable:function(){this.disabled=!0},enable:function(){this.disabled=!1},onLoad:function(){m.unmaskElement(this.el)},onBeforeLoad:function(){this.disabled||m.maskElement(this.el,this.msg,this.msgCls)},show:function(){this.onBeforeLoad()},
hide:function(){this.onLoad()},destroy:function(){this.el=null}});return h},{requires:["./util"]});
KISSY.add("gallery/grid/1.0/paggingBar",function(a,m){function h(b){b=this._formatConfig(b||{});a.mix(this,{start:0,end:0,totalCount:0,curPage:1,totalPage:1});h.superclass.constructor.call(this,b)}var e=a.DOM;a.extend(h,m);a.augment(h,{CLS_BAR:"pagging-bar",_afterStoreLoad:function(a,d){var e=this.get("pageSize"),g=0,h=0,i=0,f=1,c=1,g=d?d.start||0:0,i=a.getTotalCount(),h=i-g>e?g+a.getCount():i,c=parseInt((i+e-1)/e,10),c=0<c?c:1,f=parseInt(g/e,10)+1;this.start=g;this.end=h;this.totalCount=i;this.curPage=
f;this.totalPage=c;this._setAllButtonsState();this._setNumberPages()},_getBarTemplate:function(){return'<div class="fr"></div>'},_getButtonConfig:function(b,d,h,g){var l=this;return{id:b,type:"button",css:d,text:g,containerCss:g?"bar-btn-custom":"",disabled:!!h,handler:function(b){var b=l._findItem(b.target),d=a.one("button",b);e.hasClass(b,"lp-item-disabled")||l._pageAction(d)}}},_getPageInfoConfig:function(){return{type:"custom",template:'<span class="pb-text-container">\u7b2c</span><span class="pb-input-container"><input type="text" autocomplete="off" class="pb-item-input" size="20" name="inputItem"></span><span class="pb-text-container pb-total-page">\u9875 \u5171 0 \u9875</span>'}},
_getCountInfoConfig:function(){return{type:"custom",template:'<div class="pb-text-container">\u5171 <span class="pb-total-count">0</span> \u6761\u8bb0\u5f55</div>'}},_formatConfig:function(b){var d=[],b=a.merge(b,{items:d});d.push(this._getButtonConfig("btnfirst","pb-page-first",!0));d.push(this._getButtonConfig("btnpre","pb-page-prev",!0));d.push({type:"seperator"});d.push(this._getPageInfoConfig());d.push({type:"seperator"});d.push(this._getButtonConfig("btnnext","pb-page-next",!0));d.push(this._getButtonConfig("btnlast",
"pb-page-last",!0));d.push(this._getButtonConfig("btnok","pb-page-ok",!1,"\u8df3\u8f6c"));d.push({type:"seperator"});d.push(this._getCountInfoConfig());return b},_initEvent:function(){this.constructor.superclass._initEvent.call(this);var b=this,d=b.get("store"),e=b.get("bar");if(d)d.on("load",function(a){b._afterStoreLoad(d,a)});e.one(".pb-item-input").on("keyup",function(d){d.stopPropagation();if(13===d.keyCode){var d=a.one(this),e=parseInt(d.val(),10);b._isPageAllowRedirect(e)?b.skipToPage(e):d.val(b.curPage)}})},
_isPageAllowRedirect:function(a){return a&&0<a&&a<=this.totalPage&&a!==this.curPage},_pageAction:function(a){var d=1;if(a.hasClass("pb-page-first"))d=1;else if(a.hasClass("pb-page-next"))d=this.curPage+1;else if(a.hasClass("pb-page-prev"))d=this.curPage-1;else if(a.hasClass("pb-page-last"))d=this.totalPage;else if(a.hasClass("pb-page-ok")&&(a=this.get("bar").one(".pb-item-input"),d=parseInt(a.val(),10),!this._isPageAllowRedirect(d))){a.val(this.curPage);return}this.skipToPage(d)},skipToPage:function(a){var d=
this.get("store"),e=this.get("pageSize"),g=a-1,h=g*e,a=this.fire("beforepagechange",{from:this.curPage,to:a});d&&!1!==a&&d.load({start:h,limit:e,pageIndex:g})},_setAllButtonsState:function(){function b(b,d){a.each(e,function(e){a.inArray(e.id,b)&&e.set("disabled",!d)})}var d=this.get("store"),e=this.get("items");d&&b(["btnpre","btnnext","btnfirst","btnlast","btnok"],!0);1===this.curPage&&b(["btnpre","btnfirst"],!1);this.curPage===this.totalPage&&b(["btnnext","btnlast"],!1)},_setNumberPages:function(){var a=
this.get("bar"),d=a.one(".pb-item-input"),e=a.one(".pb-total-page"),a=a.one(".pb-total-count"),g=null;d&&e&&(d.val(this.curPage),g="\u9875 \u5171 "+this.totalPage+" \u9875",e.text(g));a&&a.text(this.totalCount)}});return h},{requires:["./bar"]});
KISSY.add("gallery/grid/1.0/store",function(a){function m(h){h=h||{};h=a.merge({root:"rows",totalProperty:"results",dataType:"json",autoLoad:!1,sortInfo:{field:"",direction:"ASC"},proxy:{method:"post"},params:{},remoteSort:!1,matchFunction:function(a,b){return a==b},compareFunction:function(e,b){void 0==e&&(e="");void 0==b&&(b="");return a.isString(e)?e.localeCompare(b):e>b?1:e===b?0:-1}},h);a.mix(this,h,{hasLoad:!1,resultRows:[],rowCount:0,totalCount:0});this.events="load,beforeload,beforeProcessLoad,addrecords,exception,removerecords,updaterecord,localsort".split(",");
this._init()}a.augment(m,a.EventTarget);a.augment(m,{add:function(h,e,b){var d=this,j=[],b=b||d._getDefaultMatch();a.isArray(h)||(h=[h]);a.each(h,function(a){if(!e||!d.contains(a,b))d._addRecord(a),j.push(a)});d.fire("addrecords",{data:j})},compare:function(a,e,b,d){b=b||this.sortInfo.field;d=d||this.sortInfo.direction;return!b||!d?1:this.compareFunction(a[b],e[b])*("ASC"===d?1:-1)},contains:function(a,e){return-1!==this.findIndexBy(a,e)},findIndexBy:function(h,e){var b=-1,d=this.resultRows,e=e||
_self._getDefaultMatch();if(a.isUndefined(h)||a.isNull(h))return-1;a.each(d,function(a,d){if(e(h,a))return b=d,!1});return b},find:function(h,e){var b=null;a.each(this.resultRows,function(a){if(a[name]===e)return b=a,!1});return b},findAll:function(h,e){var b=[];a.each(this.resultRows,function(a){a[name]===e&&b.push(a)});return b},load:function(a){this._loadData(a)},getResult:function(){return this.resultRows},getCount:function(){return this.resultRows.length},getTotalCount:function(){return this.totalCount},
remove:function(h,e){var b=this,d=[],e=e||b._getDefaultMatch();a.isArray(h)||(h=[h]);a.each(h,function(a){a=b.findIndexBy(a,e);a=b._removeAt(a);d.push(a)});b.fire("removerecords",{data:d})},setResult:function(a){this.resultRows=a=a||[];this.totalCount=this.rowCount=a.length;this.fire("load",this.oldParams)},setValue:function(a,e,b,d){var j=a;d&&(d=this._getDefaultMatch(),a=this.findIndexBy(a,d),0<=a&&(j=this.resultRows[a]));j[e]=b;this.fire("updaterecord",{record:j,field:e,value:b})},sort:function(a,
e){this.sortInfo.field=a||this.sortInfo.field;this.sortInfo.direction=e||this.sortInfo.direction;this.remoteSort?this.load():(this._sortData(a,e),this.fire("localsort",{field:a,direction:e}))},update:function(h,e){var b=h;if(e){var d=this._getDefaultMatch(),d=this.findIndexBy(h,d);0<=d&&(b=this.resultRows[d])}b=a.mix(b,h);this.fire("updaterecord",{record:b})},_addRecord:function(h,e){var b=this.resultRows;a.isUndefined(e)&&(e=b.length);b[e]=h},_loadData:function(h){var e=this,b=h||{};e.fire("beforeload");
b=a.merge(e.oldParams,e.sortInfo,b);e.oldParams=b;h="post"===e.proxy.method?b:b?a.param(b):"";a.ajax({cache:!1,url:e.proxy.url,dataType:e.dataType,type:e.proxy.method,data:h,success:function(d){e.fire("beforeProcessLoad",{data:d});var h=[],g=0,l=0;d.hasError?(e.resultRows=h,e.rowCount=g,e.totalCount=l,e.fire("exception",{error:d.error})):("json"===e.dataType&&(a.isArray(d)?(h=d,l=g=h.length):null!=d&&((h=d[e.root])||(h=[]),g=h.length,l=parseInt(d[e.totalProperty]))),e.resultRows=h,e.rowCount=g,e.totalCount=
l,e.remoteSort||e._sortData(),e.fire("load",b))},error:function(a,b,g){e.resultRows=[];e.rowCount=0;e.totalCount=0;e.fire("exception",{error:b,responseText:g.responseText,XMLHttpRequest:a})}})},_removeAt:function(a){if(!(0>a)){var e=this.resultRows,b=e[a];e.splice(a,1);return b}},_sortData:function(a,e){var b=this,a=a||b.sortInfo.field,e=e||b.sortInfo.direction;a&&e&&b.resultRows.sort(function(d,j){return b.compare(d,j,a,e)})},_getDefaultMatch:function(){return this.matchFunction},_init:function(){this.oldParams=
this.params||{};this.proxy.url||(this.proxy.url=this.url);this.resultRows=[]}});return m},{requires:[]});
KISSY.add("gallery/grid/1.0/util",function(a,m){var h=a.DOM,e=a.Event,b=window,d=a.UA,j={};a.mix(j,{mask:function(){function d(){m&&clearTimeout(m);m=setTimeout(l,300)}function l(){var a=h.viewportHeight();k.height(f>a?f:a)}var i=a.one("body"),f=i.height(),c=h.viewportHeight(),c=f>c?f:c,k=j.maskElement(i);k.height(c);e.on(b,"resize",d);k.data("reszieFunc",d);var m=null},unmask:function(){var d=a.one("body"),h=d.children(".lp-el-mask"),i=h.data("reszieFunc");i&&(e.remove(b,"resize",i),h.data("reszieFunc",
null));j.unmaskElement(d)},maskElement:function(b,e,i){var b=a.one(b),f=b.getDOMNode(),c=a.one(".lp-el-mask",f);if(!c&&(c=a.one(h.create('<div class="lp-el-mask"></div>')).appendTo(f),b.addClass("x-masked-relative x-masked"),6==d.ie&&c.height(b.height()),e)){e=['<div class="lp-el-mask-msg"><div>',e,"</div></div>"].join("");e=a.one(h.create(e)).appendTo(f);i&&e.addClass(i);try{var k=(b.width()-e.width())/2,j=(b.height()-e.height())/2;e.css({left:k,top:j})}catch(m){a.log("width error!")}}return c},
unmaskElement:function(b){b=a.one(b);b.getDOMNode();var d=b.children(".lp-el-mask-msg"),e=b.children(".lp-el-mask");d&&d.remove();e&&e.remove();b.removeClass("x-masked-relative x-masked")}});j.Format=function(){return{dateRenderer:function(a){if(!a)return"";try{var b=new Date(a)}catch(d){return""}return!b||!b.getFullYear?"":m.Date.format(a,"yyyy-mm-dd")},datetimeRenderer:function(a){if(!a)return"";try{var b=new Date(a)}catch(d){return""}return!b||!b.getFullYear?"":m.Date.format(a,"yyyy-mm-dd HH:MM:ss")},
cutTextRenderer:function(a){return function(b){b=b||"";return b.toString().length>a?b.toString().substring(0,a)+"...":b}},enumRenderer:function(a){return function(b){return a[b]||""}},multipleItemsRenderer:function(b){var d=j.Format.enumRenderer(b);return function(b){if(!b)return"";var e=[];a.isArray(b)&&(b=b.toString().split(","));a.each(b,function(a){e.push(d(a))});return e.join(",")}}}}();j.FormHelpr={serialize:function(b){return a.param(j.FormHelpr.serializeToObject(b))},serializeToObject:function(b){var b=
a.makeArray(b.elements),b=a.filter(b,function(a){return(a.id||a.name)&&!a.disabled&&(this.checked||/select|textarea/i.test(a.nodeName)||/text|hidden|password/i.test(a.type))}),d=[];a.each(b,function(b){var c=a.one(b).val();(c=null==c?null:a.isArray(c)?a.map(c,function(a){return{name:b.name||b.id,value:a}}):{name:b.name||b.id,value:c})&&d.push(c)});var e={};a.each(d,function(b){var c=e[b.name];if(c)if(a.isArray(c))c.push(b.value);else{var d=[];d.push(c);d.push(b.value);e[b.name]=d}else e[b.name]=b.value});
return e}};return j},{requires:["calendar"]});
