KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/index",function(b,k,j,e,c,a,d){function h(g){this.set("queueTarget",g.queueTarget);h.superclass.constructor.call(this,g)}var i=k.all;b.extend(h,j,{_init:function(){var g=this.get("queueTarget");this.set("queue",new e(g));b.log("[LineQueue:index] inited.")},afterUploaderRender:function(g){var m=this.get("queueTarget"),l=g.get("queue"),s=g.get("button"),o=s.get("target"),t=g.get("auth");o=i(".original-file-input",o);s.get("fileInput");var n=5,w=
this.get("defaultMsg"),u=this.get("leftMsg");if(t)n=t.getRule("max");else b.log("[LineQueue:index] Cannot get auth");i(o).remove();b.log("[LineQueue:index] old input removed.");var x=new c,p=new a({msgContainer:this.get("msgContainer"),successMsgCls:this.get("successMsgCls"),hintMsgCls:this.get("hintMsgCls"),errorMsgCls:this.get("errorMsgCls")}),q=new d(this.get("mainPicInput"),this.get("queueTarget"));g.set("message",p);l.on("add",function(f){var r=i(".J_ItemPic",f.target),v=l.getFiles("success");
x.preview(f.file.input,r);b.log("[LineQueue:index] preview done for file: "+f.file.id);v.length+1&&p.send(b.substitute(u,{left:n-v.length-1}),"hint")});if(g.get("type")=="ajax"){b.log("[LineQueue:index] advance queue");i(this.get("queueTarget")).addClass("advance-queue")}i(m).delegate("click",".J_DeleltePic",function(f){f.preventDefault();f=i(f.currentTarget).attr("data-file-id");l.remove(f)});i(m).delegate("click",".J_SetMainPic",function(f){f.preventDefault();f=i(f.currentTarget).parent("li");q.setMainPic(f)});
l.on("remove",function(){var f=l.getFiles("success");q.setMainPic();f=f.length?b.substitute(u,{left:n-f.length}):b.substitute(w,{max:n});p.send(f,"hint")});g.on("success",function(f){f=f.file;var r=f.sUrl;i(f.target).attr("data-url",r);q.setMainPic()})}},{ATTRS:{msgContainer:{value:"#J_MsgBoxUpload"},defaultMsg:{value:"最多上传{max}张照片，每张图片小于5M"},leftMsg:{value:"还可以上传{left}张图片，每张小于5M。主图将在搜索结果中展示，请认真设置。"},successMsgCls:{value:"msg-success"},hintMsgCls:{value:"msg-hint"},errorMsgCls:{value:"msg-error"},
mainPicInput:{value:"#J_MainPicUrl"}}});return h},{requires:["node","../default/index","./queue","../../plugins/preview/preview","./message","./setMainPic","./style.css"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/message",function(b,k){function j(a){this.config=b.mix({msgContainer:"#J_MsgBoxUpload",successMsgCls:"msg-success",hintMsgCls:"msg-hint",errorMsgCls:"msg-error"},a);b.log(c+"Constructed")}var e=k.all,c="[LineQueue: Message] ";b.augment(j,{send:function(a,d){if(!a){b.log(c+"You did not tell me what to show.");return false}var h=this.config.msgContainer,i=this.config[d+"MsgCls"],g=this.config.successMsgCls,m=this.config.hintMsgCls,l=this.config.errorMsgCls;
if(h)switch(d){case "success":case "hint":case "error":e(h).html(a);e(h).replaceClass([g,m,l].join(" "),i);return true;default:b.log(c+"type error");return false}}});return j},{requires:["node"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/queue",function(b,k,j,e){function c(a){c.superclass.constructor.call(this,a)}c.event=j.event;c.status=j.status;b.extend(c,j,{_renderStatus:function(a){a=a.target;var d;if(!a.length){b.log("[LineQueue:queue] Cannot get file data.");return false}d=a.children(".J_FileStatus");return new e(d,{queue:this,file:a})}},{ATTRS:{tpl:{value:'<li id="J_LineQueue-{id}" data-file-id="{id}" data-url="{sUrl}" data-name="{name}" data-size="{textSize}"><div class="J_Wrapper wrapper"><div class="tb-pic120"><a href="javascript:void(0);"><img class="J_ItemPic" src="{url}" /></a></div><div class="pic-mask"></div><div class="tips-uploading"><div class="progress-bar J_ProgressBar"><span class="progress-mask J_UploadingProgress"></span></div><p class="tips-text">上传中，请稍候</p></div><div class="tips-upload-success"><span class="progress-bar"></span><p class="tips-text">上传成功！</p></div><div class="tips-upload-error"><span class="progress-bar"></span><p>上传失败</p><p>请重新尝试！</p></div><div class="tips-upload-waiting">等待上传，请稍候</div><div class="upload-op-mask"></div><div class="upload-operations"><a class="J_SetMainPic set-as-main" data-file-id="{id}" href="#">设为主图</a><a class="J_DeleltePic del-pic" data-file-id="{id}" href="#">删除</a></div></div></li>'}}});
return c},{requires:["node","../../queue/base","./status"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/setMainPic",function(b,k){function j(a,d){a=e(a);d=e(d);if(!a||a.length<=0){b.log(c+"cannot find mainPicInput, SetMainPic function disabled.");return false}if(!d||d.length<=0){b.log(c+"cannot find queue container");return false}this.queueContainer=d;this.input=a}var e=k.all,c="[LineQueue: setMainPic] ";b.augment(j,{setMainPic:function(a){var d=this.queueContainer,h=this.getMainPic();a=e(a);if(!a||a.length<=0){a=e("li",d);if(a[0])if(h.length>0){b.log(c+
"Already have a main pic. Since you do not tell me which one to set as main pic, I will do nothing.");return h}else{b.log(c+"No li element specified. I will set the first pic as main pic.");a=a[0]}else{b.log(c+"There is no pic. I cannot set any pic as main pic. So I will empty the main pic input.");e(this.input).val("");return null}}d=e(".J_Wrapper",a);var i=e('<span class="main-pic-logo">主图</span>'),g=e(a).attr("data-url");if(h.length>0){e(h).removeClass("main-pic");e(".main-pic-logo",h).remove()}e(a).addClass("main-pic");
e(i).appendTo(d);e(this.input).val(g);b.log(c+"write main pic url to :"+g);return a},getMainPic:function(){return e(this.queueContainer).children(".main-pic")},getMainPicUrl:function(){return e(this.input).val()}});return j},{requires:["node"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/status",function(b,k,j){function e(a,d){e.superclass.constructor.call(this,a,d);this.set("target",c(a))}var c=k.all;e.type=j.type;b.extend(e,j,{_waiting:function(){this.get("uploader");this.get("queue");var a=this.get("file");c(a).attr("data-file-id");if(a.length<=0){b.log("[LineQueue: status] Cannot find this file");return false}c(a).addClass("upload-waiting")},_start:function(){this.get("target");var a=this.get("uploader"),d=this.get("file");
a=a.get("type");c(d).replaceClass("upload-waiting","uploading");if(a=="ajax"){d=c(".J_ProgressBar",d);this.set("progressBar",c(".J_UploadingProgress",d))}},_progress:function(a){a=Math.ceil(a.loaded/a.total*100);this.get("uploader");var d=this.get("progressBar");if(!d){b.log("[LineQueue: status] Cannot find progress bar");return false}c(d).width(100-a+"%")},_success:function(){var a=this.get("file");this.get("uploader").get("loaded");c(a).replaceClass("uploading","upload-success");setTimeout(function(){c(a).replaceClass("upload-success",
"upload-done")},1E3)},_error:function(a){if(!b.isObject(a)||!a.msg)a={msg:"文件上传失败！"};var d=this.get("file"),h=c(d).attr("data-file-id"),i=this.get("uploader"),g=this.get("queue");i.get("message").send(a.msg,"error");c(d).replaceClass("uploading","upload-error");setTimeout(function(){g.remove(h)},1E3)}},{ATTRS:{tpl:{value:{waiting:'<div class="clearfix"><div class="f-l">0%</div><div class="f-l uploader-icon del-icon J_DelFile"></div></div>',start:'<div class="clearfix"><div class="J_ProgressNum"><img class="loading" src="http://img01.taobaocdn.com/tps/i1/T1F5tVXjRfXXXXXXXX-16-16.gif" alt="loading" /></div></div> ',
success:'<div class="uploader-icon success-icon">100%</div>',cancel:'<div>已经取消上传，<a href="#reUpload" class="J_ReUpload">点此重新上传</a> </div>',error:'<div class="upload-error">{msg}<a href="#fileDel" class="J_FileDel">点此删除</a></div>'}}}});return e},{requires:["node","../../queue/status","../../plugins/progressBar/progressBar"]});
