KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/index",function(b,k,i,e,d,a,c){function h(g){this.set("queueTarget",g.queueTarget);h.superclass.constructor.call(this,g)}var j=k.all;b.extend(h,i,{_init:function(){var g=this.get("queueTarget");this.set("queue",new e(g));b.log("[LineQueue:index] inited.")},afterUploaderRender:function(g){var m=this.get("queueTarget"),l=g.get("queue"),r=g.get("button"),o=r.get("target"),s=g.get("auth");o=j(".original-file-input",o);r.get("fileInput");var n=5,v=
this.get("defaultMsg"),t=this.get("leftMsg");if(s)n=s.getRule("max");else b.log("[LineQueue:index] Cannot get auth");j(o).remove();b.log("[LineQueue:index] old input removed.");var w=new d,p=new a({msgContainer:this.get("msgContainer"),successMsgCls:this.get("successMsgCls"),hintMsgCls:this.get("hintMsgCls"),errorMsgCls:this.get("errorMsgCls")}),q=new c(this.get("mainPicInput"),this.get("queueTarget"));g.set("message",p);l.on("add",function(f){var x=j(".J_ItemPic",f.target),u=l.getFiles("success");
w.preview(f.file.input,x);b.log("[LineQueue:index] preview done for file: "+f.file.id);u.length+1&&p.send(b.substitute(t,{left:n-u.length-1}),"hint")});if(g.get("type")=="ajax"){b.log("[LineQueue:index] advance queue");j(this.get("queueTarget")).addClass("advance-queue")}j(m).delegate("click",".J_DeleltePic",function(f){f.preventDefault();f=j(f.currentTarget).attr("data-file-id");l.remove(f)});j(m).delegate("click",".J_SetMainPic",function(f){f.preventDefault();f=j(f.currentTarget).parent("li");q.setMainPic(f)});
l.on("remove",function(){var f=l.getFiles("success");q.setMainPic();f=f.length?b.substitute(t,{left:n-f.length}):b.substitute(v,{max:n});p.send(f,"hint")});g.on("success",function(){q.setMainPic()})}},{ATTRS:{msgContainer:{value:"#J_MsgBoxUpload"},defaultMsg:{value:"最多上传{max}张照片，每张图片小于5M"},leftMsg:{value:"还可以上传{left}张图片，每张小于5M。主图将在搜索结果中展示，请认真设置。"},successMsgCls:{value:"msg-success"},hintMsgCls:{value:"msg-hint"},errorMsgCls:{value:"msg-error"},mainPicInput:{value:"#J_UploaderForm"}}});return h},{requires:["node",
"../default/index","./queue","../../plugins/preview/preview","./message","./setMainPic","./style.css"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/message",function(b,k){function i(a){this.config=b.mix({msgContainer:"#J_MsgBoxUpload",successMsgCls:"msg-success",hintMsgCls:"msg-hint",errorMsgCls:"msg-error"},a);b.log(d+"Constructed")}var e=k.all,d="[LineQueue: Message] ";b.augment(i,{send:function(a,c){if(!a){b.log(d+"You did not tell me what to show.");return false}var h=this.config.msgContainer,j=this.config[c+"MsgCls"],g=this.config.successMsgCls,m=this.config.hintMsgCls,l=this.config.errorMsgCls;
if(h)switch(c){case "success":case "hint":case "error":e(h).html(a);e(h).replaceClass([g,m,l].join(" "),j);return true;default:b.log(d+"type error");return false}}});return i},{requires:["node"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/queue",function(b,k,i,e){function d(a){d.superclass.constructor.call(this,a)}d.event=i.event;d.status=i.status;b.extend(d,i,{_renderStatus:function(a){a=a.target;var c;if(!a.length){b.log("[LineQueue:queue] Cannot get file data.");return false}c=a.children(".J_FileStatus");return new e(c,{queue:this,file:a})}},{ATTRS:{tpl:{value:'<li id="J_LineQueue-{id}" data-file-id="{id}" data-url="{url}" data-name="{name}" data-size="{textSize}"><div class="J_Wrapper wrapper"><div class="tb-pic120"><a href="javascript:void(0);"><img class="J_ItemPic" src="{url}" /></a></div><div class="pic-mask"></div><div class="tips-uploading"><div class="progress-bar J_ProgressBar"><span class="progress-mask J_UploadingProgress"></span></div><p class="tips-text">上传中，请稍候</p></div><div class="tips-upload-success"><span class="progress-bar"></span><p class="tips-text">上传成功！</p></div><div class="tips-upload-error"><span class="progress-bar"></span><p>上传失败</p><p>请重新尝试！</p></div><div class="tips-upload-waiting">等待上传，请稍候</div><div class="upload-op-mask"></div><div class="upload-operations"><a class="J_SetMainPic set-as-main" data-file-id="{id}" href="#">设为主图</a><a class="J_DeleltePic del-pic" data-file-id="{id}" href="#">删除</a></div></div></li>'}}});
return d},{requires:["node","../../queue/base","./status"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/setMainPic",function(b,k){function i(a,c){a=e(a);c=e(c);if(!a||a.length<=0){b.log(d+"cannot find mainPicInput, SetMainPic function disabled.");return false}if(!c||c.length<=0){b.log(d+"cannot find queue container");return false}this.queueContainer=c;this.input=a}var e=k.all,d="[LineQueue: setMainPic] ";b.augment(i,{setMainPic:function(a){var c=this.queueContainer,h=this.getMainPic();a=e(a);if(!a||a.length<=0){a=e("li",c);if(a[0])if(h.length>0){b.log(d+
"Already have a main pic. Since you do not tell me which one to set as main pic, I will do nothing.");return h}else{b.log(d+"No li element specified. I will set the first pic as main pic.");a=a[0]}else{b.log(d+"There is no pic. I cannot set any pic as main pic. So I will empty the main pic input.");e(this.input).val("");return null}}c=e(".J_Wrapper",a);var j=e('<span class="main-pic-logo">主图</span>'),g=e(a).attr("data-url");if(h.length>0){e(h).removeClass("main-pic");e(".main-pic-logo",h).remove()}e(a).addClass("main-pic");
e(j).appendTo(c);e(this.input).val(g);return a},getMainPic:function(){return e(this.queueContainer).children(".main-pic")},getMainPicUrl:function(){return e(this.input).val()}});return i},{requires:["node"]});
KISSY.add("gallery/form/1.0/uploader/themes/lineQueue/status",function(b,k,i){function e(a,c){e.superclass.constructor.call(this,a,c);this.set("target",d(a))}var d=k.all;e.type=i.type;b.extend(e,i,{_waiting:function(){this.get("uploader");this.get("queue");var a=this.get("file");d(a).attr("data-file-id");if(a.length<=0){b.log("[LineQueue: status] Cannot find this file");return false}d(a).addClass("upload-waiting")},_start:function(){this.get("target");var a=this.get("uploader"),c=this.get("file");
a=a.get("type");d(c).replaceClass("upload-waiting","uploading");if(a=="ajax"){c=d(".J_ProgressBar",c);this.set("progressBar",d(".J_UploadingProgress",c))}},_progress:function(a){a=Math.ceil(a.loaded/a.total*100);this.get("uploader");var c=this.get("progressBar");if(!c){b.log("[LineQueue: status] Cannot find progress bar");return false}d(c).width(100-a+"%")},_success:function(){var a=this.get("file");this.get("uploader").get("loaded");d(a).replaceClass("uploading","upload-success");setTimeout(function(){d(a).replaceClass("upload-success",
"upload-done")},1E3)},_error:function(a){if(!b.isObject(a)||!a.msg)a={msg:"文件上传失败！"};var c=this.get("file"),h=d(c).attr("data-file-id"),j=this.get("uploader"),g=this.get("queue");j.get("message").send(a.msg,"error");d(c).replaceClass("uploading","upload-error");setTimeout(function(){g.remove(h)},1E3)}},{ATTRS:{tpl:{value:{waiting:'<div class="clearfix"><div class="f-l">0%</div><div class="f-l uploader-icon del-icon J_DelFile"></div></div>',start:'<div class="clearfix"><div class="J_ProgressNum"><img class="loading" src="http://img01.taobaocdn.com/tps/i1/T1F5tVXjRfXXXXXXXX-16-16.gif" alt="loading" /></div></div> ',
success:'<div class="uploader-icon success-icon">100%</div>',cancel:'<div>已经取消上传，<a href="#reUpload" class="J_ReUpload">点此重新上传</a> </div>',error:'<div class="upload-error">{msg}<a href="#fileDel" class="J_FileDel">点此删除</a></div>'}}}});return e},{requires:["node","../../queue/status","../../plugins/progressBar/progressBar"]});
