KISSY.add("gallery/timeline/1.0/background",function(b,f){function g(a){this.config=a;this.ATTRS=b.clone(i);this._init()}var d=b.all,i={html:{value:'<div class="timenav-bg">                <div class="middle-line K_MiddleLine"><i></i></div>              </div>'},bgBox:{value:null},middleLine:{value:null},indicator:{value:null}};b.augment(g,f,b.EventTarget,{_init:function(){this.render();this.adjustStyle();this.monitorEvent()},render:function(){var a=this.config;this.set("bgBox",d(this.get("html")));
this.get("bgBox").appendTo(a.panel);this.set("middleLine",d(".K_MiddleLine",this.get("bgBox")));this.fire("uiReady")},adjustStyle:function(){this.get("middleLine").css("left",(this.config.panel.width()-this.get("middleLine").width())/2-1);this.fire("styleReload")},monitorEvent:function(){var a=this;d(window).on("resize",function(){a.adjustStyle()})}});return g},{attach:!1,requires:["./base","template"]});
KISSY.add("gallery/timeline/1.0/base",function(b){function f(){}f.prototype={get:function(g){var d=this.ATTRS;return void 0===d[g]?void 0:b.isObject(d[g])?b.isFunction(d[g].value)?d[g].value():d[g].value:d[g]},set:function(g,d){var f=this.ATTRS;return void 0===f[g]?(f[g]={},f[g].value=d):b.isObject(f[g])?void 0===f[g].setter?f[g].value=d:f[g].setter():f[g].value=d}};return f});
KISSY.add("gallery/timeline/1.0/config",function(){return{myData:null,beginYear:null,endYear:null,maxInterval:null,widthRate:null,navWidth:null,spacer:null,realWidth:null,minLeft:null,maxLeft:null,rate:10,isScaling:!1,reg_songtime:/(\d{4})[^0-9]*(\d{1,2})?[^0-9]*(\d{1,2})?/,scale:200,minRate:3,maxRate:3,setData:function(b){this.myData=b;for(b=0;b<this.myData.length;++b){var f=this.myData[b].time.match(this.reg_songtime);this.myData[b].time=""+f[1];f[2]&&(this.myData[b].time+=""+(9<parseInt(f[2],10)?
parseInt(f[2],10):"0"+parseInt(f[2],10)));f[3]&&(this.myData[b].time+=""+(9<parseInt(f[3],10)?parseInt(f[3],10):"0"+parseInt(f[3],10)))}this.myData=this.myData.sort(function(b,d){return b.time>d.time});return this},config:function(b){b.minRate&&(this.minRate=b.minRate);b.maxRate&&(this.maxRate=b.maxRate);b.scale&&(this.scale=b.scale)},largeRate:function(b){this.rate*=2;this.initAll(b);return this},miniRate:function(b){this.rate/=2;this.initAll(b);return this},initAll:function(b){this.beginYear=parseInt(this.myData[0].time&&
this.myData[0].time.match(this.reg_songtime)[1]);this.endYear=parseInt(this.myData[this.myData.length-1].time&&this.myData[this.myData.length-1].time.match(this.reg_songtime)[1])+1;this.maxInterval=this.endYear-this.beginYear;this.widthRate=this.rate/(1/1.2/this.scale);this.navWidth=parseInt(this.widthRate*this.maxInterval,10);this.spacer=parseInt(3*b.width()/3,10);this.realWidth=this.navWidth+2*this.spacer;this.minLeft=parseInt(0-this.navWidth+this.spacer/3,10);this.maxLeft=parseInt(this.spacer/
3);return this}}});
KISSY.add("gallery/timeline/1.0/control",function(b,f,g,d,i,a,j){function e(a){this.config=a;this.ATTRS=b.clone(l);this._init()}var c=b.all,h=/(\d{4})(\d{1,2})?(\d{1,2})?/,l={};b.augment(e,f,b.EventTarget,{_init:function(){var e=this,c=e.config;c.trackConfig=b.clone(j);c.trackConfig.setData(c.data);c.trackConfig.config({minRate:c.minRate,maxRate:c.maxRate,scale:c.scale});c.trackConfig.initAll(c.panel);e.set("bg",new g(c));e.set("toolbar",new d(c));e.set("mainContent",new i(c));e.set("dd",new a(c.panel,
{dragEle:".K_Timenav"}));e.monitorEvent();e.get("mainContent").renderMarkers(e.transAjaxData(c.data));e.get("mainContent").renderInterval();c=c.trackConfig;e.set("maxRate",Math.pow(2,c.maxRate-1)*c.rate);e.set("minRate",Math.pow(0.5,c.minRate-1)*c.rate);e.get("dd").on("moving",function(a){e.get("mainContent").rigidResetOffset({left:a.ox})});e.get("dd").on("mouseup",function(a){a.buffer&&e.get("mainContent").dragBuffer({duration:a.buffer.duration,addLeft:a.buffer.addLeft})})},transAjaxData:function(a){for(var e=
[],c=0;c<a.length;++c)a[c].hidden&&!0==a[c].hidden||e.push(b.merge(a[c],{__left:this.timeToPosLeft(a[c].time)}));return e},timeToPosLeft:function(a){var e=this.config,c=0,a=a.match(h),c=e.trackConfig.beginYear,b=0,d=0;a[1]&&(c=a[1]);a[2]&&(b=a[2]);a[3]&&(d=a[3]);return c=(c-e.trackConfig.beginYear+b/12+d/12/30)*e.trackConfig.widthRate},_timeToPosTop:function(){},monitorEvent:function(){var a=this,e=a.config,b=e.trackConfig;c(document).on("resize",function(){b.initAll(e.panel)});var h=!1,d=1;a.get("toolbar").on("toggle",
function(){if(!0==h)return!1;if(0==d){var a=0;d=1}else 1==d&&(a=c(document.body).width(),d=0);h=!0;c("#KT_Navigation").animate({left:a},1,"swing",function(){h=!1})});a.get("toolbar").on("large",function(){b.rate>a.get("maxRate")||!0===b.isScaling||(b.largeRate(this.config.panel),a.get("mainContent").rate(2))});a.get("toolbar").on("mini",function(){b.rate<a.get("minRate")||!0===b.isScaling||(b.miniRate(e.panel),a.get("mainContent").rate(0.5))});a.get("toolbar").on("leftScroll",function(){a.get("mainContent").leftScroll()});
a.get("toolbar").on("rightScroll",function(){a.get("mainContent").rightScroll()});a.get("toolbar").on("gotoLast",function(){a.get("mainContent").switchTo(e.data.length-1)});a.get("mainContent").on("marker",function(e){a.fire("change",{data:e.data,target:e.target})});a.get("mainContent")},prev:function(){this.get("mainContent").prev()},next:function(){this.get("mainContent").next()},switchTo:function(a){this.get("mainContent").switchTo(a)},resetWidth:function(){this.get("mainContent").adjustStyle();
this.get("bg").adjustStyle()}});return e},{attach:!1,requires:"./base,./background,./toolbar,./main-content,./dd,./config".split(",")});
KISSY.add("gallery/timeline/1.0/dd",function(b,f){function g(a,b){this.panel=a&&"string"===typeof a?d((/^\s*[#|.]/.test(a)?"":"#")+a):a;if(void 0==this.panel)return alert("[DD] panel is undefined"),!1;this.__attr=b;this._init()}var d=b.all,i=b.DOM;b.augment(g,f,b.EventTarget,{_init:function(){var a=this;a.dragEle=d(a.get("dragEle"),a.panel);a.set("dragInfoX",[]);a.set("dragInfoY",[]);a.set("dragInfoTime",[]);a.set("ddMask",null);a.panel.on("mousedown",function(b){b.halt();b.button&&2==b.button||(a.set("ix",
b.pageX),a.set("iy",b.pageY),a.set("tx",parseInt(a.dragEle.css("left"),10)),a.set("ty",parseInt(a.dragEle.css("top"),10)),a.set("dragInfoX",[]),a.set("dragInfoY",[]),a.set("dragInfoTime",[]),a._bindWindowEvent())})},_bindWindowEvent:function(){d(document).on("mouseup",this._handleWindowMouseup,this);d(document).on("mousemove",this._handleWindowMousemove,this)},_cancelWindowEvent:function(){d(document).detach("mouseup",this._handleWindowMouseup,this);d(document).detach("mousemove",this._handleWindowMousemove,
this)},_handleWindowMousemove:function(a){a.preventDefault();null==this.get("ddMask")&&(this.set("ddMask",i.create('<div class="timeline-dd-mask"></div>')),document.body&&document.body.appendChild(this.get("ddMask")));this.get("dragInfoX").push(a.pageX);this.get("dragInfoY").push(a.pageY);this.get("dragInfoTime").push((new Date).getTime());this.fire("moving",{ox:a.pageX-this.get("ix")+this.get("tx"),oy:a.pageY-this.get("iy")+this.get("ty")})},_handleWindowMouseup:function(a){this._cancelWindowEvent();
this.get("dragInfoX").push(a.pageX);this.get("dragInfoY").push(a.pageY);this.get("dragInfoTime").push((new Date).getTime());this.fire("mouseup",{buffer:this._calculateBuffer()});i.remove(this.get("ddMask"));this.set("ddMask",null)},_calculateBuffer:function(){if(!(3>this.get("dragInfoX").length)){for(var a={a:1E4,v:100,isLeft:!0},b=this.get("dragInfoX"),e=b.length,c=this.get("dragInfoTime"),h=1,d=b[e-1],f=c[e-1];h<e&&50>f-c[e-++h];)if(2==h&&500<d-c[e-h])return;h<=e?(t1=c[e-h+1],b=b[e-1]-b[e-h],a.v=
1E3*(b/(f-t1)),0<b?a.isLeft=!0:a.isLeft=!1):(a.v=100,b[e-1]>b[0]?a.isLeft=!0:a.isLeft=!1);a.absDistance=a.v*a.v/2/a.a;a.addLeft=a.isLeft?"+="+a.absDistance:"-="+a.absDistance;a.duration=Math.abs(parseInt(1E3*(a.v/a.a),10));return a}},set:function(a,b){return this.__attr[a]=b},get:function(a){return this.__attr[a]}});return g},{attach:!1,requires:["./base"]});KISSY.add("gallery/timeline/1.0/index",function(b,f){return function(b){return new f(b)}},{requires:["./control"]});
KISSY.add("gallery/timeline/1.0/main-content",function(b,f,g,d){function i(a){this.config=a;this.ATTRS=b.clone(j);this._init()}var a=b.all,j={html:{value:'<div class="timenav K_Timenav" style="left:0;">                <div class="time-points K_MarkerBox">                </div>                <div class="time-interval">                  <div class="time-interval-major K_IntervalBox"></div>                </div>                <div class="time-ruler K_TimeRuler"></div>              </div>'},tpl_marker:{value:'<div class="marker K_Marker" id="marker_{{id}}" style="left: {{left}}px;" data-req=\'{{data}}\'>                <div class="flag" style="top:{{top}}px">                  <div class="flag-content">                    <div class="thumbnail"></div>                    <h3>{{title}}</h3>                  </div>                </div>                <div class="dot"></div>                <div class="line">                  <div class="event-line"></div>                </div>              </div>'},
tpl_interal:{value:'<div class="a-interval" style="left: {{left}}px;">{{time}}</div>'},cBox:{value:null},markerBox:{value:null},intervalBox:{value:null},timeRuler:{value:null},timenav:{value:null}};b.augment(i,f,b.EventTarget,{ATTRS:j,_init:function(){this.dragBufferAnim=null;this.isRating=!1;this.cdY=1;this.markerEles=[];this.activeMarkerIdx=null;this.render();this.adjustStyle();this.monitorEvent()},leftScroll:function(){var e=this;e.stopAnim();e.dragBufferAnim=(new d(e.get("timenav")[0],{left:"+="+
4*a(document.body).width()/5},{duration:1,easing:"easeOutStrong"})).run();e.dragBufferAnim.on("step",function(){if(e.isOverflow())return!1})},rightScroll:function(){var e=this;e.stopAnim();e.dragBufferAnim=(new d(e.get("timenav")[0],{left:"-="+4*a(document.body).width()/5},{duration:1,easing:"easeOutStrong"})).run();e.dragBufferAnim.on("step",function(){if(e.isOverflow())return!1})},rigidResetOffset:function(a){this.stopAnim();void 0!=a.left&&this.get("timenav").css("left",a.left+"px");void 0!=a.top&&
this.get("timenav").css("top",a.top+"px")},dragBuffer:function(a){var c=this;c.stopAnim();c.dragBufferAnim=(new d(c.get("timenav")[0],{left:a.addLeft},{duration:a.duration/1E3,easing:"easeOutStrong"})).run();c.dragBufferAnim.on("step",function(){if(c.isOverflow())return!1})},isOverflow:function(){var a=this.config.trackConfig,c=0;if(a.minLeft>parseInt(this.get("timenav").css("left"),10))this.stopAnim(),c=a.minLeft;else if(a.maxLeft<parseInt(this.get("timenav").css("left"),10))this.stopAnim(),c=a.maxLeft;
else return;this.dragBufferAnim=this.get("timenav").animate({left:c+"px"},{duration:0.4,easing:"easeOutStrong"});return!0},stopAnim:function(){this.dragBufferAnim&&this.dragBufferAnim.stop&&this.dragBufferAnim.stop()},resetTimenavPos:function(a,c){this.stopAnim();c&&!1===c||(this.dragBufferAnim=this.get("timenav").animate(a,{duration:1,easing:"easeOutStrong"}))},render:function(e){var c=this.config;this.set("cBox",a(this.get("html")));this.set("timenav",this.get("cBox"));this.set("markerBox",a(".K_MarkerBox",
this.get("timenav")));this.set("intervalBox",a(".K_IntervalBox",this.get("timenav")));this.set("timeRuler",a(".K_TimeRuler",this.get("timenav")));this.get("timenav").appendTo(c.panel);this.resetTimenavPos({left:parseInt(this.get("timenav").css("left"),10)+c.panel.width()/3});e&&b.isArray(e)&&this.renderMarkers(e);this.fire("uiReady");b.UA&&6==b.UA.ie&&(this.get("timenav").delegate("mouseenter",".K_Marker",function(){a(this).addClass("hover")}),this.get("timenav").delegate("mouseleave",".K_Marker",
function(){a(this).removeClass("hover")}))},renderMarkers:function(e){for(var c=e.length,h=0;h<c;++h){var d=a(g(this.get("tpl_marker")).render({id:e[h].time,title:e[h].title,data:KISSY.JSON.stringify(b.merge({count:h},e[h])),left:e[h].__left,top:(e[h].top||parseInt(55*Math.random(),10))+10}));d.appendTo(this.get("markerBox"));this.markerEles.push(d)}},renderInterval:function(a){var c=this.config.trackConfig.widthRate,b=1,d=1;2E3<=c?d=b=1:2E3>c&&1E3<=c?(b=1,d=2):1E3>c&&500<=c?(b=1,d=3):500>c&&250<=
c?(b=1,d=4):250>c&&125<=c?(b=1,d=6):125>c&&(b=2,d=12);!a||!1==a?this._renderInterval(b,d):this._styleInterval(b,d)},_renderInterval:function(b,c){var d=this.config.trackConfig;this.get("intervalBox").html("");for(var f=-1;f<d.endYear-d.beginYear+1;++f){var k=a(g(this.get("tpl_interal")).render({left:5*parseInt(f*d.widthRate/5,10)-2,time:d.beginYear+f-1+".12"}));k.appendTo(this.get("intervalBox"));0!=Math.abs(f)%b&&k.hide();for(k=1;11>=k;++k){var j=a(g(this.get("tpl_interal")).render({left:5*parseInt((f*
d.widthRate+d.widthRate/12*k)/5,10)-2,time:d.beginYear+f+"."+k}));j.appendTo(this.get("intervalBox"));0!=k%c&&j.hide()}}},_styleInterval:function(b,c){for(var d=this.config.trackConfig,f=a(".a-interval",this.get("intervalBox")),g=-1;g<d.endYear-d.beginYear+1;++g){var j=12*(g+1);f.item(j).animate({left:5*parseInt(g*d.widthRate/5,10)-2},0.5);0!=Math.abs(g)%b?f.item(j).hide():f.item(j).show();for(var i=1;11>=i;++i)f.item(j+i).animate({left:5*parseInt((g*d.widthRate+d.widthRate/12*i)/5,10)-2},0.5),0!=
i%c?f.item(j+i).hide():f.item(j+i).show()}},gotoMarker:function(a,b){var d=this.config;this.get("timenav").all(".marker").removeClass("hover");b.addClass("hover");this.stopAnim();d=a+parseInt(this.get("timenav").css("left"),10)-d.panel.width()/2+3;this.dragBufferAnim=this.get("timenav").animate({left:"-="+d},0.5,"easeOutStrong")},adjustStyle:function(){var a=this.config.trackConfig;this.get("timenav").width(a.navWidth);this.get("intervalBox").width(a.navWidth);this.get("timeRuler").width(a.realWidth+
2*Math.abs(a.spacer)).css("left",0-Math.abs(2*a.spacer))},rate:function(b){var c=this,d=c.config;if(!0!=c.isRating){d.trackConfig.isScaling=!0;c.stopAnim();a(".marker",c.get("timenav")).each(function(c){a(c).animate({left:parseInt(a(c).css("left"),10)*Math.abs(b)},0.5)});var f=parseInt(c.get("timenav").css("left"),10);c.get("timenav").width();var g=d.panel.width(),f=g/2-(0-f+g/2)*b;c.get("timenav").animate({left:f,width:"*="+b},0.5,"easeNone",function(){c.adjustStyle();c.isRating=!1;d.trackConfig.isScaling=
!1});c.renderInterval(!0)}},monitorEvent:function(){var b=this;a(window).on("resize",function(){b.adjustStyle()});b.get("timenav").on("click",function(c){c.halt();c=a(c.target);if(!c.hasClass("marker"))if(null!=c.parent(".marker"))c=c.parent(".marker");else return!1;b.clickThisMarder(c)})},clickThisMarder:function(a){var c=b.JSON.parse(a.attr("data-req"));this.gotoMarker(parseInt(a.css("left"),10),a);if(this.activeMarkerIdx==c.count)return!1;this.activeMarkerIdx=c.count;this.fire("marker",{data:c,
target:a});this.setHash()},setHash:function(){return!1},prev:function(){var a=(this.activeMarkerIdx-1+this.markerEles.length)%this.markerEles.length||0;this.clickThisMarder(this.markerEles[a]);this.activeMarkerIdx=a},next:function(){var a=(this.activeMarkerIdx+1+this.markerEles.length)%this.markerEles.length||0;this.clickThisMarder(this.markerEles[a]);this.activeMarkerIdx=a},switchTo:function(a){if(0>a||a>=this.markerEles.length)return!1;this.clickThisMarder(this.markerEles[a])}});return i},{attach:!1,
requires:["./base","template","anim"]});
KISSY.add("gallery/timeline/1.0/toolbar",function(b,f){function g(a){this.config=a;this.ATTRS=b.clone(i);this._init()}var d=b.all,i={html:{value:'<div class="timenav-toolbar">                <a hidefocus href="#" class="hide-timenav K_HideTimenav">hide</a>                <a hidefocus href="#" class="largen K_LargeRate">large</a>                <a hidefocus href="#" class="mini K_MiniRate">mini</a>                <a hidefocus href="#" class="left-scroll H_LeftScroll">left</a>                <a hidefocus href="#" class="right-scroll H_RightScroll">right</a>                <a hidefocus href="#" class="goto-last H_GotoLast">goto-last</a>              </div>'},cBox:{value:null},
hideTimenav:{value:null},largeRate:{value:null},miniRate:{value:null},leftScroll:{value:null},rightScroll:{value:null}};b.augment(g,f,b.EventTarget,{_init:function(){this.render();this.monitorEvent()},render:function(){var a=this.config;this.set("cBox",d(this.get("html")));this.get("cBox").appendTo(a.panel);this.set("hideTimenav",d(".K_HideTimenav",this.get("cBox")));this.set("largeRate",d(".K_LargeRate",this.get("cBox")));this.set("miniRate",d(".K_MiniRate",this.get("cBox")));this.set("leftScroll",
d(".H_LeftScroll",this.get("cBox")));this.set("rightScroll",d(".H_RightScroll",this.get("cBox")));this.set("gotoLast",d(".H_GotoLast",this.get("cBox")));this.fire("uiReady")},adjustStyle:function(){this.fire("styleReload")},monitorEvent:function(){var a=this;a.get("hideTimenav").on("click",function(b){b.halt();a.fire("toggle")});a.get("largeRate").on("click",function(b){b.halt();a.fire("large")});a.get("miniRate").on("click",function(b){b.halt();a.fire("mini")});a.get("leftScroll").on("click",function(b){b.halt();
a.fire("leftScroll")});a.get("rightScroll").on("click",function(b){b.halt();a.fire("rightScroll")});a.get("gotoLast").on("click",function(b){b.halt();a.fire("gotoLast")})}});return g},{attach:!1,requires:["./base"]});
