KISSY.add("gallery/digital-clock/1.0/digital-clock-js",function(e){var h='<div class="Kelement  Kvertical Ke1"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Kvertical Ke2"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Ke3"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement  Kvertical Ke4"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Kvertical Ke5"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Ke6"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Kex"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div>'.replace(/K/g,
"ks-digitalclock-"),i='<div class="Kcontainer"><div class="Kcolon1"><s class="Kcolon-top"></s><b class="Kcolon-bottom"></b></div><div class="Kcolon2"><s class="Kcolon-top"></s><b class="Kcolon-bottom"></b></div></div>'.replace(/K/g,"ks-digitalclock-"),j=e.Node,k={"0":126,1:48,2:236,3:248,4:178,5:218,6:222,7:114,8:255,9:251},g=e.UIBase.create([e.UIBase.Box.Render],{initializer:function(){},renderUI:function(){var a=this.get("el");a.html(h);for(var a=this._bars=a.children(),b=0;b<a.length;b++)a[b]=
new j(a[b])},_uiSetZoom:function(a){var b=this.get("el"),c=this._bars;b.css("margin-left",10*a+"px");b.css("margin-right",10*a+"px");b.css("width",120*a+"px");b.css("height",200*a+"px");b.all(".ks-digitalclock-element").each(function(d){d.css("height",97*a+"px")});b.all(".ks-digitalclock-vertical").each(function(d){d.css("width",20*a+"px")});b.all(".ks-digitalclock-bar").each(function(d){d.css("height",67*a+"px")});c[1].css("top",104*a+"px");c[3].css("top",104*a+"px");a>=this.get("zoomLimit")?(b.all(".ks-digitalclock-element").each(function(a){a.css("background-color",
"transparent")}),b.all(".ks-digitalclock-last").each(function(b){b.css("border-width",10*a+"px")}),b.all(".ks-digitalclock-first").each(function(b){b.css("border-width",10*a+"px")}),c[0].one(".ks-digitalclock-first").css("border-width",10*a+"px"),c[4].one(".ks-digitalclock-first").css("border-width",10*a+"px"),c[0].one(".ks-digitalclock-last").css("border-width",5*a+"px "+10*a+"px"),c[1].one(".ks-digitalclock-first").css("border-width",5*a+"px "+10*a+"px"),c[1].one(".ks-digitalclock-last").css("border-width",
10*a+"px"),c[3].one(".ks-digitalclock-last").css("border-width",10*a+"px"),c[3].one(".ks-digitalclock-first").css("border-width",5*a+"px "+10*a+"px"),c[4].one(".ks-digitalclock-last").css("border-width",5*a+"px "+10*a+"px")):b.all(".ks-digitalclock-element").each(function(a){a.css("background-color","#565656")});c[3].css("left",99*a+"px");c[4].css("left",99*a+"px");b.all(".ks-digitalclock-horizonal").each(function(b){var c=20*a;b.css("width",107*a+"px");b.css("height",c+"px");b.css("left",6*a+"px");
b.one(".ks-digitalclock-bar").css("width",67*a+"px");b.one(".ks-digitalclock-bar").css("height",c+"px")});c[2].css("left",6*a+"px");c[2].css("top",180*a+"px");c[6].css("top",90*a+"px")},_uiSetValue:function(a,b){if(b&&"prevVal"in b)for(var c=k[a],d=c^k[b.prevVal],f=this._bars,e=0;e<f.length;e++){var c=c>>1,d=d>>1,g=f[e],h=d&1;c&1&&h?g.css("display",""):h&&g.css("display","none")}}},{ATTRS:{elCls:{value:"ks-digitalclock-container"},value:{value:8},zoomLimit:{value:0.2},zoom:1}});return e.UIBase.create([e.UIBase.Box.Render],
{initializer:function(){},renderUI:function(){for(var a=this.get("el"),b=this._ns=[],c=this.get("zoomLimit"),d=0;2>d;d++)b.unshift(new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0}));this._colon=(new j(i)).appendTo(a);this._colonVisible=!0;for(var d=0;2>d;d++)b.unshift(new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0}));for(d=0;2>d;d++){var f=new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0});f.get("el").addClass("ks-digitalclock-seconds");b.unshift(f)}},_uiSetZoom:function(a){var b,c=this._ns,
d=this._colon;for(b=0;2>b;b++)c[b].set("zoom",0.4*a);for(b=2;6>b;b++)c[b].set("zoom",a);d.css("width",30*a+"px");d.css("height",200*a+"px");d.all(".ks-digitalclock-colon-top").each(function(b){b.css("border-width",10*a+"px")});d.all(".ks-digitalclock-colon-bottom").each(function(b){b.css("border-width",10*a+"px")});d.one(".ks-digitalclock-colon1").css("left",10*a+"px");d.one(".ks-digitalclock-colon2").css("left",10*a+"px");d.one(".ks-digitalclock-colon1").css("top",60*a+"px");d.one(".ks-digitalclock-colon2").css("top",
90*a+"px");this.get("render").css("width",710*a+"px")},_uiSetDate:function(a){var b=this._ns,c=a.getHours(),d=this._colonVisible,f=a.getMinutes(),a=a.getSeconds();b[5].set("value",Math.floor(c/10));b[4].set("value",Math.floor(c%10));b[3].set("value",Math.floor(f/10));b[2].set("value",Math.floor(f%10));b[1].set("value",Math.floor(a/10));b[0].set("value",Math.floor(a%10));d=!d;this._colon.css("visibility",d?"visible":"hidden");this._colonVisible=d}},{ATTRS:{elCls:{value:"ks-digitalclock-border clearfix"},
date:{value:new Date},zoom:{value:1},zoomLimit:{value:0.2}}})},{requires:["node","uibase"]});
KISSY.add("gallery/digital-clock/1.0/digital-clock",function(e){var h='<div class="Kelement  Kvertical Ke1"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Kvertical Ke2"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Ke3"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement  Kvertical Ke4"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Kvertical Ke5"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Ke6"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div><div class="Kelement Khorizonal Kex"><s class="Kfirst"></s><div class="Kbar"></div><b class="Klast"></b></div>'.replace(/K/g,"ks-digitalclock-"),
i='<div class="Kcontainer"><div class="Kcolon1"><s class="Kcolon-top"></s><b class="Kcolon-bottom"></b></div><div class="Kcolon2"><s class="Kcolon-top"></s><b class="Kcolon-bottom"></b></div></div>'.replace(/K/g,"ks-digitalclock-"),j=e.Node,k={"0":126,1:48,2:236,3:248,4:178,5:218,6:222,7:114,8:255,9:251},g=e.UIBase.create([e.UIBase.Box.Render],{renderUI:function(){var a=this.get("el");a.html(h);for(var a=this._bars=a.children(),b=0;b<a.length;b++)a[b]=new j(a[b])},_uiSetZoom:function(a){var b=this.get("el"),
c=this._bars;b.css("width",120*a+"px");b.css("height",200*a+"px");a>=this.get("zoomLimit")?(b.all(".ks-digitalclock-element").each(function(a){a.css("background-color","transparent")}),b.all(".ks-digitalclock-last").each(function(b){b.css("border-width",10*a+"px")}),b.all(".ks-digitalclock-first").each(function(b){b.css("border-width",10*a+"px")}),c[0].one(".ks-digitalclock-first").css("border-width",10*a+"px"),c[4].one(".ks-digitalclock-first").css("border-width",10*a+"px"),c[0].one(".ks-digitalclock-last").css("border-width",
5*a+"px "+10*a+"px"),c[1].one(".ks-digitalclock-first").css("border-width",5*a+"px "+10*a+"px"),c[1].one(".ks-digitalclock-last").css("border-width",10*a+"px"),c[3].one(".ks-digitalclock-last").css("border-width",10*a+"px"),c[3].one(".ks-digitalclock-first").css("border-width",5*a+"px "+10*a+"px"),c[4].one(".ks-digitalclock-last").css("border-width",5*a+"px "+10*a+"px")):b.all(".ks-digitalclock-element").each(function(a){a.css("background-color","#565656")})},_uiSetValue:function(a,b){if(b&&"prevVal"in
b)for(var c=k[a],d=c^k[b.prevVal],f=this._bars,e=0;e<f.length;e++){var c=c>>1,d=d>>1,g=f[e],h=d&1;c&1&&h?g.css("display",""):h&&g.css("display","none")}}},{ATTRS:{elCls:{value:"ks-digitalclock-container"},value:{value:8},zoomLimit:{value:0.2},zoom:1}});return e.UIBase.create([e.UIBase.Box.Render],{renderUI:function(){for(var a=this.get("el"),b=this._ns=[],c=this.get("zoomLimit"),d=0;2>d;d++){var f=new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0});f.get("el").addClass("ks-digitalclock-seconds");
b.unshift(f)}for(d=0;2>d;d++)b.unshift(new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0}));this._colon=(new j(i)).prependTo(a);this._colonVisible=!0;for(var d=0;2>d;d++)b.unshift(new g({zoomLimit:c,render:a,elOrder:0,autoRender:!0}))},_uiSetZoom:function(a){var b,c=this._colon,d=this._ns;for(b=0;4>b;b++)d[b].set("zoom",a);for(b=4;6>b;b++)d[b].set("zoom",0.4*a);c.css("width",30*a+"px");c.css("height",200*a+"px");c.all(".ks-digitalclock-colon-top").each(function(b){b.css("border-width",10*a+"px")});
c.all(".ks-digitalclock-colon-bottom").each(function(b){b.css("border-width",10*a+"px")});this.get("render").css("width",710*a+"px")},_uiSetDate:function(a){var b=a.getHours(),c=this._ns,d=this._colonVisible,e=a.getMinutes(),a=a.getSeconds();c[0].set("value",Math.floor(b/10));c[1].set("value",Math.floor(b%10));c[2].set("value",Math.floor(e/10));c[3].set("value",Math.floor(e%10));c[4].set("value",Math.floor(a/10));c[5].set("value",Math.floor(a%10));d=!d;this._colon.css("visibility",d?"visible":"hidden");
this._colonVisible=d}},{ATTRS:{elCls:{value:"ks-digitalclock-border clearfix"},date:{value:new Date},zoom:{value:1},zoomLimit:{value:0.2}}})},{requires:["node","uibase"]});KISSY.add("gallery/digital-clock/1.0/index",function(e,h,i){return{DigitalClock:h,DigitalClockJS:i}},{requires:["./digital-clock","./digital-clock-js"]});
