KISSY.add("gallery/selectable/1.0/base",function(h){function i(c,d){d=d||{};"markupType"in d||(d.itemCls?d.markupType=1:d.items&&(d.markupType=2));d=h.merge(i.Config,d||{});this.container=f.get(c);this.config=d;this._init()}var f=h.DOM,b=h.Event;i.Config={markupType:0,itemCls:"ks-selectable-item",items:[],selectedItemCls:"ks-selectable-selected",invisibleItemCls:void 0,valueKey:"ks-data-value",selectedIndex:void 0,defaultDisplay:void 0};i.Plugins=[];h.augment(i,b.Target,{_init:function(){var c=this.config;
this._parseMarkup();this._buildValueMap();!this._selectBySelectedClass()&&void 0!==c.selectedIndex&&this.index(c.selectedIndex);c.defaultDisplay||(c.defaultDisplay=f.css(this.items[0],"display"));this.fire("init")},_parseMarkup:function(){var c=this.config,d=this.container,a=[];switch(c.markupType){case 0:a=f.children(d);break;case 1:a=f.query("."+c.itemCls,d);break;case 2:a=c.items}this.fullItems=this.items=h.makeArray(a)},_buildValueMap:function(){var c=this.config,d={};h.each(this.items,function(a){var g=
f.attr(a,c.valueKey);void 0!==g&&(d[g]=a)});this.valueMap=d},_cancelSelectedItem:function(){f.removeClass(this.items[this.selectedIndex],this.config.selectedItemCls);this.selectedIndex=void 0},_setSelectedItem:function(c){var d=this.items[c],a=this.config.selectedItemCls;d?(f.addClass(d,a),this.selectedIndex=c):this.selectedIndex=void 0},_selectBySelectedClass:function(){for(var c=null,d=this.items,a,g=!1,e=this.config,b=0,h=d.length;b<h;b++)a=d[b],f.hasClass(a,e.selectedItemCls)&&(null==c&&(c=b,
g=!0),f.removeClass(a,e.selectedItemCls));this.index(c);return g},index:function(c){if(void 0===c)return this.selectedIndex;void 0!==this.selectedIndex&&this._cancelSelectedItem();this._setSelectedItem(c);c=this.items[this.selectedIndex];void 0!==c&&this.fire("selectByIndex");return c},value:function(c){if(void 0===c){if(c=this.item())return f.attr(c,this.config.valueKey)}else if(c=this.valueMap[c])for(var b=0,a=this.items.length;b<a;b++)if(c===this.items[b])return this.index(b),this.fire("selectByValue"),
c},item:function(c){if(void 0===c){if(void 0!==this.selectedIndex)return this.items[this.selectedIndex]}else for(var b=0,a=this.items.length;b<a;b++)c===this.items[b]&&this.index(b)},prev:function(){void 0===this.selectedIndex&&(this.selectedIndex=0);this.index(0<this.selectedIndex?this.selectedIndex-1:this.items.length-1);this.fire("prev");return this.item()},next:function(){void 0===this.selectedIndex&&(this.selectedIndex=this.items.length-1);this.index(this.selectedIndex<this.items.length-1?this.selectedIndex+
1:0);this.fire("next");return this.item()},filter:function(b){var d=this.fullItems,a=[],g=this.config.invisibleItemCls;this.clearFilter();if(h.isFunction(b))return h.each(d,function(e){this.index(-1);b(e,this)?a.push(e):g?f.addClass(e,g):f.css(e,"display","none")},this),this.items=a,this.fire("filter"),a},clearFilter:function(){var b=this.config,d=b.invisibleItemCls;this.index(-1);this.items=this.fullItems;d?f.removeClass(this.items,d):f.css(this.items,"display",b.defaultDisplay);this.fire("clearFilter")}});
i.events={EVENT_INIT:"init",EVENT_SELECT_BY_INDEX:"selectByIndex",EVENT_SELECT_BY_VALUE:"selectByValue",EVENT_SELECT_BY_ITEM:"selectByItem",EVENT_PREV:"prev",EVENT_NEXT:"next",EVENT_FILTER:"filter",EVENT_CLEAR_FILTER:"clearFilter"};return i});
KISSY.add("gallery/selectable/1.0/combobox",function(h,i){function f(a,g){this.container=b.get(a);this.dropList=null;this.selectValue=void 0;g=g||{};this.config=h.merge(f.Config,g);this._init()}var b=h.DOM,c=h.Event,d=document;f.Config={triggerCls:"ks-combobox-trigger",textInputCls:"ks-combobox-textinput",dropListCls:"ks-combobox-droplist",valueKey:"ks-data-value",shim:!0,options:[],autoFilter:!0,selectedItemCls:"ks-combobox-selected",invisibleItemCls:void 0,selectedIndex:0};h.augment(f,c.Target,
{_init:function(){var a=this.config;"select"===this.container.tagName.toLowerCase()?(this.selectValue=this.container.value,this._parseSelect()):this._parseMarkup();a.shim&&this._initShim();this._initSelectable();this._setTextInput();this._bindEvent()},_parseSelect:function(){var a=this.config,g=this.container,e=b.attr(g,"name"),c=b.attr(g,"class"),d=b.attr(g,"id"),j=b.create('<div class="ks-combobox"></div>');b.addClass(j,c);b.attr(j,"id",d);this.valueInput=b.create('<input name="'+e+'" class="ks-combobox-valueinput" type="hidden"/>');
this.textInput=b.create('<input class="'+a.textInputCls+'" type="text"/>');this.trigger=b.create('<span class="'+a.triggerCls+'"></span>');j.appendChild(this.valueInput);j.appendChild(this.textInput);j.appendChild(this.trigger);this.container=j;b.insertBefore(this.container,g);b.remove(g);a.options=h.makeArray(g.options);this._renderDropList()},_parseMarkup:function(){for(var a=this.config,b=this.container.children,e,c=0,d=b.length;c<d;c++)switch(e=b[c],e.className){case "ks-combobox-valueinput":this.valueInput=
e;break;case a.textInputCls:this.textInput=e;break;case a.triggerCls:this.trigger=e;break;case a.dropListCls:this.dropList=e}this._renderDropList()},_renderDropList:function(){var a=this.config,g="",c=a.options,f=a.valueKey,k=this.container,j='<div class="'+a.dropListCls+'"><ul>';if(null==this.dropList&&h.isArray(a.options)){for(var k=0,i=c.length;k<i;k++)a=c[k],g+="<li "+f+'="'+a.value+'">'+a.text+"</li>";this.dropList=b.create(j+g+"</ul></div>")}else k.removeChild(this.dropList);b.css(this.dropList,
"width",this.textInput.offsetWidth);b.css(this.dropList,"position","absolute");d.body.appendChild(this.dropList);this.collapse()},_positionDropList:function(){var a,c,e,d;a=this.dropList;c=this.shim;e=this.container;d=b.height(e);e=b.offset(e);e.top+=d;b.css(a,"left",e.left);b.css(a,"top",e.top);b.css(c,"left",e.left);b.css(c,"top",e.top)},_initSelectable:function(){var a=this.config,b=this.selectValue;if(this.ul=this.dropList.getElementsByTagName("ul")[0])this.selectable=new i(this.ul,{valueKey:a.valueKey,
selectedItemCls:a.selectedItemCls,invisibleItemCls:a.invisibleItemCls,selectedIndex:a.selectedIndex});void 0!=b&&this.selectable.value(b);a=this.selectable.item();null!=a&void 0!=a&&(this.textInput.value=this.selectable.item().innerHTML)},_initShim:function(){this.shim=b.create('<iframe class="ks-combobox-shim" style="display:none;position:absolute;border:none;filter:alpha(opacity=0);"></iframe>');d.body.appendChild(this.shim)},_setShimRegion:function(){var a=this.dropList,c=b.width(a),a=b.height(a);
b.width(this.shim,c);b.height(this.shim,a)},_bindEvent:function(){var a=this,g=a.config,e=a.textInput,d=0,f;c.on(e,"keydown",function(b){b=b.keyCode;27===b?a.collapse():40===b||38===b?(0===d++?a._selectItem(40===b):3==d&&(d=0),a._setTextInput()):13===b?(a._setTextInput(),a.collapse()):9!=b&&(a.dropList.isShow||a.expand());f=e.value});c.on(e,"keyup",function(){var b=e.value;d=0;f!=b&&(a.selectable.clearFilter(),a.selectable.filter(function(a){return 0==a.innerHTML.indexOf(b)}))});c.on(a.trigger,"click",
function(){a.textInput.focus();a.textInput.select();a.dropList.isShow?a.collapse():(a.selectable.clearFilter(),a.expand())});c.on(a.textInput,"blur",function(){});c.on(a.dropList,"click",function(c){c=c.target;"li"==c.tagName.toLowerCase()&&(c=b.attr(c,g.valueKey),a.selectable.value(c),a._setTextInput(),a.collapse())});c.on(a.dropList,"mouseover",function(c){c=c.target;"li"==c.tagName.toLowerCase()&&(c=b.attr(c,g.valueKey),a.selectable.value(c))})},_selectItem:function(a){var b=this.selectable;a?
b.next():b.prev()},_setTextInput:function(){var a=this.selectable.value(),b=this.selectable.item();null!=b&&void 0!=b&&(this.textInput.value=b.innerHTML);this.valueInput.value=void 0!=a&&null!=a?this.selectable.value():""},add:function(a){var c=this.ul,e=this.cfg,d=this.selectable.selectedIndex;h.isPlainObject(a)&&c&&(a="<li "+e.valueKey+"="+a.value+" >"+a.text+"</li>",a=b.create(a),this.ul.appendChild(a),this.selectable=new i(c,{valueKey:e.valueKey,selectedItemCls:e.selectedItemCls,invisibleItemCls:e.invisibleItemCls,
selectedIndex:d}))},remove:function(a){var b=this.cfg,c=this.ul;h.isNumber(a)&&c&&c.remove(c.children[a]);this.selectable=new i(c,{valueKey:b.valueKey,selectedItemCls:b.selectedItemCls,invisibleItemCls:b.invisibleItemCls,selectedIndex:selectedIndex})},focus:function(){},disable:function(){},blur:function(){},expand:function(){this._positionDropList();b.show(this.dropList);b.show(this.shim);this._setShimRegion();this.dropList.isShow=!0},collapse:function(){b.hide(this.dropList);b.hide(this.shim);this.dropList.isShow=
!1},value:function(a){var b,c=this.ul,d;if(void 0!=a&&null!=a){this.textInput.value=a;for(var f=0,i=c.children.length;f<i;f++)if(d=c.children[f],h.trim(a)==h.trim(d.innerHTML)){b=f;break}this.selectable.index(b)}}});return f},{requires:["./base"]});KISSY.add("gallery/selectable/1.0/index",function(h,i,f){return{Selectable:i,ComboBox:f}},{requires:["./base","./combobox"]});
