KISSY.add("gallery/form/1.2/radio/index",function(l,p,q){function o(a,b){b=l.merge({target:a},b);o.superclass.constructor.call(this,b)}var d=p.all;l.extend(o,q,{render:function(){this._loadCss();this._replaceKfbtn();this._bindEvent()},recoverKfbtn:function(){var a,b=this.get("target"),c=this.get("kfbtn"),e=this.get("getLabelFunc");d(c).each(function(f,g){f.hide();d(b[g]).show();a=e?e(d(b[g])):f.next("label");a.detach("hover").detach("click")});return this},_replaceKfbtn:function(){var a=this,b=a.get("target"),
c=a._getHtml(0),e=a._getHtml(2),f=a._getHtml(1),g,h=[],m=a.get("accessible"),j=a.get("getLabelFunc"),n;if(b.length===0)return false;b.each(function(k){k.hide();if(a._isDisabled(k))g=d(e).insertBefore(k).attr("ks-kfbtn-disabled","disabled").removeAttr("tabindex");else{g=a._isSelected(k)?d(f):d(c);g.insertBefore(k)}if(m)try{n=j?j(k).text():k.next("label").text();g.attr("aria-label",n)}catch(r){l.log("html结构不符合");return false}h.push(g)});a.set("kfbtn",h)},_loadCss:function(){var a=this.get("cssUrl");
a!==""&&l.use(a,function(){})},_getHtml:function(a){var b=this.get("cls"),c=b.selected,e=b.disabled;b={defalutName:b.init};switch(a){case 0:b.secondName="";break;case 1:b.secondName=c;break;case 2:b.secondName=e}return l.substitute('<span tabindex="0" class="{defalutName} {secondName}"></span>',b)},_bindEvent:function(){var a=this,b=d(a.get("kfbtn")),c=this.get("cls").hover,e=a.get("hasLabel");a.get("target");a.get("getLabelFunc");b.each(function(f,g){f.on("mouseenter mouseleave",function(h){if(!(a._isSelected(f)||
a._isDisabled(f)))switch(h.type){case "mouseenter":f.addClass(c);break;case "mouseleave":f.removeClass(c)}}).on("click",function(){a._isDisabled(f)||a._clickHandler.call(a,g)}).on("keyup",function(h){h.keyCode===13&&f.fire("click")});e&&a._labelHandler(g,f)})},_labelHandler:function(a,b){var c=this,e=c.get("target"),f=d(c.get("kfbtn")),g=c.get("cls"),h=g.selected,m=g.hover,j=(g=c.get("getLabelFunc"))?g(d(e[a])):b.next("label");j.on("click",function(){if(!(c._isDisabled(f[a])||c._isSelected(f[a]))){j.contains(b)&&
b.detach("click");f.each(function(n){n.removeClass(h)});b.addClass(h);d(e[a]).prop("checked",true)}}).on("mouseenter",function(){if(!(c._isDisabled(f[a])||c._isSelected(f[a]))){j.contains(b)&&b.detach("mouseenter");b.addClass(m)}}).on("mouseleave",function(){if(!c._isDisabled(f[a])){j.contains(b)&&b.detach("mouseleave");b.removeClass(m)}})},_clickHandler:function(a){var b=this.get("target"),c=d(this.get("kfbtn"));kfbtn=d(this.get("kfbtn")[a]);getCls=this.get("cls");selectedClass=getCls.selected;hoverClass=
getCls.hover;d(b[a]).fire("click");c.each(function(e){e.removeClass(selectedClass).removeClass(hoverClass)});kfbtn.addClass(selectedClass)},_isDisabled:function(a){var b=d(a).attr("disabled");a=d(a).attr("ks-kfbtn-disabled");return b==="disabled"||a==="disabled"},_isSelected:function(a){var b=d(a).prop("checked");a=d(a).hasClass(this.get("cls").selected);return b||a},setDisabled:function(a){var b=this.get("kfbtn"),c=this.get("target"),e=this.get("cls"),f=e.selected,g=e.disabled;e=e.hover;if(typeof a===
"number"){b=d(b[a]);a=d(c[a]);b.attr("ks-kfbtn-disabled","disabled").removeClass(f+" "+e).addClass(g);a.attr("disabled","disabled");b.removeAttr("tabindex")}return this},setAvailabe:function(a){var b=this.get("kfbtn"),c=this.get("target"),e=this.get("cls").disabled;if(l.isNumber(a)){b=d(b[a]);a=d(c[a]);b.removeAttr("ks-kfbtn-disabled","disabled").removeClass(e);a.removeAttr("disabled","disabled");b.attr("tabindex","0")}return this},getSelected:function(a){var b=this.get("target"),c,e=[];i=0;for(len=
b.length;i<len;i++){c=d(b[i]);if(!this._isDisabled(c))if(this._isSelected(c)){if(!a)return i;e.push(i)}}return a?e:null}},{ATTRS:{target:{value:"",setter:function(a){return d(a)},getter:function(a){return d(a)}},kfbtn:{value:[]},cls:{value:{init:"ks-radio",selected:"ks-radio-selected",disabled:"ks-radio-disabled",hover:"ks-radio-hover"}},cssUrl:{value:"gallery/form/1.2/radio/themes/default/style.css"},hasLabel:{value:false},getLabelFunc:{value:undefined,setter:function(a){return a},getter:function(a){return a}},
accessible:{value:false}}});return o},{requires:["node","base"]});
