KISSY.add("gallery/juicer/1.0/index",function(a,b){return b},{requires:["./juicer"]});
KISSY.add("gallery/juicer/1.0/juicer",function(){var a=function(){var b=[].slice.call(arguments);b.push(a.options);if(1==arguments.length)return a.compile.apply(a,b);if(2<=arguments.length)return a.to_html.apply(a,b)};window.__escapehtml={__escapehash:{"<":"&lt;",">":"&gt;",'"':"&quot;","&":"&amp;"},__escapereplace:function(a){return __escapehtml.__escapehash[a]},__escape:function(a){return"string"!==typeof a?a:a.replace(/[&<>"]/igm,__escapehtml.__escapereplace)},__detection:function(a){return"undefined"===
typeof a?"":a}};a.__cache={};a.version="0.3.0-dev";a.settings={forstart:/{@each\s*([\w\.]*?)\s*as\s*(\w*?)(,\w*?)?}/igm,forend:/{@\/each}/igm,ifstart:/{@if\s*([^}]*?)}/igm,ifend:/{@\/if}/igm,elsestart:/{@else}/igm,interpolate:/\${([\s\S]+?)}/igm,noneencode:/\$\${([\s\S]+?)}/igm,inlinecomment:/{#[^}]*?}/igm,rangestart:/{@each\s*(\w*?)\s*in\s*range\((\d+?),(\d+?)\)}/igm};a.options={cache:!0,strip:!0,errorhandling:!0};a.set=function(a,c){this.options[a]=c};a.template=function(){var b=this;this.__interpolate=
function(a,d,e){var f=a.split("|"),b="";1<f.length&&(a=f.shift(),b=f.shift());return"<%= "+(d?"__escapehtml.__escape":"")+"("+(!e||!1!==e.detection?"__escapehtml.__detection":"")+"("+b+"("+a+"))) %>"};this.__shell=function(c,d){var e=0,c=c.replace(a.settings.forstart,function(a,c,d,b){d=d||"value";b=b&&b.substr(1);a="i"+e++;return"<% for(var "+a+"=0,l="+c+".length;"+a+"<l;"+a+"++) {var "+d+"="+c+"["+a+"];"+(b?"var "+b+"="+a+";":"")+" %>"}).replace(a.settings.forend,"<% } %>").replace(a.settings.ifstart,
function(a,c){return"<% if("+c+") { %>"}).replace(a.settings.ifend,"<% } %>").replace(a.settings.elsestart,function(){return"<% } else { %>"}).replace(a.settings.noneencode,function(a,c){return b.__interpolate(c,!1,d)}).replace(a.settings.interpolate,function(a,c){return b.__interpolate(c,!0,d)}).replace(a.settings.inlinecomment,"").replace(a.settings.rangestart,function(a,c,d,b){a="j"+e++;return"<% for(var "+a+"=0;"+a+"<"+(b-d)+";"+a+"++) {var "+c+"="+a+"; %>"});if(!d||!1!==d.errorhandling)c="<% try { %>"+
c+'<% } catch(e) {console && console.warn("Juicer Render Exception: "+e.message);} %>';return c};this.__pure=function(a,d){return this.__convert(a,!d||d.strip)};this.__lexical=function(c){var d=[],b="",f=function(a,c){var c=c.match(/\w+/igm)[0],b;if(d.indexOf)b=d.indexOf(c);else a:{for(b=0;b<d.length;b++)if(d[b]==c)break a;b=-1}-1===b&&d.push(c)};c.replace(a.settings.forstart,f).replace(a.settings.interpolate,f).replace(a.settings.ifstart,f);for(c=0;c<d.length;c++)b+="var "+d[c]+"=data."+d[c]+";";
return"<% "+b+" %>"};this.__convert=function(a,b){var e;e="var data=data||{};var out='';out+='";return e=!1!==b?e+(a.replace(/\\/g,"\\\\").replace(/[\r\t\n]/g," ").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,"';out+=$1;out+='").split("<%").join("';").split("%>").join("out+='")+"';return out;"):e+(a.replace(/\\/g,"\\\\").replace(/[\r]/g,"\\r").replace(/[\t]/g,"\\t").replace(/[\n]/g,"\\n").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,
"';out+=$1;out+='").split("<%").join("';").split("%>").join("out+='")+"';return out.replace(/[\\r\\n]\\t+[\\r\\n]/g,'\\r\\n');")};this.parse=function(a,b){if(!b||!1!==b.loose)a=this.__lexical(a)+a;a=this.__shell(a,b);a=this.__pure(a,b);this.render=new Function("data",'"use strict";'+a);return this}};a.compile=function(a,c){try{var d=this.__cache[a]?this.__cache[a]:(new this.template).parse(a,c);if(!c||!1!==c.cache)this.__cache[a]=d;return d}catch(e){return console&&console.warn("Juicer Compile Exception: "+
e.message),{render:function(){}}}};a.to_html=function(a,c,d){return this.compile(a,d).render(c)};return a});
