KISSY.add("gallery/form/1.2/radio/index",function(h,n,o){function j(a,b){b=h.merge({target:a},b);j.superclass.constructor.call(this,b)}var c=n.all;h.extend(j,o,{render:function(){this._loadCss();this._replaceKfbtn();this._bindEvent()},recoverKfbtn:function(){var a,b=this.get("target"),d=this.get("kfbtn"),e=this.get("getLabelFunc");c(d).each(function(d,f){d.hide();c(b[f]).show();a=e?e(c(b[f])):d.next("label");a.detach("hover").detach("click")});return this},_replaceKfbtn:function(){var a=this,b=a.get("target"),
d=a._getHtml(0),e=a._getHtml(2),g=a._getHtml(1),f,l=[],p=a.get("accessible"),k=a.get("getLabelFunc"),m;if(0===b.length)return!1;b.each(function(b){b.hide();a._isDisabled(b)?f=c(e).insertBefore(b).attr("ks-kfbtn-disabled","disabled").removeAttr("tabindex"):(f=a._isSelected(b)?c(g):c(d),f.insertBefore(b));if(p)try{m=k?k(b).text():b.next("label").text(),f.attr("aria-label",m)}catch(j){return h.log("html结构不符合"),!1}l.push(f)});a.set("kfbtn",l)},_loadCss:function(){var a=this.get("cssUrl");""!==a&&h.use(a,
function(){})},_getHtml:function(a){var b=this.get("cls"),d=b.selected,c=b.disabled,b={defalutName:b.init};switch(a){case 0:b.secondName="";break;case 1:b.secondName=d;break;case 2:b.secondName=c}return h.substitute('<span tabindex="0" class="{defalutName} {secondName}"></span>',b)},_bindEvent:function(){var a=this,b=c(a.get("kfbtn")),d=this.get("cls").hover,e=a.get("hasLabel");a.get("target");a.get("getLabelFunc");b.each(function(b,c){b.on("mouseenter mouseleave",function(c){if(!a._isSelected(b)&&
!a._isDisabled(b))switch(c.type){case "mouseenter":b.addClass(d);break;case "mouseleave":b.removeClass(d)}}).on("click",function(){a._isDisabled(b)||a._clickHandler.call(a,c)}).on("keyup",function(a){13===a.keyCode&&b.fire("click")});e&&a._labelHandler(c,b)})},_labelHandler:function(a,b){var d=this,e=d.get("target"),g=c(d.get("kfbtn")),f=d.get("cls"),h=f.selected,j=f.hover,k=(f=d.get("getLabelFunc"))?f(c(e[a])):b.next("label");k.on("click",function(){!d._isDisabled(g[a])&&!d._isSelected(g[a])&&(k.contains(b)&&
b.detach("click"),g.each(function(a){a.removeClass(h)}),b.addClass(h),c(e[a]).prop("checked",!0))}).on("mouseenter",function(){!d._isDisabled(g[a])&&!d._isSelected(g[a])&&(k.contains(b)&&b.detach("mouseenter"),b.addClass(j))}).on("mouseleave",function(){d._isDisabled(g[a])||(k.contains(b)&&b.detach("mouseleave"),b.removeClass(j))})},_clickHandler:function(a){var b=this.get("target"),d=c(this.get("kfbtn"));kfbtn=c(this.get("kfbtn")[a]);getCls=this.get("cls");selectedClass=getCls.selected;hoverClass=
getCls.hover;c(b[a]).fire("click");d.each(function(a){a.removeClass(selectedClass).removeClass(hoverClass)});kfbtn.addClass(selectedClass)},_isDisabled:function(a){var b=c(a).attr("disabled"),a=c(a).attr("ks-kfbtn-disabled");return"disabled"===b||"disabled"===a},_isSelected:function(a){var b=c(a).prop("checked"),a=c(a).hasClass(this.get("cls").selected);return b||a},setDisabled:function(a){var b=this.get("kfbtn"),d=this.get("target"),e=this.get("cls"),g=e.selected,f=e.disabled,e=e.hover;"number"===
typeof a&&(b=c(b[a]),a=c(d[a]),b.attr("ks-kfbtn-disabled","disabled").removeClass(g+" "+e).addClass(f),a.attr("disabled","disabled"),b.removeAttr("tabindex"));return this},setAvailabe:function(a){var b=this.get("kfbtn"),d=this.get("target"),e=this.get("cls").disabled;h.isNumber(a)&&(b=c(b[a]),a=c(d[a]),b.removeAttr("ks-kfbtn-disabled","disabled").removeClass(e),a.removeAttr("disabled","disabled"),b.attr("tabindex","0"));return this},getSelected:function(a){var b=this.get("target"),d,e=[];i=0;for(len=
b.length;i<len;i++)if(d=c(b[i]),!this._isDisabled(d)&&this._isSelected(d)){if(!a)return i;e.push(i)}return a?e:null}},{ATTRS:{target:{value:"",setter:function(a){return c(a)},getter:function(a){return c(a)}},kfbtn:{value:[]},cls:{value:{init:"ks-radio",selected:"ks-radio-selected",disabled:"ks-radio-disabled",hover:"ks-radio-hover"}},cssUrl:{value:"gallery/form/1.2/radio/themes/default/style.css"},hasLabel:{value:!1},getLabelFunc:{value:void 0,setter:function(a){return a},getter:function(a){return a}},
accessible:{value:!1}}});return j},{requires:["node","base"]});
