KISSY.add("gallery/countdown/1.0/countdown",function(e){function g(a,d){if(!(this instanceof g))return new g(a,d);if(a=e.get(a))this.container=a,this.config=e.merge(g.Config,d),this._init()}var b=e.DOM;g.Config={effect:"normal",_varReg:/\$\{([\-\w]+)\}/g,_clock:["d",100,2,"h",24,2,"m",60,2,"s",60,2,"u",10,1]};var h=function(){function a(){for(var b=+new Date,h=100-b+a.lastTime,f,e;c.length;)c.shift()();f=0;for(e=d.length;f<e;f+=2)if(d[f+1]+=2,21===d[f+1]||0===(d[f+1]&1))d[f](b),d[f+1]&=1;a.lastTime=
b;setTimeout(a,0<h?h:0)}var d=[],c=[];a.lastTime=+new Date;setTimeout(a,100);return{add:function(a,b){c.push(function(){d.push(a);d.push(1E3===b?1:0)})},remove:function(a){c.push(function(){-1!==e.indexOf(a,d)&&d.splice(e.indexOf(a,d),2)})}}}();e.augment(g,e.EventTarget,{_init:function(){var a=this,d=a.config,c=d._varReg,i=d._clock,g=a.container,f=[];this._notify=[];a.hands=f;a.frequency=1E3;a.total=parseInt(b.attr(g,"data-time"),10);a.startAt=+new Date;c.lastIndex=0;g.innerHTML=g.innerHTML.replace(c,
function(d,b){if("u"===b||"s-ext"===b)a.frequency=100;var c="";"s-ext"===b?(f.push({type:"s"}),f.push({type:"u"}),c=a._html("","s","handlet")+a._html(".","","digital")+a._html("","u","handlet")):f.push({type:b});return a._html(c,b,"hand")});e.each(f,function(a){var d=a.type,b=100,c;a.node=e.one(g).one(".hand-"+d);for(c=i.length-3;-1<c&&d!==i[c];c-=3)b*=i[c+1];a.base=b;a.radix=i[c+1];a.bits=i[c+2]});a._reflow(a.startAt);var k=a._reflow;a._reflow=function(c){return k.call(a,c)};h.add(a._reflow,a.frequency);
b.css(g,"display","block")},_reflow:function(a){var d=this.total+this.startAt-a;d<this.frequency&&h.remove(this._reflow);e.each(this.hands,function(a){a.lastValue=a.value;a.value=Math.floor(d/a.base)%a.radix});this._repaint();this._notify[d]&&e.each(this._notify[d],function(a){a()});return this},_repaint:function(){g.Effects[this.config.effect].paint.apply(this);this.fire("afterPaint")},_toDigitals:function(a,d){for(var a=0>a?0:a,b=[];d--;)b[d]=a%10,a=Math.floor(a/10);return b},_html:function(a,b,
c){e.isArray(a)&&(a=a.join(""));switch(c){case "hand":b=c+" hand-"+b;break;case "handlet":b=c+" hand-"+b;break;case "digital":b="."===a?c+" "+c+"-point "+b:c+" "+c+"-"+a+" "+b}return'<s class="'+b+'">'+a+"</s>"},notify:function(a,b){var c=this._notify[a]||[];c.push(b);this._notify[a]=c;return this}});return g});
KISSY.add("gallery/countdown/1.0/effects",function(e,g){g.Effects={normal:{paint:function(){var b=this,h;e.each(b.hands,function(a){a.lastValue!==a.value&&(h="",e.each(b._toDigitals(a.value,a.bits),function(a){h+=b._html(a,"","digital")}),a.node.html(h))})}},slide:{paint:function(){var b=this,h,a,d,c;e.each(b.hands,function(e){if(e.lastValue!==e.value){h="";a=e.bits;d=b._toDigitals(e.value,a);for(c=void 0===e.lastValue?d:b._toDigitals(e.lastValue,a);a--;)h=c[a]!==d[a]?b._html([b._html(d[a],"","digital"),
b._html(c[a],"","digital")],"slide-wrap")+h:b._html(d[a],"","digital")+h;e.node.html(h)}});g.Effects.slide.afterPaint.apply(b)},afterPaint:function(){e.each(this.hands,function(b){if(b.lastValue!==b.value&&void 0!==b.lastValue){var b=b.node,e=b.one(".digital").height();b.css("height",e);b.all(".slide-wrap").css("top",-e).animate("top: 0",0.5,"easeIn")}})}},flip:{paint:function(){var b=this,h,a,d;e.each(b.hands,function(c){c.lastValue!==c.value&&(d=a=h="",e.each(b._toDigitals(c.value,c.bits),function(c){a+=
b._html(c,"","digital")}),void 0===c.lastValue?c.node.html(a):(a=b._html(a,"handlet"),e.each(b._toDigitals(c.lastValue,c.bits),function(a){d+=b._html(a,"","digital")}),h=b._html(d,"handlet mask"),d=b._html(d,"handlet"),c.node.html(a+d+h)))});g.Effects.flip.afterPaint.apply(b)},afterPaint:function(){e.each(this.hands,function(b){if(b.lastValue!==b.value&&void 0!==b.lastValue){var b=b.node,e=b.all(".handlet"),a=e.item(0),d=e.item(1),c=e.item(2),g=b.width(),j=b.height(),f=Math.floor(j/2);d.css({clip:"rect("+
f+"px, "+g+"px, "+j+"px, 0)"});c.css({overflow:"hidden",height:f+"px"});c.animate({top:f+"px",height:0},0.15,"easeNone",function(){c.html(a.html());c.css({top:0,height:f+"px",clip:"rect("+f+"px, "+g+"px, "+j+"px, 0)"});c.animate("height: "+j+"px",0.3,"bounceOut")})}})}}}},{requires:["./countdown"]});KISSY.add("gallery/countdown/1.0/index",function(e,g){return g},{requires:["./countdown","./effects"]});
