KISSY.add("gallery/form/1.1/uploader/auth/base",function(c,i,h){function f(a,b){b=c.merge({uploader:a},b);f.superclass.constructor.call(this,b);this._init()}var d=d||c;c.mix(f,{event:{ERROR:"error"}});c.extend(f,h,{_init:function(){var a=this,b=a.get("uploader"),e=b.get("queue");if(""==b)return d.log("[uploader-auth]:uploader不可以为空！"),!1;a._setSwfButtonExt();e.on("add",function(b){b=b.file;a.testAllowExt(b);a.testMaxSize(b);a.testRepeat(b)});e.on("remove",function(b){"success"==b.file.status&&a.testMax()});
b.on("success",function(){a.testMax()});b.on("error",function(){b.set("isAllowUpload",!0)})},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(a){return this.get("rules")[a]},isUploaderType:function(a){var b=this.get("uploader").get("type");return a==b},testRequire:function(){var a=this.get("uploader").get("urlsInput").get("urls"),b=this.getRule("require"),e=b?b[0]:!1,a=0<a.length;if(!e)return!0;a||(c.log("[uploader-auth]:"+b[1]),this.fire(f.event.ERROR,{rule:"require",
msg:b[1],value:e}));return a},testAllowExt:function(a){function b(a){a=a.split(".");return a[a.length-1]}if(!c.isObject(a))return!1;var e=a.name,g=this.getRule("allowExts"),k=[],d;if(!c.isArray(g))return!1;k=this._getExts(g[0].ext);d=function(a){var b=!1,e;c.each(k,function(c){e=RegExp("^.+."+c+"$");if(e.test(a))return b=!0});return b}(e);d||(e=b(e),e=c.substitute(g[1],{ext:e}),this._stopUpload(a,e),this.fire(f.event.ERROR,{rule:"allowExts",msg:e,value:g[0]}));return d},testMax:function(){var a=this.get("uploader"),
b=a.get("queue").getFiles("success").length,e=this.getRule("max");if(e){var c=a.get("button");(b=b<e[0])?(c.set("disabled",!1),a.set("isAllowUpload",!0)):(c.set("disabled",!0),a.set("isAllowUpload",!1),this.fire(f.event.ERROR,{rule:"max",msg:e[1],value:e[0]}));return b}},testMaxSize:function(a){var b=a.size,e=this.getRule("maxSize");if(e){var d=1E3*Number(e[0]),b=b<=d;b||(d=c.substitute(e[1],{maxSize:c.convertByteSize(d),size:a.textSize}),this._stopUpload(a,d),this.fire(f.event.ERROR,{rule:"maxSize",
msg:d,value:e[0]}));return b}},testRepeat:function(a){if(!c.isObject(a))return!1;var b=this,e=a.name,d=b.getRule("allowRepeat");if(d){var k=d[0],j=d[1],l=b.get("uploader").get("queue").getFiles("success"),m=!1;if(k)return!1;c.each(l,function(c){if(c.name==e)return b._stopUpload(a,j),b.fire(f.event.ERROR,{rule:"allowRepeat",msg:j,value:d[0]}),m=!0});return m}},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.getRule("allowExts"),a=a.get("button");if(!this.isUploaderType("flash")||!c.isArray(b))return!1;
a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!c.isString(a))return!1;var b=a.split(";"),e=[],d=/^\*\./;c.each(b,function(a){a=a.replace(d,"");e.push(a.toUpperCase())});c.each(e,function(a){b.push(a)});return b},_stopUpload:function(a,b){c.isString(b)||(b="");var e=this.get("uploader").get("queue"),d=e.getFileIndex(a.id);e.fileStatus(d,e.constructor.status.ERROR,{msg:b})}},{ATTRS:{uploader:{value:""},rules:{value:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},
"不支持{ext}格式的文件上传！"],require:[!1,"必须至少上传一个文件！"],max:[3,"每次最多上传{max}个文件！"],maxSize:[1E3,"文件大小为{size}，文件太大！"],allowRepeat:[!1,"该文件已经存在！"]}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/base",function(c,i,h,f,d,a,b){function e(a){e.superclass.constructor.call(this,a)}var g=h.all;c.mix(e,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});c.extend(e,
i,{render:function(){var a=this.get("serverConfig"),b=this.getUploadType(this.get("type")),d=b.event,g;if(!b)return!1;this.set("urlsInput",this._renderUrlsInput());this._renderQueue();g=this._renderButton();this.get("type")==e.type.FLASH&&c.mix(a,{swfUploader:g.get("swfUploader")});a=new b(a);a.on(d.SUCCESS,this._uploadCompleteHanlder,this);if(d.PROGRESS)a.on(d.PROGRESS,this._uploadProgressHandler,this);a.on(d.STOP,this._uploadStopHanlder,this);this.set("uploadType",a);this.fire(e.event.RENDER);return this},
upload:function(a){if(!c.isNumber(a))return!1;var b=this.get("uploadType"),d=this.get("type"),g=this.get("queue"),f=g.get("files")[a],h;if(!c.isPlainObject(f))return c.log("[uploader]:队列中不存在id为"+a+"的文件"),!1;if(""!=this.get("curUploadIndex"))return alert("第"+this.get("curUploadIndex")+"文件正在上传，请上传完后再操作！"),!1;h=f.input.id||f.input;"ajax"==d&&(h=f.data);if("error"===f.status)return!1;this.fire(e.event.START,{index:a,file:f});if(!this.get("isAllowUpload"))return!1;this.set("curUploadIndex",a);g.fileStatus(a,
e.status.START);b.upload(h)},cancel:function(a){var b=this.get("uploadType"),d=this.get("queue"),g=e.status,f=d.fileStatus(a);c.isNumber(a)&&f!=g.SUCCESS?d.fileStatus(a,g.CANCEL):(b.stop(),this._continueUpload());return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(a){c.isString(a)||(a=e.status.WAITING);this.set("uploadFilesStatus",a);this._uploaderStatusFile(a);return this},_uploaderStatusFile:function(a){a=this.get("queue").getIndexs(a);if(!a.length)return this.set("uploadFilesStatus",
""),this.fire(e.event.UPLOAD_FILES),!1;this.upload(a[0]);return this},isSupportAjax:function(){var a=!1;try{FormData&&(a=!0)}catch(b){a=!1}return a},isSupportFlash:function(){var a=c.UA.fpv();return c.isArray(a)&&0<a.length},getUploadType:function(a){var b=this,d=e.type,g;a==d.AUTO&&(a=[d.AJAX,d.IFRAME]);c.isArray(a)&&0<a.length?c.each(a,function(a){if(g=b._getType(a))return!1}):g=b._getType(a);return g},_getType:function(g){var f=e.type,l=this.isSupportAjax(),m=this.isSupportFlash();switch(g){case f.IFRAME:f=
d;break;case f.AJAX:f=l&&a||!1;break;case f.FLASH:f=m&&b||!1;break;default:return c.log("[uploader]:type参数不合法"),!1}f&&c.log("[uploader]:使用"+g+"上传方式");this.set("type",g);return f},_renderButton:function(){var a=this.get("button");if(!c.isObject(a))return c.log("[uploader]:button参数不合法！"),!1;a.on("change",this._select,this);a.render();return a},_renderQueue:function(){var a=this.get("queue"),b=this.get("urlsInput");if(!c.isObject(a))return c.log("[uploader]:queue参数不合法"),!1;a.set("uploader",this);a.on("remove",
function(a){b.remove(a.file.sUrl)});return a},_select:function(a){var b=this,d=b.get("autoUpload"),g=b.get("queue"),f=b.get("curUploadIndex"),h=a.files;c.each(h,function(b){b.size||(b.size=0);b.name||(b.name=b.fileName||"");b.input=a.input||b});b.fire(e.event.SELECT,{files:h});if(!b.get("isAllowUpload"))return!1;g.add(h,function(){""==f&&d&&b.uploadFiles()})},_renderUrlsInput:function(){var a=this.get("button").get("target"),b=this.get("urlsInputName"),a=new f(a,{name:b});a.render();return a},_uploadCompleteHanlder:function(a){var a=
a.result,b,d=e.event,g=this.get("queue"),f=this.get("curUploadIndex");if(!c.isObject(a))return!1;g.updateFile(f,{result:a});b=Number(a.status);1===b?(g.fileStatus(f,e.status.SUCCESS),this._success(a.data),this.fire(d.SUCCESS,{index:f,file:g.getFile(f),result:a})):(g.fileStatus(f,e.status.ERROR,{msg:a.msg||a.message||"",result:a}),this.fire(d.ERROR,{status:b,result:a}));this.set("curUploadIndex","");this.fire(d.COMPLETE,{index:f,file:g.getFile(f),result:a});this._continueUpload()},_uploadStopHanlder:function(){var a=
this.get("queue"),b=this.get("curUploadIndex");a.fileStatus(b,e.status.CANCEL);this.set("curUploadIndex","");this.fire(e.event.CANCEL,{index:b})},_continueUpload:function(){var a=this.get("uploadFilesStatus");""!=a&&this._uploaderStatusFile(a)},_uploadProgressHandler:function(a){var b=this.get("queue"),d=this.get("curUploadIndex"),g=b.getFile(d);c.mix(a,{file:g});b.fileStatus(d,e.status.PROGRESS,a);this.fire(e.event.PROGRESS,a)},_success:function(a){if(!c.isObject(a))return!1;var a=a.url,b=this.get("urlsInput"),
e=this.get("curUploadIndex"),d=this.get("queue");if(!c.isString(a)||!c.isObject(b))return!1;d.updateFile(e,{sUrl:a});b.add(a)},restore:function(a){var b=this.get("queue"),e=this.get("urlsInput");a||(a=this._getRestoreData());if(!a.length)return!1;c.each(a,function(a){!a.sUrl&&a.result&&(a.sUrl=a.result.data.url);var c=b.add(a),d=c.id,g=b.getFileIndex(d);e.add(a.sUrl);b.fileStatus(g,"success",{index:g,id:d,file:c})})},_getRestoreData:function(){var a=this.get("restoreHook"),a=g(a);return!a.length?
[]:c.JSON.parse(a.html())}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:e.type.AUTO},serverConfig:{value:{action:"",data:{},dataType:"json"}},isAllowUpload:{value:!0},autoUpload:{value:!0},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""},restoreHook:{value:""}}});c.convertByteSize=function(a){var b=-1;do a/=1024,b++;while(99<a);return Math.max(a,0.1).toFixed(1)+"kB,MB,GB,TB,PB,EB".split(",")[b]};return e},{requires:"base,node,./urlsInput,./type/iframe,./type/ajax,./type/flash,flash".split(",")});
KISSY.add("gallery/form/1.1/uploader/button/base",function(c,i,h){function f(a,b){b=c.merge({target:d(a)},b);f.superclass.constructor.call(this,b)}var d=i.all;c.mix(f,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(a){return a.replace(/.*(\/|\\)/,"")}});c.extend(f,h,{render:function(){var a=this.get("target");if(!1===this.fire(f.event.beforeRender))return c.log("[Uploader-Button] button render was prevented."),
!1;if(null==a)return c.log("[Uploader-Button] Cannot find target!"),!1;this._createInput();this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));this.fire(f.event.afterRender);return this},show:function(){this.get("target").show();this.fire(f.event.afterShow);return f},hide:function(){this.get("target").hide();this.fire(f.event.afterHide);return f},reset:function(){var a=this.get("inputContainer");d(a).remove();this.set("inputContainer","");this.set("fileInput","");this._createInput();
return this},_createInput:function(){var a=this.get("target"),b=this.get("name"),e=this.get("tpl");if(!c.isString(b)||!c.isString(e))return c.log("[Uploader-Button] No name or tpl specified."),!1;b=c.substitute(e,{name:b});b=d(b);d(b).appendTo(a);a=d(b).children("input");d(a).on("change",this._changeHandler,this);this.set("fileInput",a);this.set("inputContainer",b);return b},_changeHandler:function(a){var b=this.get("fileInput"),e=d(b).val(),a=a.target.files,g=[];if(""==e)return c.log("[Uploader-Button] No file selected."),
!1;a?c.each(a,function(a){c.isObject(a)&&g.push({name:a.name,type:a.type,size:a.size,data:a})}):g.push({name:f.getFileName(e)});this.fire(f.event.CHANGE,{files:g,input:b.getDOMNode()});this.reset()},_setDisabled:function(a){var b=this.get("cls").disabled,e=this.get("target"),g=this.get("fileInput");if(!e.length||!c.isBoolean(a))return!1;a?(e.addClass(b),d(g).hide()):(e.removeClass(b),d(g).show());return a},_setMultiple:function(a){var b=this.get("fileInput");if(!b.length)return!1;a&&b.attr("multiple",
"multiple")||b.removeAttr("multiple");return a}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper"><input type="file" name="{name}" hidefoucs="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(a){this.get("fileInput")&&d(this.get("fileInput")).attr("name",a);return a}},disabled:{value:!1,setter:function(a){this._setDisabled(a);return a}},multiple:{value:!0,setter:function(a){this._setMultiple(a);return a}},
cls:{value:{disabled:"uploader-button-disabled"}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/button/swfButton",function(c,i,h,f){function d(b,e){e=c.merge({target:a(b)},e);d.superclass.constructor.call(this,e)}var a=i.all;c.mix(d,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});c.extend(d,h,{render:function(){var a=this,c=a.get("target"),g,f=a.get("multiple"),h=a.get("fileFilters");c.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
g=a._initSwfUploader();g.on("contentReady",function(){g.browse(f,h);a._bindBtnEvent();g.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(d.event.RENDER)},a)},_createSwfWrapper:function(){var b=this.get("target"),e=this.get("tpl"),d=""!=this.get("swfWrapperId")&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+c.guid(),e=c.substitute(e,{id:d});this.set("swfWrapperId",d);return a(e).appendTo(b)},_initSwfUploader:function(){var a=this.get("flash"),c=this.get("swfWrapperId"),
d;try{d=new f(c,a),this.set("swfUploader",d)}catch(k){}return d},_bindBtnEvent:function(){var a=this,e=d.event,g=a.get("swfUploader");if(!g)return!1;c.each(e,function(c){g.on(c,function(){a.fire(c)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),e=this.get("target");c.mix(a.attrs,{width:e.width(),height:e.height()});this.set("flash",a)},_changeHandler:function(a){this.fire(d.event.CHANGE,{files:a.fileList})},_setDisabled:function(a){var e=this.get("swfUploader"),d=this.get("cls").disabled,
f=this.get("target"),h=this.get("swfWrapper");if(!e||!c.isBoolean(a))return!1;a?(f.addClass(d),h.hide()):(f.removeClass(d),h.show());return a}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;"></div>'},multiple:{value:!0,setter:function(a){var c=this.get("swfUploader");c&&c.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var e=this.get("swfUploader");e&&c.isArray(a)&&
e.filter(a);return a}},disabled:{value:!1,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.1/uploader/plugins/ajbridge/uploader.swf",id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:!0,btn:!0}},swfUploader:{value:""}}});return d},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.1/uploader/index",function(c,i,h,f,d,a,b,e){function g(a,b,e){e=c.mix(c.form.parseConfig(a),e);g.superclass.constructor.call(this,e);this.set("buttonTarget",a);this.set("queueTarget",b);this.set("uploaderConfig",e);this._init()}var k=h.all,j=["default","imageUploader","ershouUploader"];c.namespace("form");c.form.parseConfig=function(a,b){var e={},d,g=b||"data-config";d=k(a).attr(g);if(!c.isString(d))return{};try{e=c.JSON.parse(d)}catch(f){c.log("[uploaderRender]:请检查"+a+"上"+
g+"属性内的json格式是否符合规范！")}return e};c.extend(g,i,{_init:function(){var a=this,b=a._initButton(),e=a._initQueue(),d=a._initUploader(b,e),g=a._auth(),f={uploader:d,button:b,queue:e,auth:g},k=a.get("theme");a.set("button",b);""==k?c.later(function(){a.fire("init",f)},500):a._initThemes(function(c){c.set("uploader",d);c.set("button",b);c.set("queue",e);c.set("auth",g);c._UploaderRender(function(){d.restore();c.afterUploaderRender(d);a.fire("init",f)})})},_initUploader:function(a,b){var e=this.get("uploaderConfig"),
d=this.get("name");c.mix(e.serverConfig,{fileDataName:d});c.mix(e,{button:a,queue:b});e=new f(e);e.render();this.set("uploader",e);return e},_initButton:function(){var b=this.get("buttonTarget"),e=c.form.parseConfig(b,"data-button-config"),g=this.get("name"),f=this.get("type"),e=c.merge({name:g},e);return"flash"!=f&&new d(b,e)||new a(b)},_initQueue:function(){return new e},_initThemes:function(a){var b=this,e=b.get("theme"),d=b.get("buttonTarget"),g=c.form.parseConfig(d,"data-theme-config"),e=b._getThemeName(e);
c.use(e,function(e,c){var d=b.get("queueTarget");e.mix(g,{queueTarget:d});d=new c(g);a&&a.call(b,d)})},_getThemeName:function(a){var b=a;c.each(j,function(e){e==a&&(b="gallery/form/1.1/uploader/themes/"+a)});return b+="/index"},_auth:function(){var a=this.get("buttonTarget"),e=this.get("uploader"),d="";k(a).attr("data-auth")?(a=c.form.parseConfig(a,"data-auth"),d=new b(e,{rules:a}),e.set("auth",d)):c.log("[uploaderRender]:缺少data-auth验证配置，无启动验证！");return d}},{ATTRS:{theme:{value:"gallery/form/1.1/uploader/themes/default"},
buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},button:{value:""},queue:{value:""},uploader:{value:""}}});return g},{requires:"base,node,./base,./button/base,./button/swfButton,./auth/base,./queue".split(",")});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/ajbridge",function(c,i){function h(e,g,k){var e=e.replace(f,""),g=i._normalize(g||{}),j=this,e=f+e,l=function(a){1>a.status?j.fire("failed",{data:a}):(c.mix(j,a),(!a.dynamic||!g.src)&&j.activate())};g.id=g.id||c.guid(d);h.instances[g.id]=j;g.src&&(g.params.allowscriptaccess="always",g.params.flashvars=c.merge(g.params.flashvars,{jsEntry:b,swfID:g.id}));k?j.__args=[e,g,l]:c.later(i.add,a,!1,i,[e,g,l])}var f="#",d="ks-ajb-",a=100,b="KISSY.AJBridge.eventHandler";
c.app(h,{version:"1.0.15",instances:{},eventHandler:function(a,b){var c=h.instances[a];c&&c.__eventHandler(a,b)},augment:function(a,b){c.isString(b)&&(b=[b]);c.isArray(b)&&c.each(b,function(b){a.prototype[b]=function(){try{return this.callSWF(b,c.makeArray(arguments))}catch(a){this.fire("error",{message:a})}}})}});c.augment(h,c.EventTarget,{init:function(){this.__args&&(i.add.apply(i,this.__args),this.__args=null,delete this.__args)},__eventHandler:function(a,b){var d=b.type;b.id=a;switch(d){case "log":c.log(b.message);
break;default:this.fire(d,b)}},callSWF:function(a,b){b=b||[];try{if(this.swf[a])return this.swf[a].apply(this.swf,b)}catch(c){var d="";0!==b.length&&(d="'"+b.join("','")+"'");return(new Function("self","return self.swf."+a+"("+d+");"))(this)}}});h.augment(h,["activate","getReady","getCoreVersion"]);return window.AJBridge=c.AJBridge=h},{requires:["flash"]});
KISSY.add("gallery/form/1.1/uploader/plugins/ajbridge/uploader",function(c,i,h){function f(d,a){var a=a||{},b={};c.each(["ds","dsp","btn","hand"],function(c){c in a&&(b[c]=a[c])});a.params=a.params||{};a.params.flashvars=c.merge(a.params.flashvars,b);f.superclass.constructor.call(this,d,a)}c.extend(f,h);h.augment(f,"setFileFilters,filter,setAllowMultipleFiles,multifile,browse,upload,uploadAll,cancel,getFile,removeFile,lock,unlock,setBtnMode,useHand,clear".split(","));f.version="1.0.1";h.Uploader=
f;return h.Uploader},{requires:["flash","./ajbridge"]});
KISSY.add("gallery/form/1.1/uploader/plugins/filedrop/filedrop",function(c,i,h){var f=i.all,d=c.UA,a=function(c){a.superclass.constructor.call(this,c);this.set("mode",b())},b=function(){if(7<=d.webkit||3.6<=d.firefox)return"supportDrop";if(d.ie)return"notSupportDropIe";if(7>d.webkit||3.6>d.firefox)return"notSupportDrop"};c.mix(a,{event:{AFTER_DROP:"afterdrop"}});c.extend(a,h,{render:function(){var a=this.get("mode"),b=this.get("uploader");if("supportDrop"!=a)return c.log("该浏览器不支持拖拽上传！"),!1;if(!b)return c.log("缺少Uploader的实例！"),
!1;a=this._createDropArea();if(a.length)a.on("click",this._clickHandler,this);console.log("after randeer");this.fire("afterRender",{buttonTarget:this.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var a=this,b=f(a.get("target")),d=a.get("mode"),d=c.substitute(a.get("tpl")[d],{name:a.get("name")}),d=f(d),h=d.all(".J_ButtonWrap");d.appendTo(b);d.on("dragover",function(a){a.stopPropagation();
a.preventDefault()});d.on("drop",function(b){b.stopPropagation();b.preventDefault();a._dropHandler(b)});a.set("dropContainer",d);a.set("buttonWrap",h);a._setStyle();return d},_setStyle:function(){var a=this.get("dropContainer");if(!a.length)return!1;a.parent().css("position","relative");a.css({position:"absolute",top:"0",left:"0",width:"100%",height:"100%",zIndex:"1000"})},_clickHandler:function(a){f(a.target);this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(b){var d=
a.event,b=b.originalEvent.dataTransfer.files,f=[],h=this.get("uploader");if(!b.length||""==h)return!1;c.each(b,function(a){c.isObject(a)&&f.push({name:a.name,type:a.type,size:a.size,data:a})});this.fire(d.AFTER_DROP,{files:f});h._select({files:f})},_setDisabled:function(){}},{ATTRS:{target:{value:""},uploader:{value:""},dropContainer:{value:""},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>直接拖拽图片到这里，</p><p class="J_ButtonWrap">或者</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐使用chrome浏览器或firefox浏览器</p></div>',
notSupportDrop:'<div class="drop-wrapper"><p>您的浏览器只支持传统的图片上传，</p><p class="suggest J_ButtonWrap">推荐升级您的浏览器</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:!1,setter:function(a){this._setDisabled(a);return a}},cls:{disabled:"drop-area-disabled"}}});return a},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/plugins/preview/preview",function(c,i){function h(a,c){if(!a)return!1;"filter"!=b?a.src=c||e:(a.src=e,c&&(c=c.replace(/[)'"%]/g,function(a){return escape(escape(a))}),a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+c+"')",a.zoom=1));return!0}function f(d){this.config=c.mix({maxWidth:40,maxHeight:40},d);c.log(a+"Preview initialized. The preview mode is "+b)}var d=document,a="[Plugin: Preview] ",b=function(){var a="";
if("undefined"===typeof window.FileReader)switch(c.UA.shell){case "firefox":a="domfile";break;case "ie":switch(c.UA.ie){case 6:a="simple";break;default:a="filter"}}else a="html5";return a}(),e=8>c.UA.ie?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";c.augment(f,c.EventTarget,{preview:function(e,f){var e=i.get(e),f=i.get(f),j=this,l=function(){j.fire(void 0,{data:j.data,mode:b});f&&(h(f,j.data),j.fire("showed",{img:f}))};
j.data=void 0;if(e){c.log(a+"One file selected. Getting data...");switch(b){case "domfile":j.data=e.files[0].getAsDataURL();break;case "filter":e.select();try{j.data=d.selection.createRange().text}catch(m){c.log(a+"Get image data error, the error is: "),c.log(m,"dir")}finally{d.selection.empty()}j.data||(j.data=e.value);break;case "html5":var n=new FileReader;n.onload=function(a){j.data=a.target.result;l()};n.onerror=function(){c.log(a+"File Reader Error. Your browser may not fully support html5 file api",
"warning");j.fire("error")};e.files&&n.readAsDataURL(e.files[0]);break;default:j.data=e.value}j.data?l():"html5"!=b&&(c.log(a+"Retrive Data error."),h(f),j.fire("error"))}else c.log(a+"File Input Element does not exists.");return j.data}});return f},{requires:["dom","event"]});
KISSY.add("gallery/form/1.1/uploader/plugins/progressBar/progressBar",function(c,i,h){function f(a,b){b=c.merge({wrapper:d(a)},b);f.superclass.constructor.call(this,b)}var d=i.all;c.mix(f,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});c.extend(f,h,{render:function(){var a=this.get("wrapper"),b=this.get("width");if(!a.length)return!1;
a.addClass(f.cls.PROGRESS_BAR).width(b);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(f.event.RENDER)},show:function(){var a=this;a.get("wrapper").fadeIn(a.get("duration"),function(){a.set("visible",!0);a.fire(f.event.SHOW,{visible:!0})})},hide:function(){var a=this;a.get("wrapper").fadeOut(a.get("duration"),function(){a.set("visible",!1);a.fire(f.event.HIDE,{visible:!1})})},_create:function(){var a=this.get("wrapper"),b=this.get("value"),e=this.get("tpl"),
b=c.substitute(e,{value:b});a.html("");return d(b).appendTo(a)},_addAttr:function(){var a=this.get("wrapper"),b=this.get("value");a.attr("role","progressbar");a.attr("aria-valuemin",0);a.attr("aria-valuemax",100);a.attr("aria-valuenow",b);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:100},value:{value:0,setter:function(a){var b=this,c=b.get("wrapper"),d=b.get("bar"),h=b.get("speed"),j;100<a&&(a=100);0>a&&(a=0);j=c.width()*(a/100);d.animate({width:j+"px"},h,"none",function(){c.attr("aria-valuenow",
a);d.attr("data-value",a);b.fire(f.event.CHANGE,{value:a,width:j})});return a}},visible:{value:!0},duration:{value:0.3},tpl:{value:f.tpl.DEFAULT},speed:{value:0.2}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/queue",function(c,i,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",
SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});c.extend(f,h,{add:function(d,a){var b=this,e={};0<d.length?(e=[],c.each(d,function(a){e.push(b._addFile(a))})):e=b._addFile(d);a&&a.call(b);return e},_addFile:function(d,a){if(!c.isObject(d))return c.log("[uploader-queue]:_addFile()参数file不合法！"),!1;var b=this._setAddFileData(d),e=this.getFileIndex(b.id),g=this.get("fnAdd");c.isFunction(g)&&(b=g(e,
b));this.fire(f.event.ADD,{index:e,file:b,uploader:this.get("uploader")});a&&a.call(this,e,b);return b},remove:function(d,a){var b=this.get("files"),e;c.isString(d)&&(d=this.getFileIndex(d));e=b[d];if(!c.isObject(e))return c.log("[uploader-queue]:remove()不存在index为"+d+"的文件数据"),!1;b=c.filter(b,function(a,b){return b!==d});this.set("files",b);this.fire(f.event.REMOVE,{index:d,file:e});a&&a.call(this,d,e);return e},clear:function(){function c(){b=a.get("files");if(!b.length)return a.fire(f.event.CLEAR),
!1;a.remove(0,function(){c()})}var a=this,b;c()},fileStatus:function(d,a,b){if(!c.isNumber(d)||!c.isString(a))return!1;var e=this.getFile(d),g=this.get("theme"),h;if(!e||!g)return!1;if(e.status==a)return this;this.updateFile(d,{status:a});h="_"+a+"Handler";c.isFunction(g[h])&&(b=c.merge({uploader:this.get("uploader"),index:d,file:e,id:e.id},b),g[h].call(g,b));this.fire(f.event.FILE_STATUS,{index:d,status:a,args:b,file:e});return this},getFile:function(d){if(!c.isNumber(d))return!1;d=this.get("files")[d];
c.isPlainObject(d)||(c.log("getFile():文件数据为空！"),d={});return d},getFileIndex:function(d){var a=this.get("files"),b=-1;c.each(a,function(a,c){if(a.id==d)return b=c,!0});return b},updateFile:function(d,a){if(!c.isNumber(d))return!1;if(!c.isObject(a))return c.log("[uploader-queue]:updateFile()的data参数有误！"),!1;var b=this.get("files"),e=this.getFile(d);if(!e)return!1;c.mix(e,a);b[d]=e;this.set("files",b);this.fire(f.event.UPDATE_FILE,{index:d,file:e});return e},getIndexs:function(d){var a=this.get("files"),
b,e=[];if(!a.length)return e;c.each(a,function(a,f){c.isObject(a)&&(b=a.status,b==d&&e.push(f))});return e},getFiles:function(d){var a=this.get("files"),b=[];if(!a.length)return[];c.each(a,function(a){a&&a.status==d&&b.push(a)});return b},_setAddFileData:function(d){var a=this.get("files");if(!c.isObject(d))return c.log("[uploader-queue]:_updateFileData()参数file不合法！"),!1;d.id||(d.id=c.guid(f.FILE_ID_PREFIX));d.size&&(d.textSize=c.convertByteSize(d.size));d.status="";a.push(d);return d}},{ATTRS:{fnAdd:{value:""},
files:{value:[]},uploader:{value:""},theme:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/theme",function(c,i,h){function f(a){f.superclass.constructor.call(this,a);this._LoaderCss()}var d=i.all;c.extend(f,h,{afterUploaderRender:function(){},_getStatusWrapper:function(a){return a.children(".J_FileStatus")},displayFile:function(a,b,c){var d=this,f=d.get("duration");if(!b||!b.length)return!1;b[a&&"fadeIn"||"fadeOut"](f,function(){c&&c.call(d)})},_waitingHandler:function(){},_startHandler:function(){},_progressHandler:function(){},_successHandler:function(){},
_errorHandler:function(){},_restoreHandler:function(){},_UploaderRender:function(a){this._initQueue();this._addThemeCssName();this._loadPlugins(a)},_addThemeCssName:function(){var a=this.get("name"),b=this.get("queue"),c=d(this.get("queueTarget")),f=this.get("button");if(""==a||!b||!c.length)return!1;c.addClass(a+"-queue");if(!f)return!1;f.get("target").addClass(a+"-button")},_initQueue:function(){var a=this,b=a.get("queue");b.set("fnAdd",function(b,c){return a._addCallback(b,c)});b.set("theme",a);
b.on("add",a._addFileHandler,a);b.on("remove",a._removeFileHandler,a);b.on("statusChange",function(b){a._setStatusVisibility(b)});return b},_LoaderCss:function(){var a=this.get("cssUrl");if(""==a)return!1;c.use(a,function(){c.log(a+"加载成功！")})},_addCallback:function(a,b){var c=this.get("queue"),d=this._appendFileDom(b);c.updateFile(a,{target:d,statusWrapper:this._getStatusWrapper(d)});c.fileStatus(a,"waiting");this.displayFile(!0,d);this._bindTriggerEvent(a,b);return c.getFile(a)},_removeFileHandler:function(a){this.displayFile(!1,
a.file.target)},_bindTriggerEvent:function(a,b){var e=this.get("queue"),f=this.get("uploader"),h=b.id,j=d(".J_Upload_"+h),i=d(".J_Cancel_"+h),m=d(".J_Del_"+h);j.on("click",function(b){b.preventDefault();if(!c.isObject(f))return!1;f.upload(a)});i.on("click",function(b){b.preventDefault();f.cancel(a)});m.on("click",function(a){a.preventDefault();e.remove(h)})},_setStatusVisibility:function(a){var b=a.file.statusWrapper,a=a.file.status;if(!b||!b.length)return c.log("状态容器层不存在！"),!1;b.children(".status").hide();
b.children("."+a+"-status").show()},_appendFileDom:function(a){var b=this.get("fileTpl"),e=d(this.get("queueTarget"));if(!e.length)return!1;b=c.substitute(b,a);return d(b).hide().appendTo(e).data("data-file",a)},_loadPlugins:function(a){var b=this,d=b.get("plugins"),f=b.get("oPlugin"),h=[];if(!d.length)return a&&a.call(b,f),!1;c.each(d,function(a){h.push("gallery/form/1.1/uploader/plugins/"+a+"/"+a)});c.use(h.join(","),function(){c.each(arguments,function(a,b){1<=b&&(f[d[b-1]]=a)});b.set("oPlugin",
f);a&&a.call(b,f)})}},{ATTRS:{name:{value:""},cssUrl:{value:""},fileTpl:{value:""},plugins:{value:[]},oPlugin:{value:{}},queueTarget:{value:""},duration:{value:0.3},queue:{value:""},uploader:{value:""},button:{value:""},auth:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/ajax",function(c,i,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{event:c.merge(h.event,{PROGRESS:"progress"})});c.extend(f,h,{upload:function(d){if(!d)return c.log("[uploader-AjaxType]:upload()，fileData参数有误！"),!1;this._setFormData();this._addFileData(d);this.send();return this},stop:function(){var d=this.get("xhr");if(!c.isObject(d))return c.log("[uploader-AjaxType]:stop()，io值错误！"),!1;d.abort();this.fire(f.event.STOP);return this},send:function(){var d=
this,a=d.get("action"),b=d.get("formData"),e=new XMLHttpRequest;e.upload.addEventListener("progress",function(a){d.fire(f.event.PROGRESS,{loaded:a.loaded,total:a.total})});e.onload=function(){var a={};try{a=c.JSON.parse(e.responseText)}catch(b){c.log("[uploader-AjaxType]:ajax返回结果集responseText格式不合法！")}d.fire(f.event.SUCCESS,{result:a})};e.open("POST",a,!0);e.send(b);d._setFormData();d.set("xhr",e);return d},_setFormData:function(){try{this.set("formData",new FormData),this._processData()}catch(d){c.log("[uploader-AjaxType]:something error when reset FormData."),
c.log(d,"dir")}},_processData:function(){var d=this.get("data"),a=this.get("formData");c.each(d,function(b,c){a.append(c,b)});this.set("formData",a)},_addFileData:function(d){if(!c.isObject(d))return c.log("[uploader-AjaxType]:_addFileData()，file参数有误！"),!1;var a=this.get("formData"),b=this.get("fileDataName");a.append(b,d);this.set("formData",a)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:!1,cache:!1,dataType:"json",contentType:!1}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return f},{requires:["node","./base"]});KISSY.add("gallery/form/1.1/uploader/type/base",function(c,i,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});c.extend(f,h,{upload:function(){},stop:function(){}},{ATTRS:{action:{value:""},data:{value:{}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.1/uploader/type/flash",function(c,i,h){function f(c){f.superclass.constructor.call(this,c);this._init()}c.mix(f,{event:c.merge(h.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});c.extend(f,h,{_init:function(){var d=this,a=d.get("swfUploader");if(!a)return c.log("[uploader-FlashType]:swfUploader对象为空！"),!1;a.on("contentReady",function(){d.fire(f.event.SWF_READY)},d);a.on("uploadStart",d._uploadStartHandler,d);a.on("uploadProgress",d._uploadProgressHandler,d);a.on("uploadCompleteData",
d._uploadCompleteDataHandler,d);a.on("uploadError",d._uploadErrorHandler,d)},upload:function(c){var a=this.get("swfUploader"),b=this.get("action"),e=this.get("data");this.set("uploadingId",c);a.upload(c,b,"POST",e);return this},stop:function(){var c=this.get("swfUploader"),a=this.get("uploadingId");""!=a&&(c.cancel(a),this.fire(f.event.STOP,{id:a}));return this},_uploadStartHandler:function(c){this.fire(f.event.START,{file:c.file})},_uploadProgressHandler:function(d){c.mix(d,{loaded:d.bytesLoaded,
total:d.bytesTotal});this.fire(f.event.PROGRESS,{loaded:d.loaded,total:d.total})},_uploadCompleteDataHandler:function(d){var a;try{a=JSON.parse(d.data)}catch(b){c.log("[uploader-FlashType]:json数据格式不合法！"),this.fire(f.event.ERROR,{msg:"不是合法的json数据"})}this.set("uploadingId","");this.fire(f.event.SUCCESS,{result:a})},_uploadErrorHandler:function(c){this.set("uploadingId","");this.fire(f.event.ERROR,{msg:c.msg})}},{ATTRS:{swfUploader:{value:""},uploadingId:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/type/iframe",function(c,i,h){function f(a){f.superclass.constructor.call(this,a)}var d=i.all;c.mix(f,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:c.mix(h.event,{CREATE:"create",REMOVE:"remove"})});
c.extend(f,h,{upload:function(a){a=d(a);if(!a.length)return!1;this.fire(f.event.START,{input:a});this.set("fileInput",a);this._create();this.get("form").getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this.fire(f.event.STOP);this.fire(f.event.ERROR,{status:"abort",msg:"上传失败，原因：abort"});return this},dataToHidden:function(a){if(!c.isObject(a)||c.isEmptyObject(a))return c.log("[uploader-iframeType]:data参数不是对象或者为空！"),!1;var b="",d=this.get("tpl").HIDDEN_INPUT;
if(!c.isString(d))return!1;for(var f in a)b+=c.substitute(d,{name:f,value:a[f]});return b},_createIframe:function(){var a="ks-uploader-iframe-"+c.guid(),b=this.get("tpl"),e=b.IFRAME,f=this.get("iframe");if(!c.isEmptyObject(f))return f;if(!c.isString(e))return c.log("[uploader-iframeType]:iframe的模板不合法！"),!1;if(!c.isString(a))return c.log("[uploader-iframeType]:id必须存在且为字符串类型！"),!1;b=c.substitute(b.IFRAME,{id:a});b=d(b);b.on("load",this._iframeLoadHandler,this);d("body").append(b);this.set("id",a);this.set("iframe",
b);return b},_iframeLoadHandler:function(a){var b=a.target,a=f.event.ERROR,b=b.contentDocument||window.frames[b.id].document;if(!b||!b.body)return this.fire(a,{msg:"服务器端返回数据有问题！"}),!1;b=b.body.innerHTML;c.log("[uploader-iframeType]:服务器端输出:"+b);if(""==b)return!1;try{b=JSON.parse(b)}catch(d){c.log("[uploader-iframeType]:json数据格式不合法！"),this.fire(a,{msg:"数据："+b+"不是合法的json数据"})}this.fire(f.event.SUCCESS,{result:b});this._remove()},_createForm:function(){var a=this.get("id"),b=this.get("tpl").FORM,e=this.get("data"),
f=this.get("action"),h=this.get("fileInput");if(!c.isString(b))return c.log("[uploader-iframeType]:form模板不合法！"),!1;if(!c.isObject(e))return c.log("[uploader-iframeType]:data参数不合法！"),!1;if(!c.isString(f))return c.log("[uploader-iframeType]:action参数不合法！"),!1;e=this.dataToHidden(e);if(""==e)return!1;a=c.substitute(b,{action:f,target:a,hiddenInputs:e});h=d(a).append(h);d("body").append(h);this.set("form",h);return h},_create:function(){var a=this._createIframe(),b=this._createForm();this.fire(f.event.CREATE,
{iframe:a,form:b})},_remove:function(){var a=this.get("form");a.remove();this.reset("form");this.fire(f.event.REMOVE,{form:a})}},{ATTRS:{tpl:{value:f.tpl},id:{value:"ks-uploader-iframe-"+c.guid()},iframe:{value:{}},form:{value:{}},fileInput:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/form/1.1/uploader/urlsInput",function(c,i,h){function f(a,b){f.superclass.constructor.call(this,b);this.set("wrapper",d(a))}var d=i.all;c.mix(f,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});c.extend(f,h,{render:function(){var a=this.get("wrapper"),b=this.get("name"),b=document.getElementsByName(b)[0];if(!c.isObject(a))return c.log("[uploader-urlsInput]:container参数不合法！"),!1;b?(c.log("[uploader-urlsInput]:urls input found"),this.set("input",d(b))):this._create();
return this},add:function(a){if(!c.isString(a))return c.log("[uploader-urlsInput]:add()的url参数不合法！"),!1;var b=this.get("urls"),d=this.isExist(a);""==b[0]&&(b=[]);if(d)return c.log("[uploader-urlsInput]:add()，文件路径已经存在！"),this;b.push(a);this.set("urls",b);this._val();return this},remove:function(a){if(!a)return!1;var b=this.get("urls"),d=this.isExist(a),f=RegExp(a);if(!d)return c.log("[uploader-urlsInput]:remove()，不存在该文件路径！"),!1;b=c.filter(b,function(a){return!f.test(a)});this.set("urls",b);this._val();
return b},parse:function(){var a=this.get("input");if(a){var a=d(a).val(),b=this.get("split"),a=a.split(b);this.set("urls",a);return a}c.log("[uploader-urlsInput]:cannot find urls input.");return[]},_val:function(){var a=this.get("urls"),b=this.get("input"),c=this.get("split"),a=a.join(c);b.val(a);return a},isExist:function(a){var b=!1,d=this.get("urls"),f=RegExp(a);if(!d.length)return!1;c.each(d,function(a){if(f.test(a))return b=!0});return b},_create:function(){var a=this.get("wrapper"),b=this.get("tpl"),
e=this.get("name"),f=this.get("urls");if(!a||0>=a.length)return c.log("[uploader-urlsInput]:UrlsInput container not specified!","warn"),!1;if(!c.isString(b)||!c.isString("name"))return c.log("[uploader-urlsInput]:_create()，tpl和name属性不合法！"),!1;b=d(c.substitute(b,{name:e,value:f}));a.append(b);this.set("input",b);c.log("[uploader-urlsInput]:input created.");return b}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:f.TPL},split:{value:",",setter:function(a){this._val();return a}},input:{value:""},
wrapper:{value:""}}});return f},{requires:["node","base"]});
