KISSY.add("gallery/timeline/1.0/background",function(c,j){function e(a){this.config=a;this.ATTRS=c.clone(h);this._init()}var d=c.all,h={html:{value:'<div class="timenav-bg">                <div class="middle-line K_MiddleLine"><i></i></div>              </div>'},bgBox:{value:null},middleLine:{value:null},indicator:{value:null}};c.augment(e,j,c.EventTarget,{_init:function(){this.render();this.adjustStyle();this.monitorEvent()},render:function(){var a=this.config;this.set("bgBox",d(this.get("html")));
this.get("bgBox").appendTo(a.panel);this.set("middleLine",d(".K_MiddleLine",this.get("bgBox")));this.fire("uiReady")},adjustStyle:function(){this.get("middleLine").css("left",(this.config.panel.width()-this.get("middleLine").width())/2-1);this.fire("styleReload")},monitorEvent:function(){var a=this;d(window).on("resize",function(){a.adjustStyle()})}});return e},{attach:!1,requires:["./base","template"]});
KISSY.add("gallery/timeline/1.0/base",function(c){function j(){}j.prototype={get:function(e){var d=this.ATTRS;return void 0===d[e]?void 0:c.isObject(d[e])?c.isFunction(d[e].value)?d[e].value():d[e].value:d[e]},set:function(e,d){var h=this.ATTRS;return void 0===h[e]?(h[e]={},h[e].value=d):c.isObject(h[e])?void 0===h[e].setter?h[e].value=d:h[e].setter():h[e].value=d}};return j});
KISSY.add("gallery/timeline/1.0/config",function(){return{myData:null,beginYear:null,endYear:null,maxInterval:null,widthRate:null,navWidth:null,spacer:null,realWidth:null,minLeft:null,maxLeft:null,rate:10,scale:1,minScale:1,setData:function(c){this.myData=c;this.myData=this.myData.sort(function(c,e){return c.time>e.time});return this},largeRate:function(c){this.rate*=2;this.initAll(c);return this},miniRate:function(c){this.rate/=2;this.initAll(c);return this},initAll:function(c){var j=/(\d{4})[^0-9]*(\d{2})?[^0-9]*(\d{2})?/;
this.beginYear=parseInt(this.myData[0].time&&this.myData[0].time.match(j)[1]);this.endYear=parseInt(this.myData[this.myData.length-1].time&&this.myData[this.myData.length-1].time.match(j)[1]);this.maxInterval=this.endYear-this.beginYear;this.widthRate=this.rate/0.0050;this.navWidth=parseInt(this.widthRate*this.maxInterval,10);this.spacer=parseInt(3*c.width()/3,10);this.realWidth=this.navWidth+2*this.spacer;this.minLeft=parseInt(0-this.navWidth+this.spacer/3,10);this.maxLeft=parseInt(this.spacer/3);
return this}}});
KISSY.add("gallery/timeline/1.0/control",function(c,j,e,d,h,a,i){function b(a){this.config=a;this.ATTRS=c.clone(k);this._init()}var f=c.all,g=/(\d{4})(\d{2})?(\d{2})?/,k={};c.augment(b,j,c.EventTarget,{_init:function(){var b=this,f=b.config;f.trackConfig=c.clone(i);f.trackConfig.setData(f.data);f.trackConfig.initAll(f.panel);b.set("bg",new e(f));b.set("toolbar",new d(f));b.set("mainContent",new h(f));b.set("dd",new a(f.panel,{dragEle:".K_Timenav"}));b.monitorEvent();b.get("mainContent").renderMarkers(b.transAjaxData(f.data));b.get("mainContent").renderInterval();
b.get("dd").on("moving",function(a){b.get("mainContent").rigidResetOffset({left:a.ox})});b.get("dd").on("mouseup",function(a){a.buffer&&b.get("mainContent").dragBuffer({duration:a.buffer.duration,addLeft:a.buffer.addLeft})})},transAjaxData:function(b){for(var a=[],f=0;f<b.length;++f)b[f].hidden&&!0==b[f].hidden||a.push(c.merge(b[f],{__left:this.timeToPosLeft(b[f].time)}));return a},timeToPosLeft:function(b){var a=this.config,f=0,b=b.match(g),f=a.trackConfig.beginYear,c=0,i=0;b[1]&&(f=b[1]);b[2]&&
(c=b[2]);b[3]&&(i=b[3]);return f=(f-a.trackConfig.beginYear+c/12+i/12/30)*a.trackConfig.widthRate},_timeToPosTop:function(){},monitorEvent:function(){var b=this,a=b.config,c=a.trackConfig;f(document).on("resize",function(){c.initAll(a.panel)});var g=!1,i=1;b.get("toolbar").on("toggle",function(){if(!0==g)return!1;if(0==i){var b=0;i=1}else 1==i&&(b=f(document.body).width(),i=0);g=!0;f("#KT_Navigation").animate({left:b},1,"swing",function(){g=!1})});b.get("toolbar").on("large",function(){500<=c.rate||
(c.largeRate(this.config.panel),b.get("mainContent").rate(2))});b.get("toolbar").on("mini",function(){1>=c.rate||(c.miniRate(a.panel),b.get("mainContent").rate(0.5))});b.get("toolbar").on("leftScroll",function(){b.get("mainContent").leftScroll()});b.get("toolbar").on("rightScroll",function(){b.get("mainContent").rightScroll()});b.get("toolbar").on("gotoLast",function(){b.get("mainContent").switchTo(a.data.length-1)});b.get("mainContent").on("marker",function(a){b.fire("change",{data:a.data,target:a.target})});
b.get("mainContent")},prev:function(){this.get("mainContent").prev()},next:function(){this.get("mainContent").next()},switchTo:function(b){this.get("mainContent").switchTo(b)}});return b},{attach:!1,requires:"./base,./background,./toolbar,./main-content,./dd,./config".split(",")});
KISSY.add("gallery/timeline/1.0/dd",function(c,j){function e(a,c){this.panel=a&&"string"===typeof a?d((/^\s*[#|.]/.test(a)?"":"#")+a):a;if(void 0==this.panel)return alert("[DD] panel is undefined"),!1;this.__attr=c;this._init()}var d=c.all,h=c.DOM;c.augment(e,j,c.EventTarget,{_init:function(){var a=this;a.dragEle=d(a.get("dragEle"),a.panel);a.set("dragInfoX",[]);a.set("dragInfoY",[]);a.set("dragInfoTime",[]);a.set("ddMask",null);a.panel.on("mousedown",function(c){c.halt();c.button&&2==c.button||(a.set("ix",
c.pageX),a.set("iy",c.pageY),a.set("tx",parseInt(a.dragEle.css("left"),10)),a.set("ty",parseInt(a.dragEle.css("top"),10)),a.set("dragInfoX",[]),a.set("dragInfoY",[]),a.set("dragInfoTime",[]),a._bindWindowEvent())})},_bindWindowEvent:function(){d(document).on("mouseup",this._handleWindowMouseup,this);d(document).on("mousemove",this._handleWindowMousemove,this)},_cancelWindowEvent:function(){d(document).detach("mouseup",this._handleWindowMouseup,this);d(document).detach("mousemove",this._handleWindowMousemove,
this)},_handleWindowMousemove:function(a){a.preventDefault();null==this.get("ddMask")&&(this.set("ddMask",h.create('<div class="timeline-dd-mask"></div>')),document.body&&document.body.appendChild(this.get("ddMask")));this.get("dragInfoX").push(a.pageX);this.get("dragInfoY").push(a.pageY);this.get("dragInfoTime").push((new Date).getTime());this.fire("moving",{ox:a.pageX-this.get("ix")+this.get("tx"),oy:a.pageY-this.get("iy")+this.get("ty")})},_handleWindowMouseup:function(a){this._cancelWindowEvent();
this.get("dragInfoX").push(a.pageX);this.get("dragInfoY").push(a.pageY);this.get("dragInfoTime").push((new Date).getTime());this.fire("mouseup",{buffer:this._calculateBuffer()});h.remove(this.get("ddMask"));this.set("ddMask",null)},_calculateBuffer:function(){if(!(3>this.get("dragInfoX").length)){for(var a={a:1E4,v:100,isLeft:!0},c=this.get("dragInfoX"),b=c.length,f=this.get("dragInfoTime"),g=1,d=c[b-1],e=f[b-1];g<b&&50>e-f[b-++g];)if(2==g&&500<d-f[b-g])return;g<=b?(t1=f[b-g+1],c=c[b-1]-c[b-g],a.v=
1E3*(c/(e-t1)),0<c?a.isLeft=!0:a.isLeft=!1):(a.v=100,c[b-1]>c[0]?a.isLeft=!0:a.isLeft=!1);a.absDistance=a.v*a.v/2/a.a;a.addLeft=a.isLeft?"+="+a.absDistance:"-="+a.absDistance;a.duration=Math.abs(parseInt(1E3*(a.v/a.a),10));return a}},set:function(a,c){return this.__attr[a]=c},get:function(a){return this.__attr[a]}});return e},{attach:!1,requires:["./base"]});KISSY.add("gallery/timeline/1.0/index",function(c,j){return function(c){return new j(c)}},{requires:["./control"]});
KISSY.add("gallery/timeline/1.0/main-content",function(c,j,e,d){function h(b){this.config=b;this.ATTRS=c.clone(i);this._init()}var a=c.all,i={html:{value:'<div class="timenav K_Timenav" style="left:0;">                <div class="time-points K_MarkerBox">                </div>                <div class="time-interval">                  <div class="time-interval-major K_IntervalBox"></div>                </div>                <div class="time-ruler K_TimeRuler"></div>              </div>'},tpl_marker:{value:'<div class="marker K_Marker" id="marker_{{id}}" style="left: {{left}}px;" data-req=\'{{data}}\'>                <div class="flag" style="top:{{top}}px">                  <div class="flag-content">                    <div class="thumbnail"></div>                    <h3>{{title}}</h3>                  </div>                </div>                <div class="dot"></div>                <div class="line">                  <div class="event-line"></div>                </div>              </div>'},
tpl_interal:{value:'<div class="a-interval" style="left: {{left}}px;">{{time}}</div>'},cBox:{value:null},markerBox:{value:null},intervalBox:{value:null},timeRuler:{value:null},timenav:{value:null}};c.augment(h,j,c.EventTarget,{ATTRS:i,_init:function(){this.dragBufferAnim=null;this.isRating=!1;this.cdY=1;this.markerEles=[];this.activeMarkerIdx=null;this.render();this.adjustStyle();this.monitorEvent()},leftScroll:function(){var b=this;b.stopAnim();b.dragBufferAnim=(new d(b.get("timenav")[0],{left:"+="+
4*a(document.body).width()/5},{duration:1,easing:"easeOutStrong"})).run();b.dragBufferAnim.on("step",function(){if(b.isOverflow())return!1})},rightScroll:function(){var b=this;b.stopAnim();b.dragBufferAnim=(new d(b.get("timenav")[0],{left:"-="+4*a(document.body).width()/5},{duration:1,easing:"easeOutStrong"})).run();b.dragBufferAnim.on("step",function(){if(b.isOverflow())return!1})},rigidResetOffset:function(b){this.stopAnim();void 0!=b.left&&this.get("timenav").css("left",b.left+"px");void 0!=b.top&&
this.get("timenav").css("top",b.top+"px")},dragBuffer:function(b){var a=this;a.stopAnim();a.dragBufferAnim=(new d(a.get("timenav")[0],{left:b.addLeft},{duration:b.duration/1E3,easing:"easeOutStrong"})).run();a.dragBufferAnim.on("step",function(){if(a.isOverflow())return!1})},isOverflow:function(){var b=this.config.trackConfig,a=0;if(b.minLeft>parseInt(this.get("timenav").css("left"),10))this.stopAnim(),a=b.minLeft;else if(b.maxLeft<parseInt(this.get("timenav").css("left"),10))this.stopAnim(),a=b.maxLeft;
else return;this.dragBufferAnim=this.get("timenav").animate({left:a+"px"},{duration:0.4,easing:"easeOutStrong"});return!0},stopAnim:function(){this.dragBufferAnim&&this.dragBufferAnim.stop&&this.dragBufferAnim.stop()},resetTimenavPos:function(b,a){this.stopAnim();a&&!1===a||(this.dragBufferAnim=this.get("timenav").animate(b,{duration:1,easing:"easeOutStrong"}))},render:function(b){var f=this.config;this.set("cBox",a(this.get("html")));this.set("timenav",this.get("cBox"));this.set("markerBox",a(".K_MarkerBox",
this.get("timenav")));this.set("intervalBox",a(".K_IntervalBox",this.get("timenav")));this.set("timeRuler",a(".K_TimeRuler",this.get("timenav")));this.get("timenav").appendTo(f.panel);this.resetTimenavPos({left:parseInt(this.get("timenav").css("left"),10)+f.panel.width()/3});b&&c.isArray(b)&&this.renderMarkers(b);this.fire("uiReady");c.UA&&6==c.UA.ie&&(this.get("timenav").delegate("mouseenter",".K_Marker",function(){a(this).addClass("hover")}),this.get("timenav").delegate("mouseleave",".K_Marker",
function(){a(this).removeClass("hover")}))},renderMarkers:function(b){for(var f=b.length,g=0;g<f;++g){var d=a(e(this.get("tpl_marker")).render({id:b[g].time,title:b[g].title,data:KISSY.JSON.stringify(c.merge({count:g},b[g])),left:b[g].__left,top:(b[g].top||parseInt(55*Math.random(),10))+10}));d.appendTo(this.get("markerBox"));this.markerEles.push(d)}},renderInterval:function(b){var a=1,c=1;switch(this.config.trackConfig.widthRate){case 2E3:c=a=1;break;case 1E3:a=1;c=2;break;case 500:a=1;c=3;break;
case 250:a=1;c=4;break;case 125:a=1;c=6;break;case 62.5:a=2,c=12}!b||!1==b?this._renderInterval(a,c):this._styleInterval(a,c)},_renderInterval:function(){var b=this.config.trackConfig;this.get("intervalBox").html("");for(var c=-1;c<b.endYear-b.beginYear+1;++c){a(e(this.get("tpl_interal")).render({left:5*parseInt(c*b.widthRate/5,10)-2,time:b.beginYear+c-1+".12"})).appendTo(this.get("intervalBox"));for(var g=1;11>=g;++g)a(e(this.get("tpl_interal")).render({left:5*parseInt((c*b.widthRate+b.widthRate/
12*g)/5,10)-2,time:b.beginYear+c+"."+g})).appendTo(this.get("intervalBox"))}},_styleInterval:function(b,c){for(var g=this.config.trackConfig,d=a(".a-interval",this.get("intervalBox")),e=-1;e<g.endYear-g.beginYear+1;++e){var i=12*(e+1);d.item(i).animate({left:5*parseInt(e*g.widthRate/5,10)-2},0.5);0!=Math.abs(e)%b?d.item(i).hide():d.item(i).show();for(var h=1;11>=h;++h)d.item(i+h).animate({left:5*parseInt((e*g.widthRate+g.widthRate/12*h)/5,10)-2},0.5),0!=h%c?d.item(i+h).hide():d.item(i+h).show()}},
gotoMarker:function(b,a){var c=this.config;this.get("timenav").all(".marker").removeClass("hover");a.addClass("hover");this.stopAnim();c=b+parseInt(this.get("timenav").css("left"),10)-c.panel.width()/2+3;this.dragBufferAnim=this.get("timenav").animate({left:"-="+c},0.5,"easeOutStrong")},adjustStyle:function(){var b=this.config.trackConfig;this.get("timenav").width(b.navWidth);this.get("intervalBox").width(b.navWidth);this.get("timeRuler").width(b.realWidth+2*Math.abs(b.spacer)).css("left",0-Math.abs(2*
b.spacer))},rate:function(b){var c=this,d=c.config;if(!0!=c.isRating){c.stopAnim();a(".marker",c.get("timenav")).each(function(c){a(c).animate({left:parseInt(a(c).css("left"),10)*Math.abs(b)},0.5)});var e=parseInt(c.get("timenav").css("left"),10);c.get("timenav").width();d=d.panel.width();e=d/2-(0-e+d/2)*b;c.get("timenav").animate({left:e,width:"*="+b},0.5,"easeNone",function(){c.adjustStyle();c.isRating=!1});c.renderInterval(!0)}},monitorEvent:function(){var b=this;a(window).on("resize",function(){b.adjustStyle()});
b.get("timenav").on("click",function(c){c.halt();c=a(c.target);if(!c.hasClass("marker"))if(null!=c.parent(".marker"))c=c.parent(".marker");else return!1;b.clickThisMarder(c)})},clickThisMarder:function(b){var a=c.JSON.parse(b.attr("data-req"));if(this.activeMarkerIdx==a.count)return!1;this.activeMarkerIdx=a.count;this.fire("marker",{data:a,target:b});this.gotoMarker(parseInt(b.css("left"),10),b);this.setHash()},setHash:function(){return!1},prev:function(){var a=(this.activeMarkerIdx-1+this.markerEles.length)%
this.markerEles.length||0;this.clickThisMarder(this.markerEles[a]);this.activeMarkerIdx=a},next:function(){var a=(this.activeMarkerIdx+1+this.markerEles.length)%this.markerEles.length||0;this.clickThisMarder(this.markerEles[a]);this.activeMarkerIdx=a},switchTo:function(a){if(0>a||a>=this.markerEles.length)return!1;this.clickThisMarder(this.markerEles[a])}});return h},{attach:!1,requires:["./base","template","anim"]});
KISSY.add("gallery/timeline/1.0/toolbar",function(c,j){function e(a){this.config=a;this.ATTRS=c.clone(h);this._init()}var d=c.all,h={html:{value:'<div class="timenav-toolbar">                <a hidefocus href="#" class="hide-timenav K_HideTimenav">hide</a>                <a hidefocus href="#" class="largen K_LargeRate">large</a>                <a hidefocus href="#" class="mini K_MiniRate">mini</a>                <a hidefocus href="#" class="left-scroll H_LeftScroll">left</a>                <a hidefocus href="#" class="right-scroll H_RightScroll">right</a>                <a hidefocus href="#" class="goto-last H_GotoLast">goto-last</a>              </div>'},
cBox:{value:null},hideTimenav:{value:null},largeRate:{value:null},miniRate:{value:null},leftScroll:{value:null},rightScroll:{value:null}};c.augment(e,j,c.EventTarget,{_init:function(){this.render();this.monitorEvent()},render:function(){var a=this.config;this.set("cBox",d(this.get("html")));this.get("cBox").appendTo(a.panel);this.set("hideTimenav",d(".K_HideTimenav",this.get("cBox")));this.set("largeRate",d(".K_LargeRate",this.get("cBox")));this.set("miniRate",d(".K_MiniRate",this.get("cBox")));this.set("leftScroll",
d(".H_LeftScroll",this.get("cBox")));this.set("rightScroll",d(".H_RightScroll",this.get("cBox")));this.set("gotoLast",d(".H_GotoLast",this.get("cBox")));this.fire("uiReady")},adjustStyle:function(){this.fire("styleReload")},monitorEvent:function(){var a=this;a.get("hideTimenav").on("click",function(c){c.halt();a.fire("toggle")});a.get("largeRate").on("click",function(c){c.halt();a.fire("large")});a.get("miniRate").on("click",function(c){c.halt();a.fire("mini")});a.get("leftScroll").on("click",function(c){c.halt();
a.fire("leftScroll")});a.get("rightScroll").on("click",function(c){c.halt();a.fire("rightScroll")});a.get("gotoLast").on("click",function(c){c.halt();a.fire("gotoLast")})}});return e},{attach:!1,requires:["./base"]});
