KISSY.add("gallery/kcharts/1.1/barchart/index",function(i,s,o,v,q,w,x,p,y){var j=i.all,n=i.Event,k="ks-chart-default",t=k+"-canvas",h,u=function(a){this.init(a)};i.extend(u,o,{init:function(a){o.prototype.init.call(this,a);this.chartType="barchart";if(this._$ctnNode[0]){a={themeCls:k,autoRender:!0,colors:[],stackable:!1,title:{content:"",css:{"text-align":"center","font-size":"16px"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px"},isShow:!0},xLabels:{isShow:!0,css:{color:"#666",
"font-size":"12px","white-space":"nowrap",position:"absolute"}},yLabels:{isShow:!0,css:{color:"#666","font-size":"12px",position:"absolute"}},xAxis:{isShow:!0,css:{color:"#eee",zIndex:10}},yAxis:{isShow:!0,css:{zIndex:10},num:5},xGrids:{isShow:!0,css:{}},yGrids:{isShow:!0,css:{}},areas:{isShow:!0,css:{}},bars:{isShow:!0,css:{background:"{COLOR}",border:"1px solid #fff"},barsRatio:0.6,barRatio:0.5},legend:{isShow:!1},tip:{isShow:!0,template:"",css:{},anim:{easing:"easeOut",duration:0.3},offset:{x:0,
y:0},boundryDetect:!0,alignX:"right",alignY:"bottom"}};this._bars={};this._finished=[];k=this._cfg.themeCls||a.themeCls;this._cfg=i.mix(i.mix(a,x[k],p,p,!0),this._cfg,p,p,!0);this.color=h=new v({themeCls:k});0<this._cfg.colors.length&&h.removeAllColors();for(var b in this._cfg.colors)h.setColor(this._cfg.colors[b]);this._cfg.autoRender&&this.render(!0)}},drawTitle:function(){var a=this.paper,b=k+"-title",c=this._cfg,d=0.6*this._innerContainer.y;!this._title&&c.title.isShow&&""!=c.title.content&&(this._title=
a.rect(0,0,this._$ctnNode.width(),d).addClass(b).css(i.mix({"line-height":d+"px"},c.title.css)));this._title&&""!=c.title.content&&this._title.html(c.title.content)},drawSubTitle:function(){var a=this.paper,b=k+"-subtitle",c=this._cfg,d=this._innerContainer,e=0.4*d.y;!this._subTitle&&c.subTitle.isShow&&""!=c.subTitle.content&&(this._subTitle=a.rect(0,0.6*d.y,this._$ctnNode.width(),e).addClass(b).css(i.mix({"line-height":e+"px"},c.subTitle.css)));this._subTitle&&""!=c.subTitle.content&&this._subTitle.html(c.subTitle.content)},
drawBar:function(a,b,c,d,e,f){var g=this._cfg,h=this.paper,r=t+"-bars",j=this._innerContainer,e=this.processAttr(g.bars.css,e),l="x"==g.zoomType?!1:!0,a=(a-0).toFixed(2),b=(b-0).toFixed(2),c=(c-0).toFixed(2),d=(d-0).toFixed(2);if(g.anim)var m=g.anim.duration?i.isNumber(g.anim.duration)?g.anim.duration:0.5:0.5,g=g.anim.easing?g.anim.easing:"easeOut",a=l?h.rect(a,b,0,d).attr({posx:a,posy:b}).addClass(r).css(e).animate({width:c,marginLeft:a-j.x},m,g,function(){f&&f()}):h.rect(a,j.bl.y,c,0).attr({posx:a,
posy:b}).addClass(r).css(e).animate({height:d,marginTop:b-j.y},m,g,function(){f&&f()});else a=h.rect(a,b,c,d).attr({posx:a,posy:b}).addClass(r).css(e),f&&f();return a},getBarsPos:function(){var a=this._cfg.stackable,b=this._innerContainer,c="y"==this._cfg.zoomType,d=a?1:o.prototype.obj2Array(this._barPoints).length,e=this._cfg.bars.barsRatio,f=this._cfg.bars.barRatio,g=c?1<this._pointsY.length?this._pointsY[1].y-this._pointsY[0].y:b.height:1<this._pointsX.length?this._pointsX[1].x-this._pointsX[0].x:
b.width,d=g*e/(d+(d-1)*(1<=f?0:(1-f)/f)),f=a?0:d+d*(1-f)/f,b=this._innerContainer.bl.y,i=this._innerContainer.bl.x,e=(g*(1-e)-g)/2,g=[];this._barsPos={};for(var h in this._points){var j=[];if(c)for(var l in this._points[h]){var m={},k=Math.abs(this._points[h][l].x-i);m.y=e+this._points[h][l].y;a?(m.x=i+(g[l]||0),g[l]=g[l]?g[l]+k:k):m.x=i;m.width=k;m.height=d;j.push(m)}else for(l in this._points[h])m={},k=Math.abs(b-this._points[h][l].y),m.x=e+this._points[h][l].x,a?(m.y=this._points[h][l].y-(g[l]||
0),g[l]=g[l]?g[l]+k:k):m.y=this._points[h][l].y,m.width=d,m.height=k,j.push(m);e+=f;this._barsPos[h]=j}},drawBars:function(a){var b=this,c;for(c in b._barsPos){var d=[],e=[],f;for(f in b._barsPos[c]){var g=b._barsPos[c][f];e[f]=g;d[f]=b.drawBar(g.x,g.y,g.width,g.height,h.getColor(c).DEFAULT,function(){b._finished.push(!0);a&&b._finished.length==b._cfg.series.length&&a()}).attr({barGroup:c,barIndex:f,defaultColor:h.getColor(c).DEFAULT,hoverColor:h.getColor(c).HOVER})}d={bars:d,posInfos:e,color:h.getColor(c)};
b._bars[c]=d}return b._bars},drawGridsX:function(){var a=this._points[0];this._gridsX=[];if("x"==this._cfg.zoomType){var b=[];if(1<a.length){var c=(a[1].x-a[0].x)/2;b.push({x:a[0].x-c});for(var d in a)b.push({x:a[d].x- -c})}c=0;for(a=b.length;c<a;c++)this._gridsX.push(this.drawGridX(b[c]))}else for(c in this._pointsX)this._gridsX.push(this.drawGridX(this._pointsX[c]));return this._gridsX},drawGridX:function(a){var b=this._cfg.themeCls+"-gridsx";return this.htmlPaper.lineY(a.x,this._innerContainer.tl.y,
this._innerContainer.height).addClass(b).css(this._cfg.xGrids.css)},drawGridY:function(a,b){var c=this._innerContainer.width,b=b||this._cfg.yGrids.css,d=this._cfg.themeCls+"-gridsy";return this.htmlPaper.lineX(a.x,a.y,c).addClass(d).css(b)},drawGridsY:function(){var a=this._innerContainer.tl.x,b="x"==this._cfg.zoomType?!1:!0;this._gridsY=[];for(var c=0,d=this._pointsY.length;c<d;c++)this._gridsY[c]={"0":this.drawGridY({x:a,y:this._pointsY[c].y}),num:b?this.coordNumX[c]:this.coordNum[c]}},drawAxisX:function(){var a=
this._innerContainer,b=a.bl,c=this._cfg.themeCls+"-axisx";return this._axisX=this.htmlPaper.lineX(b.x,b.y,a.width).addClass(c).css(this._cfg.xAxis.css||{})},drawAxisY:function(){var a=this._innerContainer,b=a.tl,c=this._cfg.themeCls+"-axisy";return this._axisY=this.htmlPaper.lineY(b.x,b.y,a.height).addClass(c).css(this._cfg.yAxis.css||{})},drawLabelsX:function(){if("y"==this._cfg.zoomType)for(var a in this._pointsX)this._labelX[a]={"0":this.drawLabelX(a,this._pointsX[a].number)};else for(a in this._cfg.xAxis.text)this._labelX[a]=
{"0":this.drawLabelX(a,this._cfg.xAxis.text[a])}},drawLabelsY:function(){if("x"==this._cfg.zoomType)for(a in this._pointsY)this._labelY[a]={"0":this.drawLabelY(a,this._pointsY[a].number),num:this._pointsY[a].number};else for(var a in this._cfg.yAxis.text)this._labelY[a]={"0":this.drawLabelY(a,this._cfg.yAxis.text[a])}},drawLabelX:function(a,b){var c=this.htmlPaper,d=this._pointsX,e=this._cfg.themeCls+"-xlabels",f;f="";if(a<(d.length||0))return f=this._cfg.xLabels.template||"{{data}}",f=i.isFunction(f)?
f(a,b):s(f).render({data:b}),d=d[a],d[0]=c.text(d.x,d.y,"<span class="+e+">"+f+"</span>","center").children().css(this._cfg.xLabels.css),d[0]},drawLabelY:function(a,b){var c=this.htmlPaper,d=this._cfg.themeCls+"-ylabels",e;e="";e=this._cfg.yLabels.template||"{{data}}";return(e=i.isFunction(e)?e(a,b):s(e).render({data:b}))&&c.text(this._pointsY[a].x,this._pointsY[a].y,"<span class="+d+">"+e+"</span>","right","middle").children().css(this._cfg.yLabels.css)},renderTip:function(){var a=this._cfg,b=this._innerContainer,
a=i.mix(a.tip,{rootNode:this._$ctnNode,clsName:a.themeCls,boundry:a.tip.boundryDetect?{x:b.tl.x,y:b.tl.y,width:b.width,height:b.height}:{}});return this.tip=new y(a)},renderEvtLayout:function(){var a=this._innerContainer,b=a.height;this._evtEls._bars=[];var a=this._evtEls.paper?this._evtEls.paper:this._evtEls.paper=new q(this._$ctnNode,{clsName:"ks-chart-evtlayout",prependTo:!1,width:a.width,height:b,left:a.tl.x,top:a.tl.y,css:{"z-index":20,background:"#fff",filter:"alpha(opacity =1)","-moz-opacity":0.01,
"-khtml-opacity":0.01,opacity:0.01}}),c;for(c in this._barsPos){var b=[],d;for(d in this._barsPos[c]){var e=this._barsPos[c][d];b[d]=a.rect(e.x,e.y,e.width,e.height).addClass("ks-chart-evtlayout-bars").attr({barGroup:c,barIndex:d})}this._evtEls._bars.push(b)}return a},clearEvtLayout:function(){if(this._evtEls._bars)for(var a in this._evtEls._bars)for(var b in this._evtEls._bars[a])this._evtEls._bars[a][b].remove()},renderLegend:function(){var a=this._cfg.legend,b=a.container&&j(a.container)[0]?j(a.container):
this._$ctnNode;return this.legend=new w({container:b,chart:this,evtBind:!0,css:a.css||{}})},render:function(a){var b=this,c=b._cfg,d=b._innerContainer,e=c.themeCls;a&&b._$ctnNode.html("");b.paper=new q(b._$ctnNode,{clsName:t,width:d.width,height:d.height,left:d.tl.x,top:d.tl.y});b._barPoints=b._points;b.getBarsPos();b.htmlPaper=new q(b._$ctnNode,{clsName:e});b.drawTitle();b.drawSubTitle();b.renderEvtLayout();c.tip.isShow&&b.renderTip();c.xGrids.isShow&&b.drawGridsX();c.yGrids.isShow&&b.drawGridsY();
c.xAxis.isShow&&b.drawAxisX();c.yAxis.isShow&&b.drawAxisY();c.xLabels.isShow&&b.drawLabelsX();c.yLabels.isShow&&b.drawLabelsY();c.legend.isShow&&b.renderLegend();b.drawBars(function(){i.log("finished");b.afterRender()});b.bindEvt();i.log(b)},bindEvt:function(){var a=this,b=a._cfg;n.detach(j(".ks-chart-evtlayout-bars",a._$ctnNode),"mouseenter");n.on(j(".ks-chart-evtlayout-bars",a._$ctnNode),"mouseenter",function(c){var d=j(c.currentTarget),c=d.attr("barIndex"),d=d.attr("barGroup");b.tip.isShow&&a.tipHandler(d,
c);a.barChange(d,c)});n.detach(j(".ks-chart-evtlayout-bars",a._$ctnNode),"mouseleave");n.on(j(".ks-chart-evtlayout-bars",a._$ctnNode),"mouseleave",function(b){var d=j(b.currentTarget),b=d.attr("barIndex"),d=d.attr("barGroup"),b=a._bars[d].bars[b];b.css({background:b.attr("defaultColor")})});n.detach(a._evtEls.paper.$paper,"mouseleave");n.on(a._evtEls.paper.$paper,"mouseleave",function(){a.tip&&a.tip.hide();a.paperLeave()})},paperLeave:function(){this.fire("paperLeave",this)},barChange:function(a,
b){var c=this._bars[a];this.fire("barChange",i.mix({target:c.bars[b],currentTarget:c.bars[b],barGroup:Math.round(a),barIndex:Math.round(b)},this._points[a][b]))},tipHandler:function(a,b){var c=this._cfg,d=this.tip,e="y"==c.zoomType?!0:!1;d.getInstance();var f=this._bars[a].bars[b],g=f.attr("defaultColor"),h=this._cfg.tip.template,e=e?f.attr("posx")- -f.width()- -this._innerContainer.x:f.attr("posx"),j=f.attr("posy"),k=i.merge(this._points[a][b].dataInfo,c.series[a]);delete k.data;this._points[a][b].dataInfo;
f.css({background:f.attr("hoverColor")});h&&(d.fire("setcontent",{data:k}),d.fire("move",{x:e,y:j,style:this.processAttr(c.tip.css,g)}))},animateGridsAndLabels:function(){var a=this._cfg.zoomType;if("y"==a){for(var b in this._labelX)this._labelX[b]&&this._labelX[b][0]&&j(this._labelX[b][0]).remove(),this._gridsX[b]&&this._gridsX[b][0]&&j(this._gridsX[b][0]).remove();this.drawGridsX();this.drawLabelsX()}else if("x"==a){for(b in this._labelY)this._labelY[b]&&this._labelY[b][0]&&this._labelY[b][0].remove(),
this._gridsY[b]&&this._gridsY[b][0]&&this._gridsY[b][0].remove();this.drawGridsY();this.drawLabelsY()}},processAttr:function(a,b){var c=i.clone(a),d;for(d in c)c[d]&&"string"==typeof c[d]&&(c[d]=c[d].replace("{COLOR}",b));return c},showBar:function(a){var b=this._innerContainer;o.prototype.recoveryData.call(this,a);this._barPoints[a]=this._points[a];this.animateGridsAndLabels();this.getBarsPos();for(var c in this._bars)if(c!=a)for(var d in this._bars[c].bars)if(this._barsPos[c]){var e=this._barsPos[c][d];
e&&this._bars[c].bars[d].stop().animate({height:e.height,width:e.width,marginTop:e.y-b.y,marginLeft:e.x-b.x},0.4,"easeOut",function(){});this._bars[c].bars[d].attr({posx:e.x,posy:e.y})}var b=[],f=[];for(d in this._barsPos[a])e=this._barsPos[a][d],b[d]=e,f[d]=this.drawBar(e.x,e.y,e.width,e.height,h.getColor(a).DEFAULT).attr({barGroup:a,barIndex:d,defaultColor:h.getColor(a).DEFAULT,hoverColor:h.getColor(a).HOVER});this._bars[a]={bars:f,posInfos:b,color:h.getColor(c)};this.clearEvtLayout();this.renderEvtLayout();
this.bindEvt();i.log(this)},hideBar:function(a){var b=this._innerContainer;o.prototype.removeData.call(this,a);delete this._barPoints[a];this.animateGridsAndLabels();this.getBarsPos();for(var c in this._bars[a].bars)this._bars[a].bars[c].remove();for(c in this._bars)if(c!=a)for(var d in this._bars[c].bars){var e=this._barsPos[c]?this._barsPos[c][d]:"";e&&this._bars[c].bars[d].stop().animate({height:e.height,width:e.width,marginTop:e.y-b.y,marginLeft:e.x-b.x},0.4,"easeOut",function(){});this._bars[c].bars[d].attr({posx:e.x,
posy:e.y})}this.clearEvtLayout();this.renderEvtLayout();this.bindEvt();i.log(this)},afterRender:function(){this.fire("afterRender",this)},getPaper:function(){return this.paper},clear:function(){return this.paper.clear()}});return u},{requires:"gallery/template/1.0/index,../basechart/index,../tools/color/index,../tools/htmlpaper/index,../legend/index,./theme,../tools/touch/index,../tip/index".split(",")});
KISSY.add("gallery/kcharts/1.1/barchart/theme",function(){return{"ks-chart-default":{title:{content:"",css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px",color:"#666"},isShow:!0},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},tip:{css:{border:"2px solid {COLOR}"}}},
"ks-chart-analytiks":{title:{content:"",css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px",color:"#666"},isShow:!0},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},tip:{css:{background:"{COLOR}"}}},"ks-chart-rainbow":{title:{content:"",
css:{"text-align":"center","font-size":"16px","font-weight":"bold",color:"#666"},isShow:!0},subTitle:{content:"",css:{"text-align":"center","font-size":"12px",color:"#666"},isShow:!0},xGrids:{css:{color:"#eee"}},yGrids:{css:{color:"#eee"}},yAxis:{css:{color:"#ccc"}},xAxis:{css:{color:"#ccc"}},xLabels:{css:{color:"#666","font-size":"12px"}},yLabels:{css:{color:"#666","font-size":"12px"}},tip:{css:{background:"{COLOR}"}}}}});
