KISSY.add("gallery/juicer/1.2/index",function(a,j){return j},{requires:["./juicer"]});
KISSY.add("gallery/juicer/1.2/juicer",function(){var a=function(){var f=[].slice.call(arguments);f.push(a.options);f[0].match(/^\s*#([\w:\-\.]+)\s*$/igm)&&f[0].replace(/^\s*#([\w:\-\.]+)\s*$/igm,function(a,b){var d=document,d=d&&d.getElementById(b);f[0]=d?d.value||d.innerHTML:a});if(1==arguments.length)return a.compile.apply(a,f);if(2<=arguments.length)return a.to_html.apply(a,f)},j={escapehash:{"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&#x27;","/":"&#x2f;"},escapereplace:function(a){return j.escapehash[a]},
escaping:function(a){return"string"!==typeof a?a:a.replace(/[&<>"]/igm,this.escapereplace)},detection:function(a){return"undefined"===typeof a?"":a}},l=function(a){if("undefined"!==typeof console){if(console.warn){console.warn(a);return}if(console.log){console.log(a);return}}throw a;},k=function(a,c){a=a!==Object(a)?{}:a;if(a.__proto__)return a.__proto__=c,a;var b=function(){},b=Object.create?Object.create(c):new (b.prototype=c,b),d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b};a.__cache=
{};a.version="0.6.4-stable";a.settings={};a.tags={operationOpen:"{@",operationClose:"}",interpolateOpen:"\\${",interpolateClose:"}",noneencodeOpen:"\\$\\${",noneencodeClose:"}",commentOpen:"\\{#",commentClose:"\\}"};a.options={cache:!0,strip:!0,errorhandling:!0,detection:!0,_method:k({__escapehtml:j,__throw:l,__juicer:a},{})};a.tagInit=function(){var f=a.tags.operationOpen+"\\/each"+a.tags.operationClose,c=a.tags.operationOpen+"if\\s*([^}]*?)"+a.tags.operationClose,b=a.tags.operationOpen+"\\/if"+
a.tags.operationClose,d=a.tags.operationOpen+"else"+a.tags.operationClose,h=a.tags.operationOpen+"else if\\s*([^}]*?)"+a.tags.operationClose,e=a.tags.interpolateOpen+"([\\s\\S]+?)"+a.tags.interpolateClose,m=a.tags.noneencodeOpen+"([\\s\\S]+?)"+a.tags.noneencodeClose,i=a.tags.commentOpen+"[^}]*?"+a.tags.commentClose,g=a.tags.operationOpen+"each\\s*(\\w*?)\\s*in\\s*range\\(([^}]+?)\\s*,\\s*([^}]+?)\\)"+a.tags.operationClose,n=a.tags.operationOpen+"include\\s*([^}]*?)\\s*,\\s*([^}]*?)"+a.tags.operationClose;
a.settings.forstart=RegExp(a.tags.operationOpen+"each\\s*([^}]*?)\\s*as\\s*(\\w*?)\\s*(,\\s*\\w*?)?"+a.tags.operationClose,"igm");a.settings.forend=RegExp(f,"igm");a.settings.ifstart=RegExp(c,"igm");a.settings.ifend=RegExp(b,"igm");a.settings.elsestart=RegExp(d,"igm");a.settings.elseifstart=RegExp(h,"igm");a.settings.interpolate=RegExp(e,"igm");a.settings.noneencode=RegExp(m,"igm");a.settings.inlinecomment=RegExp(i,"igm");a.settings.rangestart=RegExp(g,"igm");a.settings.include=RegExp(n,"igm")};a.tagInit();
a.set=function(a,c){var b=this,d=function(a){return a.replace(/[\$\(\)\[\]\+\^\{\}\?\*\|\.]/igm,function(a){return"\\"+a})},h=function(a,e){var c=a.match(/^tag::(.*)$/i);c?(b.tags[c[1]]=d(e),b.tagInit()):b.options[a]=e};if(2===arguments.length)h(a,c);else if(a===Object(a))for(var e in a)a.hasOwnProperty(e)&&h(e,a[e])};a.register=function(a,c){var b=this.options._method;return b.hasOwnProperty(a)?!1:b[a]=c};a.unregister=function(a){var c=this.options._method;if(c.hasOwnProperty(a))return delete c[a]};
a.template=function(f){var c=this;this.options=f;this.__interpolate=function(a,d,c){var e=a.split("|"),a=e[0]||"";1<e.length&&(a=e.shift(),e=e.shift().split(","),a="_method."+e.shift()+".call({}, "+[a].concat(e)+")");return"<%= "+(d?"_method.__escapehtml.escaping":"")+"("+(!c||!1!==c.detection?"_method.__escapehtml.detection":"")+"("+a+")) %>"};this.__removeShell=function(b,d){var h=0,b=b.replace(a.settings.forstart,function(a,b,d,c){d=d||"value";c=c&&c.substr(1);a="i"+h++;return"<% ~function() {for(var "+
a+" in "+b+") {if("+b+".hasOwnProperty("+a+")) {var "+d+"="+b+"["+a+"];"+(c?"var "+c+"="+a+";":"")+" %>"}).replace(a.settings.forend,"<% }}}(); %>").replace(a.settings.ifstart,function(a,b){return"<% if("+b+") { %>"}).replace(a.settings.ifend,"<% } %>").replace(a.settings.elsestart,function(){return"<% } else { %>"}).replace(a.settings.elseifstart,function(a,b){return"<% } else if("+b+") { %>"}).replace(a.settings.noneencode,function(a,b){return c.__interpolate(b,!1,d)}).replace(a.settings.interpolate,
function(a,b){return c.__interpolate(b,!0,d)}).replace(a.settings.inlinecomment,"").replace(a.settings.rangestart,function(a,b,d,c){a="j"+h++;return"<% ~function() {for(var "+a+"="+d+";"+a+"<"+c+";"+a+"++) {{var "+b+"="+a+"; %>"}).replace(a.settings.include,function(a,b,d){return"<%= _method.__juicer("+b+", "+d+"); %>"});if(!d||!1!==d.errorhandling)b="<% try { %>"+b+'<% } catch(e) {_method.__throw("Juicer Render Exception: "+e.message);} %>';return b};this.__toNative=function(a,d){return this.__convert(a,
!d||d.strip)};this.__lexicalAnalyze=function(b){var d=[],c=[],e="",f="if,each,_,_method,console,break,case,catch,continue,debugger,default,delete,do,finally,for,function,in,instanceof,new,return,switch,this,throw,try,typeof,var,void,while,with,null,typeof,class,enum,export,extends,import,super,implements,interface,let,package,private,protected,public,static,yield,const,arguments,true,false,undefined,NaN".split(","),i=function(a,b){if(Array.prototype.indexOf&&a.indexOf===Array.prototype.indexOf)return a.indexOf(b);
for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},g=function(b,e){e=e.match(/\w+/igm)[0];if(-1===i(d,e)&&-1===i(f,e)&&-1===i(c,e)){if("undefined"!==typeof window&&"function"===typeof window[e]&&window[e].toString().match(/^\s*?function \w+\(\) \{\s*?\[native code\]\s*?\}\s*?$/i)||"undefined"!==typeof global&&"function"===typeof global[e]&&global[e].toString().match(/^\s*?function \w+\(\) \{\s*?\[native code\]\s*?\}\s*?$/i))return b;if("function"===typeof a.options._method[e])return c.push(e),
b;d.push(e)}return b};b.replace(a.settings.forstart,g).replace(a.settings.interpolate,g).replace(a.settings.ifstart,g).replace(a.settings.elseifstart,g).replace(a.settings.include,g).replace(/[\+\-\*\/%!\?\|\^&~<>=,\(\)]\s*([A-Za-z_]+)/igm,g);for(b=0;b<d.length;b++)e+="var "+d[b]+"=_."+d[b]+";";for(b=0;b<c.length;b++)e+="var "+c[b]+"=_method."+c[b]+";";return"<% "+e+" %>"};this.__convert=function(a,d){var c;c="'use strict';var _=_||{};var _out='';_out+='";return!1!==d?c+=a.replace(/\\/g,"\\\\").replace(/[\r\t\n]/g,
" ").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,"';_out+=$1;_out+='").split("<%").join("';").split("%>").join("_out+='")+"';return _out;":c+=a.replace(/\\/g,"\\\\").replace(/[\r]/g,"\\r").replace(/[\t]/g,"\\t").replace(/[\n]/g,"\\n").replace(/'(?=[^%]*%>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<%=(.+?)%>/g,"';_out+=$1;_out+='").split("<%").join("';").split("%>").join("_out+='")+"';return _out.replace(/[\\r\\n]\\s+[\\r\\n]/g, '\\r\\n');"};
this.parse=function(a,d){var f=this;if(!d||!1!==d.loose)a=this.__lexicalAnalyze(a)+a;a=this.__removeShell(a,d);a=this.__toNative(a,d);this._render=new Function("_, _method",a);this.render=function(a,b){if(!b||b!==c.options._method)b=k(b,c.options._method);return f._render.call(this,a,b)};return this}};a.compile=function(a,c){if(!c||c!==this.options)c=k(c,this.options);try{var b=this.__cache[a]?this.__cache[a]:(new this.template(this.options)).parse(a,c);if(!c||!1!==c.cache)this.__cache[a]=b;return b}catch(d){return l("Juicer Compile Exception: "+
d.message),{render:function(){}}}};a.to_html=function(a,c,b){if(!b||b!==this.options)b=k(b,this.options);return this.compile(a,b).render(c,b._method)};return a});
