KISSY.add("gallery/kscroll/1.1/index",function(i,m){function k(a,b){k.superclass.constructor.call(this,b);this._init(a)}var j=m.all,l=function(a){return isNaN(parseInt(a))?0:parseInt(a)};k.ATTRS={prefix:{value:"ks-"},duration:{value:0.1},easing:{value:"easeNone"},container:{},body:{},track:{},drag:{},arrowUp:{},allowArrow:{value:!0},arrowDown:{},step:{},scrollBar:{}};i.extend(k,i.Base,{_init:function(a){var b="."+this.get("prefix"),a=this._wrap(j(a));this.set("container",a);this.set("body",a.one(b+
"body"));this.set("track",a.one(b+"track"));this.set("drag",this.get("track").one(b+"drag"));this.get("allowArrow")?(this.set("arrowUp",a.one(b+"arrowup")),this.arrowUpHeight=this.get("arrowUp").outerHeight(),this.set("arrowDown",a.one(b+"arrowdown")),this.arrowDownHeight=this.get("arrowDown").outerHeight()):this.arrowUpHeight=this.arrowDownHeight=0;this._bindEvt();this._setSize()},destroy:function(){var a=this.get("container");this.get("track");var b=this.get("arrowUp"),d=this.get("arrowDown"),c=
a.children().item(0);b&&b.remove();d&&d.remove();c.insertBefore(a);a.remove();c.css(this.__backup);c.removeClass(this.get("prefix")+"body")},_wrap:function(a){var b=this.get("prefix"),d=j("<div></div>");6==i.UA.ie&&a.css({overflow:"auto"});d.insertAfter(a).append(a);d.addClass(b+"container").css({position:"relative",overflow:"hidden",width:a.outerWidth(),height:a.outerHeight()});d.append(i.substitute('<div class="{prefix}scrollbar"><div class="{prefix}track" ><div class="{prefix}drag" ><div class="{prefix}dragtop"></div><div class="{prefix}dragbottom"></div><div class="{prefix}dragcenter"></div></div></div></div>',
{prefix:b}));var c=d.one("."+b+"scrollbar");this.set("scrollBar",c);this.get("allowArrow")&&(c.append(i.substitute('<div class="{prefix}arrow{type}"><a href="javascript:void(\'scroll {type}\')" >scroll {type}</a></div>',{type:"up",prefix:b})),c.append(i.substitute('<div class="{prefix}arrow{type}"><a href="javascript:void(\'scroll {type}\')" >scroll {type}</a></div>',{type:"down",prefix:b})));c=a[0].style;this.__backup={position:c.position,top:c.top,left:c.left,width:c.width,height:c.height,overflow:c.overflow};
a.css({position:"absolute",top:0,left:0,width:"100%",height:"auto",overflow:"visible"}).addClass(b+"body");return d},_bindArrow:function(a){var b=this,d=a.charAt(0).toUpperCase()+a.substring(1),c=0,f=null,e=b.get("prefix"),g=b.get("arrow"+d),h=function(){c+=1;var d=b.get("step"),e=300-25*c;b.scrollByDistance("up"==a?d:-d);30>=e&&(e=30);f=setTimeout(function(){h()},e)};g.on("click",function(){var c=b.get("step");b.scrollByDistance("up"==a?c:-c)}).on("mousedown",function(){g.addClass(e+"arrow"+a+"-active");
h()}).on("mouseup",function(){g.removeClass(e+"arrow"+a+"-active");c=0;clearTimeout(f)}).on("mouseleave",function(){g.removeClass(e+"arrow"+a+"-active");c=0;g.removeClass(e+"arrow"+a+"-hover");clearTimeout(f)}).on("mouseover",function(){g.addClass(e+"arrow"+a+"-hover")})},_bindDrag:function(){var a=j(document),b=this,d,c=b.get("prefix"),f=0,e=b.get("drag"),g=b.get("track"),h=function(a){var c=g.outerHeight(),h=e.outerHeight(),c=c-h,a=f+(a.pageY-d);0>a&&(a=0);a>c&&(a=c);e.css("top",a);b.scrollByPercent(a/
c,1)};e.on("mouseenter",function(){e.addClass(c+"drag-hover")}).on("mouseleave",function(){e.removeClass(c+"drag-hover")}).on("click",function(a){a.stopPropagation()}).on("mousedown",function(b){e.addClass(c+"drag-active");f=parseInt(e.css("top"))||0;d=b.pageY;a.on("mousemove",h).on("mouseup",function(){e.removeClass(c+"drag-active");a.detach("mousemove",h);a.detach("mouseup",arguments.callee);d=0})})},_bindHotkey:function(){var a=this,b=a.get("body"),d=a.get("container");d.css("outline","none").attr("tabindex",
i.guid()).on("keydown",function(c){var f=c.keyCode,e=a.get("step");if(!~"INPUT,TEXTAREA".indexOf(c.target.nodeName.toUpperCase())&&~"38,39,36,40,37,35".indexOf(f)){var g=~"38,39,36".indexOf(f)?e:-e,h=l(b.css("top"));!(0<g&&0<=h||0>g&&h+b.outerHeight()<=d.outerHeight())&&c.halt();switch(f){case 38:case 39:a.scrollByDistance(e);break;case 40:case 37:a.scrollByDistance(-e);break;case 36:a.scrollByPercent(0);break;case 35:a.scrollByPercent(1)}}})},_bindTrack:function(){var a=this,b=a.get("prefix"),d=
a.get("track");d.unselectable().on("click",function(b){a.scrollByPercent((b.pageY-d.offset().top)/d.outerHeight())}).on("mousedown",function(a){a.preventDefault()}).on("mouseenter",function(){d.addClass(b+"track-hover")}).on("mouseleave",function(){d.removeClass(b+"track-hover")})},_bindBodyDrag:function(){var a=this,b=j(document),d=0,c=function(b){d>b.pageY?a.scrollByDistance(5):a.scrollByDistance(-5)};a.get("body").on("mousedown",function(a){d=a.pageY;b.on("mousemove",c).on("mouseup",function(){b.detach("mousemove",
c);b.detach("mouseup",arguments.callee);d=0})})},_bindContainer:function(){var a=this,b=a.get("body"),d=a.get("container");a.get("container").on("mousewheel",function(c){var f=c.deltaY,e=l(b.css("top"));!(0<f&&0<=e||0>f&&e+b.outerHeight()<=d.outerHeight())&&c.halt();f=a.get("step");a.scrollByDistance(0<c.deltaY?f:-f)})},_bindEvt:function(){this._bindContainer();this.get("allowArrow")&&(this._bindArrow("up"),this._bindArrow("down"));this._bindTrack();this._bindDrag();!0===this.get("hotkey")&&this._bindHotkey();
this.get("bodydrag")&&this._bindBodyDrag()},resize:function(a,b){this.get("container").css({width:a,height:b});this._setSize()},_setSize:function(){var a=this.get("body").outerHeight(),b=this.get("container").innerHeight();this.get("arrowUp");this.get("arrowDown");var d=this.get("track"),c=this.get("drag"),f=this.arrowUpHeight+this.arrowDownHeight;a<=b||b<f?(this.get("body").css({top:0}),this.get("scrollBar").hide()):(this.get("scrollBar").show(),a=(b-f)*b/a,20>a&&(a=20),this.get("step")||this.set("step",
Math.max(a/6,10)),d.css({height:b-f,top:this.arrowUpHeight}),c.css({height:a}))},_scrollBodyToPosition:function(a){var b=this.get("container"),d=this.get("body"),b=d.outerHeight()-b.innerHeight();0>b||(0<a&&(a=0),(0>a?-a:a)>b&&(a=-b),d.css("top",a))},scrollByDistance:function(a,b){this._scrollBodyToPosition(parseInt(this.get("body").css("top"))+a);b||this._updateBar()},scrollByPercent:function(a,b){a=parseFloat(a,10);if(!isNaN(a)&&!(1<a||0>a))this._scrollBodyToPosition((this.get("body").outerHeight()-
this.get("container").innerHeight())*-a),b||this._updateBar()},scrollToElement:function(a){a=j(a);a.length&&(this._scrollBodyToPosition(-(a.offset().top-this.get("body").offset().top)),this._updateBar())},_updateBar:function(){var a=this.get("drag"),b=this.get("track").innerHeight()-a.outerHeight(),d=this.get("body"),c=this.get("container"),f=parseInt(d.css("top")),d=(0>f?-f:f)/(d.outerHeight()-c.innerHeight());a.css("top",d*b)}});return k},{requires:["node"]});
