KISSY.add("gallery/spotlight/1.1/index",function(d){function k(a){for(var b=this.constructor,a=a||{};b;)a=d.merge(b.Config,a),b=b.superclass?b.superclass.constructor:null;this.config=a;this.quene=a.quene||[];delete a.quene;this.masks=["top","right","bottom","left"];this.isMasked=!1;this._init()}var g=d.DOM,l=d.Event;k.Config={zIndex:9999,bgColor:"#000",opacity:0.5,maskCls:"spotlight-mask",anim:{duration:0.2},initIndex:0,lazyInit:!0,clickOnHide:!0,lastOnEnd:!0,resizeBuffer:50,clickOnHideTip:"",toggleOnAnim:!1,
focusBorder:null,listeners:null};d.augment(k,d.EventTarget,{_init:function(){this._initEvent()},_initEvent:function(){var a=this.config.listeners;a&&d.each(a,function(b,c){d.isFunction(b)&&this.on(c,b,a.scope||this)},this)},_onRender:function(){var a=document,b=a.createElement("div"),c=a.createElement("div"),f=a.createElement("div"),e=a.createElement("div"),h=a.createDocumentFragment(),d=this.config,j=d.maskCls;h.appendChild(c);h.appendChild(b);h.appendChild(f);h.appendChild(e);b.title=c.title=f.title=
e.title=d.clickOnHideTip;b.style.position=c.style.position=f.style.position=e.style.position="absolute";b.style.backgroundColor=c.style.backgroundColor=f.style.backgroundColor=e.style.backgroundColor=d.bgColor;b.style.opacity=c.style.opacity=f.style.opacity=e.style.opacity=d.opacity;b.style.filter=c.style.filter=f.style.filter=e.style.filter="alpha(opacity="+100*parseFloat(d.opacity)+")";b.style.zIndex=c.style.zIndex=f.style.zIndex=e.style.zIndex=d.zIndex;b.className=c.className=f.className=e.className=
j;b.className+=" "+j+"-left";c.className+=" "+j+"-top";f.className+=" "+j+"-right";e.className+=" "+j+"-bottom";f.style.top=f.style.right=e.style.right=e.style.bottom=b.style.left=b.style.bottom=c.style.left=c.style.top=0;if(d.focusBorder){var i=this.border=document.createElement("div");i.className=j+"-border";i.style.border=d.focusBorder.borderStyle;i.style.position="absolute";i.style.zIndex=d.zIndex+1;i.style.top=-9999;h.appendChild(i)}g.append(h,a.body);this.fire("render");this.left=b;this.top=
c;this.right=f;this.bottom=e;!0===d.clickOnHide&&l.delegate(a.body,"click","."+d.maskCls,this.hide,this);l.on(window,"resize",this._onResize,this)},_onResize:function(){this.resizeTimer&&this.resizeTimer.cancel();this.resizeTimer=d.later(function(){if(this.isMasked){var a=this._getMaskBoxSize(this.quene[this.currentIndex].node);d.each(this.masks,function(b){g.css(this[b],a[b])},this)}},this.config.resizeBuffer,!1,this)},_unmask:function(){this._alignToBox({top:{height:0},bottom:{height:0},right:{width:0},
left:{width:0}},this.config.anim.duration);this.isMasked=!1;this.border&&(this.border.style.top=-9999)},_getMaskBoxSize:function(a){var b=g.offset(a),c=g.height(a),a=g.width(a),d=b.top,b=b.left,e=g.docWidth(),h=g.docHeight();return{top:{height:d,width:b+a},left:{height:h-d,width:b,top:d},right:{width:e-(a+b),height:d+c},bottom:{height:h-(c+d),width:e-b,top:d+c}}},_alignToBox:function(a,b){if(this.rendered){d.each(this.masks,0===b||!1===b?function(b){g.css(this[b],a[b])}:function(c){d.Anim(this[c],
a[c],b).run()},this);if(this.border){var c=this.quene[this.currentIndex].node,f=g.offset(c),e=g.height(c),c=g.width(c);g.css(this.border,{height:e,width:c,top:f.top,left:f.left})}this.isMasked=!0;this.border&&this.config.focusBorder.focusOnBlink&&this._applyBlinkBorder()}},_applyBlinkBorder:function(){this._cancelBlinkBorder();var a=this.config,b=this.border.style.top,c;this.border.style.display="block";this.borderBlinkTimer=d.later(function(){c=this.border.style.top;this.border.style.top=c==b?"-9999px":
b},a.focusBorder.interval,!0,this);a.focusBorder.blinkTime&&(this.borderBlinkStopTimer=d.later(function(){this._cancelBlinkBorder()},a.focusBorder.blinkTime,!1,this))},_cancelBlinkBorder:function(){this.borderBlinkTimer&&(this.borderBlinkTimer.cancel(),delete this.borderBlinkTimer);this.borderBlinkStopTimer&&(this.borderBlinkStopTimer.cancel(),delete this.borderBlinkStopTimer);this.border&&(this.border.style.display="none")},canNext:function(){return!!this.quene[this.currentIndex+1]},canPrevious:function(){return!!this.quene[this.currentIndex-
1]},hide:function(){this._unmask();this.fire("hide");this._cancelBlinkBorder()},end:function(){this.currentIndex=0;this.hide()},start:function(){var a=d.isNumber(this.config.initIndex)?this.config.initIndex:this.currentIndex;this.quene[a]&&(this.currentIndex=a,this.focusTo(a,!0),delete this.config.initIndex)},nextFocus:function(){var a=this.currentIndex+1;this.quene[a]&&(this.currentIndex=a,this.fire("nextFocus",{nodeTarget:this.quene[a]}),this.focusTo(this.currentIndex,this.config.toggleOnAnim))},
prevFocus:function(){var a=this.currentIndex-1;this.quene[a]&&(this.currentIndex=a,this.fire("prevFocus",{nodeTarget:this.quene[a]}),this.focusTo(this.currentIndex,this.config.toggleOnAnim))},focusTo:function(a,b){!0!==this.rendered&&(this._onRender(),this.rendered=!0);if(this.quene[a]){this.currentIndex=a;var c=this.quene[a].node,f=g.height(c),e=this._getMaskBoxSize(c),h=g.offset(c),k=h.top,j=g.viewportHeight(),i=g.scrollTop();(k>j+i||i>f+k)&&d.one(window).animate({scrollTop:k-f},0.2);this._alignToBox(e,
b?this.config.anim.duration:!1);this.fire("focusTo",{nodeTarget:c,offset:h,index:a})}},addFocus:function(a){this.quene.push(a)},removeFocus:function(a){this.quene.splice(a,1)},destroy:function(){this.hide();d.later(function(){g.remove([this.top,this.left,this.right,this.bottom,this.border]);this.top=this.left=this.right=this.bottom=this.border=null},500,!1,this)}});return k});
