KISSY.add("gallery/kcharts/1.1/piechart/index",function(p,y,C,D,E,F){function k(c,b){return c.toFixed(void 0==typeof b?b:2)}function t(c){return parseFloat(c.toFixed(4))}function B(c){w=(new F({themeCls:c.themeCls}))._colors;this.colorseed=0;this.container=p.get(c.renderTo);this.labelLayer=this.paper=y(p.get(this.container));this.textlabel=new D;this.cfg=p.mix(G,c);this.percentData=this.sectors=null;this.drawSector();this.renderTip()}var j=p.DOM,w,G={labelPadding:20};p.extend(B,p.Base,{bindEvent:function(){for(var c=
this.sectors,b=this,d=this.cfg.data,g=!1,e=null,f=0;f<c.length;f++)(function(a){c[a].mouseover(function(){g=!0;e&&clearTimeout(e);b.fire("mouseenter",{sector:c[a],data:d[a],index:a})}).mouseout(function(){g=!1;b.fire("mouseleave",{target:c[a],data:d[a],index:a});e=setTimeout(function(){g||b.tip&&b.tip.hide()},500)}).click(function(){b.fire("click",{target:c[a],data:d[a],index:a})})})(f)},onend:function(){var c=this.cfg,b=this;c.labelIndside?this.drawInsideLabel():!1!=c.label&&this.drawLabel();this.bindEvent();
setTimeout(function(){b.fire("afterRender")},0)},sectorFull:function(c,b,d,g,e){var f=Math.PI/180,a=(g+e)/2,i=c+d*Math.cos(-a*f),u=c+d*Math.cos(-g*f),m=c+d*Math.cos(-e*f),q=b+d*Math.sin(-a*f),o=b+d*Math.sin(-g*f),f=b+d*Math.sin(-e*f),c=["M",k(c),b,"L",k(u),k(o),"A",d,d,0,+(180<Math.abs(e-g)),1,k(m),k(f),"z"];g>e?(b=g,g=e):b=e;c.middle={from:b,to:g,angel:a,x:i,y:q};return c},sector:function(c,b,d,g,e,f){var a=Math.PI/180,i=(e+f)/2,u=c+d*Math.cos(-i*a),m=c+d*Math.cos(-e*a),q=c+d*Math.cos(-f*a),o=c+
g*Math.cos(-e*a),H=c+g*Math.cos(-f*a),c=b+d*Math.sin(-i*a),j=b+d*Math.sin(-e*a),p=b+d*Math.sin(-f*a),l=b+g*Math.sin(-e*a),b=b+g*Math.sin(-f*a),d=["M",k(o),k(l),"L",k(m),k(j),"A",d,d,0,+(180<Math.abs(f-e)),1,k(q),k(p),"L",k(H),k(b),"A",g,g,0,+(180<Math.abs(f-e)),0,k(o),k(l)];e>f?(g=e,e=f):g=f;d.middle={from:g,to:e,angel:i,x:u,y:c};return d},drawSector:function(){function c(c){for(var c=c.s,e=g.animater?c*o:o,f,r,n=0;n<z;n++)if(n?(f=r,r=f-360*c*a[n]):(i=90+360*(a[0]/2),u=90-360*(a[0]/2),f=i+c*(90-i),
r=f+c*(u-i)),j=v?d.sector(m,q,e,v,f,r):d.sectorFull(m,q,e,f,r),1==a.length&&(v?(j[12]=parseFloat(j[12])-0.1,j[j.length-2]=parseFloat(j[j.length-2])+0.1):j[j.length-3]=parseFloat(j[j.length-3])-0.1),k=j.join(" "),s[n]?s[n].attr("path",k):(f=b.path(k),s[n]=f,f=d.getcolor(n,t),s[n].attr({fill:f,stroke:"#fff"}),s[n].percent=a[n]),1===c)s[n].middle=j.middle}var b=this.paper,d=this,g=this.cfg,e=g.data,f=0,a=[],i,u,m=g.cx,q=g.cy,o=g.R,j,k,t=g.colors;this.percentData=a;for(var l=0;l<e.length;l++)var A=p.isNumber(e[l].data)?
e[l].data:parseFloat(e[l].data),f=f+A;for(l=0;l<e.length;l++)a.push(e[l].data/f);var s=d.sectors=[],z=a.length,v=g.r,e={sector:c,r:function(c,f){for(var f=c.s,g=f*o,e,n,l=0;l<z;l++)if(l?(e=n,n=e-360*a[l]):(i=90+360*(a[0]/2),u=90-360*(a[0]/2),e=i+(90-i),n=e+(u-i)),j=d.sectorFull(m,q,g,e,n),k=j.join(" "),s[l]?s[l].attr("path",k):(e=b.path(k),s[l]=e,e=this.getcolor(l),s[l].attr({fill:e,stroke:"#fff"}),s[l].percent=a[l]),1===f)s[l].middle=j.middle}},f=p.mix({type:"sector"},g.anim),l=p.UA.ie&&8<p.UA.ie&&
g.anim||!p.UA.ie&&g.anim,e=e[f.type]||c;l?(f=new C(f),f.on("step",e,this),f.on("end",this.onend,this),f.run()):(e({s:1,t:1}),this.onend())},scaleSector:function(c,b,d,g,e){c.scale(b,d,g,e)},transformSector:function(c,b){if(this.currentTransformedSector!=c){var d,g;b||(b=10);this.currentTransformedSector&&(g=this.currentTransformedSector.middle.angel*Math.PI/180,d=b*Math.cos(g),g=-b*Math.sin(g),this.currentTransformedSector.translate(-d,-g));g=c.middle.angel*Math.PI/180;d=b*Math.cos(g);g=-b*Math.sin(g);
c.animate({transform:"t"+d+","+g},400);this.currentTransformedSector=c}},getLabelXY:function(c,b,d,g){d=this.textlabel.getTextSize(d);c=g?c-d.width:c+5;b-=d.height/2;return{x:t(c),y:t(b)}},drawLabel:function(){for(var c=this.labelLayer,b=this.cfg,d=b.cx,g=b.cy,e=this.sectors,f,a,i=e.length,u=b.data,m=Math.PI/180,q=Math.cos,o=Math.sin,k=Math.asin,p,w,l,A,s,z=b.R,v=b.R+b.labelPadding,y=b.R+2*b.labelPadding/3,h,x=[],r=[],n=0;n<i;n++)f=e[n],a=f.middle,h={},-90<=a.angel&&90>=a.angel?x.push(h):r.push(h),
a=a.angel%360*m,p=t(d+z*q(-a)),w=t(g+z*o(-a)),l=t(d+y*q(-a)),A=t(g+y*o(-a)),s=t(d+v*q(-a)),a=t(g+v*o(-a)),h.i=n,h.x=p,h.y=w,h.x1=l,h.y1=A,h.x2=s,h.y2=a,f.label=h;e=r.length;f=0;Math.round(2*b.R/e);for(j.offset(this.container);e>f;)h=r[f],i=h.y2,a=(i-g)/v,a=1<a?1:-1>a?-1:a,a=Math.PI+k(a),m=t(d+v*q(a)),0<f&&(a=r[f-1],a=a.y3,a-14<i&&(i=a-14)),m-=5,h.x3=m,h.y3=i,o=["M",h.x,h.y,"Q",h.x2,h.y2," ",m,i],a=u[h.i].label,h.text=a,h=this.getLabelXY(m,i,a,!0),i=j.create('<span class="ks-charts-label"/>'),j.html(i,
a),j.css(this.container,"position","relative"),j.css(i,{position:"absolute",left:h.x+"px",top:h.y+"px"}),j.append(i,this.container),h=c.path(o.join(",")),h.toBack(),b.labelline&&b.labelline.attr&&h.attr(b.labelline.attr),f++;r=x.length;e=0;Math.round(2*b.R/r);for(x=x.slice(0);r>e;)h=x[e],i=h.y2,0<r&&(a=x[r-1],a.y3+14>i&&(i=a.y3+14)),a=(i-g)/v,a=1<a?1:-1>a?-1:a,a=k(a),m=t(d+v*q(a)),m+=5,h.x3=m,h.y3=i,o=["M",h.x,h.y,"Q",h.x2,h.y2," ",m,i,"L"],a=u[h.i].label,h.text=a,h=this.getLabelXY(m,i,a),i=j.create('<span class="ks-charts-label"/>'),
j.html(i,a),j.css(this.container,"position","relative"),j.css(i,{position:"absolute",left:h.x+"px",top:h.y+"px"}),j.append(i,this.container),h=c.path(o.join(",")),h.toBack(),b.labelline&&b.labelline.attr&&h.attr(b.labelline.attr),e++},drawInsideLabel:function(){for(var c=this.cfg,b=c.data,d=this.sectors,g=c.cx,e=c.cy,c=c.R,f=0,a=d.length;f<a;f++){var i=b[f].label,k=d[f].middle.angel,m=Math.PI/180,q=g+0.5*c*Math.cos(-k*m),k=e+0.5*c*Math.sin(-k*m),m=this.textlabel.getTextSize(i),o=j.create('<span class="ks-charts-label"/>');
j.text(o,i);q-=0.5*m.width;k-=0.5*m.height;j.css(this.container,"position","relative");j.css(o,{position:"absolute",left:q+"px",top:k+"px"});j.append(o,this.container)}},renderTip:function(){var c=this.cfg.tip,b=this.container,d,g,e,f;c&&c.tpl&&(d=j.offset(b),g=j.outerWidth(b),e=j.outerHeight(b),d=c.boundryDetect?{x:d.left,y:d.top,width:g,height:e}:{},p.mix(c,{rootNode:p.all(b),boundry:d,autoRender:1}),this.tip=new E(c),f=this.tip.getInstance(),this.on("mouseenter",function(a){var b=a.sector,e=b.middle,
g=e.x,e=e.y,d=y.getRGB(b.attr("fill")),k={};p.mix(k,a.data);k.percent=b.percent;b=d.hex;d=parseInt(b.substring(1,3),16);a=parseInt(b.substring(3,5),16);b=parseInt(b.substring(5,7),16);d=parseInt(80*d/100);a=parseInt(80*a/100);b=parseInt(80*b/100);d=255>d?d:255;a=255>a?a:255;b=255>b?b:255;d=1==d.toString(16).length?"0"+d.toString(16):d.toString(16);a=1==a.toString(16).length?"0"+a.toString(16):a.toString(16);b=1==b.toString(16).length?"0"+b.toString(16):b.toString(16);d="#"+d+a+b;this.tip.renderTemplate(c.tpl,
k);j.css(f,{borderColor:d});this.tip.animateTo(g,e)},this))},getcolor:function(c,b){var d=b||w,c=c%d.length;return b&&b[c]?d[c].DEFAULT:w[c].DEFAULT}});return B},{requires:["gallery/kcharts/1.1/raphael/index","gallery/kcharts/1.1/ft/index","gallery/kcharts/1.1/label/index","gallery/kcharts/1.1/tip/index","../tools/color/index"]});
