KISSY.add("gallery/kcharts/1.1/piechart/index",function(p,x,B,C,D,E){function j(c,b){return c.toFixed(void 0==typeof b?b:2)}function t(c){return parseFloat(c.toFixed(4))}function y(c){v=(new E({themeCls:c.themeCls}))._colors;this.colorseed=0;this.container=p.get(c.renderTo);this.labelLayer=this.paper=x(p.get(this.container));this.textlabel=new C;this.cfg=p.mix(F,c);this.percentData=this.sectors=null;this.drawSector();this.renderTip()}var k=p.DOM,v,F={labelPadding:20};p.extend(y,p.Base,{bindEvent:function(){for(var c=
this.sectors,b=this,f=this.cfg.data,d=!1,e=null,g=0;g<c.length;g++)(function(a){c[a].mouseover(function(){d=!0;e&&clearTimeout(e);b.fire("mouseenter",{target:c[a],data:f[a],index:a})}).mouseout(function(){d=!1;b.fire("mouseleave",{target:c[a],data:f[a],index:a});e=setTimeout(function(){d||b.tip&&b.tip.hide()},500)}).click(function(){b.fire("click",{target:c[a],data:f[a],index:a})})})(g)},onend:function(){this.cfg.labelIndside?this.drawInsideLabel():this.drawLabel();this.bindEvent();this.fire("afterRender")},
sectorFull:function(c,b,f,d,e){var g=Math.PI/180,a=(d+e)/2,i=c+f*Math.cos(-a*g),u=c+f*Math.cos(-d*g),l=c+f*Math.cos(-e*g),r=b+f*Math.sin(-a*g),n=b+f*Math.sin(-d*g),g=b+f*Math.sin(-e*g),c=["M",j(c),b,"L",j(u),j(n),"A",f,f,0,+(180<Math.abs(e-d)),1,j(l),j(g),"z"];d>e?(b=d,d=e):b=e;c.middle={from:b,to:d,angel:a,x:i,y:r};return c},sector:function(c,b,f,d,e,g){var a=Math.PI/180,i=(e+g)/2,u=c+f*Math.cos(-i*a),l=c+f*Math.cos(-e*a),r=c+f*Math.cos(-g*a),n=c+d*Math.cos(-e*a),k=c+d*Math.cos(-g*a),c=b+f*Math.sin(-i*
a),p=b+f*Math.sin(-e*a),s=b+f*Math.sin(-g*a),q=b+d*Math.sin(-e*a),b=b+d*Math.sin(-g*a),f=["M",j(n),j(q),"L",j(l),j(p),"A",f,f,0,+(180<Math.abs(g-e)),1,j(r),j(s),"L",j(k),j(b),"A",d,d,0,+(180<Math.abs(g-e)),0,j(n),j(q)];e>g?(d=e,e=g):d=g;f.middle={from:d,to:e,angel:i,x:u,y:c};return f},drawSector:function(){function c(c){for(var c=c.s,g=d.animater?c*n:n,e,h,o=0;o<t;o++)if(o?(e=h,h=e-360*c*a[o]):(i=90+360*(a[0]/2),u=90-360*(a[0]/2),e=i+c*(90-i),h=e+c*(u-i)),k=z?f.sector(l,r,g,z,e,h):f.sectorFull(l,
r,g,e,h),j=k.join(" "),q[o]?q[o].attr("path",j):(e=b.path(j),q[o]=e,e=f.getcolor(o),q[o].attr({fill:e,stroke:"#fff"}),q[o].percent=a[o]),1===c)q[o].middle=k.middle}var b=this.paper,f=this,d=this.cfg,e=d.data,g=0,a=[],i,u,l=d.cx,r=d.cy,n=d.R,k,j;this.percentData=a;for(var s=0;s<e.length;s++)g+=e[s].data;for(s=0;s<e.length;s++)a.push(e[s].data/g);var q=f.sectors=[],t=a.length,z=d.r,e={sector:c,r:function(c,e){for(var e=c.s,d=e*n,h,g,m=0;m<t;m++)if(m?(h=g,g=h-360*a[m]):(i=90+360*(a[0]/2),u=90-360*(a[0]/
2),h=i+(90-i),g=h+(u-i)),k=f.sectorFull(l,r,d,h,g),j=k.join(" "),q[m]?q[m].attr("path",j):(h=b.path(j),q[m]=h,h=this.getcolor(m),q[m].attr({fill:h,stroke:"#fff"}),q[m].percent=a[m]),1===e)q[m].middle=k.middle}},g=p.mix({type:"sector"},d.anim),s=p.UA.ie&&9<p.UA.ie&&d.anim||!p.UA.ie&&d.anim,e=e[g.type]||c;s?(g=new B(g),g.on("step",e,this),g.on("end",this.onend,this),g.run()):(e({s:1,t:1}),this.onend())},scaleSector:function(c,b,f,d,e){c.scale(b,f,d,e)},transformSector:function(c,b){if(this.currentTransformedSector!=
c){var f,d;b||(b=10);this.currentTransformedSector&&(d=this.currentTransformedSector.middle.angel*Math.PI/180,f=b*Math.cos(d),d=-b*Math.sin(d),this.currentTransformedSector.translate(-f,-d));d=c.middle.angel*Math.PI/180;f=b*Math.cos(d);d=-b*Math.sin(d);c.animate({transform:"t"+f+","+d},400);this.currentTransformedSector=c}},getLabelXY:function(c,b,f,d){f=this.textlabel.getTextSize(f);c=d?c-f.width:c+5;b-=f.height/2;return{x:t(c),y:t(b)}},drawLabel:function(){for(var c=this.labelLayer,b=this.cfg,f=
b.cx,d=b.cy,e=this.sectors,g,a,i=e.length,u=b.data,l=Math.PI/180,r=Math.cos,n=Math.sin,j=Math.asin,p,s,q,v,z,x=b.R,w=b.R+b.labelPadding,y=b.R+2*b.labelPadding/3,h,o=[],m=[],A=0;A<i;A++)g=e[A],a=g.middle,h={},-90<=a.angel&&90>=a.angel?o.push(h):m.push(h),a=a.angel%360*l,p=t(f+x*r(-a)),s=t(d+x*n(-a)),q=t(f+y*r(-a)),v=t(d+y*n(-a)),z=t(f+w*r(-a)),a=t(d+w*n(-a)),h.i=A,h.x=p,h.y=s,h.x1=q,h.y1=v,h.x2=z,h.y2=a,g.label=h;e=m.length;g=0;Math.round(2*b.R/e);for(k.offset(this.container);e>g;)h=m[g],i=h.y2,a=
(i-d)/w,a=1<a?1:-1>a?-1:a,a=Math.PI+j(a),l=t(f+w*r(a)),0<g&&(a=m[g-1],a=a.y3,a-14<i&&(i=a-14)),l-=5,h.x3=l,h.y3=i,n=["M",h.x,h.y,"Q",h.x2,h.y2," ",l,i],a=u[h.i].label,h.text=a,h=this.getLabelXY(l,i,a,!0),i=k.create('<span class="ks-charts-label"/>'),k.html(i,a),k.css(this.container,"position","relative"),k.css(i,{position:"absolute",left:h.x+"px",top:h.y+"px"}),k.append(i,this.container),h=c.path(n.join(",")),h.toBack(),b.labelline&&b.labelline.attr&&h.attr(b.labelline.attr),g++;m=o.length;e=0;Math.round(2*
b.R/m);for(o=o.slice(0);m>e;)h=o[e],i=h.y2,0<m&&(a=o[m-1],a.y3+14>i&&(i=a.y3+14)),a=(i-d)/w,a=1<a?1:-1>a?-1:a,a=j(a),l=t(f+w*r(a)),l+=5,h.x3=l,h.y3=i,n=["M",h.x,h.y,"Q",h.x2,h.y2," ",l,i,"L"],a=u[h.i].label,h.text=a,h=this.getLabelXY(l,i,a),i=k.create('<span class="ks-charts-label"/>'),k.html(i,a),k.css(this.container,"position","relative"),k.css(i,{position:"absolute",left:h.x+"px",top:h.y+"px"}),k.append(i,this.container),h=c.path(n.join(",")),h.toBack(),b.labelline&&b.labelline.attr&&h.attr(b.labelline.attr),
e++},drawInsideLabel:function(){for(var c=this.cfg,b=c.data,f=this.sectors,d=c.cx,e=c.cy,c=c.R,g=0,a=f.length;g<a;g++){var i=b[g].label,j=f[g].middle.angel,l=Math.PI/180,r=d+0.5*c*Math.cos(-j*l),j=e+0.5*c*Math.sin(-j*l),l=this.textlabel.getTextSize(i),n=k.create('<span class="ks-charts-label"/>');k.text(n,i);r-=0.5*l.width;j-=0.5*l.height;k.css(this.container,"position","relative");k.css(n,{position:"absolute",left:r+"px",top:j+"px"});k.append(n,this.container)}},renderTip:function(){var c=this.cfg.tip,
b=this.container,f,d,e,g;c&&c.tpl&&(f=k.offset(b),d=k.outerWidth(b),e=k.outerHeight(b),f=c.boundryDetect?{x:f.left,y:f.top,width:d,height:e}:{},p.mix(c,{rootNode:p.Node(b),boundry:f}),this.tip=new D(c),g=this.tip.getInstance(),this.on("mouseenter",function(a){var b=a.target,e=b.middle,f=e.x,e=e.y,d=x.getRGB(b.attr("fill")),j={};p.mix(j,a.data);j.percent=b.percent;b=d.hex;d=parseInt(b.substring(1,3),16);a=parseInt(b.substring(3,5),16);b=parseInt(b.substring(5,7),16);d=parseInt(80*d/100);a=parseInt(80*
a/100);b=parseInt(80*b/100);d=255>d?d:255;a=255>a?a:255;b=255>b?b:255;d=1==d.toString(16).length?"0"+d.toString(16):d.toString(16);a=1==a.toString(16).length?"0"+a.toString(16):a.toString(16);b=1==b.toString(16).length?"0"+b.toString(16):b.toString(16);d="#"+d+a+b;this.tip.renderTemplate(c.tpl,j);k.css(g,{borderColor:d});this.tip.animateTo(f,e)},this))},getcolor:function(c,b){var f=this.cfg,c=c%(v.length-1);return b=f.colors&&f.colors[c]?f.colors[c].DEFAULT:v[c].DEFAULT}});return y},{requires:["gallery/kcharts/1.1/raphael/index",
"gallery/kcharts/1.1/ft/index","gallery/kcharts/1.1/label/index","gallery/kcharts/1.1/tip/index","../tools/color/index"]});
