KISSY.add("gallery/form/1.1/uploader/themes/ershouUploader/index",function(b,m,l,e,i){function c(a){c.superclass.constructor.call(this,a)}var d=m.all;b.extend(c,l,{afterUploaderRender:function(a){var g=this.get("oPlugin"),h=a.get("queue"),f=a.get("button"),j=a.get("auth"),n=this.get("queueTarget");f=f.get("target");f=d(".original-file-input",f);d(f).remove();b.log("[Theme-ershou] old input removed.");f=5;if(j)f=j.getRule("max");else b.log("[Theme-ershou] Cannot get auth");this.set("maxFileAllowed",
f);g=new g.preview;j=new e({msgContainer:this.get("msgContainer"),successMsgCls:this.get("successMsgCls"),hintMsgCls:this.get("hintMsgCls"),errorMsgCls:this.get("errorMsgCls")});var o=new i(this.get("mainPicInput"),this.get("queueTarget"));this.set("message",j);this.set("preview",g);this.set("setMainPic",o);if(a.get("type")=="ajax"){b.log("[Theme-ershou] advance queue");d(this.get("queueTarget")).addClass("advance-queue")}d(n).delegate("click",".J_SetMainPic",function(k){k.preventDefault();k=d(k.currentTarget).parent("li");
o.setMainPic(k)});d(n).delegate("click",".J_DeleltePic",function(k){k.preventDefault();k=d(k.currentTarget).attr("data-file-id");h.remove(k)});return true},_updateCount:function(){var a=this.get("queue").getFiles("success"),g=this.get("maxFileAllowed")[0],h=this.get("message"),f=this.get("defaultMsg"),j=this.get("leftMsg");a=a.length?b.substitute(j,{left:g-a.length}):b.substitute(f,{max:g});h.send(a,"hint");b.log("[Theme-ershou] file count updated. Message sent.")},_addCallback:function(a,g){var h=
this.get("queue"),f=this._appendFileDom(g);h.updateFile(a,{target:f});h.fileStatus(a,"waiting");this.displayFile(true,f);this._updateCount();return h.getFile(a)},_waitingHandler:function(a){var g=this.get("preview"),h=a.file,f=h.target,j=d(".J_ItemPic",f);g&&g.preview(h.input,j);b.log("[Theme-ershou] preview done for file: "+a.file.id);d(f).addClass("upload-waiting")},_addHandler:function(){b.log("[Theme-ershou] add done.")},_startHandler:function(a){d(a.file.target).replaceClass("upload-waiting",
"uploading");b.log("[Theme-ershou] start upload")},_successHandler:function(a){a=a.file;var g=a.target,h=this.get("setMainPic");d(g).replaceClass("uploading","upload-done").attr("data-url",a.result.data.url);h.setMainPic();this._updateCount()},_removeFileHandler:function(a){a=a.file.target;this._updateCount();d(a).remove();b.log("[Theme-ershou] file deleted.")}},{ATTRS:{name:{value:"ershouUploader"},cssUrl:{value:"gallery/form/1.1/uploader/themes/ershouUploader/style.css"},fileTpl:{value:'<li id="J_LineQueue-{id}" data-file-id="{id}" data-url="{sUrl}" data-name="{name}" data-size="{textSize}"><div class="J_Wrapper wrapper"><div class="tb-pic120"><a href="javascript:void(0);"><img class="J_ItemPic" src="{sUrl}" /></a></div><div class="pic-mask"></div><div class="tips-uploading"><div class="progress-bar J_ProgressBar"><span class="progress-mask J_UploadingProgress"></span></div><p class="tips-text">上传中，请稍候</p></div><div class="tips-upload-success"><span class="progress-bar"></span><p class="tips-text">上传成功！</p></div><div class="tips-upload-error"><span class="progress-bar"></span><p>上传失败</p><p>请重新尝试！</p></div><div class="tips-upload-waiting">等待上传，请稍候</div><div class="upload-op-mask"></div><div class="upload-operations"><a class="J_SetMainPic set-as-main" data-file-id="{id}" href="#">设为主图</a><a class="J_DeleltePic del-pic" data-file-id="{id}" href="#">删除</a></div></div></li>'},
plugins:{value:["preview","progressBar"]},msgContainer:{value:"#J_MsgBoxUpload"},defaultMsg:{value:"最多上传{max}张照片，每张图片小于5M"},leftMsg:{value:"还可以上传{left}张图片，每张小于5M。主图将在搜索结果中展示，请认真设置。"},successMsgCls:{value:"msg-success"},hintMsgCls:{value:"msg-hint"},errorMsgCls:{value:"msg-error"},mainPicInput:{value:"#J_MainPicUrl"}}});return c},{requires:["node","../../theme","./message","./setMainPic"]});
KISSY.add("gallery/form/1.1/uploader/themes/ershouUploader/message",function(b,m){function l(c){this.config=b.mix({msgContainer:"#J_MsgBoxUpload",successMsgCls:"msg-success",hintMsgCls:"msg-hint",errorMsgCls:"msg-error"},c);b.log(i+"Constructed")}var e=m.all,i="[ershouUploader: Message] ";b.augment(l,{send:function(c,d){if(!c){b.log(i+"You did not tell me what to show.");return false}var a=this.config.msgContainer,g=this.config[d+"MsgCls"],h=this.config.successMsgCls,f=this.config.hintMsgCls,j=this.config.errorMsgCls;
if(a)switch(d){case "success":case "hint":case "error":e(a).html(c);e(a).replaceClass([h,f,j].join(" "),g);return true;default:b.log(i+"type error");return false}}});return l},{requires:["node"]});
KISSY.add("gallery/form/1.1/uploader/themes/ershouUploader/setMainPic",function(b,m){function l(c,d){c=e(c);d=e(d);if(!c||c.length<=0){b.log(i+"cannot find mainPicInput, SetMainPic function disabled.");return false}if(!d||d.length<=0){b.log(i+"cannot find queue container");return false}this.queueContainer=d;this.input=c}var e=m.all,i="[LineQueue: setMainPic] ";b.augment(l,{setMainPic:function(c){var d=e("li",this.queueContainer);b.isString(c)&&b.each(d,function(f){if(e(f).attr("data-url")==c){c=f;
return true}});var a=this.getMainPic();c=e(c);if(!c||c.length<=0)if(d[0])if(a.length>0){b.log(i+"Already have a main pic. Since you do not tell me which one to set as main pic, I will do nothing.");return a}else{b.log(i+"No li element specified. I will set the first pic as main pic.");c=d[0]}else{b.log(i+"There is no pic. I cannot set any pic as main pic. So I will empty the main pic input.");e(this.input).val("");return null}d=e(".J_Wrapper",c);var g=e('<span class="main-pic-logo">主图</span>'),h=
e(c).attr("data-url");if(a.length>0){e(a).removeClass("main-pic");e(".main-pic-logo",a).remove()}e(c).addClass("main-pic");e(g).appendTo(d);e(this.input).val(h);b.log(i+"write main pic url to :"+h);return c},getMainPic:function(){return e(this.queueContainer).children(".main-pic")},getMainPicUrl:function(){return e(this.input).val()}});return l},{requires:["node"]});
