KISSY.add("gallery/kcharts/1.1/basechart/index",function(l,w){var x=l.all,v=function(){};l.extend(v,w,{init:function(a){var d;if(a&&a.renderTo&&(d=this._cfg=l.mix({zIndex:0,yAxis:{},canvasAttr:{x:60,y:60},defineKey:{},zoomType:"x"},a),this._$ctnNode=x(a.renderTo),this._$ctnNode.css({"-webkit-text-size-adjust":"none","-webkit-tap-highlight-color":"rgba(0,0,0,0)"}),this.getInnerContainer(),l.mix(this,{_datas:{cur:{},total:{}},_points:{},_centerPoints:[],_pointsX:[],_pointsY:[],_gridsX:[],_gridsY:[],
_areas:[],_axisX:null,_axisY:null,_labelX:[],_labelY:[],_evtEls:[],_gridPoints:[],_multiple:!1,stackable:!1}),(a=d.series||null)&&!(0>=a.length)&&a[0].data)){1<a.length&&(this._multiple=!0);for(var c in a)this._datas.total[c]={index:c,data:a[c].data},this._datas.cur[c]={index:c,data:a[c].data};this.dataFormat()}},removeData:function(a){delete this._datas.cur[a];this.dataFormat()},recoveryData:function(a){this._datas.cur[a]=this._datas.total[a];this.dataFormat()},getInnerContainer:function(){var a=
this._$ctnNode,d=l.mix(this._cfg.canvasAttr),c=d.width||a.width()-2*d.x,a=d.height||a.height()-2*d.y,e=d.x,d=d.y;return this._innerContainer={x:e,y:d,width:c,height:a,tl:{x:e,y:d},tr:{x:e+c,y:d},bl:{x:e,y:d+a},br:{x:e+c,y:d+a}}},getAllDatas:function(a){var d=this._cfg,c=[],e=d.zoomType,f;if(d.stackable)for(var g in this._datas.cur){this._datas.cur[g].data[0]&&(l.isPlainObject(this._datas.cur[g].data[0])&&d.defineKey.y&&d.defineKey.x?f=this.getArrayByKey(this._datas.cur[g].data,d.defineKey.y):l.isArray(this._datas.cur[g].data)&&
(f="xy"==e?this.getArrayByKey(this._datas.cur[g].data,a):this._datas.cur[g].data));for(var i in f)c[i]=c[i]?f[i]+c[i]:f[i]}else for(g in this._datas.cur)this._datas.cur[g].data[0]&&(l.isPlainObject(this._datas.cur[g].data[0])&&d.defineKey.y&&d.defineKey.x?f=this.getArrayByKey(this._datas.cur[g].data,d.defineKey.y):l.isArray(this._datas.cur[g].data)&&(f="xy"==e?this.getArrayByKey(this._datas.cur[g].data,a):this._datas.cur[g].data)),c.push(f.join(","));return c.length?c.join(",").split(","):[]},_getScales:function(a,
d){if(d.text&&l.isArray(d.text))return d.text;var c=d.max-0,e=d.min-0,f=d.num||5,g=Math.max.apply(null,a),i=Math.min.apply(null,a),j=0.1*(g-i)||1*j||10,c=c||0==c?c>=g?c:g+j:g+j,j=e||0==e?e<=i?e:i-j:i-j;l.log(e||0==e);return this.getScales(c,j,f)},dataFormat:function(){var a=this._cfg,d=a.zoomType,c=this._innerContainer,e=c.width,f=c.height,g=c.x,c=c.y,i,j,p,k,o;this._pointsY=[];this._pointsX=[];"x"==d?(i=this.getAllDatas(),i=p=this.coordNum=this._getScales(i,a.yAxis),k=this.data2GrapicData(p,!1,!0)):
"y"==d?(j=this.getAllDatas(),i=j=this.coordNumX=this._getScales(j,a.xAxis),o=this.data2GrapicData(j,!0,!1)):"xy"==d&&(i=this.getAllDatas(0),j=this.getAllDatas(1),i=p=this.coordNum=this._getScales(i,a.xAxis),j=this.coordNumX=this._getScales(j,a.yAxis),k=this.data2GrapicData(p,!1,!1),o=this.data2GrapicData(j,!0,!0));if("x"==d){for(var m in k)this._pointsY[m]={number:p[m]+"",y:k[m],x:g};try{this._gridPoints=this.getSplitPoints(g,c+f,g+e,c+f,a.xAxis.text.length,!0),this._pointsX=this.getCenterPoints(this._gridPoints)}catch(v){throw Error("\u672a\u914d\u7f6e\u6b63\u786e\u7684xAxis.text\u6570\u7ec4");
}}else if("y"==d){for(m in o)this._pointsX[m]={number:j[m]+"",y:c+f,x:o[m]};try{this._pointsY=this.getSplitPoints(g,c,g,c+f,a.yAxis.text.length+1)}catch(w){throw Error("\u672a\u914d\u7f6e\u6b63\u786e\u7684yAxis.text\u6570\u7ec4");}}else if("xy"==d){for(m in o)this._pointsY[m]={number:j[m]+"",y:o[m],x:g};for(m in k)this._pointsX[m]={number:p[m]+"",y:c+f,x:k[m]}}for(m in this._datas.cur){p=this._points;j=m;k=this._datas.cur[m].data;var n=i;o=a.series[m];var r=Math.max.apply(null,n),s=Math.min.apply(null,n),n=a.defineKey,t=n.x,u=n.y,n=[],
q=0;if("x"==d)if(t&&u&&l.isPlainObject(this._datas.total[0].data[0])){var h=void 0;for(h in this._pointsX)k[q]&&a.xAxis.text[h]==k[q][t]?(n[h]={x:this._pointsX[h].x,y:this.data2Grapic(k[q][u],r,s,f,c,!0),dataInfo:k[q],index:Math.round(h)},q++):n[h]={x:this._pointsX[h].x,index:Math.round(h)}}else for(h in this._pointsX)n[h]={x:this._pointsX[h].x,y:this.data2Grapic(k[h],r,s,f,c,!0),dataInfo:{y:k[h]},index:Math.round(h)};else if("y"==d)if(t&&u&&l.isPlainObject(this._datas.total[0].data[0]))for(h in this._pointsY)k[q]&&
a.yAxis.text[h]==k[q][t]?(n[h]={x:this.data2Grapic(k[q][u],r,s,e,g),y:this._pointsY[h].y,dataInfo:{y:k[q]},index:Math.round(h)},q++):n[h]={y:this._pointsY[h].y,index:Math.round(h)};else for(h in this._pointsY)n[h]={x:this.data2Grapic(k[h],r,s,e,g),y:this._pointsY[h].y,dataInfo:{y:k[h]},index:Math.round(h)};else if("xy"==d)for(h in r=this.data2GrapicData(this.getArrayByKey(o.data,0)),s=this.data2GrapicData(this.getArrayByKey(o.data,1),!0,!0),o.data)n[h]={x:r[h],y:s[h],dataInfo:{y:k[h]},index:Math.round(h)};
p[j]=n}},data2GrapicData:function(a,d,c){if(a){var e=this._innerContainer,f=d?e.x:e.y,g=e.height,e=e.width,i=this._cfg.zoomType,j,p=d?Math.max.apply(null,this.coordNumX):Math.max.apply(null,this.coordNum),k=d?Math.min.apply(null,this.coordNumX):Math.min.apply(null,this.coordNum),o=[];"xy"==i?j=d?g:e:"x"==i?j=g:"y"==i&&(j=e);if(l.isArray(a)){for(var m in a)o.push(this.data2Grapic(a[m],p,k,j,f,c));return o}return this.data2Grapic(a,p,k,j,f,c)}},data2Grapic:function(a,d,c,e,f,g){return g?e*(1-(a-c)/
(d-c))+f:e*(a-c)/(d-c)+f},getSplitPoints:function(a,d,c,e,f,g){var i=(c-a)/f,j=(e-d)/f,l=[];g&&l.push({x:a,y:d});for(var k=0;k<f-1;k++)l.push({x:a+(k+1)*i,y:d+(k+1)*j});g&&l.push({x:c,y:e});return l},getCenterPoints:function(a){var d=[],c=a.length;if(1<c)for(var e=0;e<c-1;e++)d[e]={x:(a[e].x+a[e+1].x)/2,y:(a[e].y+a[e+1].y)/2};return d},getScales:function(a,d,c,e){var f,g;f=Math.log;g=Math.pow;var i=[],e=e&&l.isFunction(e)||function(a){return a.toFixed(2)};if(!(a<=d)){c=(a-d)/c;f=Math.floor(f(c)/f(10))+
1;c/=g(10,f);g=(0<c&&0.1>=c?0.1:0.1<c&&0.2>=c?0.2:0.2<c&&0.25>=c?0.25:0.25<c&&0.5>=c?0.5:1)*g(10,f);for(c=f=(a+d)/2-(a+d)/2%g;c>d;)c-=g;for(;f<a;)f+=g;for(a=c;a<=f;a+=g)i.push(a);return i}},arraySort:function(a,d,c){return a.sort(function(a,f){return d?"object"==typeof a&&"object"==typeof f?f[c]-a[c]:f-a:"object"==typeof a&&"object"==typeof f?a[c]-f[c]:a-f})},getArrayByKey:function(a,d){var c=[],e;for(e in a)a[e][d]&&c.push(a[e][d]);return c},coordFormat:function(a){var d=function(){};return l.isArray(a)?
d.apply(a):void 0},obj2Array:function(a,d){var c=[],e;for(e in a)c.push(d?a[d]:a[e]);return c},getObjKeys:function(a){var d=[];for(b in a)d.push(b);return d}});return v},{requires:["base"]});
