KISSY.add("gallery/sizzle/1.9.1/index",function(){return function(Z,qa){var N,$,aa,ba,O,ca,da,ea,fa,ga;function ha(a){return Ba.test(a+"")}function ia(){var a,b=[];return a=function(c,d){b.push(c+=" ")>h.cacheLength&&delete a[b.shift()];return a[c]=d}}function m(a){a[n]=!0;return a}function w(a){var b=r.createElement("div");try{return!!a(b)}catch(c){return!1}finally{}}function k(a,b,c,d){var e,f,g,j,i;(b?b.ownerDocument||b:z)!==r&&J(b);b=b||r;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(j=
b.nodeType)&&9!==j)return[];if(t&&!d){if(e=Ca.exec(a))if(g=e[1])if(9===j)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&L(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return B.apply(c,b.getElementsByTagName(a)),c;if((g=e[3])&&N&&b.getElementsByClassName)return B.apply(c,b.getElementsByClassName(g)),c}if($&&!x.test(a)){e=!0;f=n;g=b;i=9===j&&a;if(1===j&&"object"!==b.nodeName.toLowerCase()){j=P(a);
(e=b.getAttribute("id"))?f=e.replace(Da,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=j.length;g--;)j[g]=f+Q(j[g]);g=ja.test(a)&&b.parentNode||b;i=j.join(",")}if(i)try{return B.apply(c,g.querySelectorAll(i)),c}catch(Ra){}finally{e||b.removeAttribute("id")}}}var l;a:{a=a.replace(R,"$1");f=P(a);if(!d&&1===f.length){e=f[0]=f[0].slice(0);if(2<e.length&&"ID"===(l=e[0]).type&&9===b.nodeType&&t&&h.relative[e[1].type]){b=(h.find.ID(l.matches[0].replace(C,D),b)||[])[0];if(!b){l=c;break a}a=a.slice(e.shift().value.length)}for(j=
S.needsContext.test(a)?0:e.length;j--;){l=e[j];if(h.relative[g=l.type])break;if(g=h.find[g])if(d=g(l.matches[0].replace(C,D),ja.test(e[0].type)&&b.parentNode||b)){e.splice(j,1);a=d.length&&Q(e);if(!a){B.apply(c,d);l=c;break a}break}}}ka(a,f)(d,b,!t,c,ja.test(a));l=c}return l}function ra(a,b){var c=b&&a,d=c&&(~b.sourceIndex||sa)-(~a.sourceIndex||sa);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function Ea(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===
a}}function Fa(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function F(a){return m(function(b){b=+b;return m(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)if(c[e=f[g]])c[e]=!(d[e]=c[e])})})}function P(a,b){var c,d,e,f,g,j,i;if(g=ta[a+" "])return b?0:g.slice(0);g=a;j=[];for(i=h.preFilter;g;){if(!c||(d=Ga.exec(g)))d&&(g=g.slice(d[0].length)||g),j.push(e=[]);c=!1;if(d=Ha.exec(g))c=d.shift(),e.push({value:c,type:d[0].replace(R," ")}),
g=g.slice(c.length);for(f in h.filter)if((d=S[f].exec(g))&&(!i[f]||(d=i[f](d))))c=d.shift(),e.push({value:c,type:f,matches:d}),g=g.slice(c.length);if(!c)break}return b?g.length:g?k.error(a):ta(a,j).slice(0)}function Q(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function la(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=Ia++;return b.first?function(c,b,f){for(;c=c[d];)if(1===c.nodeType||e)return a(c,b,f)}:function(c,b,i){var h,l,u,o=y+" "+f;if(i)for(;c=c[d];){if((1===c.nodeType||e)&&
a(c,b,i))return!0}else for(;c=c[d];)if(1===c.nodeType||e)if(u=c[n]||(c[n]={}),(l=u[d])&&l[0]===o){if(!0===(h=l[1])||h===T)return!0===h}else if(l=u[d]=[o],l[1]=a(c,b,i)||T,!0===l[1])return!0}}function ma(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function U(a,b,c,d,e){for(var f,g=[],j=0,i=a.length,h=null!=b;j<i;j++)if(f=a[j])if(!c||c(f,d,e))g.push(f),h&&b.push(j);return g}function na(a,b,c,d,e,f){d&&!d[n]&&(d=na(d));e&&!e[n]&&(e=na(e,f));return m(function(g,
f,i,h){var l,u,o=[],s=[],n=f.length,q;if(!(q=g)){q=b||"*";for(var p=i.nodeType?[i]:i,r=[],m=0,t=p.length;m<t;m++)k(q,p[m],r);q=r}q=a&&(g||!b)?U(q,o,a,i,h):q;p=c?e||(g?a:n||d)?[]:f:q;c&&c(q,p,i,h);if(d){l=U(p,s);d(l,[],i,h);for(i=l.length;i--;)if(u=l[i])p[s[i]]=!(q[s[i]]=u)}if(g){if(e||a){if(e){l=[];for(i=p.length;i--;)if(u=p[i])l.push(q[i]=u);e(null,p=[],l,h)}for(i=p.length;i--;)if((u=p[i])&&-1<(l=e?G.call(g,u):o[i]))g[l]=!(f[l]=u)}}else p=U(p===f?p.splice(n,p.length):p),e?e(null,f,p,h):B.apply(f,
p)})}function oa(a){var b,c,d,e=a.length,f=h.relative[a[0].type];c=f||h.relative[" "];for(var g=f?1:0,j=la(function(a){return a===b},c,!0),i=la(function(a){return-1<G.call(b,a)},c,!0),k=[function(a,c,d){return!f&&(d||c!==V)||((b=c).nodeType?j(a,c,d):i(a,c,d))}];g<e;g++)if(c=h.relative[a[g].type])k=[la(ma(k),c)];else{c=h.filter[a[g].type].apply(null,a[g].matches);if(c[n]){for(d=++g;d<e&&!h.relative[a[d].type];d++);return na(1<g&&ma(k),1<g&&Q(a.slice(0,g-1)).replace(R,"$1"),c,g<d&&oa(a.slice(g,d)),
d<e&&oa(a=a.slice(d)),d<e&&Q(a))}k.push(c)}return ma(k)}function Ja(a,b){var c=0,d=0<b.length,e=0<a.length,f=function(f,j,i,n,l){var u,o,s=[],m=0,q="0",p=f&&[],t=null!=l,v=V,x=f||e&&h.find.TAG("*",l&&j.parentNode||j),w=y+=null==v?1:Math.random()||0.1;t&&(V=j!==r&&j,T=c);for(;null!=(l=x[q]);q++){if(e&&l){for(u=0;o=a[u++];)if(o(l,j,i)){n.push(l);break}t&&(y=w,T=++c)}d&&((l=!o&&l)&&m--,f&&p.push(l))}m+=q;if(d&&q!==m){for(u=0;o=b[u++];)o(p,s,j,i);if(f){if(0<m)for(;q--;)!p[q]&&!s[q]&&(s[q]=Ka.call(n));
s=U(s)}B.apply(n,s);t&&!f&&0<s.length&&1<m+b.length&&k.uniqueSort(n)}t&&(y=w,V=v);return p};return d?m(f):f}function ua(){}var K,T,h,W,va,ka,V,H,J,r,v,t,x,I,X,L,n="sizzle"+-new Date,z=Z.document;ga=fa=ea=da=ca=O=ba=aa=$=N=void 0;var y=0,Ia=0,wa=ia(),ta=ia(),xa=ia(),M=!1,Y=function(){return 0},A=typeof qa,sa=-2147483648,E=[],Ka=E.pop,La=E.push,B=E.push,ya=E.slice,G=E.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},za="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w",
"w#"),Aa="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+za+")|)|)[\\x20\\t\\r\\n\\f]*\\]",pa=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+Aa.replace(3,8)+")*)|.*)\\)|)",R=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Ga=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Ha=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,
Ma=RegExp(pa),Na=RegExp("^"+za+"$"),S={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[\w-]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Aa),PSEUDO:RegExp("^"+pa),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},ja=/[\x20\t\r\n\f]*[+~]/,Ba=/^[^{]+\{\s*\[native code/,Ca=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,Oa=/^(?:input|select|textarea|button)$/i,Pa=/^h\d$/i,Da=/'|\\/g,Qa=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,C=/\\([\da-fA-F]{1,6}[\x20\t\r\n\f]?|.)/g,D=function(a,b){var c="0x"+b-65536;return c!==c?b:0>c?String.fromCharCode(c+65536):String.fromCharCode(c>>10|55296,c&1023|56320)};try{B.apply(E=ya.call(z.childNodes),z.childNodes),E[z.childNodes.length].nodeType}catch(Sa){B={apply:E.length?function(a,
b){La.apply(a,ya.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}va=k.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};J=k.setDocument=function(a){var b=a?a.ownerDocument||a:z;if(b===r||9!==b.nodeType||!b.documentElement)return r;r=b;v=b.documentElement;t=!va(b);aa=w(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});ba=w(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");
return"boolean"!==a&&"string"!==a});N=w(function(a){a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||!a.getElementsByClassName("e").length)return!1;a.lastChild.className="e";return 2===a.getElementsByClassName("e").length});O=w(function(a){a.id=n+0;a.appendChild(r.createElement("a")).setAttribute("name",n);a.appendChild(r.createElement("i")).setAttribute("name",n);v.appendChild(a);var d=b.getElementsByName&&b.getElementsByName(n).length===2+b.getElementsByName(n+
0).length;v.removeChild(a);return d});ca=w(function(a){return a.compareDocumentPosition&&a.compareDocumentPosition(r.createElement("div"))&1});h.attrHandle=w(function(a){a.innerHTML="<a href='#'></a>";return a.firstChild&&typeof a.firstChild.getAttribute!==A&&"#"===a.firstChild.getAttribute("href")})?{}:{href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}};O?(h.find.ID=function(a,b){if(typeof b.getElementById!==A&&t){var e=b.getElementById(a);return e&&
e.parentNode?[e]:[]}},h.filter.ID=function(a){var b=a.replace(C,D);return function(a){return a.getAttribute("id")===b}}):(h.find.ID=function(a,b){if(typeof b.getElementById!==A&&t){var e=b.getElementById(a);return e?e.id===a||typeof e.getAttributeNode!==A&&e.getAttributeNode("id").value===a?[e]:qa:[]}},h.filter.ID=function(a){var b=a.replace(C,D);return function(a){return(a=typeof a.getAttributeNode!==A&&a.getAttributeNode("id"))&&a.value===b}});h.find.TAG=aa?function(a,b){if(typeof b.getElementsByTagName!==
A)return b.getElementsByTagName(a)}:function(a,b){var e,f=[],g=0,j=b.getElementsByTagName(a);if(a==="*"){for(;e=j[g++];)e.nodeType===1&&f.push(e);return f}return j};h.find.NAME=O&&function(a,b){if(typeof b.getElementsByName!==A)return b.getElementsByName(name)};h.find.CLASS=N&&function(a,b){if(typeof b.getElementsByClassName!==A&&t)return b.getElementsByClassName(a)};I=[];x=[":focus"];if($=ha(b.querySelectorAll))w(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||
x.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||x.push(":checked")}),w(function(a){var b=r.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("i","");a.querySelectorAll("[i^='']").length&&x.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");a.querySelectorAll(":enabled").length||x.push(":enabled",":disabled");a.querySelectorAll("*,:x");x.push(",.*:")});(da=ha(X=v.webkitMatchesSelector||
v.mozMatchesSelector||v.oMatchesSelector||v.msMatchesSelector))&&w(function(a){ea=X.call(a,"div");X.call(a,"[s!='']:x");I.push("!=",pa)});x=RegExp(x.join("|"));I=I.length&&RegExp(I.join("|"));L=ha(v.contains)||v.compareDocumentPosition?function(a,b){var e=a.nodeType===9?a.documentElement:a,f=b&&b.parentNode;return a===f||!(!f||!(f.nodeType===1&&(e.contains?e.contains(f):a.compareDocumentPosition&&a.compareDocumentPosition(f)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return true;return false};
Y=v.compareDocumentPosition?function(a,d){if(a===d){M=true;return 0}var e=d.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(d);return e?e&1||!ca&&d.compareDocumentPosition(a)===e?a===b||L(z,a)?-1:d===b||L(z,d)?1:H?G.call(H,a)-G.call(H,d):0:e&4?-1:1:a.compareDocumentPosition?-1:1}:function(a,d){var e,f=0;e=a.parentNode;var g=d.parentNode,j=[a],i=[d];if(a===d){M=true;return 0}if(!e||!g)return a===b?-1:d===b?1:e?-1:g?1:H?G.call(H,a)-G.call(H,d):0;if(e===g)return ra(a,d);
for(e=a;e=e.parentNode;)j.unshift(e);for(e=d;e=e.parentNode;)i.unshift(e);for(;j[f]===i[f];)f++;return f?ra(j[f],i[f]):j[f]===z?-1:i[f]===z?1:0};return r};k.matches=function(a,b){return k(a,null,null,b)};k.matchesSelector=function(a,b){(a.ownerDocument||a)!==r&&J(a);b=b.replace(Qa,"='$1']");if(da&&t&&(!I||!I.test(b))&&!x.test(b))try{var c=X.call(a,b);if(c||ea||a.document&&11!==a.document.nodeType)return c}catch(d){}return 0<k(b,r,null,[a]).length};k.contains=function(a,b){(a.ownerDocument||a)!==r&&
J(a);return L(a,b)};k.attr=function(a,b){var c;(a.ownerDocument||a)!==r&&J(a);t&&(b=b.toLowerCase());return(c=h.attrHandle[b])?c(a):!t||ba?a.getAttribute(b):((c=a.getAttributeNode(b))||a.getAttribute(b))&&!0===a[b]?b:c&&c.specified?c.value:null};k.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};k.uniqueSort=function(a){var b,c=[],d=0,e=0;M=!fa;H=!ga&&a.slice(0);a.sort(Y);if(M){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}return a};W=k.getText=function(a){var b,
c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=W(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=W(b);return c};h=k.selectors={cacheLength:50,createPseudo:m,match:S,find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(C,D);a[3]=(a[4]||a[5]||"").replace(C,
D);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||k.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&k.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(S.CHILD.test(a[0]))return null;if(a[4])a[2]=a[4];else if(c&&Ma.test(c)&&(b=P(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){if("*"===
a)return function(){return!0};a=a.replace(C,D).toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=wa[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&wa(a,function(a){return b.test(a.className||typeof a.getAttribute!==A&&a.getAttribute("class")||"")})},ATTR:function(a,b,c){return function(d){d=k.attr(d,a);if(null==d)return"!="===b;if(!b)return!0;d+="";return"="===b?d===c:"!="===b?d!==c:"^="===b?c&&0===d.indexOf(c):
"*="===b?c&&-1<d.indexOf(c):"$="===b?c&&d.slice(-c.length)===c:"~="===b?-1<(" "+d+" ").indexOf(c):"|="===b?d===c||d.slice(0,c.length+1)===c+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),j="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,h){var k,o,s,m,q,c=f!==g?"nextSibling":"previousSibling",p=b.parentNode,r=j&&b.nodeName.toLowerCase(),h=!h&&!j;if(p){if(f){for(;c;){for(o=b;o=o[c];)if(j?o.nodeName.toLowerCase()===r:1===o.nodeType)return!1;
q=c="only"===a&&!q&&"nextSibling"}return!0}q=[g?p.firstChild:p.lastChild];if(g&&h){h=p[n]||(p[n]={});k=h[a]||[];m=k[0]===y&&k[1];s=k[0]===y&&k[2];for(o=m&&p.childNodes[m];o=++m&&o&&o[c]||(s=m=0)||q.pop();)if(1===o.nodeType&&++s&&o===b){h[a]=[y,m,s];break}}else if(h&&(k=(b[n]||(b[n]={}))[a])&&k[0]===y)s=k[1];else for(;o=++m&&o&&o[c]||(s=m=0)||q.pop();)if((j?o.nodeName.toLowerCase()===r:1===o.nodeType)&&++s)if(h&&((o[n]||(o[n]={}))[a]=[y,s]),o===b)break;s-=e;return s===d||0===s%d&&0<=s/d}}},PSEUDO:function(a,
b){var c,d=h.pseudos[a]||h.setFilters[a.toLowerCase()]||k.error("unsupported pseudo: "+a);return d[n]?d(b):1<d.length?(c=[a,a,"",b],h.setFilters.hasOwnProperty(a.toLowerCase())?m(function(a,c){for(var g,h=d(a,b),i=h.length;i--;)g=G.call(a,h[i]),a[g]=!(c[g]=h[i])}):function(a){return d(a,0,c)}):d}},pseudos:{not:m(function(a){var b=[],c=[],d=ka(a.replace(R,"$1"));return d[n]?m(function(a,b,c,h){for(var h=d(a,null,h,[]),i=a.length;i--;)if(c=h[i])a[i]=!(b[i]=c)}):function(a,f,g){b[0]=a;d(b,null,g,c);
return!c.pop()}}),has:m(function(a){return function(b){return 0<k(a,b).length}}),contains:m(function(a){return function(b){return-1<(b.textContent||b.innerText||W(b)).indexOf(a)}}),lang:m(function(a){Na.test(a||"")||k.error("unsupported lang: "+a);a=a.replace(C,D).toLowerCase();return function(b){var c;do if(c=t?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(a){var b=
Z.location&&Z.location.hash;return b&&b.slice(1)===a.id},root:function(a){return a===v},focus:function(a){return a===r.activeElement&&(!r.hasFocus||r.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=
a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;return!0},parent:function(a){return!h.pseudos.empty(a)},header:function(a){return Pa.test(a.nodeName)},input:function(a){return Oa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:F(function(){return[0]}),
last:F(function(a,b){return[b-1]}),eq:F(function(a,b,c){return[0>c?c+b:c]}),even:F(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:F(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:F(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:F(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};for(K in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})h.pseudos[K]=Ea(K);for(K in{submit:!0,reset:!0})h.pseudos[K]=Fa(K);ka=k.compile=function(a,b){var c,d=[],e=
[],f=xa[a+" "];if(!f){b||(b=P(a));for(c=b.length;c--;)f=oa(b[c]),f[n]?d.push(f):e.push(f);f=xa(a,Ja(e,d))}return f};h.pseudos.nth=h.pseudos.eq;ua.prototype=h.filters=h.pseudos;h.setFilters=new ua;ga=n.split("").sort(Y).join("")===n;J();[0,0].sort(Y);fa=M;return k}(window)});
