KISSY.add("gallery/huabao/1.0/model/pic",function(b,d){function e(b){b=this.parse(b);this.constructor.superclass.constructor.call(this,b);this.set("rawData",b)}b.extend(e,d,{parse:function(b){return b}},{});e.ATTRS={id:{value:0},picSrc:{value:""},width:{value:0},height:{value:0},desc:{value:""},tags:{value:[]},rawData:{value:null}};return e},{requires:["base"]});
KISSY.add("gallery/huabao/1.0/model/poster",function(b,d){function e(b){b=this.parse(b);this.constructor.superclass.constructor.call(this,b);this.set("rawData",b)}b.extend(e,d,{parse:function(b){return b}},{});e.ATTRS={id:{value:0},title:{value:""},shortTitle:{value:""},tags:{value:[]},weight:{value:0},coverPicSrc:{value:""},channelId:{value:0},hits:{value:0},rawData:{value:null}};return e},{requires:["base"]});
KISSY.add("gallery/huabao/1.0/huabao",function(b,d,e,l,h,i){var j,k;function g(a,c){switch(arguments.length){case 2:c=b.merge(c,{srcNode:b.get(a)});break;case 1:c=a}this.constructor.superclass.constructor.call(this,c);this.get("autoDataBinding")&&this.bindData();if(this.get("autoRendering")){var f=this.get("content"),d=this.get("nav");f&&this.render(f,j);d&&this.render(d,k)}}j='{{#each pics as pic}}<li><img src="{{pic.picSrc}}" width="{{pic.width}}" height="{{pic.height}}"></li>{{/each}}';k='{{#each pics as pic}}<li><img src="{{pic.picSrc}}_100x100.jpg"</li>{{/each}}';
var m=b.get("body");b.extend(g,e,{bindData:function(){var a=this.get("dataSource"),c,f=[];c=new h(a.poster);b.each(a.pics,function(a){f.push(new i(a))},void 0);return this.set("data",{poster:c,pics:f})},render:function(a,c){var b=this.get("rawData");b.pic=b.pics[this.get("activeIndex")];b=l(c).render(b);d.html(a,b);return b},getPoster:function(){return this.get("data").poster},getPics:function(){return this.get("data").pics},getPic:function(a){for(var c=this.getPics(),b=0,d=c.length;b<d;b++){var e=
c[b];if(e.get("id")==a)return e}return null},switchTo:function(a){this.set("activeIndex",a)},prev:function(){this.set("activeIndex",-1+this.get("activeIndex"))},next:function(){this.set("activeIndex",1+this.get("activeIndex"))},pageTo:function(a){this.set("pageIndex",a)},prevPage:function(){this.set("pageIndex",-1+this.get("pageIndex"))},nextPage:function(){this.set("pageIndex",1+this.get("pageIndex"))}},{attachImgOnload:function(a,b){a&&a.complete&&a.clientWidth?b():a.onload=function(){setTimeout(b,
100)}},model:{Poster:h,Pic:i}});g.ATTRS={autoDataBinding:{value:!0},autoRendering:{value:!1},dataSource:{value:null},data:{value:{poster:null,pics:[]}},rawData:{valueFn:function(){var a=this.getPoster().get("rawData"),c=[];b.each(this.getPics(),function(a){c.push(a.get("rawData"))},void 0);return{poster:a,pics:c}}},srcNode:{value:m},navCls:{value:"ks-huabao-nav"},contentCls:{value:"ks-huabao-content"},nav:{valueFn:function(){var a=this.get("srcNode");return b.get("."+this.get("navCls"),a)}},content:{valueFn:function(){var a=
this.get("srcNode");return b.get("."+this.get("contentCls"),a)}},triggerCls:{value:"ks-huabao-trigger"},panelCls:{value:"ks-huabao-panel"},triggers:{value:[],getter:function(){var a=this.get("srcNode"),c=this.get("nav"),a=b.query("."+this.get("triggerCls"),a);if((!a||0>=a.length)&&c&&null!==c)a=d.children(c);return a}},panels:{value:[],getter:function(){var a=this.get("srcNode"),c=this.get("content"),a=b.query("."+this.get("panelCls"),a);if((!a||0>=a.length)&&c&&null!==c)a=d.children(c);return a}},
activeIndex:{value:-1,setter:function(a){var b=this.get("length")-1,a=a-0;return 0>a?0:a>b?b:a},validator:function(a){var b=this.get("length")-1,d=this.get("activeIndex"),a=a-0;return!(0>a&&0==d||a>b&&d==b)}},pageIndex:{value:-1,setter:function(a){var b=this.get("pageLength")-1,a=a-0;return 0>a?0:a>b?b:a},validator:function(a){var b=this.get("pageLength")-1,d=this.get("pageIndex"),a=a-0;return!(0>a&&0==d||a>b&&d==b)}},length:{getter:function(){return this.get("data").pics.length}},pageSize:{value:1},
pageLength:{getter:function(){return Math.ceil(this.get("length")/this.get("pageSize"))}}};return g},{requires:["dom","base","template","./model/poster","./model/pic"]});KISSY.add("gallery/huabao/1.0/index",function(b,d){return d},{requires:["./huabao"]});
