KISSY.add("gallery/form/1.0/uploader/themes/grayQueue/index",function(j,l,k,i){function g(a){g.superclass.constructor.call(this,a)}var f=l.all;j.extend(g,k,{_init:function(){var a=this.get("queueTarget");this.set("queue",new i(a))},afterUploaderRender:function(a){var d=a.get("queue"),b=f(this.get("elStartUpload")),e=f(this.get("elTotalProgressNum")),h=this.get("startUploadDisabledCls");d.on("add",function(){b.removeClass(h)});a.on("uploadAll",function(){var c=a.get("progressBar");c.set("value",100);
c.hide();e.text("100%")});b.on("click",function(c){c.preventDefault();if(!b.hasClass(h)){(c=a.get("progressBar"))&&c.show();a.uploadAll()}})}},{ATTRS:{elStartUpload:{value:"#J_StartUpload"},startUploadDisabledCls:{value:"start-upload-disabled"},elTotalProgressNum:{value:"#J_TotalProgressNum"}}});return g},{requires:["node","../default/index","./queue","./style.css"]});
KISSY.add("gallery/form/1.0/uploader/themes/grayQueue/queue",function(j,l,k,i){function g(f){g.superclass.constructor.call(this,f)}j.extend(g,k,{_renderStatus:function(f){var a=f.target;if(!a.length)return false;a=a.children(".J_FileStatus");return new i(a,{queue:this,file:f})}},{ATTRS:{tpl:{value:'<li id="queue-file-{id}" class="clearfix queue-file" data-name="{name}"><div class="f-l file-name">{name}</div><div class="f-r file-status J_FileStatus">0%</div><div class="f-r file-size">{textSize}</div></li>'}}});
return g},{requires:["node","../../queue/base","./status"]});
KISSY.add("gallery/form/1.0/uploader/themes/grayQueue/status",function(j,l,k,i){function g(a,d){g.superclass.constructor.call(this,a,d);this.set("target",f(a))}var f=l.all;g.type=i.type;j.extend(g,i,{_waiting:function(){var a=this.get("tpl").waiting,d=this.get("uploader"),b=this.get("queue"),e=this.get("file"),h=e.id,c=d.get("total"),m=e.size;a=this._changeDom(a).children(".J_DelFile");a.length&&a.on("click",function(){b.remove(h);c-=m;f("#J_TotalSize").text(i.convertByteSize(c));d.set("total",c)});
if(!m)return false;if(c)c+=m;else{c=m;d.set("loaded",0)}f("#J_TotalSize").text(i.convertByteSize(c));d.set("total",c)},_start:function(){var a=this.get("tpl").start,d=this.get("target"),b=this.get("uploader"),e=b.get("type");if(!j.isString(a))return false;a=this._changeDom(a);if(e=="ajax"){if(!b.get("progressBar")){e=new k(f("#J_ProgressBar"));e.render();b.set("progressBar",e)}b.get("progressBar").set("value",0);b=a.children(".J_ProgressNum");b.html("0%");this.set("elProgressNum",b)}d.parent().addClass("current-upload-file")},
_progress:function(a){var d=a.loaded;a=Math.ceil(d/a.total*100);var b=this.get("uploader"),e=b.get("progressBar"),h=b.get("total");b=b.get("loaded");var c=this.get("elProgressNum");if(!c.length||e=="")return false;c.html(a+"%");d+=b;a=Math.ceil(d/h*100);e.set("value",a);f("#J_TotalProgressNum").text(a+"%")},_success:function(){var a=this.get("tpl").success,d=this.get("target");this.get("queue");var b=this.get("file").size,e=this.get("uploader"),h=e.get("loaded");if(!j.isString(a))return false;this._changeDom(a);
d.parent().removeClass("current-upload-file");if(!b)return false;h+=b;e.set("loaded",h)}},{ATTRS:{tpl:{value:{waiting:'<div class="clearfix"><div class="f-l">0%</div><div class="f-l uploader-icon del-icon J_DelFile"></div></div>',start:'<div class="clearfix"><div class="J_ProgressNum"><img class="loading" src="http://img01.taobaocdn.com/tps/i1/T1F5tVXjRfXXXXXXXX-16-16.gif" alt="loading" /></div></div> ',success:'<div class="uploader-icon success-icon">100%</div>',cancel:'<div>已经取消上传，<a href="#reUpload" class="J_ReUpload">点此重新上传</a> </div>',
error:'<div class="upload-error">{msg}<a href="#fileDel" class="J_FileDel">点此删除</a></div>'}}}});return g},{requires:["node","../../plugins/progressBar/progressBar","../../queue/status"]});
